### ISSUE TITLE
Part IV, Section B (Specific yearly turnover)

### ISSUE THREAD

**Issue by rantati7** [OP-TED/ESPD-EDM#10]
**Specific yearly turnover**

CA must be able to define the minimun requirement. for the turnover.

CA must also be able to define what is means with specific turnover (normally the area of the EOs business the turnover requirement concerns)

CA must be able to define from which years EO must fill in its turnover,

**Comment by JoseLuisCueva** [comment]
I agree.
Regarding with the "business area" definition I think that the use of the contract CPV (CPVs) could be a workable solution towards clarity and interoperability (and avoiding problems from free text descriptions in different languages). Other taxonomies (UN/SPSC, etc) could also "fit the bill" but for this context CPV seems the obvious choice.
Regarding from which years I agree, but as turnover is a "flow" amount I guess (again) that using "period" is better than using "year" (being "year" a particular case of "period")

**Comment by paulakeen** [comment]
Please find the details of the final decision in https://github.com/ESPD/ESPD-EDM/wiki/2.-Specific-Turnover
