### ISSUE TITLE
[C7] Payment of taxes + Mapping

### ISSUE THREAD

**Issue by millstream** [OP-TED/ESPD-EDM#100]
Mapping for C7 + C8 appear to have a parent group which think is incorrect. This should have 3 primary groups, can you please explain why it has been set up like this?

This makes no sense to have it this way as the first group is not conditional.

{CRITERION |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | --
  **| {REQUIREMENT_GROUP |   |   |   |   |   |**  
  |   | {REQUIREMENT} |   |   |   |   |  
  |   | {REQUIREMENT} |   |   |   |   |  
  |   | {QUESTION_SUBGROUP |   |   |   |   |  
  |   |   | {QUESTION} |   |   |   |  
  |   |   | {QUESTION_SUBGROUP |   |   |  
  |   |   |   | {QUESTION} |   |   |  
  |   |   |   | {QUESTION} |   |   |  
  |   |   |   | {QUESTION_SUBGROUP |   |  
  |   |   |   |   | {QUESTION} |   |  
  |   |   |   |   | {QUESTION_SUBGROUP |   |  
  |   |   |   |   |   | {QUESTION} |  
  |   |   |   |   | QUESTION_SUBGROUP} |   |  
  |   |   |   |   | {QUESTION_SUBGROUP |   |  
  |   |   |   |   |   | {QUESTION} |  
  |   |   |   |   |   | {QUESTION_SUBGROUP |  
  |   |   |   |   |   |   | {QUESTION}
  |   |   |   |   |   | QUESTION_SUBGROUP} |  
  |   |   |   |   | QUESTION_SUBGROUP} |   |  
  |   |   |   |   | {QUESTION_SUBGROUP |   |  
  |   |   |   |   |   | {QUESTION} |  
  |   |   |   |   |   | {QUESTION_SUBGROUP |  
  |   |   |   |   |   |   | {QUESTION}
  |   |   |   |   |   |   | {QUESTION}
  |   |   |   |   |   | QUESTION_SUBGROUP} |  
  |   |   |   |   | QUESTION_SUBGROUP} |   |  
  |   |   |   | QUESTION_SUBGROUP} |   |  
  |   |   | QUESTION_SUBGROUP} |   |   |  
  |   | QUESTION_SUBGROUP} |   |   |   |   |  
  |   | {QUESTION_SUBGROUP |   |   |   |   |  
  |   |   | {QUESTION} |   |   |   |  
  |   |   | {QUESTION_SUBGROUP |   |   |  
  |   |   |   | {QUESTION} |   |   |  
  |   |   | QUESTION_SUBGROUP} |   |   |  
  |   | QUESTION_SUBGROUP} |   |   |   |   |  
  | REQUIREMENT_GROUP} |   |   |   |   |   |

**Comment by ec-mcs** [comment]
We will look at this issue and come back to it ASAP.

**Comment by paulakeen** [comment]
Dear Millstream,

In principle this structure maps the behaviour of the ESPD-Service Interface. If we're not wrong the mapping would be logic. But we'd like to hear from you what would be a more correct structure. Could you please propose your own so we can analyse it and come to a common understanding/agreement on the structure of this criterion?

**Comment by mondorf** [comment]
This issue would be related to the ESPD service layout. However we cannot investigate this issue further and haven't received a concrete explanation of the issues from millstream. Therefore we close the issue and it might be re-entered as new issue by millstream if relevant.
