### ISSUE TITLE
Criteria 9-11

### ISSUE THREAD

**Issue by millstream** [OP-TED/ESPD-EDM#101]
Mapping document indicates the following question should be of type DESCRIPTION, but it should be of type INDICATOR

Have you taken measures to demonstrate your reliability (Self-Cleaning)?

**Comment by ec-mcs** [comment]
We will update the spec

**Comment by paulakeen** [comment]
Corrected in v2.0.1 to be released on the Github 2.0.1 branch by the 25th February 2018.
