### ISSUE TITLE
Available Electronically Question

### ISSUE THREAD

**Issue by millstream** [OP-TED/ESPD-EDM#102]
It appears that the question

Is this information available electronically?

has changed to 

Is this information available at no cost to the authorities from an EU Member State database?

Can you please confirm if this was intentional?

**Comment by ec-mcs** [comment]
We will use "Is this information available electronically?". The information about 
- at no cost
- for authorities
- in an EU Member State database
will be provided in the future through eCertis. And it would be a problem if we would combine the requirements into the question.
We will update the specs.

**Comment by paulakeen** [comment]
The text "Is this information available at no cost to the authorities from an EU Member State database?" has been replaced by "Is this information available electronically?" in the data structure files (both REGULATED and SELF-CONTAINED) and in the online documentation. To be released in version 2.0.1 by the 25th February 2015 on Github branch 2.0.1.
