### ISSUE TITLE
C18 + Question Description

### ISSUE THREAD

**Issue by millstream** [OP-TED/ESPD-EDM#103]
The grammar in this question makes no sense

Is the economic operator  guilty of grave professional misconduct? Where applicable, see definitions in national law, the relevant notice **or the in the** ESPD, the relevant notice **or .**

**Comment by ec-mcs** [comment]
We will update the spec.

**Comment by paulakeen** [comment]
Corrected in v2.0.1 to be released on the Github 2.0.1 branch by the 25th February 2018 (both in the data structures and the Criteria Taxonomy spreadsheets, see "dist/cl" folder files).

The REGULATED version now reads: Is the economic operator guilty of grave professional misconduct? Where applicable, see definitions in national law, the relevant notice or the procurement documents.

The SELF-CONTAINED version now reads: Is the economic operator guilty of grave professional misconduct? Where applicable, see definitions in the ESPD and the national law, the relevant notice or the procurement documents.
