### ISSUE TITLE
C18 + C19 = Wrong element code

### ISSUE THREAD

**Issue by millstream** [OP-TED/ESPD-EDM#104]
Have you taken measures to demonstrate your reliability 

The subgroup it belongs to should have ONTRUE as its element code.

**Comment by ec-mcs** [comment]
Correct, we will update the spec.

**Comment by paulakeen** [comment]
Corrected in v2.0.1 to be released on the Github 2.0.1 branch by the 25th February 2018. Data Structures (REGULATED and SELF-CONTAINED) have been modified. The documentation has been updated, too.
