### ISSUE TITLE
C22 - Element Code Mistake

### ISSUE THREAD

**Issue by millstream** [OP-TED/ESPD-EDM#106]
If initial answer is yes, please describe them subgroup should have process instruction ONTRUE

**Comment by ec-mcs** [comment]
We will update the spec.

**Comment by paulakeen** [comment]
Many   thanks for contributing to the quality of the specification, Millstream. This   has been corrected in version 2.0.1. The following artefacts have been   updated:          Criterion 22 in the REGULATED Data Structures spreadsheets book     Criterion 22 in the SELF-CONTAINED Data Structures spreadsheets book     The online documentation (released on the 25th February 2018 on the Github   v2.0.1 branch).
