### ISSUE TITLE
C22 - Incorrect Element Code

### ISSUE THREAD

**Issue by millstream** [OP-TED/ESPD-EDM#107]
Have you taken measures to demonstrate your reliability (Self-Cleaning)?

This should be an indicator

**Comment by ec-mcs** [comment]
Yes, it is wrong, it should be an indicator. We will update the spec.

**Comment by paulakeen** [comment]
Many thanks for contributing to the quality of the specification, Millstream. This has been corrected in version 2.0.1. The following artefacts have been updated:

1. Criterion 22 in the REGULATED Data Structures spreadsheets book
2. Criterion 22 in the SELF-CONTAINED Data Structures spreadsheets book
3. In the online documentation
