### ISSUE TITLE
C30 - CPV codes

### ISSUE THREAD

**Issue by millstream** [OP-TED/ESPD-EDM#108]
Question 30 asks for CPV codes, is that intentional?

**Comment by ec-mcs** [comment]
Yes this is intentional because it will allow the CA to either use a business domain description OR a CPV code to provide the domain for the yearly turnover.
Text will be checked.

**Comment by paulakeen** [comment]
MC is right. Additional explanatory texts have been added at the beginning of sections "VI.2.6 Self-contained specific yearly turnover" and "VI.2.8 Self-contained specific average turnover", e.g.:

**One characteristic of the "specific" turnovers is that the contracting authority requires to know which is the economic operator's turnover for a concrete business domain. The only way of responding that requirement is either by describing the domain in a free-text field or to use the Common Procurement Vocabulary (CPV) codes to narrow as much as possible the business domain. 

Notice that in the Mock-ups and the Data Structures, below, both options are available to the economic operator.

See also section about the SELF-CONTAINED specific average turnover.**
