### ISSUE TITLE
C7 - Payment of taxes

### ISSUE THREAD

**Issue by millstream** [OP-TED/ESPD-EDM#109]
There seems to be a new subgroup with element code ONFALSE

The question is

"If this breach of obligations was established through a judicial or administrative decision, was this decision final and binding?"

This makes no sense if the answer to the original question was no

**Comment by ec-mcs** [comment]
This is maybe an error. Enric will check it.

**Comment by paulakeen** [comment]
We have been reviewing the behaviour of the ESPD Service and, in principle, the ONFALSE code would be rightly used in the data structure defined in version 2.0.0. It is linked to the question: "Has this breach of obligations been established by means other than a judicial or administrative decision?" If the answer is "yes" (ONTRUE) the field "Please describe which means were used" is shown:
![yes](https://user-images.githubusercontent.com/16134316/35153467-ee73ed5c-fd26-11e7-939d-54dc3aef095b.png)

On the opposite, if the answer is "no" (ONFALSE) the question "If this breach of obligations was established through a judicial or administrative decision, was this decision final and binding?" is shown:

![no](https://user-images.githubusercontent.com/16134316/35153514-1b401a90-fd27-11e7-877c-a72f47517c8a.png)
