### ISSUE TITLE
Part IV, Section B (Specific average turnover)

### ISSUE THREAD

**Issue by rantati7** [OP-TED/ESPD-EDM#11]
**Specific average turnover**

CAS must be able to define what is the minimum requirement for the average yearly turnover. Also CA must be able to define not just from how many years the average is but also from which years the average will need to be calculated.

CA must be able to define the what is means with specific (i.e. often business area of EO)

**Comment by JoseLuisCueva** [comment]
I recall my comments on the former issues.
I agree, with the remarks of 
- using "period" for expressing the time span along the average must be computed, 
- using a taxonomy or codelist for precision, clarity and interoperability in expressing the business area (CPV is the obvious choice, but there are other options, just in case)

**Comment by lauramrtn** [comment]
Agree with both comments.

**Comment by paulakeen** [comment]
Please find the details of the final decision in https://github.com/ESPD/ESPD-EDM/wiki/2.-Specific-Turnover
