### ISSUE TITLE
C23 - Multiple line description

### ISSUE THREAD

**Issue by millstream** [OP-TED/ESPD-EDM#110]
Can you please explain what the following means:

"BEWARE THAT IN THIS CASE, THE CRITERION DESCRIPTION IS SPLIT IN THREE LINES. THIS WILL GENERATE THREE DESCRIPTION ELEMENTS IN THE XML INSTANCE (THE UBL-2.2 XSD SCHEMA DOES ALWAY CATTER FOR 0..n DESCRIPTION LINES."

In the example response you have provided this is not the case, in fact a/b/c is not included

**Comment by ec-mcs** [comment]
Text will be updated to give more guidance.

**Comment by paulakeen** [comment]
The   documentation and XML have been corrected.
