### ISSUE TITLE
C36 - Other economic or financial requirements

### ISSUE THREAD

**Issue by millstream** [OP-TED/ESPD-EDM#111]
As per so many of the new criteria updates, there are grammar errors in the text. 

"Concerning the other economic or financial requirements, if any, that may have been specified in the relevant notice or **the** in the ESPD, **the relevant notice or** , the economic operator declares that:"

Were the updates automated? There are grammar mistakes throughout.

**Comment by paulakeen** [comment]
1. These texts were copied and pasted from the ESPD-Service interface. Therefore any error detected are also to be checked against that interface and reported onto the ESPD-Service issue space in this very Github.

2. This particular C36 error has been corrected in the documentation and will appear as so in version 2.0.1.
