### ISSUE TITLE
JurisdictionLevelCode link between eCertis and ESPD

### ISSUE THREAD

**Issue by mondorf** [OP-TED/ESPD-EDM#114]
When you ask eCertis for the legal information of a criterion it returns a JurisdictionLevelCode with values that are different to the ones defined for the JurisdictionLevelCode in ESPD.
 
Can the eCertis JurisdictionLevel be linked somehow to the ESPD JurisdicitonLevel?
 
Sample of eCertis:
<ccv:LegislationReference>
<ccv-cbc:Title languageID="en">Public Procurement Directive 2014/24/EU</ccv-cbc:Title>
<cbc:Description languageID="en">
Directive 2014/24/EU of the European Parliament and of the Council of 26 February 2014 on public procurement and repealing Directive 2004/18/EC
</cbc:Description>
<ccv-cbc:JurisdictionLevelCode>eu</ccv-cbc:JurisdictionLevelCode>
<ccv-cbc:Article languageID="en">Article 57(1)</ccv-cbc:Article>
<cbc:URI>
http://eur-lex.europa.eu/legal-content/EN/TXT/?uri=uriserv:OJ.L_.2014.094.01.0065.01.ENG
</cbc:URI>
</ccv:LegislationReference>
 
ESPD CodeList for JurisdictionLevelCode:
https://github.com/ESPD/ESPD-EDM/blob/1.0.2/docs/src/main/asciidoc/code_lists/pdf/CriterionJurisdictionLevel.pdf

**Comment by mondorf** [comment]
There is a mismatch between the eCERTIS structure and the ESPD code lists. They should be coherent. This is something that cannot be solved quickly. However, it will be taken into consideration for the next release of eCERTIS which is planned in the next year. Currently it is not possible to specify a specific date for this. Within this release eCERTIS should also provide the entire criteria structure .

**Comment by paulakeen** [comment]
1. This is an issue for eCertis: The codes defined in ESPD-EDMv1.0.2 are the same as the ones used in the subsequent versions of the ESPD-EDM. We recommend the creation of a specific area for eCertis in this Github space and move all the issues related to eCertis there.

2. Beware, however, that the name of the codelist (not its content) changed from "JurisdictionLevelCode" in version 1.0.2 to "LegislationType" in version 2.0.0.

**Comment by paulakeen** [comment]
The Working Group decided to close this issue as it should be addressed to eCertis.
