### ISSUE TITLE
Missing eCertis information for "Direct or indirect involvement in the preparation of this procurement procedure" criterion

### ISSUE THREAD

**Issue by mondorf** [OP-TED/ESPD-EDM#116]
eCertis is not returning information for the following criterion:
ID: 61874050-5130-4f1c-a174-720939c7b483
Name: Direct or indirect involvement in the preparation of this procurement procedure
 
Isn't there a requirement that states that all ESPD criteria must be defined in eCertis? 
Is this a problem to be solved by eCertis?

**Comment by mondorf** [comment]
We will check and look into the details where the problem is.

**Comment by ec-mcs** [comment]
The problem, is likely that this criterion is not currently in eCertis. We have to "exchange" it with another criterion which is duplicated in eCertis.

**Comment by paulakeen** [comment]
Do we have to have this Issue in the ESPD-EDM issues management tab of the Github? I propose to open a third space (addittionally to the ESPD Service and ESPD-EDM) named eCertis and move these issues there.

**Comment by paulakeen** [comment]
The Working Group decided to close this issue as it should be addressed to eCertis.
