### ISSUE TITLE
Evidence Supplied / Evidence Identifier in ESPD Data Structures

### ISSUE THREAD

**Issue by mondorf** [OP-TED/ESPD-EDM#117]
For each criteria there should be a possibility to indicate an evidence through an evidence identifier in order to support the once only principle. If not available, EOs have to re-enter their prequalification information into the ESPD since they are managed in external documents. At least for the following criteria they should be added in order to link to documents available in the German prequalification database:
Breaching of obligations in the fields of social law
Breaching of obligations in the fields of labour law
Guilty of grave professional misconduct
Agreements with other economic operators aimed at distorting competition
Early termination, damages or other comparable sanctions
General yearly turnover
Specific yearly turnover
Average yearly turnover
Specific yearly turnover
Number of managerial staff
Average annual manpower

**Comment by mondorf** [comment]
Link to electronic evidence (evidence identifier) will be added to all criteria as a general pattern.

**Comment by paulakeen** [comment]
All Data Structures in ESPD-Regulated and ESPD-SELFCONTAINED Excels have been reviewed and modified. The images in the documentation too.
The change request can be summed up as follows: the user should be able to associate one or more evidence to any criterion. The followin data structures have been vary now from version 1.0:
REGULATED:
* EG-Convictions -> NO CHANGES!
* EG-Contributions -> NO CHANGES!
* EG-Environ-Social-Labour_Law -> Group #UUID 9026e403-3eb6-4705-a9e9-e21a1efc867d added at the end of the structure
* EG-Business  -> NO CHANGES!
* EG-Misconduct -> Group -> Group #UUID 9026e403-3eb6-4705-a9e9-e21a1efc867d added at the end of the structure
* EG-Conflict_of_interest -> Group #UUID 9026e403-3eb6-4705-a9e9-e21a1efc867d added at the end of the structure
* EG-Early_termination -> Group #UUID 9026e403-3eb6-4705-a9e9-e21a1efc867d added at the end of the structure
* EG-Misinterpretation -> Group #UUID 9026e403-3eb6-4705-a9e9-e21a1efc867d added at the end of the structure
* EG-Purely_national -> NO CHANGES!
* SC-Suitability -> NO CHANGES!
* SC-Yearly_Turnovers -> Group #UUID 9026e403-3eb6-4705-a9e9-e21a1efc867d added at the end of the structure
* SC-Average_Turnovers -> NO CHANGES!
* SC-Setup_of_economic_operator -> Group #UUID 9026e403-3eb6-4705-a9e9-e21a1efc867d added at the end of the structure
* SC-Financial_ratios -> Group #UUID 9026e403-3eb6-4705-a9e9-e21a1efc867d added at the end of the structure
* SC-Professional_risk_insurance -> NO CHANGES!
* SC-Other_economic_or_financial -> Group #UUID 9026e403-3eb6-4705-a9e9-e21a1efc867d added at the end of the structure
* SC-References -> NO CHANGES!
* SC-Abilities_1 -> NO CHANGES!
* SC-Abilities_2_checks -> Group #UUID 9026e403-3eb6-4705-a9e9-e21a1efc867d added at the end of the structure
* SC-Abilities_3 -> Group #UUID 9026e403-3eb6-4705-a9e9-e21a1efc867d added at the end of the structure
* SC-Subcontracting_proportion -> Group #UUID 9026e403-3eb6-4705-a9e9-e21a1efc867d added at the end of the structure
* SC-Samples_certificates -> NO CHANGES!
* SC-Quality_assurance -> In this case the Subgroup #UUID 9026e403-3eb6-4705-a9e9-e21a1efc867d has been extracted from the 
* SC-Quality_assurance -> In this case the Subgroup #UUID 4887c3d7-05fc-4e3e-b066-f338910f0c4c and has been added at the end of the criterion data structure
* OTHER-EO-SHELTERED -> Group #UUID 9026e403-3eb6-4705-a9e9-e21a1efc867d added at the end of the structure
* OTHER-EO-PQS -> Group #UUID 9026e403-3eb6-4705-a9e9-e21a1efc867d added at the end of the structure
* OTHER-EO-GROUPS -> Group #UUID 9026e403-3eb6-4705-a9e9-e21a1efc867d added at the end of the structure
* OTHER-EO-Lots -> Group #UUID 9026e403-3eb6-4705-a9e9-e21a1efc867d added at the end of the structure
* OTHER-EO-Contributions -> Group #UUID 9026e403-3eb6-4705-a9e9-e21a1efc867d added at the end of the structure
* OTHER-EO-NOT_RELIED_ON-ENTITIES -> Group #UUID 9026e403-3eb6-4705-a9e9-e21a1efc867d added at the end of the structure




SELF-CONTAINED:
* EG-Convictions -> NO CHANGES!
* EG-Contributions -> NO CHANGES!
* EG-Business  -> NO CHANGES!
* EG-Misconduct -> Group #UUID 9026e403-3eb6-4705-a9e9-e21a1efc867d added at the end of the structure
* EG-Conflict_of_interest -> Group #UUID 9026e403-3eb6-4705-a9e9-e21a1efc867d added at the end of the structure
* EG-Early_termination -> Group #UUID 9026e403-3eb6-4705-a9e9-e21a1efc867d added at the end of the structure
* EG-Misinterpretation -> Group #UUID 9026e403-3eb6-4705-a9e9-e21a1efc867d added at the end of the structure
* EG-Purely_national -> NO CHANGES!
* SC-Suitability -> NO CHANGES!
* SC-General_Turnover -> Subgroup #UUID 9026e403-3eb6-4705-a9e9-e21a1efc867d added inside the the requirement group #UUID 5ca58d66-3ef1-4145-957c-45d5b18a837f
* SC-Specific_Turnover -> Subgroup #UUID 9026e403-3eb6-4705-a9e9-e21a1efc867d added inside the the requirement group #UUID 19a68e37-d307-4a28-9061-c22cd767be58
* SC-General_Average_Turnover -> Subgroup #UUID 9026e403-3eb6-4705-a9e9-e21a1efc867d added inside the the requirement group #UUID 53882893-f4a8-40ae-99dc-cad7b0748790
* SC-Specific_Average_Turnover -> Subgroup #UUID 9026e403-3eb6-4705-a9e9-e21a1efc867d added inside the the requirement group #UUID 6cff132b-8d15-4f79-ae37-2f9295432381
* SC-Specific_Average_Turnover -> Group #UUID 9026e403-3eb6-4705-a9e9-e21a1efc867d added at the end of the structure
* SC-Financial_ratios -> Group #UUID 9026e403-3eb6-4705-a9e9-e21a1efc867d added at the end of the structure
* SC-Other_economic_or_financial -> Group #UUID 9026e403-3eb6-4705-a9e9-e21a1efc867d added inside the requirement group #UUID  4ddccd16-91e4-4b72-ae0f-78f2f1ab9490
* SC-Abilities_2_Checks -> Group #UUID 9026e403-3eb6-4705-a9e9-e21a1efc867d added inside the requirement group #UUID  10822ddd-9ba6-42d5-9339-de0845aeafc9
* SC-Abilities_3 -> Group #UUID 9026e403-3eb6-4705-a9e9-e21a1efc867d added inside the requirement group #UUID  7f7949a8-dbe6-496c-a9f6-6f05b8648bad
* SC-Subcontracting_proportion -> Group #UUID 9026e403-3eb6-4705-a9e9-e21a1efc867d added at the end of the structure
* SC-Samples_certificates -> NO CHANGES!
* SC-Quality_assurance -> In this case the Subgroup #UUID 9026e403-3eb6-4705-a9e9-e21a1efc867d has been extracted from the Subgroup #UUID 4887c3d7-05fc-4e3e-b066-f338910f0c4c and has been added at the end of the requirement_group #UUID 612d99eb-ea3b-4275-ac06-0db05e039c8c
* OTHER-EO-SHELTERED -> Group #UUID 9026e403-3eb6-4705-a9e9-e21a1efc867d added at the end of the structure
* OTHER-EO-PQS -> Group #UUID 9026e403-3eb6-4705-a9e9-e21a1efc867d added at the end of the structure
* OTHER-EO-GROUPS -> Group #UUID 9026e403-3eb6-4705-a9e9-e21a1efc867d added at the end of the structure
* OTHER-EO-Lots -> Group #UUID 9026e403-3eb6-4705-a9e9-e21a1efc867d added at the end of the structure
* OTHER-EO-Contributions -> Group #UUID 9026e403-3eb6-4705-a9e9-e21a1efc867d added at the end of the structure
* OTHER-EO-RELIED_ON-ENTITIES -> Group #UUID 9026e403-3eb6-4705-a9e9-e21a1efc867d added at the end of the structure
* OTHER-EO-NOT_RELIED_ON-ENTITIES -> Group #UUID 9026e403-3eb6-4705-a9e9-e21a1efc867d added at the end of the structure

The documentation has been changed accordingly: the images corresponding to all these data structures have been updated.
