### ISSUE TITLE
Missing code "NGOJ" in DocRefContentType

### ISSUE THREAD

**Issue by klakegg** [OP-TED/ESPD-EDM#119]
The code "NGOJ" seem to be missing in the DocRefContentType codelist part of 1.0.2.

"NGOJ" is used by the ESPD Service when providing ESPD Response 1.0.2 documents.

**Comment by paulakeen** [comment]
Thanks for the observation, Klakegg. I'm goint to check this with the team maintaining the ESPD-Service. 

BTW, the code NGOJ does not exist in version 1.0.2 nor in version 2.0.0. National Government Official Journal-related codes for the ESPD-EDM-2.0.0 are: NOJCN, NOJPIN and NOJCAN. See Codelists in 
[CodeLists ESPD-EDM-2.0.0](https://github.com/ESPD/ESPD-EDM/blob/2.0.0/docs/src/main/asciidoc/dist/cl/xlsx/ESPD-CodeLists-V02.00.00.xlsx)

**Comment by paulakeen** [comment]
The Working Group decided to close this issue as it should be addressed to the ESPD-Service.

**Comment by klakegg** [comment]
What is the new issue number?

**Comment by paulakeen** [comment]
https://github.com/ESPD/ESPD-Service/issues/218

**Comment by klakegg** [comment]
Please transfer this issue to ESPD/ESPD-Service. Thank you.
