### ISSUE TITLE
Propper schemeID of TED number

### ISSUE THREAD

**Issue by klakegg** [OP-TED/ESPD-EDM#120]
When generating an ESPD Request in the ESPD Service using a dummy TED number, I get the following:

```xml
<cbc:ID
    schemeID="COM-GROW-TEMPORARY-ID" 
    schemeAgencyID="EU-COM-GROW"
    schemeAgencyName="DG GROW (European Commission)"
    schemeVersionID="1.1">0000/S 000-000000</cbc:ID>
```

When uploading the very same ESPD Request to the ESPD Service and using the very same dummy TED number, I get the following in the ESPD Response:

```xml
<cbc:ID
    schemeID="ISO/IEC 9834-8:2008 - 4UUID"
    schemeAgencyID="EU-COM-GROW"
    schemeAgencyName="DG GROW (European Commission)" 
    schemeVersionID="1.1">0000/S 000-000000</cbc:ID>
```

1. The TED number is not an UUID.
2. What is the expected schemeID for ESPD Response when a TED number is provided?

**Comment by paulakeen** [comment]
Dear Erlend Klakegg Bergheim,

This is not an issue related to the Exchange Data Model but to the ESPD Service. So please create a new issue in the ESPD Service Issues space (https://github.com/ESPD/ESPD-Service/issues) and copy and paste the name and description of the isue. I could do it myself but then the issue would not be associated to you.

Many thanks!

**Comment by paulakeen** [comment]
The Working Group decided to close this issue as it should be addressed to the ESPD-Service.

**Comment by klakegg** [comment]
What is the new issue number?

**Comment by paulakeen** [comment]
Please see comment by @paulakeen on 15 Jan, namely the part reading "please create a new issue in the ESPD Service Issues space (https://github.com/ESPD/ESPD-Service/issues)". ;)

Tks.,

**Comment by klakegg** [comment]
Please transfer this issue to ESPD/ESPD-Service. Thank you.
