### ISSUE TITLE
Change request for Insurance criteria (Part IV)

### ISSUE THREAD

**Issue by EU-Supply-Renier** [OP-TED/ESPD-EDM#121]
**Background**
In Ireland it’s common to have more that one insurance requirement in procurements. Therefore we would like to suggest an extension for the “Professional Risk Indemnity Insurance” in V1.0.2 data model or the regulated ESPD

**Description of the Extension**
_Area/Scope_
This extension is only applicable for the Economic Operator and for the V1.0.2 or Regulated ESPD data model

_Extension_
1.	We need to Add one more field “Insurance type” to the existing “Professional Risk Indemnity Insurance” criterion. This new field is a simple text field that will allow the EO to specify the insurance type
2.	Allow the EO to Add multiple insurance.

Please see screenshot below for an illustration
![insurance requiremnet](https://user-images.githubusercontent.com/27767920/34870984-1fe0e9bc-f78c-11e7-88a8-06286e074810.PNG)

**Other info**
Please note that we understand that this issue has been addressed it in V2 (self-contained). Therefore our request is only scoped and necessary for the V1.0.2 data model or the regulated ESPD

**Comment by mondorf** [comment]
The regulated ESPD version is mandated by law and fixed according to this mandate. Thus, we are not able to re-open version 1.0.2 and the regulated ESPD. Because of this we cannot implement the requested change.
