### ISSUE TITLE
Need to re-model some data structures as UBL-classes

### ISSUE THREAD

**Issue by paulakeen** [OP-TED/ESPD-EDM#124]
Since the very beginning of the ESPD-EDM until the latest version 2.0.0, some data structures were modelled using the Criterion class to express information that are not true criteria. Examples of this, in version 2.0.0 are:

* C57: OTHER-EO-SHELTERED
* C58: OTHER-EO-PQS
* C59: OTHER-EO-GROUPS
* C60: OTHER-EO-Lots
* C61: OTHER-EO-Contributions
* C62: OTHER-EO-RELIED_ON-ENTITIES
* C63: OTHER-EO-NOT_RELIED_ON-ENTITIES

The information requirements that now are "super-modelled" as data structures in these "false criteria" should go in future UBL classes. Our proposal is to take them into account for the UBL-2.3 version (as a basis for a future ESPD-EDM version 3?).

**Comment by hricolor** [comment]
After present this issue in the last OUC of the 1st of October, and discuss with the stakeholders, this is the proposed solution that will be implemented:

The ‘Other Criteria’ will be kept as per today, except for the ‘OTHER-CA-Lots’ that will be removed. The information asked in other criteria comes from eForms, therefore, the different 'Other Criteria’ will be requested only when CA asks in the CN. 

This issue will be implemented within the next ESPD-EDM 3.0.0.

**Comment by psotofer** [comment]
As commented before, this issue was included in the last ESPD-EDM Release v3.0.0. therefore we proceed to close this issue.
In case you need further detail regarding this topic, please open a new issue referencing this one.
