### ISSUE TITLE
Misalignment between ESPD-CriteriaTaxonomy-V02.00.00.xlsx and ESPD-Data_Structures-SELFCONTAINED-V02.00.01.xlsx

### ISSUE THREAD

**Issue by paulakeen** [OP-TED/ESPD-EDM#125]
The ESPD-Data_Structures-SELFCONTAINED-V02.00.01.xlsx should be updated according to the data structures in files ESPD-Data_Structures-REGULATED-V02.00.01.xlsx and ESPD-Data_Structures-SELFCONTAINED-V02.00.01.xlsx.

**Comment by mondorf** [comment]
The data structures are not aligned between self-contained and regulated ESPD. Enrics team will check this.

**Comment by paulakeen** [comment]
This was done in the transition between 2.0.1 and 2.0.2. In the transition from 2.0.2 to 2.0.3 this is not an issue any more.

This issue should be closed.

**Comment by mireiaBM** [comment]
This issue has been solved in version 2.1.0 of the ESPD-EDM
