### ISSUE TITLE
Sole Contractor and Lead Entity should not share the same code

### ISSUE THREAD

**Issue by paulakeen** [OP-TED/ESPD-EDM#126]
The current version of the ESPD-EDMv2.0.0 defines one single code "SCLE" to both Sole Contractor and Lead Entity.

This is an inconvenient and error-prone when the times comes to draft schematron rules in order to decide whether the role of the economic operator and determine which additional information needs to be required or not.

For version 2.0.1 the rule to distinguish whether the economic operator is a Leader consists in:

The EO role code = SCLE **AND** the element "/cbc:EconomicOperatorGroupName" contains a value.

We propose to discuss this and promote a solution for the release 2.0.2.

**Comment by paulakeen** [comment]
Corrected in the new version of the documentation (ESPD-EDM-2.0.1).

**Comment by mondorf** [comment]
Share Tenderer Structure Works from PEPPOL.

**Comment by mondorf** [comment]
It was concluded to split the roles to better distinguish between these different concepts. However in principal both are responsible to communicate to the CA. A split of roles might be also better for integration with eCERTIS. 
Code list should be extended with two new additional codes one for sole contractor and one for lead entity. There should be a maintenance guideline for the code list illustrating the changes done.

**Comment by paulakeen** [comment]
Decision (see Mondorf, 22 Mar) will be applied in v2.0.3.

**Comment by mireiaBM** [comment]
This issue has been solved in version 2.1.0 of the ESPD-EDM
