### ISSUE TITLE
Part IV, Section B (Professional risk indemnity insurance)

### ISSUE THREAD

**Issue by rantati7** [OP-TED/ESPD-EDM#13]
**Professional risk indemnity insurance**

CA must be able to set the minimum value for the indemnity insurance.

**Comment by JoseLuisCueva** [comment]
I agree.
Perhaps the "expiration date" or the "minimum validity period" should be considered as well.

**Comment by paulakeen** [comment]
Could you please provide examples of particular requirements for several procedures, so we can identify the information that should be required to the CA?

**Comment by steveP1967** [comment]
This is the current version of the ESPD (Scotland) insurance question. Obviously it's not self-contained at the moment, but it does show that the EO will  only "fail"  if they respond that they do not have the required insurance and they cannot commit to obtain it prior to the commencement of the contract. 




![espd insurace question scotland](https://cloud.githubusercontent.com/assets/20239077/24454871/7304cd38-1485-11e7-8d84-5944003247bc.PNG)

Below is the version of the insurance question we used to use in our standard PQQ, before the introduction of the ESPD. This sPQQ was self-contained, and also shows the different types of insurance commonly required. The CA would edit this prior to publication and provide the value of insurance required, and also delete any types of insurance not required for a particular procurement exercise. 
![spqq insurance question](https://cloud.githubusercontent.com/assets/20239077/24455474/998285a2-1487-11e7-9926-d854afb12b7d.PNG)

**Comment by paulakeen** [comment]
Please find below what was commented about this issue in the discussion group:

John Degiorgio: Insurance requiremnts and thresholds are different in various states

John Degiorgio: Agree!

Anne Katrine Mortensen, NIRAS A/S, DK: It´s easy to get the insurance if a firm is awarded the contract.

Steve Pastterson (Scottish Government): yes, but they shouldn't need it up front

John Degiorgio: Moreover, there are countries that do not except insurance from providers of other countries.

John Degiorgio: Accept!

Anne Katrine Mortensen, NIRAS A/S, DK: and a contract will be available at the same time as the contract notice so the requirements will be known.

John Degiorgio: Usually in Malta the insurance is required on contract stage

Anne Katrine Mortensen, NIRAS A/S, DK: john, I don´t think that is according to EU-law.

Jose Luis Cueva - Spain: I agree with Anne Katrina. Allowing to defer the insurance equals to no req at all!

John Degiorgio: A declaration that an EO can provide the required insurance once it is awarded with the contract.

Anne Katrine Mortensen, NIRAS A/S, DK: I prefer insurance as a contract requirement.

Anne Katrine Mortensen, NIRAS A/S, DK: I agree.

Anne Katrine Mortensen, NIRAS A/S, DK: It is a contract thing in Denmark.

John Degiorgio: Too demanding!

John Degiorgio: We don't have to repeat obligations under the particular tender

Anne Katrine Mortensen, NIRAS A/S, DK: I agree with JD

John Degiorgio: ESPD shall only include a declaration whereby the EO shall provide the required insurance covers

John Degiorgio: Yes 

John Degiorgio: Make it simple!

Anne Katrine Mortensen, NIRAS A/S, DK: Normally a CA in Denmark doesn´t ask for insurance info neither in the c. notice nor in the ESPD.

John Degiorgio: So it's very simple!

Jose Luis Cueva - Spain: Example: required coverage against medical malpractice: >1M eur

Jose Luis Cueva - Spain: So: domain of rik, minimal amount

Jose Luis Cueva - Spain: typo: risk

Jose Luis Cueva - Spain: actual/promised

**Comment by paulakeen** [comment]
Please find below a proposal for the mock-ups, as commented in the last meeting:

- View of the CA (without lots)

![image](https://cloud.githubusercontent.com/assets/16134316/24657477/ab843f34-1946-11e7-8df3-27a427367af1.png)

- View of the CA (with lots)

![image](https://cloud.githubusercontent.com/assets/16134316/24657490/b7c3e704-1946-11e7-9b87-7884e5f9a2c2.png)

- View of the EO

![image](https://cloud.githubusercontent.com/assets/16134316/24698063/a8aa1780-19ef-11e7-8c89-644928ae3859.png)

When the amount provided by the EO is < than the minimum amount required by the CA, the EO will need to indicate whether it will commit to obtain the minimum amount required.

**Comment by ec-mcs** [comment]
I will check with Claudio the mutual recognition of insurances between countries.

**Comment by paulakeen** [comment]
Please find below what was commented about this issue in the discussion group:

John Degiorgio: Re insurance I ahve already highlighted this that some countries accept only insurances from their respective jurisdiction

John Degiorgio: Yes agree

John Degiorgio: But there are insurance companies that do not accept such liabilities

Timo Rantanen / Hansel / Finland: insurances have funny clauses.... they do sometimes limit the geographical coverage area

John Degiorgio: I has a surgeon who had a PI from his origin country but to operate in Malta he had to take out another PI

Jose Luis Cueva (Spain): I suspect it is against free flow of services (insurance services)

John Degiorgio: But we cannot put insurances to accept risks that they are not redy to accept. There are types of insurance that by default cover EU members but not all typeof policies. Check it out Marc please

**Comment by paulakeen** [comment]
Please find below a proposal for the solution and mock-up, as commented in the last meeting.

When the CA requests the type of insurance "Employers (Compulsory) Liability Insurance", the EO will be asked if its business is exempt. For all other types of insurance, this option will not be available.

View of the EO:
![image](https://cloud.githubusercontent.com/assets/16134316/25389926/34c24c6e-29d2-11e7-8a42-0a857a622a30.png)

**Comment by JoseLuisCueva** [comment]
I think that "professional indemnity insurance" is too generic; therefore an additional field should be provided for expressing the particular professional field/activity covered (eg. medical practice, engineering project/design defects, etc.). If not, the professional risk covered hast to be inferred from the contract/lot (against self-contained ESPD).
Ideally this additional field should be coded (for interoperability in multi-lingual context) but if not available, a "free text" field could suffice.

**Comment by paulakeen** [comment]
Please find below a new proposal of a mock-up of he view of the EO.

The option "I am exemp" will only be displayed when the type of insurance is "Employers (Compulsory) Liability Insurance".

![image](https://cloud.githubusercontent.com/assets/16134316/25613505/be0dc8fc-2f2e-11e7-8bfd-19dbac091df3.png)

**Comment by paulakeen** [comment]
Please find the details of the final decision in https://github.com/ESPD/ESPD-EDM/wiki/16.-Professional-risk-indemnity-insurance
