### ISSUE TITLE
Cardinality of cac:Evidence/cbc:ID should be mandatory

### ISSUE THREAD

**Issue by mondorf** [OP-TED/ESPD-EDM#131]
The "/QualificationApplicationResponse/cac:Evidence/cbc:ID" should have a cardinality of 1..1 (currently 0..1). 

Reason: If there is an evidence used in the ESPD response, it should be always connected to a criterion and criterion response through a cross reference to the class /QualificationApplicationResponse/cac:TenderingCriterionResponse". 

(similar relationsship occurs between "TenderingCriterionResponse" and  "cac:TenderingCriterion")

 
--

**Comment by paulakeen** [comment]
Your right mondorf, this should have been Cardinality 1 since the beginning. Corrected in version 2.0.1:

1. A Schematron rule has been added to control the cardinality of this element
2. The documentation has been modified

Tks.!
