### ISSUE TITLE
Lots: need for multiple identifiers

### ISSUE THREAD

**Issue by albenzio** [OP-TED/ESPD-EDM#140]
**cac:ProcurementProjectLot/cbc:ID** is the sole element in version 2.0.1 self-contained to reference a Lot.
XML implementation guide suggests:
> Convention: Lots should always be identified with a sequential number, as in the examples: Lot1, Lot2, ..Lot7

In the Italian context, Lots are tagged with a unique identifier (in Italy, it is named CIG) which is obtained from a central authority and that is fundamental for monitoring national expenditure.
The national implementation of electronic ESPD could use **cbc:ID** to reference this unique identifier, with disregard to the naming convention suggested in the guide. Nevertheless, the naming convention does make sense, especially from the EOs perspective: when producing a ESPD response, the EO should be able to identify the Lots for which it is bidding by means of a human-readible identifier (also declared in the contract notice).

This brings to the need for multiple identifiers:

- a Lot identifier, useful for interoperability among systems in the e-procurement framework;

- a Lot identifier which is much more a title for the Lot, recalling what is declared in the contract notice, useful for the software application on the EO side, in order to ease the filling in of the document;

In the Italian case, it should always be possible to associate a CIG given a title of the Lot: this information should be carried by the ESPD, otherwise software applications would require extra data to process the information correctly.

Would it be possible to add an additional identifier to the ProcurementProjectLot?

**Comment by paulakeen** [comment]
We'll discuss this requirement in the UBL-2.3 Technical Committee.

**Comment by paulakeen** [comment]
A Jira Ticket has been created in the UBL-TC assigned for discussion with the Pre-award subcommittee:

Enric Torregrosa created UBL-176:
------------------------------------

             Summary: Lots: need for multiple identifiers
                 Key: UBL-176
                 URL: https://issues.oasis-open.org/browse/UBL-176
             Project: OASIS Universal Business Language (UBL) TC
          Issue Type: Improvement
            Reporter: Enric Torregrosa
            Assignee: Ole Madsen

**Comment by paulakeen** [comment]
The UBL-2.3 assessed this request change and will look forward to implemeting it in UBL-2.3.

The ESPD-EDM Working group decided to include this issue as one important topic to tackle during the discussions with MS and the rest of stakeholders about Lots, to be held asap.

**Comment by hricolor** [comment]
On the one hand, the JIRA ticket created in UBL-TC was rejected, because increasing cardinality of the ID element will require to define a scheme to allow systems to recognize the human-readable identifier from the machine-readable. 
On the other hand, this was also discussed within the ESPD OUC meetings (Thursday 9 of July), it was agreed to only use 1 identifier. This identifier for lots will follow the same logic and the scheme as eForms (for example: LOT-XXXX, where XXXX is a set of 4 digits), to ensure as much as possible the alignment between both models. Therefore, there is no need to use the extension for the identification of Lots with an extra cbc:ID.  

This issue will be fixed in the new version of the ESPD.

**Comment by ec-mcs** [comment]
One addition. We would need five digits not 4. I have seen procedures with more lots than 9999. This should be discussed in the eForms/Ontology group. We will take over the results of it.

**Comment by hricolor** [comment]
> On the one hand, the JIRA ticket created in UBL-TC was rejected, because increasing cardinality of the ID element will require to define a scheme to allow systems to recognize the human-readable identifier from the machine-readable.
> On the other hand, this was also discussed within the ESPD OUC meetings (Thursday 9 of July), it was agreed to only use 1 identifier. This identifier for lots will follow the same logic and the scheme as eForms (for example: LOT-XXXX, where XXXX is a set of 4 digits), to ensure as much as possible the alignment between both models. Therefore, there is no need to use the extension for the identification of Lots with an extra cbc:ID.
> 
> This issue will be fixed in the new version of the ESPD.

According to the discussion and the decision made in the OUC meeting from Thursday 9th July, this has been aligned with eForms and therefore there is no need to include additional identifiers.
