### ISSUE TITLE
Need for consistency in v2.0.x UUIDs

### ISSUE THREAD

**Issue by paulakeen** [OP-TED/ESPD-EDM#141]
In ESPD-EDM version 2.0.1 some UUIDs that are assigned to identical data structures (or sub-structures) are different (e.g. the group related to the question "Is this information available electronically", amongst other. This is not coherent and should be corrected in version 2.0.2.

**Comment by paulakeen** [comment]
We need you to be more specific. Can you enumerate which criteria, group or property exactly (criteria number, spread-sheet tab name, row in the spread-sheet, etc.) are affected?

In the case of the UUIDs for the "Is this information available electronically" no inconsistency should occur from version 2.0.2 on...but we'll review it once more in version 2.0.3!

**Comment by mireiaBM** [comment]
This issue has been solved in version 2.1.0 of the ESPD-EDM
