### ISSUE TITLE
v2.0.2 examples are not valid ESPD files

### ISSUE THREAD

**Issue by jerouris** [OP-TED/ESPD-EDM#146]
The Example artifacts found in github (branch 2.0.2 and current master) do not pass validation on the ISA ESPD Validator. 

Problematic artifacts: 
https://github.com/ESPD/ESPD-EDM/blob/master/docs/src/main/asciidoc/dist/xml/REGULATED_ESPD-Request_2.0.2.xml
https://github.com/ESPD/ESPD-EDM/blob/master/docs/src/main/asciidoc/dist/xml/REGULATED_ESPD-Response_2.0.2.xml

**Comment by lotzmann** [comment]
I have done some analysis on this issue. Cause are invalid characters (line feed, space) between UUIDs and the end tag `</cbc:ID>` in 58 cases, for example at lines 2003, 2013, 2054, etc. in REGULATED_ESPD-Request_2.0.2.xml.

**Comment by paulakeen** [comment]
New examples were provided some months ago.... Do you still experience problems with this? Please confirm. Thanks

**Comment by paulakeen** [comment]
v2.03. will provide new XML valid and validated examples.

**Comment by mireiaBM** [comment]
This issue has been solved in version 2.1.0 of the ESPD-EDM
