### ISSUE TITLE
Part IV B:  Set up of economic operator should be shown with turnover

### ISSUE THREAD

**Issue by ec-mcs** [OP-TED/ESPD-EDM#148]
Currently the criterion "Set up of economic operator" - In case the information concerning turnover (general or specific) is not available for the entire period required, please state the date on which the economic operator was set up or started trading
Is disconnected from the turnover criteria. It should appear when a CA selects a turnover criterion.

**Comment by paulakeen** [comment]
@MC: Would this not be an ESPD-Service-related issue? I don't see how this affects the ESPD-EDM?

**Comment by paulakeen** [comment]
This is an ESPD-Service related issue. The WG decided to transfer it to the ESPD-Service issues and close this one.
