### ISSUE TITLE
Part IV C: In references receipients should be categorised into public/private

### ISSUE THREAD

**Issue by ec-mcs** [OP-TED/ESPD-EDM#149]
The 2016/7 ESPD regulation states for references:
When drawing up the list, please indicate the amounts, dates and beneficiaries, **whether public or private**.

We should categorize recipients in the following:

- Public
- Private
- Private/Public

**Comment by paulakeen** [comment]
It could be easily introduced in v2.0.3. The impacts would be:
1) Modify slightly the Data Structure to add a code
2) Create the Code List "Reference Beneficiary Type" (or similar name)
3) Document this in the online documentation.

**A question, though**: 

Shoud we tackle this only in SELF-CONTAINED? if we   introduce it in REGULATED too the foward-compatibility mapping between v1.0.2   and 2.0.3 won't cover this datum.

**Comment by paulakeen** [comment]
The decision by the WG was not to modify the data structure in order not to break backwards compatibility.
