### ISSUE TITLE
Part IV: Selection criteria, C: Technical and professional ability - For works contracts

### ISSUE THREAD

**Issue by rantati7** [OP-TED/ESPD-EDM#15]
**For works contracts: performance of works of the specified type**

CA must be able to define the specified type

CA must be able to define minimum requirements for the performance of works.

**Comment by rantati7** [comment]
it would be good if this quesions would be shown only if works in question.

**Comment by paulakeen** [comment]
We move to this issue the requirements from issue #19, for both issues are related:

**For works contracts: technicians or technical bodies to carry out the work**
CA must be able to define minimum criteria for technicians or technical bodies
It would be good if the question is shown only if works contracts in question.

**Comment by paulakeen** [comment]
Unified with issue #7 
Please find the details of the final decision in https://github.com/ESPD/ESPD-EDM/wiki/23.-Criteria-for-a-particular-type-of-contract
