### ISSUE TITLE
Part V:  Reduction of the number of qualified candidates

### ISSUE THREAD

**Issue by paulakeen** [OP-TED/ESPD-EDM#150]
The information required in PART V of Annex 2 of the [ESPD Regulation](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:32016R0007&from=EN) should be captured in the ESDP-EDM v.2.0.3.

**Comment by mondorf** [comment]
Hi Enric, another subrequest with regard to this issue. The documentation should also make clear how the PART V behaves in relation to Weighting. Thus, few process/business rules are required that explain the consequences if weighting is used:
- Just for certain procedures (I think this is already in your specs)
- No Part V

**Comment by ec-mcs** [comment]
The rules are simple:
Open procedure: No weighting, no Part V
Everything else: 

- Weighting used in ESPD v2sc, no Part V
- Weighting not used in ESPD v2sc, Part V necessary

**Comment by mireiaBM** [comment]
This issue has been solved in version 2.1.0 of the ESPD-EDM
