### ISSUE TITLE
Inconsistent UUIDs

### ISSUE THREAD

**Issue by lotzmann** [OP-TED/ESPD-EDM#151]
The rationale for a UUID change is not clear in one case and should be revisited:
The UUID of the Question Group containing the Question “Have you taken measures to demonstrate your reliability (Self-Cleaning)?” has been changed for criteria related to EG-Convictions, but left untouched for other criteria.
UUID for EG-Convictions in ESPD 2.0.2 regulated: `f4978772-3126-4ded-bc30-f50da8c3a038`
UUID in other cases and in ESPD 1.0.2: `5f9f09f7-f701-432c-9fdc-c22c124a74c9`

**Comment by paulakeen** [comment]
It's a bug; v2.0.2 UUID should be aligned to the v1.0.0 UUID in all cases, not only in the case of Convictions. Proposed to change in v2.0.3.

**Comment by lotzmann** [comment]
I have further investigated this topic and put together a detailed analysis for criteria affected by this and similar issues - see [UUID-Anomalies_2018-09-27a.pdf](https://github.com/ESPD/ESPD-EDM/files/2426041/UUID-Anomalies_2018-09-27a.pdf).

**Comment by paulakeen** [comment]
Done in v2.0.3. We'll close this issue because its identifical to issue #141.
