### ISSUE TITLE
Criterion 58: EO registered in a PQS

### ISSUE THREAD

**Issue by lotzmann** [OP-TED/ESPD-EDM#152]
Rather an editorial question than an issue: In criterion 58, the Questions “_Will the economic operator be able to provide a certificate with regard to the payment of social security contributions and taxes or provide information enabling the contracting authority or contracting entity to obtaining it directly by accessing a national database in any Member State that is available free of charge?_” was tagged as point “_e)_” in ESPD 1.0.2, which has been removed in ESPD 2.0.2 regulated. Was this done on purpose?

**Comment by paulakeen** [comment]
ESPD-EDM   2.0.2 DID NOT removed this criterion neither in the REGULATED nor in the   SELF-CONTAINED versions. See criterion #63 in tab OTHER-EO-Contributions of   the spread-sheet containing the data structures, please.

Beware though that in the ESPD Service this question is located under "Part II: Information concerning the economic operator", "Section A: information about the economic operator", paragrah under the title: "In addition, please complete the missing information in Part IV, Sections A, B, C or D as the case may be ONLY if this is required in the relevant notice or procurement documents".

**Comment by mireiaBM** [comment]
This issue has been solved in version 2.1.0 of the ESPD-EDM
