### ISSUE TITLE
Criterion 60: Relied on entities

### ISSUE THREAD

**Issue by lotzmann** [OP-TED/ESPD-EDM#153]
Rather an editorial question than an issue: A completely new structure for Criterion 60 has been introduced in ESPD 2.0.2 regulated, which makes it incompatible with ESPD 1.0.2. This regards the following Questions:
“_Name of the entity_”
“_ID of the entity_”
“_Activity of the entity (for this specific procedure)_”
“_Is this information available electronically?_”
“_Evidence supplied_”
Has this been added to ESPD 2.0.2 regulated on purpose, or was it designed for the self-contained ESPD?

**Comment by paulakeen** [comment]
If we intend to keep maximum compatibility between the Regulated versions the splitting should go only to the Self-contained and not to the Regulated.

Hence I propose that, in v2.0.3, we roll-back the decision of the splitting and keep it only for the Self-Contained "flavour" of the ESPD.

**Comment by paulakeen** [comment]
Proposals exclusively oriented to ensure compatibility need more reflection and would be taken into account in next revision. The proposal is therefore rejected for the time being.

**Comment by mfontsan** [comment]
This issue was solved in version 2.1.0 of the model. The structure is in the extended model and not in basic onw.
