### ISSUE TITLE
Criterion 61: Not relied on entities

### ISSUE THREAD

**Issue by lotzmann** [OP-TED/ESPD-EDM#154]
Rather an editorial question than an issue: The structure for Criterion 61 has been revised in ESPD 2.0.2 regulated, which makes it incompatible with ESPD 1.0.2. 
The Requirement “_If yes and in so far as known, please list the proposed subcontractors:_” has been split into three Questions “_Name of the entity_”, “_ID of the entity_” and “_Activity of the entity (for this specific procedure)_”.
Has this been added to ESPD 2.0.2 regulated on purpose, or was it designed for the self-contained ESPD?

**Comment by paulakeen** [comment]
If we intend to keep maximum compatibility between the Regulated versions the splitting should go only to the Self-contained and not to the Regulated. 

Hence I propose that, in v2.0.3, we roll-back the decision of the splitting and keep it only for the Self-Contained "flavour" of the ESPD.

**Comment by mireiaBM** [comment]
To end the discussion, we must clarify the following aspects:
1. We think that @paulakeen suggestion of rolling back the splitting only in the regulated model should be implemented.
2. However, a version 2.0.3 was never produced. Instead, it ended up as version 2.1.0 (which never included this issue)
3. It should be included in version 2.1.1

**Comment by JosePRevenga** [comment]
As mireiaBM announced in her comment, in new v2.1.1 the first question subgroup of Criterion #61: NOT_RELIED_ON_ENTITITES of Basic model has been rolled-up to the state on previous v1.0.2, so to ensure maximum compatibility between versions. I.e. "Name of entity", "ID of the entity" and "Activity of the entity" questions have been removed.
