### ISSUE TITLE
EG-Conviction Criteria: Cardinality

### ISSUE THREAD

**Issue by MariaSpr** [OP-TED/ESPD-EDM#155]
In the CriteriaTaxonomy Regulated v2.0.2, at the EG-Conviction Criteria and more specifically at the question-groups with UUID `7c637c0c-7703-4389-ba52-02997a055bd7`
the cardinality should be 1 and not 1...N

![cardinalities_1n](https://user-images.githubusercontent.com/15072613/45297226-58928600-b50d-11e8-8c24-890537bea2f0.PNG)

**Comment by paulakeen** [comment]
Agree, both in the Regulated and Self-Contained ESPD data structures. This will be corrected in v2.0.3.

**Comment by paulakeen** [comment]
This is also in https://github.com/ESPD/ESPD-EDM/issues/173. So I close this one.
