### ISSUE TITLE
Need to add combination of EO Roles

### ISSUE THREAD

**Issue by ec-mcs** [OP-TED/ESPD-EDM#156]
https://espd.github.io/ESPD-EDM/v2.0.2/xml_guide.html#mock-up-selfcontained-economic-operator
We have currently the following roles for an EO

- Sole contractor
- Lead entity
- Group member
- Other entity (relied upon)
- Other entity (not relied upon)

We need to add the possibility that an EO could have the two roles in one bid
- Other entity (relied upon)
- Other entity (not relied upon)

The reason behind this is that (relied upon) only means that this EO is needed to fulfil the selection criteria (like turnover) but is not necessary to actually do some work. And it happens not seldom that an EO is not only needed to fulfil the selection criteria but also is a subcontractor.

We should check with the ontology if we could not find a clearer wording for
- Other entity (relied upon)
- Other entity (not relied upon)

A suggestion would be
- EO to fulfil the selection criteria
- Subcontractor

**Comment by AJDAKOST** [comment]
About the EO roles:

The question that relates to Chapter 5. “EO roles”, more exactly the part of the picture saying: “Is the EO participating in the procurement procedure together with others;…”, where the information on who fulfills it or what kind of answers has to give here (especially in the case of other entity) regarding the relationship between the lead entity and the other entity (relied upon and not relied upon) is missing or in our opinion, it is not clearly evident.

Thank you for the answer.

**Comment by paulakeen** [comment]
My opinion -->Tackling this aspects needs reflection on both the business and the technical sides:

@MCS: Adding new codes to this code list should be agreed with OP (NMURIC) as they do also need this code list for the ontology.
@MCS: Allowing multiple cardinality to this code needs implies: (1) controlling which roles may be combined and which not (e.g. two "lead" EO cannot be possible, one "lead" and "subcontractor" can be allowed, "subcontractor" and "EO to fulfill" would not be possible, would it? etc. (2) Is it actually possible to have an EO partner of a consortium or sole contractor that is or is not an EO to fulfill, but not both? 

@AJDAKOST: documenting and implementing the roles well imply understanding well the meaning of the roles, and as you can see from the discussion thread not all roles, and combinations of roles, are clear in everyone's mind. So let's clarify them first please, for which we need also relevant attendants: you, OP, ESPDint, CEN TC440 representatives, ISA, MS, COM....

**Comment by hricolor** [comment]
After present this issue in the last OUC of the 1st of October, and discuss with the stakeholders, this is the proposed solution that will be implemented:

The roles within the ESPD will be kept as simple as possible, allowing only 1 role per EO and procedure. 

This issue will be implemented within the next ESPD-EDM 3.0.0.

**Comment by psotofer** [comment]
As commented before, this issue was included in the last ESPD-EDM Release v3.0.0. therefore we proceed to close this issue.
In case you need further detail regarding this topic, please open a new issue referencing this one.
