### ISSUE TITLE
Payments of Taxes and Social Security

### ISSUE THREAD

**Issue by AJDAKOST** [OP-TED/ESPD-EDM#157]
The question that relates to Chapter 10. “Payments of Taxes and Social Security”. What answer options will be at EO disposal (ESPDResponse), when CA will indicate the threshold value (in accordance with international legislation) in ESPDRequest form? Our suggestion would be an option Yes/No only instead of a field, which allows detailed explanations.

Thank you for the answer.

**Comment by paulakeen** [comment]
@AJDAKOST: can you please explain with more detail the context? e.g. 

- "Chapter 10. “Payments of Taxes and Social Security" of which document?
- "Yes/No" as an answer to what question?

In ESPD-EDM v.2.0.x only the [self-contained](https://github.com/ESPD/ESPD-EDM/blob/master/docs/src/main/asciidoc/dist/cl/xlsx/ESPD-CriteriaTaxonomy-SELFCONTAINED-V2.0.2.xlsx) "flavour" allows for the specification of a threshold in the case of social contributions. As far as I remember only one country raised this as a legal need (was it Lithuania?).

**Comment by AJDAKOST** [comment]
In accordance with the Slovenian legislation CA shall exclude an EO from participation in a procurement procedure where they have established, by verifying, that the EO has not complied with its obligations relating to the payment of compulsory charges or other pecuniary non-tax liabilities under the law governing financial administration, collected by the tax authority in accordance with the regulations of the country in which it is established or with the regulations of the country of the contracting authority, where those unpaid overdue liabilities total EUR 50 or more as at the date of the submission of the tender or request. An economic operator shall also be considered not to comply with its obligations as referred to in the preceding sentence if, by the date of the submission of the tender or request, it has not submitted all the withholding tax returns for income from the employment relationship for the period of five years preceding the date of the submission of the tender or request.

If we understand correctly, ESPD (in Chapter 10. “Payments of Taxes and Social Security")  instructs the EO to fill in the specific amount of unpaid taxes, if applicable. Since in Slovenia, the proof of the (non)existence of this exclusion ground is acquired at a later stage by the CA from the official evidence only in the form of the statement (yes – unpaid taxes are higher than 50 euros, no- unpaid taxes are higher than 50 euros) we believe there is no need for the EO to fill in the eventual amount of non-payed taxes.

**Comment by paulakeen** [comment]
We already have this threshold, but only the ESPD-EDM Self-contained. As far as this particularity is not in the ESPD Regulation the decision by the rest of the MS and members of the Working Group was not to included in the ESDP-EDM Regulated version.

**Comment by mireiaBM** [comment]
If you have a look at Criterion #7 or #8, you will notice that the group of questions identified as f8499787-f9f8-4355-95e2-9784426f4d7b has cardinality 0..1, meaning that, if it is not appropriate to provide the amount of taxes the EO has the possibility to not provide this information.
