### ISSUE TITLE
Criteria for a particular type of contract

### ISSUE THREAD

**Issue by AJDAKOST** [OP-TED/ESPD-EDM#158]
The question that relates to Chapter 23. “Criteria for a particular type of contract”. What about mixed procurement (i.e. public contracts which have as their subject-matter two or more types of procurement (works, services or supplies))? For example: In the case of mixed contracts consisting partially of services and partially of works, the CA wants from EO to fulfil both types of criteria (for works contracts and for service contracts). Will there be an option in a form to display criteria for both types?

Thank you for the answer.

**Comment by paulakeen** [comment]
This needs analysis and discussion with the MS, the legal team, other stakeholders.

**Comment by psotofer** [comment]
Good morning,

The information related to type of contract will be provided by eForms in the pertinent Lot. 
Henceforth, there is no need to include this element in the new version of ESPD.

Best Regards.

**Comment by ec-mcs** [comment]
Indeed. This issue was discussed in the group and we came to the same conclusion. The issue was closed therefore.
