### ISSUE TITLE
Criterion 32 ("Specific yearly turnover"): Cardinality

### ISSUE THREAD

**Issue by lotzmann** [OP-TED/ESPD-EDM#159]
In the CriteriaTaxonomy Regulated v2.0.2, at criterion 32 ("Specific yearly turnover") and more specifically at the question group with UUID `c0cd9c1c-e90a-4ff9-bce3-ac0fe31abf16`, the cardinality should be 1..n and not 1.

**Comment by paulakeen** [comment]
Agree....it will be fixed in v2.0.3.

**Comment by mireiaBM** [comment]
This issue has been solved in version 2.1.0 of the ESPD-EDM
