### ISSUE TITLE
Part IV: Selection criteria, C: Technical and professional ability - For supply contracts

### ISSUE THREAD

**Issue by rantati7** [OP-TED/ESPD-EDM#16]
**For supply contracts: performance of deliveries of the specified type** 

CA must be able to define the specified type

CA must be able to define minimum requirements for the performance of deliveries

**Comment by rantati7** [comment]
Again would be good if this could be shown only if supply contract in question

**Comment by paulakeen** [comment]
Requirements from issue #30:
**For supply contracts: samples, descriptions or photographs without certification of authenticity**
CA must be able to define the required samples etc: what samples it requires, how are those going to be used and where & when the samples will need to be delivered.
It would be good if this question is only shown when supply contracts in question.

**Comment by paulakeen** [comment]
Requirements from issue #31 :
**For supply contracts: samples, descriptions or photographs with certification of authenticity**
CA must be able to define the required samples etc: what samples it requires, how are those going to be used and where & when the samples will need to be delivered.
It would be good if this question is only shown when supply contracts in question.

**Comment by paulakeen** [comment]
From issue #32 
**For supply contracts: certificates by quality control institutes**
CA must be able to define what is required
Agree, we think when the ESPD is self-contained the required certificates/standards should sit next to the question.
It would also be useful, if this only appeared when it was a supply contract - perhaps if there was a conditional question at the start of the ESPD asking if the tender was goods, works or services the appropriate questions could pre-populate.

**Comment by paulakeen** [comment]
Unified with issue #7
Please find the details of the final decision in https://github.com/ESPD/ESPD-EDM/wiki/23.-Criteria-for-a-particular-type-of-contract
