### ISSUE TITLE
Social Contributions data structure needs to be updated

### ISSUE THREAD

**Issue by paulakeen** [OP-TED/ESPD-EDM#160]
The current data structure (v.2.0.2) is not aligned to the ESPD Regulation specification nor the current ESPD-Service behaviour. It should be corrected.

**Comment by paulakeen** [comment]
Yes:

1. The Schematron needs to be corrected, but I need to consult this issue with Maria first, and she’s on holidays until the 3rd. (next week).
2. About the data structure (the indicators-related issue): the rule is the closest “parent” indicator, understanding by “parent” the indicator that is exactly at same level as the group with “ONTRUE/ONFALSE” condition. The problem with the example you provide is that the structure provided in v2.0.2 doesn’t exactly match the behaviour of the current ESPD Service interface, and would need to be modified as depicted below:

![socialcontributions](https://user-images.githubusercontent.com/16134316/46138697-d3b5a500-c24c-11e8-9270-69322b4261dc.jpg)

**Comment by mireiaBM** [comment]
This issue has been solved in version 2.1.0 of the ESPD-EDM
