### ISSUE TITLE
Scotland needs additional financial ratios

### ISSUE THREAD

**Issue by ec-mcs** [OP-TED/ESPD-EDM#161]
Steve send an eMail to me on 29 September 2018 
Please find attached the additional ratios that have been most frequently requested by users of our ESPD service here in Scotland. 

Ratio   Name | Definition
-- | --
Acid Test Ratio | Liquid Assets (Cash and Cash Equivalents   + Marketable Securities + Accounts Receivable) /    𝐶𝑢𝑟𝑟𝑒𝑛𝑡   𝐿𝑖𝑎𝑏𝑖𝑙𝑖𝑡𝑖𝑒𝑠
Cash Interest Cover Ratio | 𝐸𝑎𝑟𝑛𝑖𝑛𝑔𝑠   𝑏𝑒𝑓𝑜𝑟𝑒 𝐼𝑛𝑡𝑒𝑟𝑒𝑠𝑡,𝑇𝑎𝑥𝑎𝑡𝑖𝑜𝑛,   𝐷𝑒𝑝𝑟𝑒𝑐𝑖𝑎𝑡𝑖𝑜𝑛   𝑎𝑛𝑑 𝐴𝑚𝑜𝑟𝑡𝑖𝑠𝑎𝑡𝑖𝑜𝑛 /    𝐼𝑛𝑡𝑒𝑟𝑒𝑠𝑡   𝑃𝑎𝑦𝑎𝑏𝑙𝑒
Return on Capital Employed | 𝐸𝑎𝑟𝑛𝑖𝑛𝑔𝑠   𝑏𝑒𝑓𝑜𝑟𝑒 𝐼𝑛𝑡𝑒𝑟𝑒𝑠𝑡   𝑎𝑛𝑑 𝑇𝑎𝑥 /   𝑇𝑜𝑡𝑎𝑙   𝐴𝑠𝑠𝑒𝑡𝑠 − 𝐶𝑢𝑟𝑟𝑒𝑛𝑡   𝐿𝑖𝑎𝑏𝑖𝑙𝑖𝑡𝑖𝑒𝑠
Operating Profit ratio | 𝑂𝑝𝑒𝑟𝑎𝑡𝑖𝑛𝑔   𝑃𝑟𝑜𝑓𝑖𝑡 /   𝑇𝑢𝑟𝑛𝑜𝑣𝑒𝑟
Gearing | Total   Long Term Liabilities (excluding Pension Liability and Provisions) /    Shareholder   Funds
Net Profit Margin | Net   Profit /    Revenue

**Comment by steveP1967** [comment]
The following additional ratios have also been requested by users:

| Ratio                                      | Calculation                                                                       |
|--------------------------------------------|-----------------------------------------------------------------------------------|
| Profit   before interest and  taxes (PBIT) | Net   profit + Interest + Taxes.                                                  |
| Interest   coverage                        | Earnings   before interest and taxes (EBIT) / interest payments due in the period |
| Net current   assets                       | Current assets   / current liabilities                                            |
| Gearing:   debt-to-equity                  | Total debt /   total equity                                                       |

**Comment by steveP1967** [comment]
Hi Paula  and MC - I have now had further clarification from our accountancy experts here in Scotland, who agree that the original list of ratios should be sufficient for most user needs. We have now created additional guidance for users on.   Therefore please consider that these additional ratios are no longer required, and that this issue can be closed.
