### ISSUE TITLE
ESPD-EDM SELF-CONTAINED: Distinction between Requirement Subgroups and Question Subgroups

### ISSUE THREAD

**Issue by paulakeen** [OP-TED/ESPD-EDM#162]
Is there a way of distinguishing between the requirement group (and sub group) and the question group (and subgroup)?

**Comment by paulakeen** [comment]
The Data Structure makes this distinction clear, but this is just a "meta-language" used to generate XML example instances where both REQUIREMENT_GROUP/_SUBGROUP and QUESTION_GROUP/_SUBGROUP end up both as cac:TenderingCriterionPropertyGroup or cac:SubsidiaryTenderingCriterionPropertyGroup.

Two ways of solving this could be to use the cbc:PropertyGroupTypeCode differently to how we're doing it now (e.g. appending REQUIREMENT_GROUP_ON*, REQUIREMENT_GROUP_ONTRUE, REQUIREMETN_GROUP_ONFALSE, QUESTION_GROUP_ON*, QUESTION_GROUP_ONTRUE, QUESTION_GROUP_ONFALSE). This solution would not impact on the schema, but the CodeList would have to be enriched with these new codes.
A second option would be to add a new element to the schema, e.g. a cbc:PropertyGroupContentType or similar, to indicate the type of content we're referring to.

**Comment by paulakeen** [comment]
**NOTICE that** each CriterionProperty, inside a group or a sub-group, is identified as CAPTION, REQUIREMENT or QUESTION. 
Hence, one way of deducing whether a group a group of requirements is to detect whether the first element (different to CAPTION) inside the group is of type REQUIREMENT or of type QUESTION.

**Comment by paulakeen** [comment]
An alternative powerful and flexible solution would be to enrich the XML instances with annotations. This solution would help plan a "transition period" that does not break the back-wards compatibility and yet allows the software developers to understand what is each group or property about and process them in many different ways. 

Let me put you one nice example. Take for instance a complex Criterion like the ESPD-EDM SELFCONTAINED Suitability "Enrolment in a relevant professional register" (Criterion #25 in the ESPD-CriteriaTaxonomy-SELFCONTAINED-V2.0.2.xlsx file).

We could add the following "annotations" in the xls spread-sheet of the new version 2.0.3:

![selfcontained_espd_request-annotatedcriterion-proposal](https://user-images.githubusercontent.com/16134316/48211370-a561d400-e379-11e8-9ec6-42940c4996c4.png)

[Click here to download the spread-sheet](https://github.com/ESPD/ESPD-EDM/blob/2.0.3/docs/src/main/asciidoc/dist/doc/evolution/Annotations%20Proposal/ESPD-CriteriaTaxonomy-SELFCONTAINED-V2.0.3-Annotated-Proposal.xlsx) corresponding to the figure above.

The [XLS-T transformation artefacts developed for version 2.0.2](https://github.com/ESPD/ESPD-EDM/tree/2.0.2/docs/src/main/asciidoc/dist/xslt) could be evolved to produce annotated XML instances ([click here to download an example of ESPD-SELFCONTAINED-Request with annotations](https://github.com/ESPD/ESPD-EDM/blob/2.0.3/docs/src/main/asciidoc/dist/doc/evolution/Annotations%20Proposal/SELFCONTAINED_ESPD-Request.V2.0.2-Annotated-Proposal.xml)). 

This is just a proposal. Please feel free to contribute in optimising the proposal or in providing any feedback about the convinence or inconvienience of using this method.

Thanks!

**Comment by mireiaBM** [comment]
This issue has been solved in version 2.1.0 of the ESPD-EDM
