### ISSUE TITLE
Weighting: documentation not clear

### ISSUE THREAD

**Issue by paulakeen** [OP-TED/ESPD-EDM#164]
Regarding the weighting, there are some things in the mockup that are not reflected back to the taxonomy. For example, the requirement "Is this criterion weighted" is the only thing / requirement that exists in the taxonomy, but in the mockup and the XML there are way more elements that need to be added. Is there a convention that one can use on what the elements should be inside the weighted criteria? The EDM is a bit confusing, mentioning root elements, criteria elements and requirements, but I can't understand the correlation, if there is any, between the weighted elements and the taxonomy.

**Comment by paulakeen** [comment]
The problem here is that the information is separated I different (and far-away) places inside the XML. And additionally the documentation is a confusing because the bullet numbers are spread in two mockups; we also see that at least one sentence of the mockup ("One or more criteria will be weighted") is different from the XML example ("Is this criterion weighted?"). We'll try to clarify this in the documentation, and clarify the relationship between the mockups, the XML example and the Data Structure.

**Comment by mireiaBM** [comment]
This issue has been solved in version 2.1.0 of the ESPD-EDM
