### ISSUE TITLE
Cardinality of evidences

### ISSUE THREAD

**Issue by paulakeen** [OP-TED/ESPD-EDM#165]
For one given criterion the user should be able to provide more than one evidence. Right now the cardinality of the QUESTION in QUESTION_SUBGROUP 41dd2e9b-1bfd-44c7-93ee-56bd74a4334b is set to 0..1 and should be modified to 1..n (see data structures "Is this information availabe electronically").

**Comment by paulakeen** [comment]
Will be addressed in v2.0.3.

**Comment by mireiaBM** [comment]
This issue has been solved in version 2.1.0 of the ESPD-EDM
