### ISSUE TITLE
Semantisation of Response Data Types

### ISSUE THREAD

**Issue by paulakeen** [OP-TED/ESPD-EDM#166]
# Context

The Criterion and Evidence Vocabulary is a very generic one. This generic design of the vocabulary was intended precisely to be reused cross-sector.

The vocabulary was introduced in the OASIS UBL-2.2 syntax as part of the pre-award [aggregate business information elements library](https://github.com/ESPD/ESPD-EDM/blob/master/docs/src/main/asciidoc/dist/mod/UBL-Entities-2.2-Pre-award.xls) (cac:TenderingCriterion and related elements).

# Issue

Due to its generality the XSD Schema elements for the Criterion are devoided of business-domain semantics. Hence, a particular domain software application needs to know how concrete groups and subgroups of data elements are uniquelly identified and organised  in order to process them adequately. 

In order to help developers process the rich set of criteria existing in eProcurement, the ESPD-Exchange Data Model (since version 2.0.0) provides two artefacts (two spread-sheets) where every exclusion and selection criterion is structurally represented, uniquelly identified and coded: see the files "[ESPD-CriteriaTaxonomy-REGULATED-V2.0.3.xlsx](https://github.com/ESPD/ESPD-EDM/blob/master/docs/src/main/asciidoc/dist/cl/xlsx/ESPD-CriteriaTaxonomy-REGULATED-V2.0.2.xlsx)" and "[ESPD-CriteriaTaxonomy-SELFCONTAINED-V2.0.3.xlsx](https://github.com/ESPD/ESPD-EDM/blob/master/docs/src/main/asciidoc/dist/cl/xlsx/ESPD-CriteriaTaxonomy-SELFCONTAINED-V2.0.2.xlsx)". Each criterion is therein defined by means of "data structures" made of groups and subgroups of REQUIREMENTs and QUESTIONs.

Notwithstanding, there are some circumstances where data that are part of the criterion previously existed or were defined for the UBL-2.2 XSD Schema. This cast the situation where part of the data are defined in the Schema (sometimes in diferent far-away parts of it) AND parts of them are defined in the Criterion Data Structure.

This is the case for the data structure with the QUESTION "Is this information available electronically"? In this particular case, in case of a "Yes" answer, the Economic Operator has to introduce the identifier of an evidence, which according to the Code List "ResponseIdentifier" has to be of type **EVIDENCE_IDENTIFIER**.

This type of identifier helps software applications to "understand" what this structure is about and where to find the data in the XML instance (namely from elements that are defined in the XSD Schema).

The recent developments of the SELF-CONTAINED data structures has revealed that this approach is also necessary in, at least, two other circumstances, for the **identification of Lots** and the **identification of weighted criteria**. The reason is exactly the same as for the identification of evidences: the data is spread in both the UBL-2.2 XSD Schema and the Criterion Data Structures. 

# Solution proposed

Add two new codes to the ResponseDataType Code List: 

- **LOT_IDENTIFIER**
- **WEIGHT_INDICATOR** 

Modify the Data Structures in the ESPD-CriteriaTaxonomy-SELFCONTAINED spread-sheet where these types are used.

**Comment by paulakeen** [comment]
Two   new codes have been added to the [ResponseDataType Code List](https://github.com/ESPD/ESPD-EDM/blob/2.0.3/docs/src/main/asciidoc/dist/cl/xlsx/ESPD-CodeLists-V2.0.3.xlsx): 

- **LOT_IDENTIFIER** (used in tabs "SC-Suitability-I", "SC-Suitability-II", "SC-Professional_risk_insurance", "SC-References" of spreadsheet [ESPD-CriteriaTaxonomy-SELFCONTAINED-V2.0.3.xlsx](https://github.com/ESPD/ESPD-EDM/blob/master/docs/src/main/asciidoc/dist/cl/xlsx/ESPD-CriteriaTaxonomy-SELFCONTAINED-V2.0.2.xlsx));

- **WEIGHT_INDICATOR** (used in tab "SC-Abilities_1" of spreadsheet [ESPD-CriteriaTaxonomy-SELFCONTAINED-V2.0.3.xlsx](https://github.com/ESPD/ESPD-EDM/blob/master/docs/src/main/asciidoc/dist/cl/xlsx/ESPD-CriteriaTaxonomy-SELFCONTAINED-V2.0.2.xlsx));

**Comment by mireiaBM** [comment]
This issue has been solved in version 2.1.0 of the ESPD-EDM
