### ISSUE TITLE
ESPD Taxonomy self contained 2.0.2

### ISSUE THREAD

**Issue by AFSOLUZIONI** [OP-TED/ESPD-EDM#167]
we are customizing ESPD taxonomy self-contained 2.0.2 with our national (italian) criteria.
In this job we discover some problem or question to submit to you. First of all I have a question about criteria from 42 to 47 in the tab "SC-Abilities_1". It seems that they are a kind of "cut & paste" of the previous criteria and, in some case (e.g. 42 that refer to machine) the "first name" and "last name" seems to be inappropriate. I'm wrong?? Please could you explain me the ratio?? 

I have a lot of question more. Could be better to include all of them in an attach or I must write down them in one or more question.
Thank you for a response.

**Comment by paulakeen** [comment]
Dear AFSOLUZIONI, many thanks for your comments. 

Regarding your last question: it's better if you split in different very atomic issues each problem than if you put them altogether.

Regardin the first part ... let us have a look into Criteria 42 to 47 and we'll come back with a response shortly.

**Comment by paulakeen** [comment]
Dear AFSOLUZIONI, you're right about the "copy-pasting" isssue in criteria [42, 47]. 

We need a  bit of more time to discuss with GROW and MS how to solve this, as we could need to model some relevant data per each of these criteria (e.g. about the technical body).

If you have modelled this already please feel free to suggest how YOU would structure these particular criteria.

We'll come back to you asap.

**Comment by paulakeen** [comment]
Dear Francesco,

It would be really great if you could propose how the data structures of criteria 42 to 47 should look like. We mean, which requirements and questions each criterion should ask for.

I'll send an email to Giampaolo Selitto (i don't have your email) inviting you, Timo Rantanen (FI), José Luis Cueva (ES) and Steven Patterson (Scotland) to parcitipate in a short meeting ASAP so we can propose the most final data structures we can for these criteria.

And of course any other MS or stakeholder is invited to contribute, too, as well. So, please, anyone interested in joining this meeting show your interest.

KR
Enric

**Comment by paulakeen** [comment]
We'll try to include the solution in v2.0.3.

**Comment by paulakeen** [comment]
As a result of the discussion held with MS, ESPDint and other Stakeholders (held on Wednesday the 14th November 2018), new data structures have been defined for criteria 42 to 47. 

Please see spread-sheet [ESPD-CriteriaTaxonomy-SELFCONTAINED-V2.0.3.xlsx](https://github.com/ESPD/ESPD-EDM/blob/2.0.3/docs/src/main/asciidoc/dist/cl/xlsx/ESPD-CriteriaTaxonomy-SELFCONTAINED-V2.0.3.xlsx) and feel free to react via comments to this issue.

**Comment by mireiaBM** [comment]
This issue has been solved in version 2.1.0 of the ESPD-EDM
