### ISSUE TITLE
ESPD Self-contained 2.0.2: Criteria 7 & 8

### ISSUE THREAD

**Issue by AFSOLUZIONI** [OP-TED/ESPD-EDM#168]
Hi,
In the criteria in subject the description of the main Question is the follow:

"Has the economic operator fulfilled its obligations by paying or entering into a binding arrangement with a view to paying the taxes or social security contributions due, including, where applicable, any interest accrued or fines?"

Thi description is the same in both the criterion.

Maybe could be more clear in the following way:
Criterion 7
"Has the economic operator fulfilled its obligations by paying or entering into a binding arrangement with a view to paying the taxes due, including, where applicable, any interest accrued or fines?"

Criterion 8
"Has the economic operator fulfilled its obligations by paying or entering into a binding arrangement with a view to paying the social security contributions due, including, where applicable, any interest accrued or fines?"

Thx for the support
Francesco

**Comment by paulakeen** [comment]
Dear Francesco,

In version 2.0.2 of the ESPD-SELFCONTAINED and REGULATED taxonomy spreadsheets criteria 7 and 8 read differently to what you comment above:

C7: Has the economic operator breached its obligations relating to the **payment of taxes**, both in the country in which it is established and in Member State of the contracting authority or contracting entity if other than the country of establishment?

C8: Has the economic operator breached its obligations relating to the payment of **social security contributions**, both in the country in which it is established and in Member State of the contracting authority or contracting entity if other than the country of establishment?

Are you perhaps working with an old version? please confirm.

**Comment by AFSOLUZIONI** [comment]
Hi Paula,
I was not so clear in my question.
Having a look in the last taxonomy, I'm referring the row 25 for criterion 7 and the row 70 for Criterion 8.
I hope that now you're able to detect the little misprint due to historicl reason (in the beginnig the criterion was only one for both!!)

**Comment by paulakeen** [comment]
Understood now! this will be corrected in v2.0.3.

**Line 25 will read**: Has the   economic operator fulfilled its obligations by paying or entering into a   binding arrangement with a view to paying the taxes contributions due,   including, where applicable, any interest accrued or fines?

**Line 70 will read**: Has the economic operator fulfilled its obligations by paying or entering into a binding arrangement with a view to paying **the social security contributions due**, including, where applicable, any interest accrued or fines?

**Comment by mireiaBM** [comment]
This issue has been solved in version 2.1.0 of the ESPD-EDM
