### ISSUE TITLE
ESPD Self-contained Criterion 33

### ISSUE THREAD

**Issue by AFSOLUZIONI** [OP-TED/ESPD-EDM#169]
Hi,
the criterion is expecting the date on wich the OE starts his activity, if it starts after the beginning of required period. The main description (criterion) is:

"the information concerning turnover (general or specific) is not available for the entire period required, please state the date on which the economic operator was set up or started trading:"

Then it seems to be better to change the following element:

Description of question from **Please specify** to **Please Insert Date**
Property Data Type from **Description** to **Date**

Francesco

**Comment by paulakeen** [comment]
Dear Francesco,

We'll change the Property Data Type from DESCRIPTION to DATE, however we'd like to keep the text "Please specify" for reasons related to translation into all EU official languages.

This will be fixed in version 2.0.3

**Comment by mireiaBM** [comment]
This issue has been solved in version 2.1.0 of the ESPD-EDM
