### ISSUE TITLE
Part IV, Section C (For service contracts: performance of services of the specified type)

### ISSUE THREAD

**Issue by rantati7** [OP-TED/ESPD-EDM#17]
**For service contracts: performance of services of the specified type** 

CA must be able to define the specified type

CA must be able to define minimum requirements for the performance of services.

**Comment by rantati7** [comment]
would be good if this could be shown to CA only if supplies in question.

**Comment by paulakeen** [comment]
We close this issue for it has been unified with issue #7

**Comment by paulakeen** [comment]
Please find the details of the final decision in https://github.com/ESPD/ESPD-EDM/wiki/8.-References-on-similar-works,-deliveries-or-services
