### ISSUE TITLE
ESPD Self-contained 2.0.2: Criterion 36

### ISSUE THREAD

**Issue by AFSOLUZIONI** [OP-TED/ESPD-EDM#171]
Hi
I discover the same misprint of the previous criterion (use CAPTION instead of REQUIREMENT for Lot ID).
In addition it seems the cardinality for Requisites and Ratig must be 0..n and not 0..1 (see figure below)

![image](https://user-images.githubusercontent.com/44367854/47377589-fcb74180-d6f5-11e8-94d4-29a21626ee09.png)

**Comment by paulakeen** [comment]
You're right about the CAPTION, it should have been declared as {REQUIREMENT]}. This will be fixed in v2.0.3.

**Comment by paulakeen** [comment]
You're also right about the cardinalities. These have been also fixed in v2.0.3.

**Comment by mireiaBM** [comment]
This issue has been solved in version 2.1.0 of the ESPD-EDM
