### ISSUE TITLE
ESPD 2.0.2 Self-Contained: some Criterion 

### ISSUE THREAD

**Issue by AFSOLUZIONI** [OP-TED/ESPD-EDM#172]
Hi,
for our need, in italian version of ESPD 2.0.2 Self-Contained, we insert national subcriteria in some Criterion that not have in the taxonomy the right place.
Is it possible???

Francesco

**Comment by paulakeen** [comment]
Can you provide us with a Use Case please? We do not see why you would need to alter the order of the elements as they're now defined in the UBL-2.2 XSD Schema. An example would be appreciated.

The current XSD Schema wouldn't allow to alter the order of the elements, I'm afraid. And a criterion cannot "contain" sub-criteria but "refer to them" as associated objects, i.e. an element like CriterionProperty cannot refer to a sub-criterion, and it wouldn't make much sense, I think.

**Comment by paulakeen** [comment]
May be what you could do is to take one data structure that is currently defined in the ESPD-EDM and include it inside your national sub-criterion.

**Comment by AFSOLUZIONI** [comment]
Sorry for delay, but it's a tough period :-).
Here you are an example:
![image](https://user-images.githubusercontent.com/44367854/48897285-ebbf3480-ee49-11e8-933a-2728f00ef8f4.png)
Of course, we used the correct structures, but the taxonomy doesn't contain the rows that we insert ourselves

**Comment by mireiaBM** [comment]
We are closing this issue, as this is something that should be solved at national level, not European. @AFSOLUZIONI  ,if you need any guidance on how to draft more criteria, please let us know.
