### ISSUE TITLE
Wrong PropertyDataType in Criterion 35 and 36

### ISSUE THREAD

**Issue by MariaSpr** [OP-TED/ESPD-EDM#174]
In the 2.0.3 taxonomy: 
the criterion 35 with code `CRITERION.SELECTION.ECONOMIC_FINANCIAL_STANDING.RISK_INDEMNITY_INSURANCE`
and `ElementUUID 7604bd40-4462-4086-8763-a50da51a869c`
The PropertyDataType of the REQUIREMENT at row 14 (the one that was previously a CAPTION in 2.0.2) shouldn't have been set to  "NONE". The correct PropertyDataType is "LOT_IDENTIFIER".

The same issue occurs also in the criterion 36, ElementUUID `ab0e7f2e-6418-40e2-8870-6713123e41ad `with the REQUIREMENT at row 14 

Screenshot attached
![wrongpropertydatatype_35](https://user-images.githubusercontent.com/15072613/48066019-11570780-e1d5-11e8-9814-159b70e38456.PNG)

**Comment by paulakeen** [comment]
yes, this was pending of correction. Thank you for the kind reminder.

**Comment by mireiaBM** [comment]
This issue has been solved in version 2.1.0 of the ESPD-EDM
