### ISSUE TITLE
Missing QUESTION - INDICATOR in Criterion 59

### ISSUE THREAD

**Issue by MariaSpr** [OP-TED/ESPD-EDM#175]
In the Criterion 59 with ElementUUID `ee51100f-8e3e-40c9-8f8b-57d5a15be1f2`
There is a question with a missing indicator response. The structure of the criterion should be just like the Criterion's 60 structure.

![criterion_59_missing_indicator](https://user-images.githubusercontent.com/15072613/48067099-0b165a80-e1d8-11e8-9eb6-d76917bc2cff.PNG)

**Comment by paulakeen** [comment]
Solved in  v2.0.3. The problem, actually, is that the criterion was not aligned with the one in REGULATED flavour. From now on they will.

**Comment by mireiaBM** [comment]
This issue has been solved in version 2.1.0 of the ESPD-EDM
