### ISSUE TITLE
Missing Expected Value elements holding requirement information (CA Side, ESPD Req)

### ISSUE THREAD

**Issue by jerouris** [OP-TED/ESPD-EDM#176]
For the following Property Data Type of REQUIREMENTS there is no clear mapping of an XML element that can hold the actual value:

- URL
- INDICATOR

**Comment by paulakeen** [comment]
1. For the URL, see [Issue #181](https://github.com/ESPD/ESPD-EDM/issues/181)

2. For the INDICATOR, see [Issue #166](https://github.com/ESPD/ESPD-EDM/issues/166)

As these issues are addressed in other issues, I close this one.
