### ISSUE TITLE
Missing Cardinality information in Exchange Data Model jar

### ISSUE THREAD

**Issue by mpetruzzi** [OP-TED/ESPD-EDM#177]
Hello! There is no information on Cardinality in the jar exchange-model2.2.0.2.jar library. Under the package test.x.ubl.pre_award.commonbasic I expected a CardinalityType.class, but any classes doesn't have this information. 
Also when I use the transform tool [folder ESPD-EDM/docs/src/main/asciidoc/dist/xslt/ODS Data Structures to ESPD XML/..], the generated xml doesn't have tags on Cardinality (example cbc:Cardinality).

Where can I found this information? Will there be a release about this fix?

Thanks,
Max

**Comment by Trampy71** [comment]
Hi all,
   the issue described by Max is critical to release a first version of a ESPD application and to substain an acceptance test in the next week.
Any help will be welcomed.

Thanks
Fulvio

**Comment by paulakeen** [comment]
About the two issues above:

1. Issues related to the Java code are to be addressed in the ESPD-Service Issues workspace, please. 

2. About the transformation tool: One way of illustrating how the cardinalities work is to produce XML examples of your own.

The drafting of the XSL-T templates was a voluntary elementary exercise aimed to facilitate the generation of XML templates to have a non-humanly-drafted XML example onto which start working more realistic instances. Unfortunately the generation of n elements when the cardinality indicated in the Criteria Taxonomy spread-sheets was never implemented. But please you're more than welcome to improve the XSL-T and feed-back with the results of your work to the Community. 

The reason for the production of these XSL-T artefacts was that the ESPD Service was discontinued. And one of the explained reasons for this discontinuity was that you, the MS, were being funded to develop your solutions.

No evolution of the XSL-T is foreseen for now. However the maintenance of the ESPD-EDM is being handed-over to the Publications Office of the European Union (OP) soon. Why don't you propose this evolution of the XSL-T mechanisms to the OP? 

Kindly yours,
Enric

**Comment by mpetruzzi** [comment]
Thanks a lot, Enric.

I opened an issue in the ESPD-Service Issues workspace about Java code.

**Comment by mireiaBM** [comment]
This issue has been solved in version 2.1.0 of the ESPD-EDM
