### ISSUE TITLE
UUID standard

### ISSUE THREAD

**Issue by AFSOLUZIONI** [OP-TED/ESPD-EDM#178]
Hi,
just a question about UUID:

we use the SQL Server standard function NEWID(). This function  adopt the standard RFC4122 that is (it seems) the same of ISO/IEC 9834-8:2008.

May we use this function or we must use another generation  function to produce UUID??
Thank you for support.
Francesco

**Comment by paulakeen** [comment]
Provided they're version 4 no problem. See an example here (right side of the screen):

https://www.uuidgenerator.net/

**Comment by AFSOLUZIONI** [comment]
Thank you for the prompt answer.
Yes It's level 4 UUID.
Francesco
