### ISSUE TITLE
Criterion 35, wrong question_subgroup indentation

### ISSUE THREAD

**Issue by MariaSpr** [OP-TED/ESPD-EDM#179]
At the Criterion 35 `CRITERION.SELECTION.ECONOMIC_FINANCIAL_STANDING.RISK_INDEMNITY_INSURANCE`
the QUESTION_SUBGROUP at row 20 and UUID `42dc8062-974d-4201-91ba-7f2ea90338fd`
has wrong indentation

Attached screenshot to make things easier:

![criterion35_identation_questiongroup](https://user-images.githubusercontent.com/15072613/48181328-b2f26c00-e32f-11e8-8cc7-0b73aa0d6563.PNG)

**Comment by paulakeen** [comment]
You're right. See [Issue #170](https://github.com/ESPD/ESPD-EDM/issues/170). As this issue is been solved there i close it now.

Thank you Maria.
