### ISSUE TITLE
Part IV: Selection criteria, C: Technical and professional ability - Specific requirements

### ISSUE THREAD

**Issue by rantati7** [OP-TED/ESPD-EDM#18]
**Technicians or technical bodies for quality control**

CA must be able to determine minimum criteria for technicians and technical bodies

**Comment by paulakeen** [comment]
Requirements from issue #20:
**Technical facilities and measures for ensuring quality**
CA must be able to define minimum criteria for technical facilities and measures

Requirements from issue #21:
**Study and research facilities**
CA must be able to define minimum criteria for study and research facilities
NOTE: there are some translation issues in some languages with the word "facilities"

Requirements from issue #22 :
**Supply chain management**
CA must be able to define minimum criteria for supply chain management.
NOTE: it is very unclear what can be required here. The main problem being: which criteria are linked to supplier and which to the goods or services that are purchased. Guidance note would be needed.
Extreme example: when car is the object of procurement can CA require here that the manufacturer of the car is paying living wages or using other sustanable practices throught out its supply chain.

Requirements from issue #23 :
**Allowance of checks**
CA cannot require full check of everything (the text implies that CA would require all kinds of checks and audits).
CA must set a limit / set maximum for cheks and audits.

Requirements from issue #24 :
**Educational and professional qualifications**
CA must be able to define minimum criteria for educational and professional qualifications.

Requirements from issue #25 :
**Environmental management measures**
CA must be able to define minimum criteria for environmental management measures.
NOTE: it is very unclear what can be required here. The main problem being: which criteria are linked to supplier and which to the goods or services that are purchased. Guidance note would be needed.
We think this question relates solely to the EO not the goods or services to be purchased.

Requirements from issue #26 :
**Number of managerial staff**
CA must be able to define minimum / maximu, criteria for the staff.
NOTE: how is this related to object of procurement? Need to pay close attention when defining.

Requirements from issue #27 :
**Average annual manpower**
"The economic operator's average annual manpower and the number of managerial staff for the last three years were as follows:"
CA must be able to define minimum criteria.
CA must be able to define the years (preferably the system would generate last 3 years automatically)
NOTE: there are two separate questions here: average annual manpower AND number of managerial stuff - latter being asked already in the previous ESPD question.

Requirements from issue #28 :
**Tools, plant or technical equipment**
CA must be able to define minimum criteria

Requirements from issue #30:
**For supply contracts: samples, descriptions or photographs without certification of authenticity**
CA must be able to define the required samples etc: what samples it requires, how are those going to be used and where & when the samples will need to be delivered.

Requirements from issue #31: 
**For supply contracts: samples, descriptions or photographs with certification of authenticity**
CA must be able to define the required samples etc: what samples it requires, how are those going to be used and where & when the samples will need to be delivered.

Requirements from issue #32 : 
**For supply contracts: certificates by quality control institutes**
CA must be able to define what is required
Agree, we think when the ESPD is self-contained the required certificates/standards should sit next to the question.
It would also be useful, if this only appeared when it was a supply contract - perhaps if there was a conditional question at the start of the ESPD asking if the tender was goods, works or services the appropriate questions could pre-populate.

**Comment by paulakeen** [comment]
Could you please provide examples of particular requirements for the different criteria for several procedures, so we can identify the information that should be required to the CA?

**Comment by paulakeen** [comment]
Please find below what was commented about this issue in the discussion group:

Timo Rantanen / Hansel / Finland: text field is fine

Rudolf Maier: Requirement text field.

Timo Rantanen / Hansel / Finland: I recon text field is the anwer to all of these

Jose Luis Cueva (Spain): Annex XII tells " a description of..." so a textfield fits the bill

Anne Katrine, NIRAS A/S, DK: I agree reg following.

**Comment by paulakeen** [comment]
The final decisions on the criteria of Part IV: Selection criteria, C: Technical and professional ability is provided in the wiki.
