### ISSUE TITLE
Same UUID for Evidence and Convinction subgroups

### ISSUE THREAD

**Issue by Eux86** [OP-TED/ESPD-EDM#180]
ID 41dd2e9b-1bfd-44c7-93ee-56bd74a4334b is used in both Conviction and Evidence subgroups.

![image](https://user-images.githubusercontent.com/7115595/48191774-e936e800-e33d-11e8-9b79-0d1fce1c8e3b.png)

**Comment by paulakeen** [comment]
Ouch!

Thank you for spotting this. Fortunately in the Regulated version this error was not made. Bear in mind no SELF-Contained was being implemented until recently....so you're kinda pioneers.

We'll solve it in v2.0.3 (to be released soon).

![issue180](https://user-images.githubusercontent.com/16134316/48221064-4f992600-e391-11e8-90eb-0d83abbbb055.png)

**Comment by mireiaBM** [comment]
This issue has been solved in version 2.1.0 of the ESPD-EDM
