### ISSUE TITLE
How to refer to an "expected URI type" for a CA REQUIREMENT in SELF-CONTAINED

### ISSUE THREAD

**Issue by paulakeen** [OP-TED/ESPD-EDM#181]
1. In the UBL-2.2 TC we "forgot" adding a "cbc:ExpectedURI" element in "cac:TenderingCriterionProperty" (or maybe not). Right now we are addressing these issues in the UBL-2.3 Jira. 
2. The UBL-2.3. TC did not forget including it as part of the "cac:ResponseValue" (see the element cbc:ResponseURI).

One way of solving this could be:

1. Use the cbc:ExpectedID
2. Additionally (and optionally) add the value "URI" to the ccts:Identifier attribute "schemID".

In the ePO (eProcurement Ontology) we proposed a simpler and (hopefully) smarter solution: only one class for both needs the expected and the responded values (the epo:Datum class). This solutions is precisely being discussed in SEMIC.eu now as input for the evolution of their Core Criterion Vocabulary. See the SEMIC.eu Issue #2: https://github.com/SEMICeu/CCCEV/issues/2 or https://github.com/eprocurementontology/eprocurementontology/wiki/Conceptual-Model-v2.0.1#conceptual-model-diagrams (Criterion entry):

![criterion](https://user-images.githubusercontent.com/16134316/48219345-8d478000-e38c-11e8-9c2c-e0610a996c4f.jpg)

**Comment by jerouris** [comment]
Hi Enric,

What about when the expected value is of type INDICATOR?

**Comment by paulakeen** [comment]
Originally no situation was foreseen where an "expected indicator" would be necessary. However the richness/complexities of the SELF-CONTAINED version has made conspicuous this need. That is the case of Criterion #36 (CRITERION.SELECTION.ECONOMIC_FINANCIAL_STANDING.OTHER_REQUIREMENTS).

I'll create a new issue explaining the issue and proposing a solution and what are the impacts. See new I[ssue #182](https://github.com/ESPD/ESPD-EDM/issues/182).

**Comment by mireiaBM** [comment]
This issue has been solved in version 2.1.0 of the ESPD-EDM
