### ISSUE TITLE
No cbc:ExpectedIndicator

### ISSUE THREAD

**Issue by paulakeen** [OP-TED/ESPD-EDM#182]
In the list of possible data values expected in a CA REQUIREMENT or a QUESTION addressed to the EO, there is not a cbc:ExpectedIndicator element (similar to cbc:ExpectedDescription, cbc:ExpectedCode, cbc:ExpectedIdentifier, etc.), under cac:TenderingCriterionProperty.

Nonetheless, in the response, the element cac:TenderingCriterionResponse/cac:ResponseValue there is a cbc:ResponseIndicator element for the Economic Operator to answer this type of data. Beware however that this issue does not affect the EO, but affects the CA when indicating its choice between two mutually requirements.

Originally no situation was foreseen where an "expected indicator" would be necessary. However the richness/complexities of the SELF-CONTAINED version has made conspicuous this need. That is the case of Criterion #36 (CRITERION.SELECTION.ECONOMIC_FINANCIAL_STANDING.OTHER_REQUIREMENTS).

We should comment with the MS, in the case of these type of requirements, if we should treat this sub-block of requirements to only two (and mutually exclusive) or if we should open the possibility for the CA to require more than two non-mutually exclusive requirements.

This needs to be solved for v2.0.2 and in v2.0.3.

Unfortunately the UBL-2.2 XSD Schema cannot be changed and this need should be addressed by the UBL-2.3 TC. We'll initiate an issue in the UBL-2.3 Jira requesting this change.

In the meantime we propose to solve this issue like this:

1. Let's use the cac:TenderingCriterionProperty/cbc:expectedTypeCode element for this;
2. Two codes will be possible: TRUE and FALSE. Later on the list could be enriched with other codes to include more than one subgroups of requirements. 
3,. As this does not address the responses by the EO the solution adopted for the CA REQUIREMENTS has no impact on the EO;
3. A new tab will be needed in the spreadsheet containing the code lists ()
4. No need for a new schematron rule, in principle, as the schematron rules currently developed control that if the type of requirement is cbc:ValueDataTypeCode is "CODE" then the value and attributes are the right ones for a cbc:ExpectedCode
5. This approach will be documented in section [VI of the online documentation](https://espd.github.io/ESPD-EDM/v2.0.2/xml_guide.html#vi-6-other-economic-or-financial-requirements).

**Comment by mireiaBM** [comment]
This issue has been solved in version 2.1.0 of the ESPD-EDM
