### ISSUE TITLE
ESPD-EDM SELF-CONTAINED: {QUESTION} MISSING in C#63

### ISSUE THREAD

**Issue by paulakeen** [OP-TED/ESPD-EDM#183]
In C63, CRITERION.OTHER.EO_DATA.CONTRIBUTIONS_CERTIFICATES, line 10, the tag {QUESTION} is missing.

**Comment by paulakeen** [comment]
To be solved in v2.0.3.

**Comment by mireiaBM** [comment]
This issue has been solved in version 2.1.0 of the ESPD-EDM
