### ISSUE TITLE
ESPD-EDM SELF-CONTAINED: {QUESTION} MISSING in C#57

### ISSUE THREAD

**Issue by paulakeen** [OP-TED/ESPD-EDM#185]
ESPD-EDM SELF-CONTAINED: {QUESTION} MISSING in C#63 line 14.

**Comment by paulakeen** [comment]
Will be fixed in v2.0.3.

**Comment by mireiaBM** [comment]
This issue has been solved in version 2.1.0 of the ESPD-EDM
