### ISSUE TITLE
WRONG PropertyDataType for EO identifier in EO together with others REGULATED and SELF-CONTAINED

### ISSUE THREAD

**Issue by paulakeen** [OP-TED/ESPD-EDM#186]
The PropertyDataType for the Economic Operator in Regulated and Self-contained versions in v2.0.2 is DESCRIPTION and should be IDENTIFIER.

It has been proposed also to name this property EO_IDENTIFIER, this would help validate the Agencies issuers of accepted IDs (e.g. as in the OpenPeppol Identification policy).

**Comment by paulakeen** [comment]
1. The PropertyDataType has been changed from DESCRIPTION to EO_IDENTIFIER.
2. An EO_IDENTIfIER will be added to the Code List ResponseDataType.

**Comment by jerouris** [comment]
Will it be EO_Identifier or ECONOMIC_OPERATOR_IDENTIFIER?

**Comment by paulakeen** [comment]
The one you prefer, now it is the moment to make the decision, as it has never been used, yet.

**Comment by paulakeen** [comment]
We've changed it to ECONOMIC_OPERATOR_IDENTIFER. It's clearer for anyone. Thank you for the support/suggestion.

**Comment by mireiaBM** [comment]
This issue has been solved in version 2.1.0 of the ESPD-EDM
