### ISSUE TITLE
Schematron error for QUANTITY* and PERCENTAGE response types

### ISSUE THREAD

**Issue by lotzmann** [OP-TED/ESPD-EDM#191]
According to the EDM, QuantityResponse must be used in the criterion response, when QUANTITY, QUANTITY_INTEGER, QUANTITY_YEAR and PERCENTAGE are declared as response value types.
However, the schematrons state that ResponseMesaure should be used, as can be seen e.g. in the following validation error message:
`The type of answer expected by the contracting authority is 'QUANTITY_INTEGER' ('cac:ResponseValue/cbc:ResponseMeasure' element) - ('cbc:ID' is a5e18e84-b60c-4667-9ca7-139243f5b800).
Test:( ($currentDataType = 'QUANTITY_INTEGER') and (cac:ResponseValue/cbc:ResponseMeasure) ) or not($currentDataType = 'QUANTITY_INTEGER')`.

This needs to be sorted out by correcting the schematrons and improving the EDM.

**Comment by paulakeen** [comment]
Yes, you're right. This was detected some weeks ago and the correction was applied. Thank you any way for creating the issue and keeping track of the problem.

We'll add this to the configuration matrix and V2.0.3 will implement and document the solution.

**Comment by daniel-filipe-lobo** [comment]
Has we are developing 2.0.2 and we don't have the budget to just extend the project and have whatever more time to develop a new version, we used this workaround:
<cac:TenderingCriterionResponse>
  <cbc:ID schemeID="ISO/IEC 9834-8:2008 - 4UUID" schemeAgencyID="EU-COM-GROW" schemeVersionID="2.0.2">d5b6906c-7779-b147-5bbe-fa3c5b8963cb</cbc:ID>
  <cbc:ValidatedCriterionPropertyID schemeID="CriteriaTaxonomy" schemeAgencyID="EU-COM-GROW" schemeVersionID="2.0.2">d34e47a8-ed9a-4003-8db8-546e4e1901cd</cbc:ValidatedCriterionPropertyID>
  <cbc:ConfidentialityLevelCode listID="ConfidentialityLevel" listAgencyID="EU-COM-GROW" listVersionID="2.0.2">PUBLIC</cbc:ConfidentialityLevelCode>
  <cac:ResponseValue>
    <cbc:ID schemeID="ISO/IEC 9834-8:2008 - 4UUID" schemeAgencyID="EU-COM-GROW" schemeVersionID="2.0.2">467564f5-c005-e04f-f5b2-6ac5297fb74b</cbc:ID>
    <cbc:ResponseMeasure unitCode="**YEAR**">2012</cbc:ResponseMeasure>
  </cac:ResponseValue>
</cac:TenderingCriterionResponse>

**Comment by paulakeen** [comment]
We can revisit the schematron validation rule and try and get it a bit more flexible. We'll feed-back you the soonest.

**Comment by mireiaBM** [comment]
This issue has been solved in version 2.1.0 of the ESPD-EDM
