### ISSUE TITLE
Cardinality of cac:AdditionalDocumentReference/cbc:ID

### ISSUE THREAD

**Issue by mondorf** [OP-TED/ESPD-EDM#192]
The cardinality of cac:AdditionalDocumentReference/cbc:ID is currently mandatory. However the rule states that there are exclusions where no TED number can be provided by the CA (esp. when the notice has not been published yet - see rule below). It would be better solution to make the element optional (at least for the request) instead of forcing the user to include dummy values. 

"If the document referenced is a Contract Notice published on TED the ID must follow the scheme defined by the Publications Office: [][][][]/S [][][]-[][][][][][] (e.g. 2015/S 252-461137). If at the time of drafting the ESPD document the Publication Office has not published yet the Contract Notice the value 0000/S 000-000000 value must be used to indicate that a temporary identifier is being used."

**Comment by paulakeen** [comment]
If you refer to the cardinality of the data structure that should not be a problem as that cardinality referes to the obligation tho show the group, and if the information is not available then no evidence is supplied whatsoever. 

Please let's clarify the situation first.

**Comment by paulakeen** [comment]
We agree that this is not an issue and that should be closed.
