### ISSUE TITLE
urn:X-test:UBL:Pre-award:

### ISSUE THREAD

**Issue by AFSOLUZIONI** [OP-TED/ESPD-EDM#193]
Hi,
there are news about the correct value to insert in the XML for UBL 2.2??
Thank you for answer.
Francesco

**Comment by paulakeen** [comment]
ESPD-EDM v2.03 will use the official UBL-2.2 version released on the 9th of July 2018. In this final version the namespaces for the ESPD-Request (UBL-QualificationApplicationRequest) and ESPD-Response (UBL-QualifiicationApplicationResponse) equivalent documents are:

* urn:oasis:names:specification:ubl:schema:xsd:QualificationApplicationRequest-2
* urn:oasis:names:specification:ubl:schema:xsd:QualificationApplicationResponse-2

These two documents can be (should be) downloaded from the official UBL-2.2 [web site](http://docs.oasis-open.org/ubl/UBL-2.2.html), e.g. the [zip distribution](http://docs.oasis-open.org/ubl/os-UBL-2.2/UBL-2.2.zip).

However, as the maindoc folder contains many documents we use to distribute only the two documents (and related common schemas) with the ESPD-EDM distribution (see [branch 2.0.3 in our GitHub](https://github.com/ESPD/ESPD-EDM/tree/2.0.3/docs/src/main/asciidoc/dist/xsdrt), but beware that this branch is not final and has not been yet merged to the current master branch). The xsdrt (runtime) version is used for development purposes whilst the xsd (annotated) is used for documentation purposes.

**Comment by AFSOLUZIONI** [comment]
THX

**Comment by mireiaBM** [comment]
This issue has been solved in version 2.1.0 of the ESPD-EDM
