### ISSUE TITLE
Wrong PropertyDataType at Criterion #38

### ISSUE THREAD

**Issue by MariaSpr** [OP-TED/ESPD-EDM#194]
in the criterion # 38 with code `CRITERION.SELECTION.TECHNICAL_PROFESSIONAL_ABILITY.REFERENCES.SUPPLIES_DELIVERY_PERFORMANCE` and
Element UUID `3a18a175-1863-4b1d-baef-588ce61960ca` 
The PropertyDataType of the QUESTION at row 72 shouldn't have been set to "IDENTIFIER". The correct PropertyDataType should be "LOT_IDENTIFIER".
Also the cardinality should be changed to `1...N `

Screenshot attached for better understanding
![criterion_38](https://user-images.githubusercontent.com/15072613/48371056-88076f80-e6c3-11e8-8544-3e2f015fea76.PNG)

**Comment by paulakeen** [comment]
Done! Thank you. Will go to v2.0.3.

**Comment by mireiaBM** [comment]
This issue has been solved in version 2.1.0 of the ESPD-EDM
