### ISSUE TITLE
Wrong PropertyDataType in Criteria # 31 and # 32

### ISSUE THREAD

**Issue by MariaSpr** [OP-TED/ESPD-EDM#195]
In the criterion # 31 with code `CRITERION.SELECTION.ECONOMIC_FINANCIAL_STANDING.TURNOVER.SPECIFIC_AVERAGE`

The PropertyDataType of the REQUIREMENT at row 12 shouldn't have been set to "AMOUNT". The correct PropertyDataType should be "QUANTITY_INTEGER" since at the description says "Number of fiscal years".

The same applies for criterion # 32 as well
( code `CRITERION.SELECTION.ECONOMIC_FINANCIAL_STANDING.TURNOVER.SPECIFIC_YEARLY`
the REQUIREMENT at row 12 )

See attached screenshot
![criterion31](https://user-images.githubusercontent.com/15072613/48486904-645c3a80-e825-11e8-9992-0acd85f3c7fa.PNG)

**Comment by paulakeen** [comment]
Many thanks Maria for your contribution in fixing these bugs. We'll correct it immediately as part of the v2.0.3 bug-fixing.

**Comment by mireiaBM** [comment]
This issue has been solved in version 2.1.0 of the ESPD-EDM
