### ISSUE TITLE
schemeID e schemeAgencyID

### ISSUE THREAD

**Issue by AFSOLUZIONI** [OP-TED/ESPD-EDM#196]
Hi,
just a question on the argument in re:
How we must code the schemeID?? Is there a code list??
In the positive case if the code list doesn't contain the value I need what I can do??

Same problem for schemeAgencyID: how we must fill this tag??
Is there a code list? there is a rule to fill in information??

For example if we ask for a /QualificationApplicationRequest/cac:ContractingParty/cac:Party/cac:PartyIdentification/cbc:ID
the national fiscal number of CA, what we must insert in the two tag??
Thank you for support.

**Comment by paulakeen** [comment]
This is a soooo interesting and relevant question!!!! Thank you Francesco for asking this. 

My response would be: ESPD has not defined a policy about this particular aspect. "An Identifier policy is needed". 

Now, who should be responsible for the drafting and governance of this policy? an EU institution in charge of eProcurement-related policy-making (e.g. DG GROW) or should that be the body responsible for the context of use of the ESPD (e.g. the Publications Office in the context of the publication of notices and ESPD Requests on the TED in the future, OpenPeppol in the context of inclusion of ESDP Responses in the VCD and exchange of the Response between EO's Service Providers and Contracting Authorities, other?).

In any case, at least a recommendation based on a good practice should be pointed at by someone. Let me add that the [OpenPEPPOL policy for identifiers](https://peppol.eu/wp-content/uploads/2017/12/PEPPOL_Policy-for-use-of-identifiers-300-11_certificates.pdf) is, for me, a good example of how this can be solved. 


In absence of general recommendation then my advise is that you use your own national schemeIDs and schemeAgencyIDs, i.e. "VAT" (for the schemeID) and "AEAT" (Agencia Tributaria, for the schemeAgencyID) in the case of Spain) for one example.

**Comment by ec-mcs** [comment]
There is a discussion in the EMSFEI on identifiers for invoices. Maybe we can use some inspiration from there as well?

**Comment by paulakeen** [comment]
What is EMSFEI? can you please provide an URL where to get documented on their work?

**Comment by ec-mcs** [comment]
The Electronic Address Scheme Code List was published by CEF on 23rd November. Could we use this for us? https://ec.europa.eu/cefdigital/wiki/display/SDBX/2018/11/23/CEF+eInvoicing%3A+Publication+of+the+Electronic+Address+Scheme+Code+List

**Comment by juskoljo** [comment]
Hi, I don't know does this help any, but there is a codelist of agencies for schemeAgencyID http://www.unece.org/trade/untdid/d08a/tred/tred3055.htm

**Comment by JachymHercher** [comment]
For eForms, we plan to use the same scheme as for eInvoicing - given by @ec-mcs in https://github.com/ESPD/ESPD-EDM/issues/196#issuecomment-444051488. All three of our "standards"  (eForms, eInvoicing, ESPD) should use the same one.

**Comment by paulakeen** [comment]
Let's propose it. It looks quite functional, but not exhaustive.

**Comment by AFSOLUZIONI** [comment]
Hi,
I had a look into the code list and I don't find some agencies (e.g. AdE that states the fiscal number in Italy). Maybe each member State must activate a procedure to insert their own Agencies in the code list.
Francesco.
P.S. is there a know procedure to insert values in this code list??

**Comment by paulakeen** [comment]
It's not only about the exhaustivity of the Agencies but also of the SchemeIDs.

**Comment by JachymHercher** [comment]
The codelist contains schemes, not agencies themselves, so what should be registered are the schemes. If a scheme is missing (which is quite likely), then the person responsible for the scheme should request for it to be added. The instructions are at https://ec.europa.eu/cefdigital/wiki/display/CEFDIGITAL/Code+lists#Codelists-1ElectronicAddressSchemecodelist(EAS), "Register or request changes". 

CEF will then explain how to register in the ISO 6523 (ICD, the international code designator), which will then trickle down into the relevant codelists used in the EU.

**Comment by acolomer** [comment]
Good afternoon,
The ESPD provides just an identifier and no code list is currently foreseen in the ESPD-EDM. Therefore, we proceed to close the issue.
Kind regards,
The ESPD Team
