### ISSUE TITLE
Wrong PropertyDataType in C#59: should be a code, not an identifier

### ISSUE THREAD

**Issue by paulakeen** [OP-TED/ESPD-EDM#198]
In criterion "CRITERION.OTHER.EO_DATA.TOGETHER_WITH_OTHERS" in both REGULATED and SELF-CONTAINED versions, the QUESTION "Please indicate the role of the economic operator in the group (leader, responsible for specific tasks...)" has been assigned an IDENTIFIER, and should be a CODE. The CodeList to use for this code is "EORoleType".

**Comment by paulakeen** [comment]
This will be solved in v2.0.3 as follows:

Criterion "CRITERION.OTHER.EO_DATA.TOGETHER_WITH_OTHERS" in both REGULATED and SELF-CONTAINED versions, a new code ECONOMIC_OPERATOR_ROLE_CODE will replace the type IDENTIFIER (which was wrongly assigned to this element). This code is new and have been addd to the CodeList ResponseDataType. 

The values (in this case code identifiers) that must be used to indicate the role are defined in the CodeList "EORoleType". See tab "EORoleType" in the [CodeList spread-sheet](https://github.com/ESPD/ESPD-EDM/blob/2.0.3/docs/src/main/asciidoc/dist/cl/xlsx/ESPD-CodeLists-V2.0.3.xlsx).

**Comment by mireiaBM** [comment]
This issue has been solved in version 2.1.0 of the ESPD-EDM
