### ISSUE TITLE
Change cardinality of req inside req-groups from 1...* to 0...*

### ISSUE THREAD

**Issue by ESPD** [OP-TED/ESPD-EDM#2]
We need to change the cardinality of req inside req-groups from 1...\* to 0...\* because there are req-groups which have directly other req-groups. 
Example would be for "General yearly turnover"
This change will have no effect on existing solutions as it is easing a constraint.

**Comment by paulakeen** [comment]
## Impact analysis

1) **Benefits**

Some data structures  in the XML instances of the ESPD documents will become more logical and less burdened with useless requirements. Applications's users, like the ESPD Service ones, would also benefit of a better user experience.

2) **Caveat**: 

The schema won't be able anymore to check whether a group of requirements contains at least one requirement or not.

3) **Solution**:

A new rule needs to be put in place to check that at least one requirement is instantiated within a group of requirements.

4) **Decision**:

The change request will be implemented and a new schema will be provided in the next release 1.0.2.
