### ISSUE TITLE
Part IV: Some selection criteria allow only for one requirement

### ISSUE THREAD

**Issue by ec-mcs** [OP-TED/ESPD-EDM#201]
Again using the EPSDint solution it seems that the EDM is not reflecting what we decided in 2017. For quite a number of selection criteria, it is not possible to provide multiple requirements (suitability, enrolment in a register, for references).

**Comment by jerouris** [comment]
This is a regression in ESPDInt Implementation. It is already properly reflected in 2.1.0 taxonomy.
