### ISSUE TITLE
Criterion # 60: Wrong PropertyDataTypes

### ISSUE THREAD

**Issue by MariaSpr** [OP-TED/ESPD-EDM#204]
In the 2.1.0 taxonomy: 
The changes made at the Criterion # 61 should also be reflected at the criterion # 60  
(ElementCode:  `CRITERION.OTHER.EO_DATA.RELIES_ON_OTHER_CAPACITIES` )

In line 8, the PropertyDataType of the QUESTION should be `ECONOMIC_OPERATOR_IDENTIFIER` instead of just `IDENTIFIER`.
In line 9, the PropertyDataType of the QUESTION should be `CODE` (CpvCodes) instead of  `DESCRIPTION`.

**Comment by paulakeen** [comment]
Shall we apply this for both, the ESPD-REGULATED and the SELF-CONTAINED? We'd applied it only for the SELF-CONTAINED, until you confirm.

**Comment by paulakeen** [comment]
I'll apply this also for the **REGULATED v2.1.0**. Please react if you do not agree.

**Comment by mireiaBM** [comment]
This issue has been solved in version 2.1.0 of the ESPD-EDM
