### ISSUE TITLE
Criteria 35 & 36: Wrong indentation at QUESTION_SUBGROUP

### ISSUE THREAD

**Issue by MariaSpr** [OP-TED/ESPD-EDM#205]
Taxonomy 2.1.0:
At the EG-Contributions criteria (Criteria 35 and 36) 
As you can see from the screenshot, there is an issue with the indentation of the QUESTION inside the QUESTION_SUBGROUP with UUID `41dd2e9b-1bfd-44c7-93ee-56bd74a4334b`

![identationcriterion35_36](https://user-images.githubusercontent.com/15072613/49156838-0b150080-f327-11e8-8bae-d73e13473177.PNG)

**Comment by paulakeen** [comment]
Solved, thank you

**Comment by mireiaBM** [comment]
This issue has been solved in version 2.1.0 of the ESPD-EDM
