### ISSUE TITLE
WEIGHT_INDICATOR Description Typo

### ISSUE THREAD

**Issue by MariaSpr** [OP-TED/ESPD-EDM#207]
In every REQUIREMENT with PropertyDataType `WEIGHT_INDICATOR` there is a typo in the description.
This criterion will be waited ----> This criterion will be weighted

For example: 
![weight_typo](https://user-images.githubusercontent.com/15072613/49159336-efacf400-f32c-11e8-96b6-eb1d9cbed76d.PNG)

**Comment by paulakeen** [comment]
Corrected! 

Thank you.

**Comment by mireiaBM** [comment]
This issue has been solved in version 2.1.0 of the ESPD-EDM
