### ISSUE TITLE
Criterion 47: Missing closing QUESTION_SUBGROUP

### ISSUE THREAD

**Issue by MariaSpr** [OP-TED/ESPD-EDM#209]
Self-contained 2.1.0 taxonomy:
At the Criterion # 47 with ElementCode `CRITERION.SELECTION.TECHNICAL_PROFESSIONAL_ABILITY.TECHNICAL.PROFESSIONAL_QUALIFICATIONS`
There is a missing closing QUESTION_SUBGROUP} after line 32.

![criterion47](https://user-images.githubusercontent.com/15072613/49246474-b2745f00-f41d-11e8-900e-a7dcdbe54ccb.PNG)

**Comment by paulakeen** [comment]
Corrected! Thank you.

**Comment by mireiaBM** [comment]
This issue has been solved in version 2.1.0 of the ESPD-EDM
