### ISSUE TITLE
Part IV, Section C (Technical facilities and measures for ensuring quality / Study and research facilities)

### ISSUE THREAD

**Issue by rantati7** [OP-TED/ESPD-EDM#21]
**Study and research facilities**

 CA must be able to define minimum criteria for study and research facilities

NOTE: there are some translation issues in some languages with the word "facilities"

**Comment by paulakeen** [comment]
We close this issue for it's been unified with issue #18

**Comment by paulakeen** [comment]
Please find below what was commented about this issue in the discussion group:

Jose Luis Cueva (Spain): Name, Description?

Timo Rantanen / Hansel / Finland: just a note on translations if this field: study and reseach facilities is translated wrongly in at least 3 languages that I have checked...

Timo Rantanen / Hansel / Finland: of

Anne Katrine, NIRAS A/S, DK: And I sugest an URL.

Timo Rantanen / Hansel / Finland: LOOK at the next questtions

Timo Rantanen / Hansel / Finland: questions

Anne Katrine, NIRAS A/S, DK: Yes.

Rudolf Maier: There shoul be a possibility ffor the CA to "hide" these requirement fields if  it does not apply to his/her contract.

Marc-Christopher SCHMIDT: Name of the facility, Measures for ensuring quality, Other information

Timo Rantanen / Hansel / Finland: there is study and research feacilities again

Anne Katrine, NIRAS A/S, DK: I agree, Timo.

Anne Katrine, NIRAS A/S, DK: Couldnt that be erased?

Jose Luis Cueva (Spain): They seem 2 different questions in a single box

Timo Rantanen / Hansel / Finland: I agree

Anne Katrine, NIRAS A/S, DK: erase it in th

Anne Katrine, NIRAS A/S, DK: Deleted in the first

Jose Luis Cueva (Spain): study and research is different than quality control

Timo Rantanen / Hansel / Finland: and thas why they are also translated wrongly 

Jose Luis Cueva (Spain): I would suggest splitting in two different fields

Anne Katrine, NIRAS A/S, DK: I agree MC.

Timo Rantanen / Hansel / Finland: this is correct

Timo Rantanen / Hansel / Finland: CA neeeds requirement field and splitting into 2 would make more sence

Anne Katrine, NIRAS A/S, DK: I have never seen it being used.

Rudolf Maier: Title and description is OK.

Jose Luis Cueva (Spain): either name or title is OK

Jose Luis Cueva (Spain): OK

Timo Rantanen / Hansel / Finland: If they are IT systems: names may exists, but for processes names may not exist

Jose Luis Cueva (Spain): eg ITIL says a lot of info with just 4 letters

Timo Rantanen / Hansel / Finland: description only - 

Rudolf Maier: Name also

Enric Staromiejski (GROW): @all: in the end two or three free-text fields = 1 large description field

Timo Rantanen / Hansel / Finland: only description

Jose Luis Cueva (Spain): name and description

Anne Katrine, NIRAS A/S, DK: Descr

Timo Rantanen / Hansel / Finland: it does not really matter

Timo Rantanen / Hansel / Finland: it does not really matter

John Degiorgio: Name & Description

Jose Luis Cueva (Spain): name is optional of  course (can alwais say "unnamed")

Enric Staromiejski (GROW): just specify what you expect in the requirement

**Comment by paulakeen** [comment]
Please find below a proposal for the solution and mock-ups, as commented in the last meeting:

The CA will be able to add multiple requirements.

The EO will need to provide, for each requirement: 

- For Technical facilities and measures for ensuring quality: Name of the facility; Measures for ensuring quality; and Other information.

- For Study and research facilities: Name of the facility; and Other information.

There's been a change in the description of the criterion.

View of the CA:
![image](https://cloud.githubusercontent.com/assets/16134316/25391012/74f46daa-29d5-11e7-83a7-24ec069d9f62.png)

View of the EO:
![image](https://cloud.githubusercontent.com/assets/16134316/25391021/7b3cc7ca-29d5-11e7-85be-66e10ab788c6.png)

**Comment by paulakeen** [comment]
Please find below what was commented about this issue in the discussion group:

Enric Staromiejski (GROW): @all: these requirements are defined by the CA for this particular requirement. Therefore the CA could ask the EO in the text of the CA's requirement to provide a specific type of information in the "Other information" free-text box

Timo Rantanen / Hansel / Finland: agree with J-L. combning those must be the idea a "a competent" lawyer 

Timo Rantanen / Hansel / Finland: .-)

Robin: RnD

Jose Luis Cueva (Spai): Annex XII says "facilities"

Jose Luis Cueva (Spai): I suggests maintaininig the Directive wording "facilities" and "measures"

Jose Luis Cueva (Spai): The English wording, I mean

Jose Luis Cueva (Spai): I understand a facility is a "tangible asset". OTOH a "resource can be tangible or not  (a procedure, a standard, etc)

Timo Rantanen / Hansel / Finland: facility and in sedish

Anne Katrine, NIRAS A/S, DK: I agree with JL.

Timo Rantanen / Hansel / Finland: facilities and in swedish utrustning indeed implies more towards tangible assets

Anne Katrine, NIRAS A/S, DK: yes, T

Timo Rantanen / Hansel / Finland: agree with one

Timo Rantanen / Hansel / Finland: criteria

Timo Rantanen / Hansel / Finland: yes ... ablity of the body/facility/ what ever

Timo Rantanen / Hansel / Finland: this is ok

Timo Rantanen / Hansel / Finland: the name stilll leaves some Qs open what to write there but nevermind

Jose Luis Cueva (Spai): can always put "unnamed"

Jose Luis Cueva (Spai): no name

Timo Rantanen / Hansel / Finland: yes no need to add name therer

Timo Rantanen / Hansel / Finland: that's what I mean with never mind...

Jose Luis Cueva (Spai): name optional

Timo Rantanen / Hansel / Finland: ok

**Comment by paulakeen** [comment]
The current criteria: (1) Technical facilities and measures for ensuring quality; and (2) Study and research facilities; are to be unified into a single criterion: Technical, Study, Research and Development facilities/resources.

The CA must be able to add multiple requirements.

For each requirement, the EO must be able to add multiple facilities/resources. 

- View of the CA:
![image](https://cloud.githubusercontent.com/assets/16134316/25692354/255ac716-30a2-11e7-8688-2b4a7f3a5692.png)

- View of the EO:
![image](https://cloud.githubusercontent.com/assets/16134316/25692359/32d97ffe-30a2-11e7-81f5-9ebedacee46a.png)

**Comment by paulakeen** [comment]
Please find the details of the final decision in https://github.com/ESPD/ESPD-EDM/wiki/25.-Technical,-Study,-Research-and-Development-facilities-resources
