### ISSUE TITLE
Criterion 47: ESCO Taxonomy CodeList

### ISSUE THREAD

**Issue by MariaSpr** [OP-TED/ESPD-EDM#210]
Self-contained 2.1.0 Taxonomy:

At criterion # 47: 
ESCO Taxonomy codelist is not provided in the ESPD EDM and thus should not be used inside the taxonomy as an assosiated codelist for CODE Property Type.

![esco-taxonomy](https://user-images.githubusercontent.com/15072613/49246786-67a71700-f41e-11e8-9cae-d4459cc7418b.PNG)

**Comment by paulakeen** [comment]
I propose not to remove this field but to replace the data property type from CODE to URI, which is the way ESCO uses for the identification of their concepts. 

Please react to this proposal.

KR

**Comment by jerouris** [comment]
What should the specific business rules be, when using URIs? Should this be a free text field from a UI Perspective?

**Comment by paulakeen** [comment]
No schematron rule applied to this, but as any URI the XSD should take care of verifying that the content of the field is conformant with the anyURI scheme. From the GUI perspective I guess you could apply a typical Regular Expression to check that this is an URL following the scheme HTTP://domain.zone/whatever.

**Comment by mireiaBM** [comment]
This issue has been solved in version 2.1.0 of the ESPD-EDM
