### ISSUE TITLE
Criteria 7 & 8: Wrong indentation at QUESTION_SUBGROUP

### ISSUE THREAD

**Issue by MariaSpr** [OP-TED/ESPD-EDM#211]
Taxonomy 2.1.0:
At the EG-Contributions criteria (Criteria 7 and 8)
As you can see from the screenshot, there is an issue with the indentation of the QUESTION inside the QUESTION_SUBGROUP with UUID `41dd2e9b-1bfd-44c7-93ee-56bd74a4334b`

![eg_contribution78](https://user-images.githubusercontent.com/15072613/49397237-ae10b480-f743-11e8-98c7-16c56becfc30.PNG)

**Comment by paulakeen** [comment]
Corrected in the spread-sheet. XML instances will be generated asap.

**Comment by mireiaBM** [comment]
This issue has been solved in version 2.1.0 of the ESPD-EDM
