### ISSUE TITLE
New version of Exchange Data Model

### ISSUE THREAD

**Issue by mpetruzzi** [OP-TED/ESPD-EDM#213]
Hello!
I have a question. The latest documentation refers to version 2.0.2 of exchange-model2. 
With the new version of taxonomy (2.1.0), it will be there a new version of Exchange Data Model library?

Thanks,
Max

**Comment by paulakeen** [comment]
There will be new documentation for version 2.1.0.

**Comment by mireiaBM** [comment]
This issue has been solved in version 2.1.0 of the ESPD-EDM
