### ISSUE TITLE
Criterion 35: QUESTION Evidence supplied

### ISSUE THREAD

**Issue by ghost** [OP-TED/ESPD-EDM#214]
2.1.0 Selfcontained taxonomy in the Criterion 35 - 
CRITERION.SELECTION.ECONOMIC_FINANCIAL_STANDING.RISK_INDEMNITY_INSURANCE

Seems to have the wrong cardinality in the 'Evidence supplied' question:
![image](https://user-images.githubusercontent.com/12980038/50166588-4c258280-02df-11e9-8a8b-f81169565082.png)

**Comment by everis-rpam** [comment]
OK, corrected in v2.1.0 for Criteria #35 and #47.

**Comment by paulakeen** [comment]
OK.   Corrected in Criteria #35 and 47

**Comment by mireiaBM** [comment]
This issue has been solved in version 2.1.0 of the ESPD-EDM
