### ISSUE TITLE
Criterion 39: Wrong description text

### ISSUE THREAD

**Issue by lotzmann** [OP-TED/ESPD-EDM#215]
For criterion 39 ("For service contracts: performance of services of the specified type") the wrong description text is used, starting with "For public supply contracts only:...".

**Comment by paulakeen** [comment]
OK, Corrected. The text now reads: "For public service contracts only: During the reference period, the economic operator has provided the following main services of the type specified. Contracting authorities may require up to three years and allow experience dating from more than three years.".

This text has been taken from the EC's ESPD-Service GUI.

**Comment by mireiaBM** [comment]
This issue has been solved in version 2.1.0 of the ESPD-EDM
