### ISSUE TITLE
Criterion #36, two UUIDs missing

### ISSUE THREAD

**Issue by paulakeen** [OP-TED/ESPD-EDM#216]
Two UUID are missing in SC-Other_economic_or_financial (Criterion #36):

![image](https://user-images.githubusercontent.com/16134316/50831794-52da6f00-134c-11e9-8f9b-f7055fd3a323.png)

**Comment by paulakeen** [comment]
Corrected in v2.1.0:

![image](https://user-images.githubusercontent.com/16134316/50831852-87e6c180-134c-11e9-865f-3ed951480ead.png)

**Comment by xavieroudin1** [comment]
Hi everyone,

Can someone tell me what is the cardinality of theses two elements? 

Thank you

Xavier
(French ESPD)

**Comment by mireiaBM** [comment]
This issue has been solved in version 2.1.0 of the ESPD-EDM
