### ISSUE TITLE
Criteria #7 and #8, missing cardinalities

### ISSUE THREAD

**Issue by paulakeen** [OP-TED/ESPD-EDM#217]
Missing cardinalities in Criterion #7 EG-Contributions:

![image](https://user-images.githubusercontent.com/16134316/50832050-4571b480-134d-11e9-9b4d-b3307354195b.png)

**Comment by paulakeen** [comment]
Corrected in v2.1.0:

![image](https://user-images.githubusercontent.com/16134316/50832099-7520bc80-134d-11e9-9a3a-fd19219cc441.png)

**Comment by mireiaBM** [comment]
This issue has been solved in version 2.1.0 of the ESPD-EDM
