### ISSUE TITLE
Criteria #7 and #8, DESCRIPTIONs that should be PERIODs

### ISSUE THREAD

**Issue by paulakeen** [OP-TED/ESPD-EDM#218]
![image](https://user-images.githubusercontent.com/16134316/50844166-72809000-136a-11e9-8bc3-426d8e7e22eb.png)

**Comment by paulakeen** [comment]
Solved in v2.1.0:

![image](https://user-images.githubusercontent.com/16134316/50983706-4f87e480-1500-11e9-9b60-c0f587ebd3b2.png)

**Comment by mireiaBM** [comment]
This issue has been solved in version 2.1.0 of the ESPD-EDM
