### ISSUE TITLE
Part IV, Section C (Supply chain management)

### ISSUE THREAD

**Issue by rantati7** [OP-TED/ESPD-EDM#22]
**Supply chain management** 

CA must be able to define minimum criteria for supply chain management.

NOTE: it is very unclear what can be required here. The main problem being: which criteria are linked to supplier and which to the goods or services that are purchased. Guidance note would be needed.

Extreme example: when car is the object of procurement can CA require here that the manufacturer of the car is paying living wages or using other sustanable practices throught out its supply chain.

**Comment by paulakeen** [comment]
We close this issue for it's been unified with issue #18

**Comment by paulakeen** [comment]
Please find below a proposal for the solution and mock-ups, as commented in the last meeting:

The CA will be able to add multiple requirements.

The EO will need to provide, for each requirement: Name (optional); and Description (mandatory).

View of the CA:
![image](https://cloud.githubusercontent.com/assets/16134316/25391260/282c7840-29d6-11e7-963a-bd5ecc086a25.png)

View of the EO:
![image](https://cloud.githubusercontent.com/assets/16134316/25391271/2ea13fbc-29d6-11e7-92bd-b68d3f3b4fe7.png)

**Comment by paulakeen** [comment]
Please find the details of the final decision in https://github.com/ESPD/ESPD-EDM/wiki/19.-Supply-chain-management
