### ISSUE TITLE
Missing Criteria in the ESPD

### ISSUE THREAD

**Issue by muricna** [OP-TED/ESPD-EDM#221]
During our discussions in the eProcurement ontology working group today we discovered that the following 2 points are not covered in the ESPD and we think this may be an ommoission

Participation in the procedure is reserved to organisations pursuing a public service mission and fulfilling the conditions set in Article 77(2) of Directive 2014/24/EU.
Participation in the procedure is reserved to organisations pursuing a public service mission and fulfilling the conditions set in Article 94(2) of Directive 2014/25/EU.

**Comment by ec-mcs** [comment]
Could it be that this was raised by @JachymHercher in https://github.com/ESPD/ESPD-EDM/issues/220? We should indeed update this with the next release of the ESPD EDM to be in line with the new eForms.
