### ISSUE TITLE
Criteria #34, SC-Financial_ratios

### ISSUE THREAD

**Issue by mpetruzzi** [OP-TED/ESPD-EDM#222]
Hello,

I have noticed that there's a difference between the old mock-up and the structure of criterion (taxonomy  v.2.1.0).

This is the old mock-up.
![financialratio-mockup](https://user-images.githubusercontent.com/38982989/51317542-231c1d00-1a58-11e9-851c-8ae17233f0d8.PNG)

This is the structure of criterion (V.2.1.0)
![financialratio](https://user-images.githubusercontent.com/38982989/51317580-3dee9180-1a58-11e9-8390-b9c13cb4b406.PNG)

Maybe, is it correct to move the Question_Subgroup under the Requirement_Subgroup?
Because every "Ratio Quantity" (Question) is referred to every "Minimum Requirement" (Requirement).

Thank you,
Max

**Comment by paulakeen** [comment]
@mpetruzzi  I think your proposal would clarify the way of treating the QUESTION by software applications, yes. We can propose it for the next release, unfortunately v2.1.0 is closed now.

**Comment by mireiaBM** [comment]
This issue will be addressed in version 3.0.0 of the ESPD data model.

**Comment by AFSOLUZIONI** [comment]
Maybe we must move only the "REQUIREMENT_SUBGROUP}" closure near to the "REQUIREMENT_GROUP}" closure. This means that requirement and response for each Financial Ratio will be near each other (as in the mock up!
Francesco

**Comment by mireiaBM** [comment]
In the ESPD-EDM meeting with the MS, held on September 10, 2019, it was decided that this issue should be closed, since the data structure is correct and fits the purpose expressed in the mock-up. In any case, the contracting authority will ask for a ratio without providing a threshold.
