### ISSUE TITLE
No need for Criterion #51: Subcontracted Proportion

### ISSUE THREAD

**Issue by paulakeen** [OP-TED/ESPD-EDM#223]
UBL-2.2 collects a richer set of information requirements related to this subject (see element  cac:AllowedSubcontractTerms, in cac:TenderingTerms), including a cbc:Description element, which is the only value added by the current ESDP-EDM criterion.

Our proposal is to remove it from the ESPD as a Criterion, as it already is in ProcurementProjectLot, and that the decision was made that all Procurement Procedures have at least one ProcurementProjectLot.

KR

**Comment by ec-mcs** [comment]
I am not sure if we should just replace a selection criteria (in this case no 51 "subcontracted proportion"). Could you post the structure of cac:AllowedSubcontractTerms here?

**Comment by paulakeen** [comment]
The rationale is that this data structure is not a criterion, but an additional information about the EO and its subcontractors. 

The UBL XSD element looks like this (btw, it is in the Lot and in the Procedure):

![image](https://user-images.githubusercontent.com/16134316/51518689-0ba9af00-1e1f-11e9-9b92-202a17841dd2.png)

**Comment by paulakeen** [comment]
We need to discuss it together, as "terms" are always what the CA stipulates, however, we still need to analyse how UBL tackles the response by the EO.

**Comment by mireiaBM** [comment]
In the ESPD-EDM meeting with the MS held on September 10, 2019, it was decided that UBL will be asked to include a new class "EOSubcontractedProportion".
To be implemented in version 3.0.0 and only for the extended model.

**Comment by hricolor** [comment]
In November of 2019, it was discussed and agreed that this change proposed in the comment above was not needed. 
 
The reason to not include this change is that the element for the subcontracted proportion is already present in the ePO. Lot has SubcontractTerms,SubcontractTermshasMaximumSharePercent; Lot has SubcontractTerms, SubcontractTermshasMinimumSharePercent.
 
Moreover, it is currently being analysed at OP and the DG GROW.

**Comment by psotofer** [comment]
Greetings,
@ec-mcs is checking the best way to address this topic with eForms.
We will come back to you when we have more details.

**Comment by psotofer** [comment]
Greetings,

Since it was agreed that this change is not needed in ESPD we proceed to close this discussion.
How this could affect eForms will be addressed in a future discussion and we will inform you accordingly.

**Comment by acolomer** [comment]
Due to policy obligations, it is necessary to keep the criterion as it is today both in eForms and in the ESPD. Therefore, it was decided on the 13th September of 2021 to close this issue.
