### ISSUE TITLE
listID attribute for cbc:CriterionTypeCode is not aligned with CodeLists-V2.1.0 

### ISSUE THREAD

**Issue by albenzio** [OP-TED/ESPD-EDM#224]
Element "cbc:CriterionTypeCode " in _xml/SELFCONTAINED_ESPD-Request.V2.1.0.xml_ has the following value for the listID attribute

>  listID="CriteriaTypeCode"

Looking into ESPD-CodeLists-V2.1.0.xlsx, it seems that the same value should be 

> listID="CriteriaTaxonomy".

This is not currently revealed by the ESPD validation service, but it should be fixed.
Thanks for your reply

**Comment by paulakeen** [comment]
Please see examples provided by ESPDint in folder [dist/xml](https://github.com/ESPD/ESPD-EDM/tree/2.1.0/docs/src/main/asciidoc/dist/xml).

**Comment by paulakeen** [comment]
Dear @albenzio, 

Do the newest examples solve the issue? can we close it?

**Comment by mireiaBM** [comment]
This issue has been solved in version 2.1.0 of the ESPD-EDM
