### ISSUE TITLE
Unnecessary redundant data about the criterion weight

### ISSUE THREAD

**Issue by paulakeen** [OP-TED/ESPD-EDM#225]
the REQUIREMENT(s) ''This criterion will be weighted'' in Criteria #40 to #50 is redundant with the element
`cbc:EvaluationMethodTypeCode` (inside the cac:TenderingCriterion) and could cause inconsistency. It should be removed from the data structure. This implies that the REQUIREMENT would have to be replaced with a CAPTION, because of the cardinality constraint imposed by the UBL-2.2 requiring that the first element inside a group or subgroup is a `cac:TenderingCriterionProperty`.

**Comment by mireiaBM** [comment]
The data about the criterion weight in criteria # 40 and # 50 is needed by the GUI for the contracting authority to be asked about the specific weight of one criterion.
This means that the data structure is correct. However, this should be well explained in the documentation for version 2.1.1.

**Comment by JosePRevenga** [comment]
In the [Table 47. Order of occurrence of the different blocks of data related to weights](https://espd.github.io/ESPD-EDM/v2.1.1/xml_guide.html#information-requirement-check-list) of Section IX.2, All about weights, of the online documentation it is now clearly stated that the data about the criterion weight in criteria # 40 and # 50 is needed by the GUI for the contracting authority to be asked about the specific weight of one criterion.
