### ISSUE TITLE
ESPD 2.0.2 Self contained: XML Validator unavailable

### ISSUE THREAD

**Issue by ghost** [OP-TED/ESPD-EDM#228]
We've been using the URL http://isaitb2.northeurope.cloudapp.azure.com/espd/upload to test our Self cointaned artefacts of the version 2.0.2 but it seems to be unavailable for some time now.

We currently have no way to test and validate our artefacts for this version. Could you provide us with an alternative?

Thank you
Mariana Marques

**Comment by mfontsan** [comment]
The URL you are using is an old one, that's why it is unavailable.

The XML validator tool has been migrated into the following URL:
- https://www.itb.ec.europa.eu/espd/upload

**Comment by paulakeen** [comment]
This will be corrected in  the recent documentation.

Apologies.

**Comment by mireiaBM** [comment]
This issue has been solved in version 2.1.0 of the ESPD-EDM
