### ISSUE TITLE
Part IV, Section C (Allowance of checks)

### ISSUE THREAD

**Issue by rantati7** [OP-TED/ESPD-EDM#23]
**Allowance of checks**

CA cannot require full check of everything (the text implies that CA would require all kinds of checks and audits).

CA must set a limit / set maximum for cheks and audits.

**Comment by paulakeen** [comment]
We close this issue, for it's been unified with issue #18

**Comment by paulakeen** [comment]
Please find below a proposal for the solution and mock-ups, as commented in the last meeting:

The CA will be able to add multiple requirements.

The EO will need to  answer YES/NO to each requirement.

View of the CA:
![image](https://cloud.githubusercontent.com/assets/16134316/25391428/834fee82-29d6-11e7-8228-f58960520748.png)

View of the EO:
![image](https://cloud.githubusercontent.com/assets/16134316/25613799/d45ded98-2f2f-11e7-8ace-ad1463d07cfd.png)

**Comment by paulakeen** [comment]
Please find the details of the final decision in https://github.com/ESPD/ESPD-EDM/wiki/20.-Allowance-of-checks
