### ISSUE TITLE
Criterion #24 Purely National Exclusion Grounds

### ISSUE THREAD

**Issue by AFSOLUZIONI** [OP-TED/ESPD-EDM#231]
Hi,
In Italian project team we are discussing about the QUESTION in the criterion:

It seems a question for the contracting authority (REQUIREMENT) and not for the EO. Maybe it could be a question for the member State (are there  or not National Criteria??).
The risk of the current situation is related to an answer "NO" from EO and then an incorrect completation of National Criteria.
A solution could be leaving the decision to CA (change in REQUIREMENT) and open or not the national criteria on   content of the previous requirement.
The solution isn't so linear but we can't expect that the EO fill "YES" to see if there are NAtional Criteria or not.
What do you think abaut??

Francesco

**Comment by ec-mcs** [comment]
I hope to answer your question correctly. The idea with the self-contained ESPD was to show all national criteria https://espd.github.io/ESPD-EDM/v2.0.2/xml_guide.html#mock-ups-contracting-authority-perspective-strong-regulated-strong 
The EO should tick for each of them "No" instead of a single no.
So indeed the question(s) should come from the CA side. The EO should only reply to them.

**Comment by AFSOLUZIONI** [comment]
Hi Marc,
we have an old version of criterion #24 and I don't know when started the difference. We have a subcriterion zone to represents the different national criteria. In the current version (I saw the EDM and the taxonomy) we have a criterion with a subgroup (1..n) to insert the different national criteria:

1. the subgroup criteria description is the description of national criterion

2. the stucture inside the subgroup is the articulation of national criterion

3. the step 1 and 2 must be repeated for all the national criteria.

am I right??
In this case I have only question about UUID for the subgroup (I suppose must be the same it have in e-CERTIS) and for all the other structure needed to express the national criteria  ( I suppose defined by Member State).
Could you help me on this two questions??
Thank you 

P.S. If a member state haven't national criteria ... the 24 criterion disappear (maybe by the CA customization)??

Francesco

**Comment by ec-mcs** [comment]
About how which UUID to use, or about the data structure @paulakeen knows best. 
If there is no national criterion, I would expect that the CA does not select national criteria. If the data model is integrated in an eTendering solution, national exclusion grounds will not be offered likely. And there are countries where there are no national exclusion grounds.

**Comment by AFSOLUZIONI** [comment]
Thank you Marc,
I'm waiting from an answer from Paula :-)

Francesco

**Comment by ricardoreais** [comment]
Let me add one more thing here. According to the data structure of the Purely National Exclusion Grounds we have 1..n subgroups with the national criteria from e-Certis. But for some countries, like Portugal for example, the e-Certis has no national criteria available. So we have to add a subgroup with empty captions. Should this be 0..n?

![image](https://user-images.githubusercontent.com/22318105/54306958-762ad000-45c2-11e9-8c11-6aca148b7e5e.png)

**Comment by mireiaBM** [comment]
Dear @AFSOLUZIONI and @ec-mcs : 
1. Regarding the UUIDs of the groups and subrgroups, we observed that, in the self-contained model, some UUIDs are missing. This is a bug. We will generate UUIDs for these subgroups in the ESPD self-contained and we will ask e-Certis to take them into account. 
2. @ec-mcs you are right as far as the ESPD self-contained is concerned: the difference with the regulated is that in the self-contained we are not asking about self-clearing measures. We only ask for yes/no (as agreed with the members of the working group).

Dear @ricardoreais :
The cardinality 1..n of the first subgroup of questions as it is now seems correct to us: if Portugal has not national Criteria, then the data structure for the whole Criterion should not be instantiated at all. If you have the need of instantiating other national criteria, that would mean that at least you have one national criterion.

**Comment by JosePRevenga** [comment]
The missing UUIDs have been added and the validator rules updated so purely National exclusion grounds are no longer mandatory in v2.1.1.
