### ISSUE TITLE
Multiple Lots response not allowed

### ISSUE THREAD

**Issue by ricardoreais** [OP-TED/ESPD-EDM#232]
Currently in the documentation it is shown that we can have a TenderingCriterionResponse with multiple ResponseValues, but the schematron doesn't allow it (Response (version 2.0.2))
![54150578-afcbd180-4430-11e9-9afe-72cb7165f918](https://user-images.githubusercontent.com/22318105/54274117-3abae200-457f-11e9-94e4-e788fb091cb3.png)

**Comment by paulakeen** [comment]
hum, this had been solved long time ago....let us see what's going on....but if you could share the validation report you're getting that would help, too.

many thanks!

**Comment by ricardoreais** [comment]
Using the validator: https://www.itb.ec.europa.eu/espd/upload

I am getting this in the report:
![image](https://user-images.githubusercontent.com/22318105/54285292-93977400-4599-11e9-9e82-228f0a43674e.png)

**Comment by mfontsan** [comment]
We have updated the validation related to the multiple lots response to align it with version 2.1.0. (One and only one response element per criterion response is mandatory).

This change is already committed in GitHub and in the Interoperablity TestBed validator.

**Comment by mireiaBM** [comment]
This issue has been solved in version 2.1.0 of the ESPD-EDM
