### ISSUE TITLE
Cardinality of EG-Purely_national

### ISSUE THREAD

**Issue by xavieroudin1** [OP-TED/ESPD-EDM#233]
![EG Purely National](https://user-images.githubusercontent.com/48014200/54533832-61b45200-498b-11e9-8c64-45bb1b994d28.png)
Hi everyone, 

For the EG-Purely_national criteria there is no UUID on the 1st question group. And in their question subgroup there is no cardinality. 

Can someone help us

Thank you

Xavier
(French ESPD)

**Comment by mireiaBM** [comment]
Same issue as issue #231
