### ISSUE TITLE
Average yearly turnover general and specific - Start / end date instead of number

### ISSUE THREAD

**Issue by xavieroudin1** [OP-TED/ESPD-EDM#236]
Hi everyone

For the criterion average yearly turnoever, the contracting autority can in the self contained ESPD indicate the number of years it asks for. 

In the documentation it is an start and a end date that is asked. 

We don't understand how it is possible. Accounting exercises can start anytime in the year. 

Is this an issue that can be corrected ? For us it can generate some questions from EO such as "the CA ask me my account exersises from 01 / 01/2016 to 31/31/2016 but my exersises is from 31/03/2017. What can I do?" 

Moreover, I'v seen there is the same system for the specific general turnover. The documentation 2.0.2 mookup indicates "number of years" and the taxonomy a stard / end date. 

How to tackle this subject? 

Xavier
French ESPD

![startend2](https://user-images.githubusercontent.com/48014200/54770555-c548b480-4c03-11e9-8199-611b54c44880.png)

![startdate](https://user-images.githubusercontent.com/48014200/54769734-21aad480-4c02-11e9-84f7-3b8789aefe44.png)

**Comment by paulakeen** [comment]
@xavieroudin1 , the CA only specifies the amount of years, but it cannot specify the period when the fiscal year starts and ends, that is for the EO to say. If you look the mock-up below the one you paste above you will notice that the period corresponding to the fiscal years corresponds to the form the economic operator fills in:

![image](https://user-images.githubusercontent.com/16134316/54917185-85334b80-4efb-11e9-9f33-1007d7d4a3eb.png)

**Comment by xavieroudin1** [comment]
@paulakeen Thank you you're right. Do you confirm it is the same for average yearly turnover? My impression is that here it is the CA that indicates the period
![image](https://user-images.githubusercontent.com/48014200/54919365-e01b7180-4f00-11e9-885e-c594381f7e25.png)

**Comment by mireiaBM** [comment]
Dear @xavieroudin1 , you are right. We will modify the general average turnover, replacing start date/end date with number of fiscal years, both in the mockup and in the data structure.

**Comment by JosePRevenga** [comment]
The type of "Number of fiscal years" requirement of Criterion #30: SC-General_Average_Turnover of Extended model has been changed from start date/end date to QUANTITY_INTEGER in v2.1.1.
