### ISSUE TITLE
Criterion #62 self contained

### ISSUE THREAD

**Issue by AFSOLUZIONI** [OP-TED/ESPD-EDM#237]
Hi,
We found an issue in the validator for 2.1.0 ESPD self contained Request for the criterion #62.
We have this error:

**The Tendering Criterion, which 'cac:TenderingCriterion/cbc:ID = 8b9700b7-b13c-41e6-a220-6bbf8d5fab31', has '1' missing 'cac:TenderingCriterionPropertyGroup' element(s).**

We verified our XML was correct and, maybe, the validator was not allined with the 2.1.0 for the #62.
Here you are the taxonomy for the criterion in the 2.0.2 and 2.1.0
![Criterion #62 v 2 0 2](https://user-images.githubusercontent.com/44367854/54912246-8e6aeb00-4ef0-11e9-9314-76e30d327d24.jpg)

![Criterion #62 v 2 1 0](https://user-images.githubusercontent.com/44367854/54912257-94f96280-4ef0-11e9-97da-24e39fc1cad1.jpg)

We added a second group to our XML with the UUID of the one in the 2.0.2 taxonomy and the error disappeared.
Could you please alligne the validator??
Thank you for support.

Francesco.

**Comment by paulakeen** [comment]
Could you please link the XML instance you are using, please. We'll have a look at it tomorrow.
Tks.

**Comment by AFSOLUZIONI** [comment]
Hi,
here you are the XML .
Francesco
[ESPD_REQUEST_missing_group.txt](https://github.com/ESPD/ESPD-EDM/files/3003140/ESPD_REQUEST_missing_group.txt)

P.S. I must change the extension in .txt from .xml to attach the file.

**Comment by mfontsan** [comment]
Hi, 

We have updated the validator in order to align the Criteria Taxonomy to the latest updates, including the Tendering Criterion with ID = 8b9700b7-b13c-41e6-a220-6bbf8d5fab31.

Thank you.

**Comment by mireiaBM** [comment]
This issue has been solved in version 2.1.0 of the ESPD-EDM
