### ISSUE TITLE
Call for expression of interests published by the Publications Office

### ISSUE THREAD

**Issue by MindaugasPaulavicius** [OP-TED/ESPD-EDM#238]
This is not an EDM issue.

This is to announce, that the Publications Office has published a Call for expression of interests to build a list of experts (business editor and technical editor) in the domain of public procurement. We expect that this call might interest many participants of ESPD EDM thread.

Please follow this [link](https://ted.europa.eu/udl?uri=TED%3ANOTICE%3A77906-2019%3ATEXT%3AEN%3AHTML&src=0&fbclid=IwAR2tAmMdnCnPBdpvxDE33cBdROE4zDJdYhEDH1FXwutdnbnIFHRW4YVU6tQ) for the notice on TED.

-------------------------------------------------

If you are a European standards expert, make note of the  StandICT.eu 6th Open Call.  This may allow you to apply for financial support to your ICT Standards activities & help contribute to the international ICT Standardisation arena.   
[https://www.standict.eu/OpenCalls/6th-Open-Call](https://www.standict.eu/OpenCalls/6th-Open-Call)

Submission deadline on 30th April 2019 @17:00 CET.

**Comment by mireiaBM** [comment]
Closing this issue, as it is not an issue but an announcement and therefore does not need to be solved.
