### ISSUE TITLE
Part IV, Section C ("Educational and professional qualifications" and "Environmental management measures")

### ISSUE THREAD

**Issue by rantati7** [OP-TED/ESPD-EDM#24]
**Educational and professional qualifications**

CA must be able to define minimum criteria for educational and professional qualifications.

**Comment by lauramrtn** [comment]
Agree, we think when the ESPD is self-contained the required qualifications should sit next to the question.

.

**Comment by paulakeen** [comment]
We close this issue, for it's been unified with issue #18

**Comment by paulakeen** [comment]
Please find below a proposal of mock-ups, both for the view of the CA and the view of the EO.

- View of the CA:
![image](https://cloud.githubusercontent.com/assets/16134316/25663239/6851bbaa-3017-11e7-8f5d-91a56c076d27.png)

- View of the EO:
![image](https://cloud.githubusercontent.com/assets/16134316/25663298/9290eeea-3017-11e7-84db-d09a19543b71.png)

**Comment by paulakeen** [comment]
Please find the details of the final decision in https://github.com/ESPD/ESPD-EDM/wiki/21.-Educational-and-professional-qualifications-and-Environmental-management-measures
