### ISSUE TITLE
SC  - Reference - Recipient name 0..n

### ISSUE THREAD

**Issue by xavieroudin1** [OP-TED/ESPD-EDM#240]
Hi everyone, 

Why, for the criterion "Referecens", the Recipient Name is 00..n and not 0..1 (as for contact person name and contact mail ) ?

Xavier

**Comment by AFSOLUZIONI** [comment]
Hi,
I agree with you.
In addition we have 00..n even for "Recipients". We assume that "Reference" could be 00..n (according with requirement) and "Recipient" and "Recipient Name" must be 0..1.
Are we wrong?? And if so what is the reason??
![Criterion #37](https://user-images.githubusercontent.com/44367854/55098406-fde20580-50bd-11e9-9a40-a68040138512.jpg)

These considerations apply also to Criteria #38 and #39
Francesco

**Comment by guifregusta** [comment]
Hello,

There may be several "Recipients" for a "Reference", and each "Recipients" has one "Recipient's Name" that may be complete or not.

This "Reference" describes each component of the upper group (a44e24e9-f878-4651-9ead-e0b1387dae09) of multiple References. 

In the next release of ESPD, the cardinality of "Recipient's name" will be updated to 0..1. The others will remain as they are.

"Recipient's name" is a question in "Recipients" (6afa7569-e4c4-4538-be89-84a82b2a301b).
It's used in:
37 - CRITERION.SELECTION.TECHNICAL_PROFESSIONAL_ABILITY.REFERENCES.WORKS_PERFORMANCE
38 - CRITERION.SELECTION.TECHNICAL_PROFESSIONAL_ABILITY.REFERENCES.SUPPLIES_DELIVERY_PERFORMANCE
39 - CRITERION.SELECTION.TECHNICAL_PROFESSIONAL_ABILITY.REFERENCES.SERVICES_DELIVERY_PERFORMANCE

**Comment by JosePRevenga** [comment]
As previously announced by guifregusta, in the v2.1.1, in the selection Criterion #37: SC-REFERENCES, the cardinality of the QUESTION, "Recipient name" has been changed to 0..1 .
