### ISSUE TITLE
Criteria #25, #26 and # 33 inconsistency with regulation and improvement suggestion

### ISSUE THREAD

**Issue by sakispantazis** [OP-TED/ESPD-EDM#244]
Criteria 25, 26 (i.e. the question asking if the economic operator is enrolled in the relevant professional or trade registers) and Criterion 33 (the question regarding the date that the economic operator started trading or set up)

The Regulation’s stipulations for these criteria are:

Criteria 25, 26
![image](https://user-images.githubusercontent.com/16813866/57987990-6089c900-7a91-11e9-972b-cd36adcb5386.png)

 Criterion  33
 
![image](https://user-images.githubusercontent.com/16813866/57987992-667faa00-7a91-11e9-89b1-13015b7b0464.png)

In the current implementation of the ESPD taxonomy/structure for criteria 25, 26 there is a yes/no radio button, which we find ok. However, the Regulation implies that there should be a text field (which makes no sense – hence the Regulation have to be improved/changed here).  As far as criterion 33 concerns we suggest the text field, used now in the taxonomy/structure, should be replaced with a date field.

**Comment by mireiaBM** [comment]
Dear @sakispantazis, thanks for pointing this out! However, the structure will be left as it currently is in the ESPD EDM.

**Comment by sakispantazis** [comment]
Dear @mireiaBM and @ec-mcs,

I would like to point out that there are several issues (#242, #246) with inconsistencies of the wording ("negative" questions; unnecessary fields; date field instead of simple text field,etc.)  compared with the Regulation. As stated, we don' t mind to keep the ESPD EDM interpretation, but there has to be some feedback mechanism towards the lawyers/legal department of the PO in order to incorporate these "changes/improvements" into the next version of the Regulation. Simply, closing these issues, won't help ...
