### ISSUE TITLE
Criteria #27 and #28 missing “yes/no” sub-question and potential cardinality issue

### ISSUE THREAD

**Issue by sakispantazis** [OP-TED/ESPD-EDM#245]
Criteria 27, 28 (i.e. the question asking if a particular authorization or membership is needed)

The Regulation’s stipulations for these criteria are:
![image](https://user-images.githubusercontent.com/16813866/57988226-32f24f00-7a94-11e9-8ed0-04213014e4a6.png)

  
a)	In the current implementation of the ESPD taxonomy/structure for criteria 27, 28, there are no extra “yes/no” radio buttons for answering if the EO has the particular authorization or membership or not (after the EO has specified those in the relevant text field).  This issue applies only for the ESPD response in case of the regulated ESPD. However, it might be relevant for both request and response in case of the self-contained ESPD.
b)	There might be also a cardinality issue in case that there are more than one organization memberships requested, i.e. the following set of fields/questions: [text field for specific organization membership + “yes/no” question for specific membership + web address fields for documentation for specific membership] should have cardinality 1..n

**Comment by sakispantazis** [comment]
c) Also, the wording, «Please describe them», should be replaced by the wording “If yes, please specify which and specify it the economic operator has it:” is missing.

**Comment by mireiaBM** [comment]
Dear @sakispantazis , this issue will be addressed in version 2.1.1 of the ESPD data model.

**Comment by JosePRevenga** [comment]
For v2.1.1, In criteria #27 and #28 a new QUESTION_SUBGROUP has been added to assemble both the new "yes/no" QUESTION and the, now reworded one, "If yes, please describe them". The cardinality of this new QUESTION_SUBGROUP is 0..n, as many authorisations/memberships, or none, could be required.
