### ISSUE TITLE
Criteria #60 and #61 new fields  inconsistent to Regulation

### ISSUE THREAD

**Issue by sakispantazis** [OP-TED/ESPD-EDM#247]
Criterion 60 (i.e. the question asking if the economic operator relies on the capacities of other entities in order to meet the selection criteria ) and criterion 61 (i.e. the question asking if the economic operator intends to subcontract any share of the contract to third parties)

The Regulation’s stipulations for these criteria are:

Criterion 60:
      
![image](https://user-images.githubusercontent.com/16813866/57989007-96cd4580-7a9d-11e9-8e86-db6b49a2260f.png)
![image](https://user-images.githubusercontent.com/16813866/57989008-9c2a9000-7a9d-11e9-8cb9-9eb162a17d54.png)

 
Criterion 61:
    
![image](https://user-images.githubusercontent.com/16813866/57989011-a3ea3480-7a9d-11e9-9261-717117e80924.png)
    

In the current implementation of the ESPD taxonomy/structure for both criteria 60 and 61 and in case of a positive answer following fields appear: name of the entity, ID of the entity, type of ID, CPV codes. 
The regulated version is supposed to show some extra static text for criterion 60 and only one text field for criterion 61. I think we could keep these fields (name of the entity, ID of the entity, type of ID, CPV codes), but in any case for the criterion 60 the extra static text (grey box in the Regulation) has to appear as well.

**Comment by ec-mcs** [comment]
Hi Sakis, happy to hear that you would suggest to keep the field names. Indeed this is important to know who is part of the offer as well. The suggestion about the static field (info field), this is for the application/UI in my view and should not belong in the ESPD data model. I would therefore like to close this issue.

**Comment by sakispantazis** [comment]
Dear @ec-mcs, I and @jerouris are not sure that the info field belongs to the applcation/UI. This info field appears in an if clause of the criterion's response, it is not as much "static" as the labels of the Parts or Sections of the ESPD.
