### ISSUE TITLE
EO Response: Missing initial “yes/no” answer for all selection criterion @ Section B and C of Part IV

### ISSUE THREAD

**Issue by sakispantazis** [OP-TED/ESPD-EDM#249]
Like in Section A of Part IV, all selection criteria in Section B and C of Part IV should offer the possibility of an initial “yes/no” answer by the EO for each criterion.
The EO shouldn’t be obliged to fill in mandatory fields describing how the EO fulfills specific selection criteria in Section B and C of Part IV, in case it does not meet these criteria and hence has to rely upon a third party EO for these criteria.

**Comment by ec-mcs** [comment]
We should foresee this in a v3 of the ESPD data model. Actually when thinking about digitisation the process should be like this: If the EO cannot satisfy one selection criterion and they say "no", than it should be possible to indicate which company will fulfil this criterion. This would help during the evaluation phase.

**Comment by sakispantazis** [comment]
Sorry, but we would appreciate specifically for this issue to have a solution sooner, i.e. we cannot wait for v.3.0.0

I would like to remind everybody that in Part IV (selection criteria) the EO can answer for all criteria of section A and D and for some criteria of section C with "yes/no" at the beginning, indicating if the EO is meeting this criteria or not (hence the EO must rely upon another EO), and then the EO is presented or not with the mandatory subsequent questions of the criterion. Why is this not the case with the criteria in section B and some of the criteria in section C (where do they differ business-wise)?

The problem is that the subsequent fields of these criteria are now mandatory (v.2.x vs v.1.x), hence if the ESPD request contains one of these criteria and the EO relies upon another EO for those, than the first EO cannot complete its ESPD response (because the fields are mandatory)!

Our HelpDesk suggestion towards the EOs (for the time being  marginal acceptable), is: Fill out these mandatory fields with dummy data, in order to be able to produce the ESPD response (XML and PDF; note PDF is important for submission in Greece), and then erase from the PDF file the dummy data (using Acrobat or by converting it to DOC first and than back to PDF).

**Comment by JosePRevenga** [comment]
Unfortunately, introducing the changes required in v2.1.1 would break backwards compatibility with currently existing solutions. We will address this as a major change for v3.0.0 in a dedicated session. Sorry for the inconvenience.

**Comment by AFSOLUZIONI** [comment]
Hi, even if the answer is a solution in 3.0.0, could you are more specific in defining the criteria you are referring to??
For example, for turnover information I suppose all EO must insert their information, same thing for professional risk insurance and so on.
My opinion (but is on italian procurement law) is the main EO (sole contractor or lead entity) must have, maybe only a part of the value requested, the values (turnover, insurance, etc. etc.).
Then I need to know the criteria you are referring to make a complete analisys.
Hope it can help.
Francesco

**Comment by JosePRevenga** [comment]
Dear Francesco,

We are referring to Criteria CRITERION.SELECTION.ECONOMIC_FINANCIAL_STANDING.* and CRITERION.SELECTION.TECHNICAL_PROFESSIONAL_ABILITY.*.

As stated in the[ 6.2 point](https://espd.github.io/ESPD-EDM/v2.1.0/xml_guide.html#viii-6-2-self-contained-economic-operator-party) of VIII section of the ESPD v2.1.0 documentation Guide, only the Sole-contractor/lead Entity and the group members are required to produce a complete ESPD Response, while other entities (relied upon or not) will have to produce an ESPD skipping the parts they are not actually required to fill.

If you have further issues or doubts, we remain at your disposal.

**Comment by AFSOLUZIONI** [comment]
OK, understood.
I have two answer for you.

The first one:
in our procurement platform we are able to customize the ESPD to be produced for each kind of EO. (See form below)
![image](https://user-images.githubusercontent.com/44367854/67467340-ddc0f780-f648-11e9-9ab3-4767b342d15a.png)
where "DGUE Strutturato" is the one for Sole-Contractor / lead Entity
"DGUE mandanti" is for group partecipant
"DGUE Ausiliarie" is for "rely on entity"
and so on.
Then you can insert or not the criteria that are needed in the different situation before you publish the procurement.
Obviously  the mandatory criteria (e.g. exclusion ground criteria) cannot be deleted!!

The second one:
in the beginning of ESPD you must declare the role you have in the offer ([8.6.2 paragraph of EDM](https://espd.github.io/ESPD-EDM/v2.1.0/xml_guide.html#viii-6-2-self-contained-economic-operator-party))
(see figure below)
![image](https://user-images.githubusercontent.com/44367854/67468585-0e099580-f64b-11e9-8537-9cc5867bff06.png)

Then you can manage your application on the basis of the field "role" to insert or delete the criteria that are not useful.

I hope this answer to your question. Anyway I'm available to further analisys.

Regards
Francesco

**Comment by JosePRevenga** [comment]
Dear Francesco,

Thank you for your comments, we will take them into account when assessing the issue for v3.0.0.

**Comment by hricolor** [comment]
As discussed an agreed during the last OUC meeting _**(9th July 2020)**_, here there are the different options proposed solutions for its discussion: 
 
**Option 1:** 
 
![image](https://user-images.githubusercontent.com/15996178/91972471-10cd2080-ed1b-11ea-8b81-f4ac9819828a.png)

**Implications:** 
- Keep using Booleans.
- Add a new sub-question to indicate if the criteria is relied upon or not.
- Add the identifier of the organisation that is relied upon.
- Include the link to Part II – Section C - “Relied upon” criterion # 60 (CRITERION.OTHER.EO_DATA.RELIES_ON_OTHER_CAPACITIES), to enhance the automatization of the CA data processing. And the link to Part II  - Section A – “EO together with others” criterion # 59 (CRITERION.OTHER.EO_DATA.TOGETHER_WITH_OTHERS).

 
**Option 2:**

![image](https://user-images.githubusercontent.com/15996178/91972734-643f6e80-ed1b-11ea-94d3-83f5c074fd35.png)

**Implications:** 
- Implies the change of PropertyDataType from Boolean to another PropertyDataType (adhoc).
- Add the identifier of the organisation that is relied upon.
- Include the link to Part II – Section C - “Relied upon” criterion # 60 (CRITERION.OTHER.EO_DATA.RELIES_ON_OTHER_CAPACITIES), to enhance the automatization of the CA data processing. And the link to Part II  - Section A – “EO together with others” criterion # 59 (CRITERION.OTHER.EO_DATA.TOGETHER_WITH_OTHERS).

 
Please, feel free to comment and discuss the different proposals to ensure a quality final decision

**Comment by hricolor** [comment]
After present this issue in the last OUC of the 1st of October, and discuss with the stakeholders, this is the proposed solution that will be implemented:

It will be included in the Selection Criteria, a first question to ask if the EO fulfils the criteria by itself or instead, relies on another entity to do so. This solution includes diverse ways to answer the Criteria. 

If the EO filfils the requirements by itself, it will be shown like in the following image: 
![Issue249_OP_YES](https://user-images.githubusercontent.com/60606496/96234177-63942c00-0f99-11eb-91a8-967e4699371a.png)
And, then the EO picks “NO”, the following step will be taken: 
![Issue249_OP1_NO](https://user-images.githubusercontent.com/60606496/96234464-c1c10f00-0f99-11eb-81e2-3bce2ffbdd71.png)
In this second option, the EO has to answer yes if relies on other Entity, and then provide the name and ID of the EO which relies on. 

In case the EO selects no in this second step, the EO would be out of the procedure. 

This issue will be implemented within the next ESPD-EDM 3.0.0.

**Comment by psotofer** [comment]
As commented before, this issue was included in the last ESPD-EDM Release v3.0.0. therefore we proceed to close this issue.
In case you need further detail regarding this topic, please open a new issue referencing this one.
