### ISSUE TITLE
Part IV, Section C (Environmental management measures)

### ISSUE THREAD

**Issue by rantati7** [OP-TED/ESPD-EDM#25]
**Environmental management measures**

CA must be able to define minimum criteria for environmental management measures.

NOTE: it is very unclear what can be required here. The main problem being: which criteria are linked to supplier and which to the goods or services that are purchased. Guidance note would be needed.

**Comment by lauramrtn** [comment]
We think this question relates solely to the EO not the goods or services to be purchased.

**Comment by paulakeen** [comment]
We close this issue, for it's been unified with issue #18

**Comment by paulakeen** [comment]
Issue unified with issue #24
