### ISSUE TITLE
Criterion #59 roles

### ISSUE THREAD

**Issue by sakispantazis** [OP-TED/ESPD-EDM#250]
In criterion #59 (i.e. the question whether the EO is participating along with others) and in the case the EO is participating along with others, the roles should be 
either the following three:
a)	Lead entity/Contractor (i.e. one EO response has to be submitted in a tender by the EO that is either the leader of a consortium/group of EOs or the contractor when this EO is using others as subcontractors)
b)	Consortium/Group Member (i.e. one or more EO responses have to be submitted in a tender by the EOs that are members of a consortium/group of EOs, independently if lead entity relies upon them or not)
c)	Subcontractor (i.e. one or more EO responses might have to be submitted in a tender by the EOs that are participating as subcontractors along with the contractor, independently if the contractor relies upon them or not)

or the following six (three pairs):
a)	Consortium Leader
b)	Consortium Member
c)	Group Leader
d)	Group Member 
e)	Contractor
f)	Subcontractor 

The information for “relied upon” or “not relied upon” is irrelevant for this criterion and it is also redundant information, since it is being requested with the criteria of Section C and D of Part II.

**Comment by mireiaBM** [comment]
Dear @sakispantazis, a code list that defines these categories already exists in ESPD (EORoleType: https://github.com/ESPD/ESPD-EDM/blob/2.1.0/docs/src/main/asciidoc/dist/cl/gc/EORoleType-CodeList.gc) and it is being used in other parts of the XSD (in particular, cac:EconomicOperatorParty/ cac:EconomicOperatorRole/cbc:RoleCode). So, the information of this code list cannot be currently modified since the information for “relied upon” or “not relied upon” is needed in the Economic Operator.

**Comment by sakispantazis** [comment]
Dear @mireiaBM, I would like to re-open this issue because I would like to discuss the revision of this codelist's values, because:

i) The purpose of this question/criteria is to determine the role of the EO in the tender, i.e. 
ii) In order to determine "rely upon or not", there are separate questions/criteria, i.e. section C and D in Part II.
iii)  As mentioned before, this codelist should include the following six values (or three pairs of values):
a) Consortium Leader
b) Consortium Member (note: the consortium leader may or may not rely upon the consortium member) 
c) Group Leader
d) Group Member (note: the group leader may or may not rely upon the group member)
e) Contractor
f) Subcontractor (note: the contractor may or may not rely upon the subcontractor) 

iv) EOs are getting confused concerning these three values:
**Sole   contractor / Lead entity** | Sole entity or, in case of Consortium,   Joint Venture or other types of groups, the leader of the group.
**Sole   contractor** | Sole entity
**Lead Entity** | The leader of a Consortium, Joint Venture or another type of group.
Which of the above do they have to choose if they are Sole Contractor (1st or 2nd?), Lead entity (1st or 3rd?)

v) EOs are getting confused concerning these values as well:
**Group   member** | Member (not leader) of the Consortium,   Joint Venture or other type of group.
**Other entity (relied upon)** | Entity on which the main contractor, the group or another subcontractor   relies in order to meet the selection criteria.
**Other entity (not relied   upon)** | Entity on which the main contractor, the group or another subcontractor   does not rely in order to meet the selection criteria.
Which of the above do they have to choose if they are Group Member **and** Other entity (relied upon)?

**Comment by ec-mcs** [comment]
Hi @sakispantazis

Yes, the idea is to understand the role of a specific EO in the bid and to understand how much they need to fill in in the ESPD and to help service providers to support their suppliers.
The problem of "entity to rely upon" and "not to rely upon" is indeed a very legal one that is not easily to be understood by suppliers. 
Currently we have

- **(1)** Sole contractor / Lead entity
- **(2)** Sole contractor
- **(3)** Lead Entity
- **(4)** Group member
- **(5)** Other entity (relied upon)
- **(6)** Other entity (not relied upon)

On (1): We started with "Sole contractor / Lead entity" but as this was two different concepts, we decided later to split them up in (2), (3). This should be marked deprecated and not be used anymore. We need to see how to do this, as changing a codelist is always tricky.

So we would/should only have **(2), (3), (4), (5), (6)** in the end.

I don't think that the suggestion to have Consortium Member or Group Member, or Contractor would help. 

Mathematically I would say the following:
- If **(2)** then there can be (**(5)** and/or **(6)**), (but and NOT **(3)** or **(4)**)
- If **(3)** then there must be **(4)** and can be (**(5)** and/or **(6)**), (but and NOT **(2)**)
This distinction would not be possible in the categories that you present. 

To help EOs to fill in the right role I would suggest the following:
Already now some ESPD services allow to invite suppliers to fill in an ESPD. In this way, an ESPD service can help to select from the very beginning the role of the EO and not to leave it for the user.

I will reopen this issue to discuss it and test if the assumptions are correct.

**Comment by sakispantazis** [comment]
**I think we need to discuss this verbally, because it seems I am missing something.** 

A) Maybe it is a matter of definitions, i.e. in Greek legal system a bidder might be either

1) **Sole Contractor =** One EO is going for the bid and will solely sign the contract with the CA; however the Sole Contractor may use also Subcontractors, i.e. the EO is going for the bid along with a third party (subcontractor(s)); Also, the EO may or may not rely upon this/these subcontractor(s); if "not rely upon" subcontractors are going to implement more than 30% of a contract's subject matter, then these subcontractors have to fill out a separate ESPD; However, all "rely upon" subcontractors  have to fill out a separate ESPD. 

or

2) **Union/Group of EOs =** no distinct legal entity with distinct name and distinct VAT ID; just a union/group of EOs bound to each other by a contract to pursue a venture; one of these EOs is usually the designated leader of the union/group; Although, usually the union/group is formed because the EOs rely upon each other as far as selection criteria concerns, there are cases where union/group members are entities which the union/group does not rely upon. Anyway, according to the Regulation, all members have to submit a separate ESPD.

or

3) **Consortium =** one legal entity with distinct name and VAT ID comprised by several EOs; one of these EOs is usually the designated leader representing the consortium; the others are consortium members; Although, usually the consortium is formed because the EOs rely upon each other as far as selection criteria concerns, there are cases where consortium members are entities which the consortium does not rely upon. Anyway, according to the Regulation, all members have to submit a separate ESPD.

Hence the "three pairs of values for the roles" which I described in my initial comment ...

B) Also, I think we need to clarify what information exactly we want to capture with this question/criteria:
i. the bidder (consortium/group/contractor) and/or
ii. role and/or
iii. need for separate ESPD by the third party and/or
iv. rely upon or not

**Comment by ec-mcs** [comment]
Yes, it would be better to discuss this verbally.

on 2 Union/Group of EOs: I would see as well that there is a leader in charge for the communication and the other group members are signing the contract as well. They are not (but often they are as well) entities they rely on or entities the leader does not rely on.

We need to discuss how to tackle this indeed...

**Comment by mfontsan** [comment]
In principle this is not an issue but needs a further reflexion just in case.

We should check that this rule about the naming is well explained in the documentation. We will discuss how to tackle this during the next eMeeting September 27.

**Comment by JosePRevenga** [comment]
The discussion is about a code list. As codes are totally externalised from the data model, adding new concepts to the current EO role code list would not impact on the existing applications. However, the mapping of the newly added codes with previous versions of the ESPD could cause semantic loss or semantic field mismatching. For this reason, it has been agreed to implement this in v3.0.0.

**Comment by hricolor** [comment]
During the last OUC meeting held on the 9th of July, the discussion started around the possibility of EO being "relied upon entity" or "not relied upon" (subcontractor). 
 
An Economic Operator could be Relied upon entity and Not Relied entity at the same time. Then: 
 
The following logic raised from the discussion: an entity that is relied upon has to provide information about the compliance of the Selection Criteria, while a "not relied upon entity" only has to provide information regarding Exclusion Grounds. Then, it would not be needed to indicate that is a subcontractor as it is fulfilling more information than being a "not relied upon" entity. 
 
Please, feel free to answer the question below to allow a broad sample and opinions to solve the issue: 
“Would you agree to say that if an entity is relied upon, that they do not need to inform that they are a subcontractor at the same time?"

**Comment by hricolor** [comment]
After present this issue in the last OUC of the 1st of October, and discuss with the stakeholders, this is the proposed solution that will be implemented:

The usage of the EORoleType will be kept but including the following changes: 

              Sole Contractor, SC --> Sole Tenderer, ST

              Other Entity Not Relied Upon, OENRON --> Subcontractor

This issue will be implemented within the next ESPD-EDM 3.0.0.

**Comment by psotofer** [comment]
As commented before, this issue was included in the last ESPD-EDM Release v3.0.0. therefore we proceed to close this issue.
In case you need further detail regarding this topic, please open a new issue referencing this one.
