### ISSUE TITLE
Link eCertis and ESPD

### ISSUE THREAD

**Issue by ec-mcs** [OP-TED/ESPD-EDM#251]
The ESPD EDM is complex. What about the idea to link entries from eCertis to the ESPD. 
An example would be legislation. This information is available in ESPD and eCertis. Instead of having a copy in the ESPD, how about that the legislation could be linked to eCertis. If the information does not exist in eCertis than this information can be provided in the ESPD directly.
The general idea is see if we can make the ESPD EDM simpler by linking information to eCertis.

Maybe for Legislation the cbc:id could be used for the eCertis ID.
![Capture](https://user-images.githubusercontent.com/20335285/60433012-0178b180-9c04-11e9-8129-a857d3b86914.PNG)

**Comment by JosePRevenga** [comment]
It is a very good idea, but it must be implemented on v3.0.0. Given the fact that as per today e-Certis is evolving and the ELI model is being proposed to replace the element cac:Legislation, this idea of replacing the whole set of data related to this legislation inside the Criterion with "controlled" identifiers (e.g. the ELI identifier) is even better.

**Comment by SellittoGiampaolo** [comment]
That would be optimal, not only for legislation.
It would be a great thing if one could make an espd request from eCertis, to have a uniform behavior both  crossborder and inside the MS

**Comment by psotofer** [comment]
Greetings,
We are currently studying a more close alignment between ESPD and eCertis and will be updating any further detail in this issue.

**Comment by hricolor** [comment]
Greetings, 
 
As discussed during the Open User Community Meeting of 7th October, here is the relevant information presented yesterday regarding the link between ESPD, ESPD Services and eCertis. 
 
This first image shows the goal and parties implied in this new proposal: 
![2021-11-05 09_40_03-ESPD_OUC_Meetings_20211007_eCertis_Discussion1](https://user-images.githubusercontent.com/60606496/140482852-7729a7c4-ddff-4988-aeb4-3b919de0512b.jpg)

The second picture depicts the transaction between parties involved and the information exchanged:
![2021-11-05 09_40_44-ESPD_OUC_Meetings_20211007_eCertis_Discussion_2](https://user-images.githubusercontent.com/60606496/140482926-d4597b19-ca3d-47e8-9858-3f693b9ff8f3.jpg)

This third image shows how the current eCertis page is displayed: 
![2021-11-05 09_41_16-ESPD_OUC_Meetings_20211007_eCertis_Discussion3](https://user-images.githubusercontent.com/60606496/140482954-b4d47d3c-8c74-449a-97b9-b7c365ad8e03.jpg)

This fourth image shows the new functionality developed by eCertis about non-mandatory/non-applicable criteria:
![2021-11-05 09_41_56-ESPD_OUC_Meetings_20211007_eCertis_Discussion4](https://user-images.githubusercontent.com/60606496/140483076-0b9b11a8-0d57-4f99-a622-14d7d9558abc.jpg)

This fifth picture screenshot shows which data would be provided by eCertis taking the ESPD XML instances as reference:
![2021-11-05 09_42_32-ESPD_OUC_Meetings_20211007_eCertis_Discussion5](https://user-images.githubusercontent.com/60606496/140483115-d491f78f-cb30-46a3-b3b1-49042838e76a.jpg)

And this last image shows the change that ESPD-EDM should include into the schema to be aligned with the proposal: 
![2021-11-05 09_43_08-ESPD_OUC_Meetings_20211007_eCertis_Discussion6](https://user-images.githubusercontent.com/60606496/140483136-92405923-0e18-40f3-a6c7-4beb87a0052a.jpg)

Please check the proposal and do not hesitate to provide any question, insight or improvement to the proposal.

**Comment by dragos-eu** [comment]
Hello,

The integration between ESPD and eCERTIS was completed in ESPD v3.3.0. The ESPD Service implementer will retrieve full information from eCERTIS and display it in the interface as per specific national laws and regulations. ESPD provides a generic placeholder for this sections. The ESPD Service will customize the model so that it will accommodate the mandatory fields.

Please let us know if you would like to have more details from our side.

Kind regards,
The ESPD Team
