### ISSUE TITLE
Alignment of the ESPD validator with eCertis: many errors appearing when validating an ESPD request

### ISSUE THREAD

**Issue by mireiaBM** [OP-TED/ESPD-EDM#253]
After analysing the issues found during the validation of the XMLs for ESPD requests with national criteria, 2 types of errors were identified in the validation tool (https://www.itb.ec.europa.eu/espd/upload):

1. Regarding the multiple errors related to the compulsory use of the UUIDs supplied by e-Certis:

- When does this error appear?: the validator throws this error because it cannot find all national criteria (included in the path \cac:TenderingCriterion\cac:SubTenderingCriterion) in e-Certis.

- Why?: we have found that the problem is in the validation tool: 
The validator should not validate whether the national criteria exists in e-Certis or not. However, because of a bug in the validator tool, it is checking, not only if the exclusion and selection criterion exist in e-Certis, but also if the national criteria exists. 

- This bug will be fixed in the version 2.1.1 of the validator tool.

2. On the other hand, the validation error displaying the message "The current qualification application request has '1' exclusion criterion missing " is caused due to the fact that CRITERION.EXCLUSION.NATIONAL.OTHER does not exist in the XMLs.

**Comment by mfontsan** [comment]
According to the documentation (see https://espd-edm.github.io/xml_guide.html#v-9-purely-national-criteria), it is possible to add individual national criteria to the “CRITERION.EXCLUSION.NATIONAL.OTHER”. However, the validator tool throws multiple errors when this happen; as it does not take into account that perpahs, there are national criteria.

The validator tool should be updated in order to take it into account.

**Comment by JosePRevenga** [comment]
The aforementioned bug in the validator tool has been fixed in v2.1.1.

**Comment by rantati7** [comment]
**Further question on ESPD validator** ( https://www.itb.ec.europa.eu/espd/upload): when testing 2.1.1 self contained ESPD requests we get errors if ESPD request does not have all the exclusion grounds selected. 

However it is my understanding that there are two types of exclusion grounds: 1. mandatory and 2. voluntary. Voluntary exclusion grounds have to be selected by the CA when drawing up self contained ESPD and only mandatory exclusion grounds have to be used all the time. **Is there a bug in the validator?**

The file I tested it attached.

[67baf9af-59db-4a75-8673-74fb0b02ac82 (1).zip](https://github.com/ESPD/ESPD-EDM/files/5224303/67baf9af-59db-4a75-8673-74fb0b02ac82.1.zip)

The error message I receive from the validator is:

"The current qualification application request has '15' exclusion criterion missing. 
Test:count($ElementUUID_Exclusion) <= count($current_Exclusion)"

**Comment by ec-mcs** [comment]
Indeed. We will check it.

**Comment by mfontsan** [comment]
Hi @rantati7 ,

Currently, the tool is validating that all exclusions grounds are in the XML (24 Exclusion grounds), without taking into account whether they are mandatory or voluntary.  

We will check it and update the tool for the next release.

**Comment by rantati7** [comment]
Thank you!

**Comment by hricolor** [comment]
After present this issue in the last OUC of the 1st of October, and discuss with the stakeholders, this is the proposed solution that will be implemented: 

Update the validator tool to make mandatory just the following Exclusion Grounds: Part III, A – Criminal convictions, and Part III, B – Payment of taxes. 

This issue will be implemented within the next ESPD-EDM 3.0.0.

**Comment by psotofer** [comment]
As commented before, this issue was included in the last ESPD-EDM Release v3.0.0. therefore we proceed to close this issue.
In case you need further detail regarding this topic, please open a new issue referencing this one.
