### ISSUE TITLE
Where do you find language specific Criterion descriptions?

### ISSUE THREAD

**Issue by BoSejer** [OP-TED/ESPD-EDM#255]
Hello
I am in the process of implementing an ESPD service.

I saw that the implementation that was on EU's website the exported XML used English for description fields in criteria inside of the XML document. Whereas on the actual UI a text in the selected language was shown, my question is how can I from a UUID get the display text for the different supported languages?

I have been looking through all the material on this project, on eCertis, and links on EU's website and I have not been able to find any way of coming from a UUID to a language specific description text.

**Comment by JosePRevenga** [comment]
Hello BoSejer,

This question is related to the ESPD Service and not to the ESPD-EDM and therefore it should be posted in the [ESPD Service](https://github.com/ESPD/ESPD-Service/issues) repository.

However, I think you will find useful the following [section ](http://espd.github.io/ESPD-Service/docs/html/espd.html#internationalization-i18n)of the ESPD Service documentation, as it addresses precisely internationalisation. Additionally, you could also check this [web page](https://ec.europa.eu/growth/single-market/public-procurement/digital/espd_en), where you may find some more useful information and the list of the services implemented in different Member States.
