### ISSUE TITLE
How do you get added to the official ESPD provider list?

### ISSUE THREAD

**Issue by BoSejer** [OP-TED/ESPD-EDM#256]
Hello again

I have been told that questions about the ESPD should be directed here.

I was wondering, as the title states, how to get added to the official list?
I have been informed by EU that questions about ESPD should be asked in this forum.

I am also interested in hearing where to validate the implementation of the ESPD-EDM to ensure that the rules are followed?
I have found https://www.itb.ec.europa.eu/espd/upload, but I do not know if this is the correct place to validate.

Is there a test bed where you can use the ESPD documents, as they are used in real life?

Thank you
Best regards
Bo

**Comment by ec-mcs** [comment]
Hi Bo,

The link is correct but the testbed seems to be not reachable. This is how we validate ESPD services. I informed the testbed team.
We will have our next ESPD stakeholder eMeeting end of November. The best is that you write to OPESPD@publications.europa.eu to be put on the mailing list.

Best MC

**Comment by ec-mcs** [comment]
The test bed is again available.
