### ISSUE TITLE
Subcontractors and relied and non-relied-upon entities

### ISSUE THREAD

**Issue by paulakeen** [OP-TED/ESPD-EDM#259]
In ePO we need to distinguish clearly between subcontractors and entities that are relied-upon (or not) (as mentioned in the ESPD EORoleType codelist).

The main reasons are:

1) The concept subcontractor is needed in different phases of the procurement, not only at tendering time (like in ESPD); and
2) We need to understand very well how relied-upon and non-relied-upon entities can be modelled in ePO in order to satisfy the ESPD requirements.

**Comment by ec-mcs** [comment]
We distinguish between entities relied upon and not-relied upon. 

- Relied upon: Entity is needed to fulfill some of the selection criteria (ESPD Part II c)
- Not-relied upon: Entity is a subcontractor (ESPD Part II d)

It can be that an entity can be both - relied upon and not-relied upon.

**Comment by hricolor** [comment]
This issue is a question from the ePO WGM team, which has been resolved successfully by @ec-mcs . At this point, we would like to thank you for your contribution. Therefore, this issue does not affect ESPD development.  Having said this, we proceed to close the issue.
