### ISSUE TITLE
References Criteria (#37, #38 and #39) in the extended version

### ISSUE THREAD

**Issue by AFSOLUZIONI** [OP-TED/ESPD-EDM#267]
hi all,
it seems we have another time a problem discovered in the past.
I'm referring to cardinality of "Reference" QUESTION_SUBGROUP. 
In the mockup (see the figure) it's very clear we need a cardinality 1..n, but in the taxonomy we have just 1 (see taxonomy extract). I think we must modify the taxonomy because it's clear that CA could ask one or more references for each set of lots.
Let me know what do you think about!
Thank you
Francesco
 
![image](https://user-images.githubusercontent.com/44367854/80724261-ef0c2480-8b01-11ea-843f-506eaa4f08a5.png)
Mock up criterion #38 

![image](https://user-images.githubusercontent.com/44367854/80724694-6e015d00-8b02-11ea-9885-43fadd9d9ec5.png)
extract from #38 criterion

**Comment by ec-mcs** [comment]
Indeed. It must be possible for a CA to ask for references to different lots. So it is 1..n

**Comment by AFSOLUZIONI** [comment]
Thank you Marc,
I'll change national taxonomy waiting (in a future rev) the changes in the european one.
Francesco

**Comment by hricolor** [comment]
Hi both, 

First of all, thanks @ec-mcs for your contribution. 
Yesterday we were working on it to provide an answer to the arose question. Indeed, as MC says, the Regulation endorses the possibility to ask for more than one reference. Therefore, the cardinality for "Reference" REQUIEREMENT_SUBGROUP should be 1.n. 
Additionally, we will check if this rationale would apply to other criteria to harmonise them (if any).

Thanks, 
Héctor.

**Comment by hricolor** [comment]
After the presentation in the OUC meeting (Wednesday 17 of June), this issue will be solved by changing the cardinality of the "QUESTION_SUBGROUP" "Reference" from 1 to 1..n, as it is possible for the CA to ask for more than one reference and also to the EO to provide more than 1 reference. 

This issue will be fixed in the new version of ESPD.
