### ISSUE TITLE
Part IV, Section C (Average annual manpower)

### ISSUE THREAD

**Issue by rantati7** [OP-TED/ESPD-EDM#27]
**Average annual manpower**

"The economic operator's average annual manpower and the number of managerial staff for the last three years were as follows:"

CA must be able to define minimum criteria. 
CA must be able to define the years (preferably the system would generate last 3 years automatically)

NOTE: there are two separate questions here: average annual manpower AND number of managerial stuff - latter being asked already in the previous ESPD question.

**Comment by paulakeen** [comment]
We close this issue, for it's been unified with issue #18

**Comment by paulakeen** [comment]
Please find below a proposal of mock-ups, both for the view of the CA and the view of the EO.

- View of the CA:
![image](https://cloud.githubusercontent.com/assets/16134316/25661939/e39139d0-3012-11e7-9577-635dedddf29c.png)

- View of the EO:
![image](https://cloud.githubusercontent.com/assets/16134316/25661954/f130065c-3012-11e7-93c0-a2527ac6e0a9.png)
