### ISSUE TITLE
Criterion #29 - extended - missing field: number of fiscal years 

### ISSUE THREAD

**Issue by rantati7** [OP-TED/ESPD-EDM#275]
Please omit if already taken into account (I did not find an issue for this)

In general yearly turnover (#29)  the CA should be able to define two things:

1. Number of fiscal years (QUANTITY_INTEGER) with cardinality 1...3 (or can it be 1...5?)
2. Minimum amount (AMOUNT) in currency

Now, requirement #1 above is missing.

**Comment by ec-mcs** [comment]
Indeed we do not have the number of fiscal amount. But it is solved differently. As the minimum amount could vary for the fiscal years (this was discussed in the former stakeholder group), you can add 'rows' which is equal to the number of fiscal years. 
https://espd.github.io/ESPD-EDM/v2.1.1/xml_guide.html#vi-3-2-extended-general-turnover
Do we need to adjust this? Can the amount vary?

**Comment by rantati7** [comment]
Users are confused... they do not know that by adding rows -> one row is for one fiscal year. However if we add static text on each field: "fiscal year 1" "fiscal year 2".... "fiscal year n"= (n =3 or 5??) we can do a workaround.

**Comment by psotofer** [comment]
Greetings, 
Thanks for your comments. We will take them on account and come back to you with a resolution as soon as possible.

Best regards.

**Comment by hricolor** [comment]
After present this issue in the last OUC of the 1st of October, and discuss with the stakeholders, this is the proposed solution that will be implemented: 

The CA could ask for a common threshold for all the fiscal years. See the mockup below: 
![275 1](https://user-images.githubusercontent.com/60606496/96235460-20d35380-0f9b-11eb-8769-19082ba8a375.png)

Also, if needed, the CA can assign a threshold per FY. As it is specified in the following mockup: 

<img width="750" alt="Imagen1" src="https://user-images.githubusercontent.com/60606496/96235618-4eb89800-0f9b-11eb-8c90-41b2bb1bd227.png">

 This issue will be implemented within the next ESPD-EDM 3.0.0.

**Comment by psotofer** [comment]
As commented before, this issue was included in the last ESPD-EDM Release v3.0.0. therefore we proceed to close this issue.
In case you need further detail regarding this topic, please open a new issue referencing this one.
