### ISSUE TITLE
TOOP extension to describe evidence metadata within the ESPD EDM 

### ISSUE THREAD

**Issue by mondorf** [OP-TED/ESPD-EDM#277]
The following issue https://github.com/ESPD/ESPD-EDM/issues/254  already addressed the need to align the ESPD EDM with TOOP requirements. The principle need was to better describe evidence metadata in the ESPD and to convert TOOP Responses into ESPD Responses when an Economic Operator settles references to national data providers, databases and base registers. Several works have been done since the issue 254 was raised and the resulting changes are illustrated in the followin. 

During the last month there was an alignment between TOOP and CCCEV which resulted in new EDMs for both projects based on common grounds that were derived from a set of Core Vocabularies such as CAV, CLV, CAGV and application profiles such as dcat-ap. Dcat-ap played a significant role in the redesign of CCCEV and alignment process since the TOOP architecture is using dcat-ap to define how dataset are published in dataportals and how these datasets can be shared, discovered and re-used in processes like eProcurement qualification.

According to the understanding of TOOP and CCCEV, evidence is a particular occurrence of a dataset requested during a procedure to proof a certain requirement or criterion. CCCEV adopted the most relevant classes and properties from DCAT in order to better describe the class evidence through the generic concept dataset. Thereby the following information entities were used: 
•	Dataset: A conceptual entity that represents the information published.
•	Data Services: A collection of operations that provides access to one or more datasets or data processing functions 
•	Distribution: A physical embodiment of the Dataset in a particular format.
•	Relationship: An association class for attaching additional information to a relationship between DCAT Resources
•	Period of time: An interval of time that is named or defined by its start and end dates
•	Creator: This property refers to the entity primarily responsible for producing the dataset.

The whole list of elements adopted by CCCEV can be found at:  https://github.com/SEMICeu/CCCEV/tree/CV-2.0.0 

TOOP adopted a subset of information entities which are used by the TOOP data model to describe data responses of a data providers (pls. see rim:Slot “DocumentMetadata” and rim:Slot “DataProvider” http://wiki.ds.unipi.gr/display/TOOPSA210CEF/TOOP+Response+Syntax+Mapping ). The TOOP data responses shall be used to adopt references to appropriate evidence in the ESPD.  

Therefore the elements of rim:Slot “DocumentMetadata” and rim:Slot “DataProvider” were mapped to the existing ESPD response specification whenever possible. Elements with no matching ESPD EDM concept have been directly mapped to the underlying UBL syntax. Thus, a TOOP extension to the ESPD EDM has been created to cover all aspects described above. In this respect, all elements described above were mapped to the underlying UBL syntax except the class “dcat:qualifiedRelation” and the dcat:dataset property “modified”. The syntax mapping of the TOOP extension is illustrated here: http://wiki.ds.unipi.gr/display/CCTF/ESPD+Extension . It contains an overview about the new ESPD information entities and a mapping between TOOP syntax and the corresponding UBL path for the ESPD syntax binding. 

Thus, the TOOP extension to describe evidence metadata within the ESPD EDM illustrates how the ESPD EDM evidence class could be enriched to appropriately reflect the TOOP requirements for referencing appropriate datasets according to the new CCCEV 2.0 and its underlying vocabularies.

**Comment by mfontsan** [comment]
Thank you @mondorf . We are currently having a look to your comment and analysing it. We'll come back to you the soonest.

**Comment by hricolor** [comment]
After present and discuss the issue in the OUC of 29th October, it was agreed that the different inputs provided by the TOOP will be documented in the ESPD Online documentation. 

Moreover, since the cac:Evidence is linked to cac:Signature, ESPD will include more information on the evidence and it will be possible that the national databases can sign the content they provide. 

This solution will be implemented in the next ESPD 3.0.0

**Comment by psotofer** [comment]
As commented before, this issue was included in the last ESPD-EDM Release v3.0.0. therefore we proceed to close this issue.
In case you need further detail regarding this topic, please open a new issue referencing this one.

**Comment by hricolor** [comment]
Hi all, to clarify, this information is documented within the section "[1.4 UBL-2.3 and TOOP Requirements](https://espd.github.io/ESPD-EDM/v3.0.0/xml_technical_handbook.html#1-4-ubl-2-3-and-toop-requirements )". Please check the documentation and provide any additional comment on this.

**Comment by psotofer** [comment]
Greetings, 
after providing detail regarding the documentation and since we did not receive additional comments we proceed to close this issue. 
In case you need further detail regarding this topic, please open a new issue referencing this one.
