### ISSUE TITLE
Specific yearly turnover and Specific average turnover

### ISSUE THREAD

**Issue by AJDAKOST** [OP-TED/ESPD-EDM#280]
What is meant by Business Domain Description?

**Comment by ec-mcs** [comment]
The area where the EO is working. The idea behind this was, that if the CA receives dozens of ESPD for a single bid, this business domain description allows them to understand the business domain they work in.

**Comment by hricolor** [comment]
Many thanks for your contribution @ec-mcs, 

Since the doubt is resolved, we proceed to close the issue.
