### ISSUE TITLE
Part II: »Information concerning the economic operator / A: Information about the economic operator«

### ISSUE THREAD

**Issue by AJDAKOST** [OP-TED/ESPD-EDM#282]
In Part II: »Information concerning the economic operator / A: Information about the economic operator«, we find data on number of employees and annual turnover unnecessary, as they are not with accordance with the efficiency and reduction of burdens for companies (especially SMEs), since they have to enter the same data here in Part II and then again in Part IV (if the data are required by the CA).

**Comment by ec-mcs** [comment]
As you indicate, the selection criteria have to be seen as a menu card, that the CA can request from the EO to answer. Often only 3 or 4 criteria are selected. It is not a must that all selection criteria should be answered by EOs. This would be actually a very bad practice. Unfortunately, we do not have a statistic on which items are selected by CAs for specific procedures.
Having said this, Part II and Part IV to not overlap in this regard in my opinion. Only Part IV asks about the turnover and number of employees.

**Comment by hricolor** [comment]
Many thanks for your contribution @ec-mcs, 

Since the doubt is resolved, we proceed to close the issue.
