### ISSUE TITLE
ESPD request (CA side) 

### ISSUE THREAD

**Issue by AJDAKOST** [OP-TED/ESPD-EDM#283]
On the ESPD request (CA side) we did not find anywhere the data about reserved contracts. Is there any particular reason why they are not included? CA may reserve the right to participate in public procurement procedures to sheltered workshops and economic operators whose main aim is the social and professional integration of disabled or disadvantaged persons or may provide for such contracts to be performed in the context of sheltered employment programmes, provided that at least 30 % of the employees of those workshops, economic operators or programmes are disabled or disadvantaged workers. Reserved contracts are included only on the ESPD response (EO side).

**Comment by ec-mcs** [comment]
The ESPD needs to be read especially for this indicator together with the notice. Therefore, the ESPD response starts for this point with 'If applicable.....". Indeed this is not the best solution.
With the new version of the ESPD, we will 'link' it with eForms. IF eForms, the CA marked that this is for a reserved contract THEN show this question to the EO in Part II, ELSE don't show it at all.
What do you think?

**Comment by hricolor** [comment]
Many thanks for your contribution @ec-mcs, 

Since the doubt is resolved, we proceed to close the issue.

**Comment by AJDAKOST** [comment]
If we want to reduce the burden of tender documentation and double work for CA and EO, we still think the data refering to reserved contracts on the CA's side are important, as the EO may miss ticking it. We find the data is on the EO's side redundant, as the decision on the implementation of the reserved contracts being held by CA.
