### ISSUE TITLE
Part IV: »Selection criteria, B: Economic and financial standing / Set up of economic operator« 

### ISSUE THREAD

**Issue by AJDAKOST** [OP-TED/ESPD-EDM#284]
On the ESPD request (CA side) in Part IV: »Selection criteria, B: Economic and financial standing / Set up of economic operator« is written In case the information concerning turnover (general or specific) is not available for the entire period required, please state the date on which the economic operator was set up or started trading. What is the purpose of this sentence on side of CA? CA cannot know which EO will participate in public procurement and when the EO was set up or started trading.

**Comment by ec-mcs** [comment]
These questions need to be answered by the EO and evaluated by the CA. In the ESPD request the CA needs to indicate only that these information must be given by the EO.

**Comment by hricolor** [comment]
Many thanks for your contribution @ec-mcs.  

Since the doubt is resolved, we proceed to close the issue.
