### ISSUE TITLE
ESPD 2.1.1. Schema & other discrepancies

### ISSUE THREAD

**Issue by rantati7** [OP-TED/ESPD-EDM#285]
Sorry for not reporting these isseus as they should be reported. I received some comments / observations from our Chief Architect regarding ESPD schema 2.1.1.

-----

 1.	For QualificationApplicationResponse the FinancialCapability and Employee Count are both in criteria and under EconomicOperatorParty. Documentation related to these is inconsistent. 

2.	EcomonicOperatorGroupName are both under QualificationApplicationResponse directly and under criteria CRITERION.OTHER.EO_DATA.TOGETHER_WITH_OTHERS. The documentation is inconsisten about whouw it should be used.

3.	BusinessClassificationScheme has only Description described as required in documentation, however the schema requires also ID and ClassificationCategory.

4.	EconomicOperatorParty.Party.IndistryClassificationCode is required in validator but it is not shown in documenation examples. 

5.	The size of the company ('/cac:EconomicOperatorParty/cac:Party/cbc:IndustryClassificationCode') is mandatory.

Test:(cbc:IndustryClassificationCode)

6.	In documentation PowerOfAttrney Country Identifier example has wrong listVersionId. It is ‘2.1.1’, should be ‘1.0’

7.	EvidenceSupplied examples are missing mandatory schemeAgencyID

**Comment by hricolor** [comment]
Dear, 

After present this issue in the Open User Community meeting of 29th October, we will take into account all these inputs for the improvement of the online documentation for the new version of the ESPD 3.0.0.

**Comment by psotofer** [comment]
As commented before, this issue was taken on account for the last ESPD-EDM Release v3.0.0. therefore we proceed to close this issue.
In case you need further detail regarding this topic, please open a new issue referencing this one.

**Comment by hricolor** [comment]
> - For QualificationApplicationResponse the FinancialCapability and Employee Count are both in criteria and under EconomicOperatorParty. Documentation related to these is inconsistent.

In the current documentation, it is referenced under the ESPD response document referring to the [Economic Operator](https://espd.github.io/ESPD-EDM/v3.0.0/xml_technical_handbook.html#6-6-economic-operator) (EconomicOperatorParty).  

> - EcomonicOperatorGroupName are both under QualificationApplicationResponse directly and under criteria CRITERION.OTHER.EO_DATA.TOGETHER_WITH_OTHERS. The documentation is inconsisten about whouw it should be used.

The information regarding the EconomicOperatoGroupName is included within the QualificationApplicationResponse, specifically through the section [“Root elements”](https://espd.github.io/ESPD-EDM/v3.0.0/xml_technical_handbook.html#6-4-root-elements)  where it is explained how and where it should be used.  

> - BusinessClassificationScheme has only Description described as required in documentation, however the schema requires also ID and ClassificationCategory.

On this point, this will need to be revisited and addressed for the next release.  

> - EconomicOperatorParty.Party.IndistryClassificationCode is required in validator but it is not shown in documentation examples.

It is shown in the expected elements defined in section [6.6 Economic Operator](https://espd.github.io/ESPD-EDM/v3.0.0/xml_technical_handbook.html#6-6-economic-operator). 

> - The size of the company ('/cac:EconomicOperatorParty/cac:Party/cbc:IndustryClassificationCode') is mandatory.

It is shown in the expected elements defined in section [6.6 Economic Operator](https://espd.github.io/ESPD-EDM/v3.0.0/xml_technical_handbook.html#6-6-economic-operator).    

> - In documentation PowerOfAttrney Country Identifier example has wrong listVersionId. It is ‘2.1.1’, should be ‘1.0’

This has been updated according to the changes agreed with all interested parties. The current version 3.0.0 is using the EU Vocabularies list in its version “20201216-0”. See cac:PowerOfAttorney example in the documentation (specifically section [6.6.1 Economic operator representatives](https://espd.github.io/ESPD-EDM/v3.0.0/xml_technical_handbook.html#6-6-economic-operator))

> - EvidenceSupplied examples are missing mandatory schemeAgencyID

On this point, the examples are missing the schemeAgencyID and will need to be revisited and addressed for the next release.

**Comment by psotofer** [comment]
Greetings, 
after providing detail regarding the documentation and since we did not receive additional comments we proceed to close this issue. 
In case you need further detail regarding this topic, please open a new issue referencing this one.
