### ISSUE TITLE
In general

### ISSUE THREAD

**Issue by AJDAKOST** [OP-TED/ESPD-EDM#289]
In general

We have noticed, when CA or EO insert the data in the field, the meaning of the field disappeared. It is not clear on both sides, especially on the EO`s side, what were the CA`s requirements.

An example is attached.
[example-works.docx](https://github.com/ESPD/ESPD-EDM/files/5487812/example-works.docx)

**Comment by hricolor** [comment]
Hello

This question is related to the ESPD Service and not to the ESPD-EDM and therefore it should be posted in the [ESPD Service](https://github.com/ESPD/ESPD-Service/issues) repository.

However, here you have the link to the [ESPD Service Documentation](https://github.com/ESPD/ESPD-Service#documentation) where you can find useful information to solve future issues or questions related to the Service. 

Thank you.
