### ISSUE TITLE
Trade and commercial registers

### ISSUE THREAD

**Issue by AJDAKOST** [OP-TED/ESPD-EDM#290]
Here we still think, that it does not make sense that the CA defines the name of the register nor URL for it. CA cannot require (and he also don`t know) the EO to belong to certain national register as all registers in EU are equally good.

**Comment by hricolor** [comment]
Hi, 

For more insights on this topic, see the issue #273 where it is posted the solution agreed during the last OUC 29th October. 

Thank you
