### ISSUE TITLE
ESPD request (CA side), referring to #283

### ISSUE THREAD

**Issue by AJDAKOST** [OP-TED/ESPD-EDM#291]
If we want to reduce the burden of tender documentation and double work for CA and EO, we still think the data refering to reserved contracts on the CA's side are important, as the EO may miss ticking it. We find the data is on the EO's side redundant, as the decision on the implementation of the reserved contracts being held by CA.

**Comment by hricolor** [comment]
Hi, many thanks for your inputs and active participation. 

In the new approach, new version 3..0.0 of the ESPD, it will be linked to eForms. Then, this information will be asked in eForms, not needing it in the ESPD Request nor ESPD Response. And, for the EO side, this information only would appear if the CA declares so in the CN. 

With this new approach, by reducing the replication of information by the CA, it reduces the administrative burden while creating ESPD.
