### ISSUE TITLE
Code List BidType

### ISSUE THREAD

**Issue by hricolor** [OP-TED/ESPD-EDM#294]
Hi All, 

As presented in the OUC community of 3rd of February, the code list **BidType** will be removed for the ESPD v3.0.0. 

If you have any additional comment, please do not hesitate to comment on this issue. 

Thanks.

**Comment by psotofer** [comment]
As commented before, this issue was included in the last ESPD-EDM Release v3.0.0. therefore we proceed to close this issue.
In case you need further detail regarding this topic, please open a new issue referencing this one.
