### ISSUE TITLE
Code List access-right

### ISSUE THREAD

**Issue by hricolor** [OP-TED/ESPD-EDM#295]
As presented in the OUC community of 3rd of February, the current **ConfidentialityLevel** code list will be updated for next ESPD release 3.0.0. 

The main changes will be: 

- Change name: from current CondifentialityLevel to access-right (EU vocabularies)
- Version 3.0.0 will include the code list maintained by ESPD as it is per today
- Next 3.1.0 will include the EU Vocabulary “access-right” that will include the code ‘CONFIDENTIAL’
- Mid-2021 the code list will be maintained by EU Vocabularies. 

If you have any additional comment, please do not hesitate to comment on this issue. 

Thanks.

**Comment by psotofer** [comment]
As commented before, this issue was included in the last ESPD-EDM Release v3.0.0. therefore we proceed to close this issue.
In case you need further detail regarding this topic, please open a new issue referencing this one.

**Comment by hricolor** [comment]
As agreed, for ESPD 3.0.0 a code list was provided together with the generic code aligned with EU vocabularies 'access-right' standards. See the [cl folder](https://github.com/ESPD/ESPD-EDM/tree/3.0.0/docs/src/main/asciidoc/dist/cl) in ESPD v3.0.0

The next version of the ESPD will use the already published code list from EU Vocabularies that includes the ESPD context for the two codes used in ESPD. 

The latest version of the code list can be found in the following [URL](https://op.europa.eu/en/web/eu-vocabularies/dataset/-/resource?uri=http://publications.europa.eu/resource/dataset/access-right).
