### ISSUE TITLE
Code list Country

### ISSUE THREAD

**Issue by hricolor** [OP-TED/ESPD-EDM#296]
As presented in the OUC community of 3rd of February, the current **ContryCodeIdentifier** will be updated for next ESPD release 3.0.0. 

The main changes will be: 

-	Change name: from CountryCodeIdentifier to country (EU vocabularies)
-	This code list will be maintained by EU Vocabularies
-	Code pattern changes to 3-character to be aligned with eForms. 

If you have any additional comment, please do not hesitate to comment on this issue. 

Thanks.

**Comment by psotofer** [comment]
As commented before, this issue was included in the last ESPD-EDM Release v3.0.0. therefore we proceed to close this issue.
In case you need further detail regarding this topic, please open a new issue referencing this one.

**Comment by hricolor** [comment]
As agreed with the OUC and commented before, the country code list was updated in ESPD 3.0.0 to the one in EU Vocabularies '[country](https://op.europa.eu/en/web/eu-vocabularies/dataset/-/resource?uri=http://publications.europa.eu/resource/dataset/country)'. 

The version used for the latest version of the ESPD 3.0.0 was [20201216-0](https://op.europa.eu/web/eu-vocabularies/dataset/-/resource?uri=http://publications.europa.eu/resource/dataset/country&version=20201216-0). 

It is going to be updated to the lastest one, which is: [20210616-0](https://op.europa.eu/en/web/eu-vocabularies/dataset/-/resource?uri=http://publications.europa.eu/resource/dataset/country). 

However, the latest version of the code list can be consulted in the following [url](https://op.europa.eu/en/web/eu-vocabularies/dataset/-/resource?uri=http://publications.europa.eu/resource/dataset/country).
