### ISSUE TITLE
Code list Currency

### ISSUE THREAD

**Issue by hricolor** [OP-TED/ESPD-EDM#297]
As presented in the OUC community of 3rd of February, the current **CurrencyCode** code list will be updated for next ESPD release 3.0.0.

The main changes will be: 

-	Change name: from CurrencyCode to currency (EU Vocabularies)
-	This code list will be maintained by EU Vocabularies
-	This fact eases the alignment between ESPD and eForms. 

If you have any additional comment, please do not hesitate to comment on this issue. 

Thanks.

**Comment by psotofer** [comment]
As commented before, this issue was included in the last ESPD-EDM Release v3.0.0. therefore we proceed to close this issue.
In case you need further detail regarding this topic, please open a new issue referencing this one.

**Comment by hricolor** [comment]
As agreed with the OUC and commented before, in version 3.0.0 of the ESPD the code list was updated to the 'currency' code from EU Vocabularies. It was used the code list version: [20201216-0](https://op.europa.eu/web/eu-vocabularies/dataset/-/resource?uri=http://publications.europa.eu/resource/dataset/currency&version=20201216-0). 

For next release, the ESPD will keep the usage of ['currency'](https://op.europa.eu/en/web/eu-vocabularies/dataset/-/resource?uri=http://publications.europa.eu/resource/dataset/currency ) from EU Vocabularies. 

The actual version of the code list is "20210317-0". And the latest version of the code list can be found in [currency](https://op.europa.eu/en/web/eu-vocabularies/dataset/-/resource?uri=http://publications.europa.eu/resource/dataset/currency)
