### ISSUE TITLE
Code list DocRefContentType

### ISSUE THREAD

**Issue by hricolor** [OP-TED/ESPD-EDM#298]
As presented in the OUC community of 3rd of February, the current **CurrencyCode** code list will be updated for next ESPD release 3.0.0.

The main changes will be: 
-	Change Name: from DocRefContentType to docref-content-type to allow its publication in EU Vocabularies
-	In March it will be provided with the translation in English, and for mid-21 it will be included in all languages and published in EU Vocabularies
-	The code list will be maintained by EU Vocabularies by mid-21

If you have any additional comment, please do not hesitate to comment on this issue. 

Thanks.

**Comment by psotofer** [comment]
As commented before, this issue was included in the last ESPD-EDM Release v3.0.0. therefore we proceed to close this issue.
In case you need further detail regarding this topic, please open a new issue referencing this one.
