### ISSUE TITLE
Code list eo-role-type

### ISSUE THREAD

**Issue by hricolor** [OP-TED/ESPD-EDM#299]
As presented in the OUC community of 3rd of February, the current **EORoleType** code list will be updated for next ESPD release 3.0.0.

These changes are related to issue #250 where part of the changes were already discussed
.
The main changes will be: 
-	Change name: from EORoleType to eo-role-type (EU Vocabularies format)
-	Change in codes: 
              o	OENRON (Other entity (not relied upon)) to _subcont_ (Subcontractor)
              o	SC(Sole contractor) to _sole-tenderer_ (Sole tenderer)
              o	LE(Lead Entity) to _group-lead_ (Group leader)
              o	GM to _group-mem_ (Group member)
-	Changes in codes other than the ones agreed in issue #250 are related to eForms alignment and the usage of the same codes. These codes are contained in organisation-role and organisation-subrole from EU Vocabularies. 
-	For version 3.0.0 the code list will be maintained by ESPD. 

If you have any additional comment, please do not hesitate to comment on this issue. 

Thanks.

**Comment by psotofer** [comment]
As commented before, this issue was included in the last ESPD-EDM Release v3.0.0. therefore we proceed to close this issue.
In case you need further detail regarding this topic, please open a new issue referencing this one.

**Comment by hricolor** [comment]
The code list is already published in EU Vocabularies and in the next release will be used directly from the source. 
[eo-role-type](https://op.europa.eu/web/eu-vocabularies/dataset/-/resource?uri=http://publications.europa.eu/resource/dataset/eo-role-type)

**Comment by eprocurementontology** [comment]
The actual version at the time of this comment is [the version of 2021-06-16](https://op.europa.eu/en/web/eu-vocabularies/dataset/-/resource?uri=http://publications.europa.eu/resource/dataset/eo-role-type&version=2021-06-16)
The latest version of the code list at any time can be found at [eo-role-type](https://op.europa.eu/en/web/eu-vocabularies/dataset/-/resource?uri=http://publications.europa.eu/resource/dataset/eo-role-type) at the time of writing the latest version is the version of 2021-06-16
