### ISSUE TITLE
Add explanation what will happen if EO selects YES / NO

### ISSUE THREAD

**Issue by rantati7** [OP-TED/ESPD-EDM#3]
EOs do not understand what happens if they answer YES or NO to questions. There would need to be a tool tip or something similar warning "you will be excluded" or "you may be excluded if you answer this way".

**Comment by rantati7** [comment]
This applies to all parts not just Part III (exclusion grounds) but also and particularly in part IV (selection critreria)

**Comment by ec-mcs** [comment]
As this is related to the ESPD service I close it here. You will find it here
https://github.com/ESPD/ESPD-Service/issues/11
