### ISSUE TITLE
Part IV, Section C (For supply contracts)

### ISSUE THREAD

**Issue by rantati7** [OP-TED/ESPD-EDM#30]
**For supply contracts: samples, descriptions or photographs without certification of authenticity** 

CA must be able to define the required samples etc: what samples it requires, how are those going to be used and where & when the samples will need to be delivered.

It would be good if this question is only shown when supply contracts in question.

**Comment by ec-mcs** [comment]
We got this requirement as well from HU.

**Comment by paulakeen** [comment]
We close this issue, for it's been unified with issues #16 and #18

**Comment by paulakeen** [comment]
The CA must be able to add multiple requirements.

For each requirement, the EO will be required to answer YES or NO and, when the answer is YES.

- View of the CA:
![image](https://cloud.githubusercontent.com/assets/16134316/25738745/1774d3b6-317f-11e7-89ef-67368dfafa67.png)

- View of the EO:
![image](https://cloud.githubusercontent.com/assets/16134316/25738748/1ed7d4b4-317f-11e7-89ce-97b89a533871.png)

**Comment by rantati7** [comment]
Just a note: for supplies the samples are hardly ever available online and would need to be delivered for inspection to CA or sometimes to another authority.

Sent from my iPad

On 5 May 2017, at 11.39, paulakeen <notifications@github.com<mailto:notifications@github.com>> wrote:


The CA must be able to add multiple requirements.

For each requirement, the EO will be required to answer YES or NO and, when the answer is YES.

  *   View of the CA:
[image]<https://cloud.githubusercontent.com/assets/16134316/25738745/1774d3b6-317f-11e7-89ef-67368dfafa67.png>

  *   View of the EO:
[image]<https://cloud.githubusercontent.com/assets/16134316/25738748/1ed7d4b4-317f-11e7-89ce-97b89a533871.png>
