### ISSUE TITLE
Code list EvaluationMethodType

### ISSUE THREAD

**Issue by hricolor** [OP-TED/ESPD-EDM#300]
As presented in the OUC community of 3rd of February, the current **EvaluationMethodType** code list will be removed.

As agreed in the OUC meeting from the [19th May 2020](https://github.com/ESPD/ESPD-EDM/blob/wgm-reports/ESPD_Minutes_MS_Meetings_20200519_v1.0.pdf), the ESPD 3.0.0 will not include weightings, therefore the code list is no longer required. 

If you have any additional comment, please do not hesitate to comment on this issue. 

Thanks.

**Comment by psotofer** [comment]
As commented before, this issue was included in the last ESPD-EDM Release v3.0.0. therefore we proceed to close this issue.
In case you need further detail regarding this topic, please open a new issue referencing this one.
