### ISSUE TITLE
Code List LanguageCodeEU (language)

### ISSUE THREAD

**Issue by hricolor** [OP-TED/ESPD-EDM#301]
As presented in the OUC community of 3rd of February, the current **LanguageCodeEU** code list will be updated for next ESPD release 3.0.0.

The main changes will be: 
-	Change name: from LanguageCodeEU to language (Eu Vocabularies)
-	This code list will be (is maintained) by EU Vocabularies
-	The code pattern will change from 2-character code to a 3-character code easing the alignment with eForms. 
-	The CL will include the same use_context as eForms, containing 55 languages. 

If you have any additional comment, please do not hesitate to comment on this issue. 

Thanks.

**Comment by psotofer** [comment]
As commented before, this issue was included in the last ESPD-EDM Release v3.0.0. therefore we proceed to close this issue.
In case you need further detail regarding this topic, please open a new issue referencing this one.

**Comment by hricolor** [comment]
As agreed during the development of ESPD v3.0.0, the code list to be used was updated to 'language' from EU Vocabularies.

The version of the code list used in ESPD v3.0.0 is [20201216-0](https://op.europa.eu/web/eu-vocabularies/dataset/-/resource?uri=http://publications.europa.eu/resource/dataset/language&version=20201216-0).

The current version of the code list in EU Vocabularies is [20210616-0](https://op.europa.eu/o/opportal-service/euvoc-download-handler?cellarURI=http%3A%2F%2Fpublications.europa.eu%2Fresource%2Fcellar%2Fa6c51d84-ce0b-11eb-ac72-01aa75ed71a1.0001.01%2FDOC_1&fileName=Language.gc).

Additionally, the latest version of the code list can be consulted [here](https://op.europa.eu/en/web/eu-vocabularies/dataset/-/resource?uri=http://publications.europa.eu/resource/dataset/language).
