### ISSUE TITLE
Code list LegislationType

### ISSUE THREAD

**Issue by hricolor** [OP-TED/ESPD-EDM#302]
As presented in the OUC community of 3rd of February, the current **LegislationType** code will be removed.

This code list is not used for the current version 2.1.1, and it is documented in the excel for ESPD 2.1.1 code list. 

If you have any additional comment, please do not hesitate to comment on this issue. 

Thanks.

**Comment by psotofer** [comment]
As commented before, this issue was included in the last ESPD-EDM Release v3.0.0. therefore we proceed to close this issue.
In case you need further detail regarding this topic, please open a new issue referencing this one.
