### ISSUE TITLE
Code list economic-operator-size

### ISSUE THREAD

**Issue by hricolor** [OP-TED/ESPD-EDM#303]
As presented in the OUC community of 3rd of February, the current EOIndustryClassificationCode code list will be updated for next ESPD release 3.0.0.

The main changes will be: 

-	Change name: from EOIndustryClassificationCode to economic-operator-size (EU Vocabularies)
-	This code list is maintained by EU Vocabularies
-	This update will ease the alignment with eForms. 

If you have any additional comment, please do not hesitate to comment on this issue. 

Thanks.

**Comment by psotofer** [comment]
As commented before, this issue was included in the last ESPD-EDM Release v3.0.0. therefore we proceed to close this issue.
In case you need further detail regarding this topic, please open a new issue referencing this one.

**Comment by hricolor** [comment]
As agreed during the development of ESPD v3.0.0, the code list to be used was updated to '[economic-operator-size](https://op.europa.eu/en/web/eu-vocabularies/dataset/-/resource?uri=http://publications.europa.eu/resource/dataset/economic-operator-size)' from EU Vocabularies. 

The veresion of the code list used in ESPD v3.0.0 is [20200923-0](https://op.europa.eu/web/eu-vocabularies/dataset/-/resource?uri=http://publications.europa.eu/resource/dataset/economic-operator-size&version=20200923-0). 

The current version of the code list in EU Vocabularies is: [20210317-0](https://op.europa.eu/en/web/eu-vocabularies/dataset/-/resource?uri=http://publications.europa.eu/resource/dataset/economic-operator-size). 

Additionally, the latest version of the code list can be consulted [here](https://op.europa.eu/en/web/eu-vocabularies/dataset/-/resource?uri=http://publications.europa.eu/resource/dataset/economic-operator-size).
