### ISSUE TITLE
Code list ServiceProjectSubType

### ISSUE THREAD

**Issue by hricolor** [OP-TED/ESPD-EDM#304]
As presented in the OUC community of 3rd of February, the current **ServiceProjectSubType** code will be removed.

The information related to the object of the contract will be defined by eForms, this information is no longer required.

If you have any additional comment, please do not hesitate to comment on this issue. 

Thanks.

**Comment by psotofer** [comment]
This issue was included in the last ESPD-EDM Release v3.0.0. therefore we proceed to close this issue.
In case you need further detail regarding this topic, please open a new issue referencing this one.
