### ISSUE TITLE
Code list CPVCodes

### ISSUE THREAD

**Issue by hricolor** [OP-TED/ESPD-EDM#306]
As presented in the OUC community of 3rd of February, the current **CPVCodes** code list is proposed to be removed.  

On one hand, the CPV is information related to the procedure and it will be provided by eForms at lot level it is no longer needed in the ESPD. However, as it was shown during the meeting, it is also used in the ESPD response to specify the activity of the Economic Operator for relied upon and subcontract. The following image shows it:  

 
![image](https://user-images.githubusercontent.com/60606496/106920520-775fcb80-670b-11eb-985c-f2944320af4b.png)

Then, is it used so far for this purpose in your different implementations? Or it can be removed? 

If you have any additional comment, please do not hesitate to comment on this issue. 

Thanks.

**Comment by hricolor** [comment]
@ec-mcs any input on this issue?

**Comment by ec-mcs** [comment]
@hricolor We should have two different issues for the CPV. For the selection criteria we decided this week that they should be removed (and close this issue) as they are now linked to eForms and not necessary anymore. We should create a new one asking, if the CPV was used in Part II to define the activity of the supplier. We should say that we would like to remove them if not needed anymore and agree in the next OUC to leave them or to remove them.

**Comment by psotofer** [comment]
The CPV was removed in the ESPD-EDM Release v3.0.0. Therefore we close this issue.
In case you need further detail regarding this topic, please request the reopen this issue.
