### ISSUE TITLE
New Code list 'occupation'

### ISSUE THREAD

**Issue by hricolor** [OP-TED/ESPD-EDM#307]
As presented in the OUC community of 3rd of February, a new code list **e.g. RegisterType** should be created to address issue #273. 

During the meeting, it was discussed the possibility to use the Regulated Professions database classification (https://ec.europa.eu/growth/tools-databases/regprof/index.cfm?action=regprofs). However, it did not cover all the professions and needs that MS have to solve issue 273. 

Then, It was also proposed the use of ISCO (https://www.ilo.org/public/english/bureau/stat/isco/docs/publication08.pdf), which is also used in different Member States such as Finland or Norway use it in other fields. (e.g. statistical agencies). 

The OUC shown willingness into the usage of this ISCO classification for the creation of the code list. Therefore, we would like to ask you about the usage of this classification in different countries and if would fit your purposes. 

Please feel free to participate and elaborate. 

Thanks.

**Comment by hricolor** [comment]
Hi all, 

Additional information on this issue: 

* The proposed name to be used is _Occupation_. 
* The Commission has the ESCO (https://ec.europa.eu/esco/portal/home), which is also based on ISCO. This is the proposed source for the creation of the code list, which is narrowly aligned with European Institution's purposes and would impact positively in the Once-Only Principle. 

@ec-mcs is it clear enough? Feel free to introduce any information you consider.

**Comment by psotofer** [comment]
This issue was included in the last ESPD-EDM Release v3.0.0. therefore we proceed to close this issue.
In case you need further detail regarding this topic, please open a new issue referencing this one.

**Comment by hricolor** [comment]
As agreed in the OUC of February 3rd, it was created a new code list called 'occupation' based on [ESCO occupations classification](https://ec.europa.eu/esco/portal/occupation). 

The code list created can be consulted within the [code list xslx](https://github.com/ESPD/ESPD-EDM/blob/master/docs/src/main/asciidoc/dist/cl/xlsx/ESPD-CodeLists-V3.0.0.xlsx). 

It is going to be revisited in order to check the possibility of using the [ESCO API](https://ec.europa.eu/esco/portal/api) to provide and also validate that the codes are properly used in the ESPD. Therefore, we are going to reopen this issue to follow up on this development. Moreover, this issue has been renamed to 'New Code list occupation'.

**Comment by hricolor** [comment]
Good afternoon, 
The codelist is finally going to be maintained by EU Vocabularies. It can be found here: https://op.europa.eu/web/eu-vocabularies/dataset/-/resource?uri=http://publications.europa.eu/resource/dataset/occupation. 

The ESPD-EDM will include the gc generated by EU Vocabularies, maintain the metadata on the repository, and update the validation rules accordingly. 

The new release of the codelist has been updated and uploaded to the specific branch [upadate-codelists](https://github.com/OP-TED/ESPD-EDM/tree/update-codelist/codelists). The update of the codelist will be part of a future release. 

Best Regards, 
The ESPD Team.
