### ISSUE TITLE
Code list CriteriaTaxonomy (CL name TBD)

### ISSUE THREAD

**Issue by hricolor** [OP-TED/ESPD-EDM#309]
As presented in the OUC community of 3rd of February, the current **CriteriaTaxonomy** code list will be updated for next ESPD release 3.0.0. 

The main objective of the update of the code list is to make it non-domain specific and allow its reuse behind the procurement domain.

The main changes will be: 

-	Change name: from CriteriaTaxonomy to criteria or criterion (TBD). 
o	The change of name is due to the objective of making the code list non-domain specific.
-	Code Change to define non-specific domain criteria (final code changes to be provided in March)
-	Adapt concepts when needed
-	Code list to be maintained by EU Vocabularies (mid-2021)

Find here the file with the proposals shown during the meeting. 
[criterion_cl_sample.xlsx](https://github.com/ESPD/ESPD-EDM/files/5932480/criterion_cl_sample.xlsx)

If you have any additional comment, please do not hesitate to comment on this issue.

**Comment by psotofer** [comment]
As commented before, this issue was included in the last ESPD-EDM Release v3.0.0. therefore we proceed to close this issue.
In case you need further detail regarding this topic, please open a new issue referencing this one.

**Comment by hricolor** [comment]
As agreed during the development of ESPD v3.0.0, the code list to be used was updated to 'criterion' and published in EU Vocabularies.

The version of the code list used in ESPD v3.0.0 is [3.0.0](https://github.com/ESPD/ESPD-EDM/blob/master/docs/src/main/asciidoc/dist/cl/xlsx/ESPD-CodeLists-V3.0.0.xlsx) since it was not yet published in EU Vocabularies.

The current version of the code list in EU Vocabularies is [20210616-0](https://github.com/ESPD/ESPD-EDM/blob/master/docs/src/main/asciidoc/dist/cl/xlsx/ESPD-CodeLists-V3.0.0.xlsx).

Additionally, the latest version of the code list can be consulted [here](https://op.europa.eu/en/web/eu-vocabularies/dataset/-/resource?uri=http://publications.europa.eu/resource/dataset/criterion).
