### ISSUE TITLE
Part IV, Section C (For supply contracts: samples, descriptions or photographs with certification of authenticity)

### ISSUE THREAD

**Issue by rantati7** [OP-TED/ESPD-EDM#31]
**For supply contracts: samples, descriptions or photographs with certification of authenticity** 

CA must be able to define the required samples etc: what samples it requires, how are those going to be used and where & when the samples will need to be delivered.

It would be good if this question is only shown when supply contracts in question.

**Comment by ec-mcs** [comment]
We got this requirement as well from HU.

**Comment by paulakeen** [comment]
We close this issue, for it's been unified with issue #16 and #18
