### ISSUE TITLE
Use of CPV in Part II to define the activity of the supplier

### ISSUE THREAD

**Issue by hricolor** [OP-TED/ESPD-EDM#310]
As we presented in the OUC meeting on 3rd February, the CPVCodes code list is being revisited to see whether it is actually needed/used. 

In the current version of the ESPD 2.1.1, this CPV is included within the criterion "CRITERION.OTHER.EO_DATA.RELIES_ON_OTHER_CAPACITIES" which refers to information from the Part II of the ESPD. 

![image](https://user-images.githubusercontent.com/60606496/107486878-d7c89000-6b85-11eb-8e8d-ee5020e833b1.png)

We propose to remove this CPV code from this part of the ESPD. However, we would have your inputs on whether this can be removed and if it has been used so far. 

Do not hesitate to provide any input on the topic. 

Thanks.

**Comment by psotofer** [comment]
The CPV was removed in the ESPD-EDM Release v3.0.0. Therefore we close this issue.
In case you need further detail regarding this topic, please request the reopen this issue.
