### ISSUE TITLE
Question on UUIDs for REQUIREMENT(s) and QUESTION(s) 

### ISSUE THREAD

**Issue by mkrynski** [OP-TED/ESPD-EDM#311]
Hi ESPD team!
The technical handbook for v3.0.0 specifies that REQUIREMENT(s) and QUESTION(s) do not have a UUID assigned. This is because the UUID for each cac:TenderingCriterionProperty element has to be generated dynamically: each criterion property needs a unique identifier. There are 2 reasons for that mentioned in the documentation. But given that I have some doubts how to map Answers provided by suppliers (economic operators) with ESPD questions if there is no static identifier for Questions. Could you please help me understand how it should be resolved? 

Thanks in advance for your support!

**Comment by AFSOLUZIONI** [comment]
Hi,
to understand how we discussed a solution to your issue, you can see the issue #226 that explain a proposal to manage "dynamic" UUIDs.
Hope could be useful
Francesco

**Comment by mkrynski** [comment]
Hi @AFSOLUZIONI ,
#226 is very helpful to understand how the issue can be resolved. But it doesn't reply to the question how to manage the situation in which supplier can give multiple responses to a given question_subgroup. How to link the supplier answers from the response with the questions from the Request? See the post: #312. 
BR,
Marek

**Comment by psotofer** [comment]
Greetings,

UUIDs created dynamically for each QUESTION that the EO has to answer are provided as a unique UUID in the REQUEST document and need to be referred afterwards in the RESPONSE in the related cac:TenderingCriterionResponse.  

For instance, if the REQUEST  has the following cac:SubsidiaryTenderingCriterionPropertyGroup for f5276600-a2b6-4ff6-a90e-b31fe19dae41  

<cac:SubsidiaryTenderingCriterionPropertyGroup> 
                <cbc:ID schemeID="criterion" schemeAgencyID="EU-COM-GROW" schemeVersionID="3.0.0">f5276600-a2b6-4ff6-a90e-b31fe19dae41</cbc:ID> 
                <cbc:PropertyGroupTypeCode listID="PropertyGroupType" listAgencyID="EU-COM-GROW" listVersionID="3.0.0">ONTRUE</cbc:PropertyGroupTypeCode> 
                <cac:TenderingCriterionProperty> 
                                <cbc:ID schemeID="criterion" schemeAgencyID="EU-COM-GROW" schemeVersionID="3.0.0">
                                **UUID-1**</cbc:ID> 
                                <cbc:Description>Date of conviction</cbc:Description> 
                                <cbc:TypeCode listID="CriterionElementType" listAgencyID="EU-COM-GROW" listVersionID="3.0.0">QUESTION</cbc:TypeCode> 
                                <cbc:ValueDataTypeCode listID="ResponseDataType" listAgencyID="EU-COM-GROW" listVersionID="3.0.0">DATE</cbc:ValueDataTypeCode> 
                </cac:TenderingCriterionProperty> 
... 
</cac:SubsidiaryTenderingCriterionPropertyGroup>   

the RESPONSE document (that includes the criteria provided in the REQUEST document) must answered accordingly with the referred UUID like follows:  

<cac:TenderingCriterionResponse> 
                <cbc:ID schemeID="ISO/IEC 9834-8:2008 - 4UUID" ...>...</cbc:ID> 
                <cbc:ValidatedCriterionPropertyID schemeID="Criterion" schemeAgencyID="EU-COM-GROW" schemeVersionID="3.0.0">**UUID-1**</cbc:ValidatedCriterionPropertyID> 
                <cac:ResponseValue> 
                        <cbc:ID schemeID="ISO/IEC 9834-8:2008 - 4UUID"...>...</cbc:ID> 
                        <cbc:ResponseDate>XXXX-XX-XX</cbc:ResponseDate> 
                </cac:ResponseValue> 
</cac:TenderingCriterionResponse>

Please, let us know if you need further detail.

**Comment by psotofer** [comment]
Greetings,

As we discussed in the last OUC meeting, we described in #312 our proposal to address reusable dynamic UUIDs.
We proceed to close this issue since all discussions regarding the UUID will be conducted in #312.
Thank you.
