### ISSUE TITLE
Replacing #Criterion 62 Lots the EO tenders to

### ISSUE THREAD

**Issue by SellittoGiampaolo** [OP-TED/ESPD-EDM#313]
Dear all,
at national level we have some requests to simplify the submission of the ESPD response for EOs that are submitting for more than one lot having the same requirements. 
The current situation foresees that the EO signs the ESPD for each lot, since the ID off the lot is part of the ESPD and the electronic signature affects all of the information contained in the ESPD, so they cannot modify the information on the lot and mantain the same signature.

The foreseen solution is to allow the EO to specify that the same ESPD response (the document it is going to mark with e-signature) refers to a group of lots for which the EO is submitting an offer.

The platform implementors are asking for some structured way to perform this passage, so the idea could be to have something like Criterion 62 as a purely national criterion (it is not a criterion, we know) or as a SLOT in the ESPD request EDM

**Comment by ec-mcs** [comment]
Hi Giampaolo,

I do not think that this will work always. With v3 the rules are very clear. THere are two possibilities
- CA defines group of lots: If the CA participates in such a situtation, there will be one ESPD response catering for this group of lots. In your case only one signature is necessary.
- CA defines no group of lots: The EO must provide individual ESPD responses for each lot. In your case they would need to be signed individually.

As the ESPD response does not include to my knowledge anymore the Lot number but links only to a procedure, it would mean that the EO could reuse the same ESPD response for as many lots they would need. 

One more thing, as the tenders will be grouped into lots, the ESPD would then appear multiple times. 

So maybe this is not an issue after all?

**Comment by SellittoGiampaolo** [comment]
Thanks, Marc-Christopher
"As the ESPD response does not include to my knowledge anymore the Lot
number but links only to a procedure, it would mean that the EO could reuse
the same ESPD response for as many lots they would need."
This was what I responded to the objection, V3 solves this issue in my
opinion.

The proposal of a group of lots is the other way around the issue, proposed
by another expert and it should also work for EDM V.2.X
So it seems we have a deal here or more than one...
I strongly hope it will suffice...

**Comment by acolomer** [comment]
According to what was agreed in the OUC meeting of June 30th (see the meeting minutes here: https://github.com/ESPD/ESPD-EDM/blob/wgm-reports/ESPD_Minutes_OUC_Meetings_20210630_v2.0.pdf), the OUC accepts the solution above proposed by Marc-Christopher on the 21st of April and the issue can be closed.
