### ISSUE TITLE
ESPD V.3 and multidomain: is the order of the Criteria in an ESPD request Relevant?

### ISSUE THREAD

**Issue by SellittoGiampaolo** [OP-TED/ESPD-EDM#314]
The question in its simplest form is this one:
**is the order in which the criteria are presented in an ESPD request relevant?**
or shall we consider only which criteria are present and not their relative ordering?
(The response will reflect the order in the request)
If the order is relevant, where do we derive the order from?

**Comment by ec-mcs** [comment]
The current order comes from the ESPD regulation and is as such as well depicted in the eCertis scenario.
It makes sense to have a specific order as this will make it easier for suppliers to fill it out - at least in a country. If all solutions in one country would shuffle them, suppliers would need more time to fill it out manually or even to check.
The more data comes from national databases, it could probably makes sense to change the order. First the ones that are automatically answers and the rest that have to be filled out manually.
Another reason to change the order is when the supplier is answering to several lots. There it could make sense to do it differently.
To adjust the order, it should always be thought of, if this helps the supplier to provide the information.

**Comment by acolomer** [comment]
According to what was agreed in the OUC meeting of June 30th (see the meeting minutes here: https://github.com/ESPD/ESPD-EDM/blob/wgm-reports/ESPD_Minutes_OUC_Meetings_20210630_v2.0.pdf), the OUC accepts the solution above proposed by Marc-Christopher on the 22nd of April and the issue can be closed.
