### ISSUE TITLE
Evidences External Reference URI #interproc

### ISSUE THREAD

**Issue by konstantinosraptis91** [OP-TED/ESPD-EDM#319]
Hi, 

I am currently studying the ESPD-EDM v3.0.0 technical handbook. During my study I came across to this: In the Evidences section (6.8), in table 45 there is a reference about cac:Attachment/cac:ExternalReference/cbc:URI. In the requirements column, on the rule scope it says: “None. Not currently used in ESPD” but in the XML Examples part for that section there is a value for that field in the XML and also there is a value for that field in the XML artefact that exist in the ESPD-EDM repo XML examples.

Apparently it seems that cac:Attachment/cac:ExternalReference/cbc:URI is used according to those examples. So, I would like to ask if the rule scope reference is incorrect or it means something else.

<img width="955" alt="Στιγμιότυπο 2021-10-21, 11 27 52 πμ" src="https://user-images.githubusercontent.com/15834471/139083545-15fbf6a7-3e27-43c4-b38c-59350e44df30.png">

<img width="737" alt="Στιγμιότυπο 2021-10-21, 11 46 11 πμ" src="https://user-images.githubusercontent.com/15834471/139083648-aca2484d-f39f-4c6d-85e2-4e03188a8b4c.png">

<img width="438" alt="Στιγμιότυπο 2021-10-21, 11 46 58 πμ" src="https://user-images.githubusercontent.com/15834471/139083674-dd7b96c6-53a0-4f72-bf7b-d05515beb694.png">

<img width="889" alt="Στιγμιότυπο 2021-10-21, 11 45 07 πμ" src="https://user-images.githubusercontent.com/15834471/139083693-77130af6-f15d-4186-bdcc-32ad81ddb91f.png">

**Comment by psotofer** [comment]
We are currently reviewing this case.
We will come back to you with further detail.

**Comment by psotofer** [comment]
We are sorry the text in table 45 is misleading. Please read the Text as

**Rule:** None.
No rule is applied.

**Comment by acolomer** [comment]
Thank you for your comment. The reported issue has been fixed in v3.0.1.
