### ISSUE TITLE
Part IV, Section C (For supply contracts: certificates by quality control institutes)

### ISSUE THREAD

**Issue by rantati7** [OP-TED/ESPD-EDM#32]
**For supply contracts: certificates by quality control institutes**

CA must be able to define what is required

**Comment by lauramrtn** [comment]
Agree, we think when the ESPD is self-contained the required certificates/standards should sit next to the question.

It would also be useful, if this only appeared when it was a supply contract - perhaps if there was a conditional question at the start of the ESPD  asking if the tender was goods, works or services the appropriate questions could pre-populate.

**Comment by paulakeen** [comment]
We close this issue, for it's been unified with issues #16 and #18
