### ISSUE TITLE
data misplacement for Criteria #52 and #53 in ESPD-criterion-V3.0.0.xlsx #interproc

### ISSUE THREAD

**Issue by konstantinosraptis91** [OP-TED/ESPD-EDM#322]
Hello ESPD team,

I found a minor issue in ESPD ESPD-criterion-V3.0.0.xlsx (former taxonomy). In Criteria 52 and 53 there is a data misplacement in lines  15,16,17 and in lines 43,44,45. In those lines, the data in the right of column R should be moved (including the data in column R) one column to the right.

<img width="1021" alt="Στιγμιότυπο 2022-02-23, 11 32 28 πμ" src="https://user-images.githubusercontent.com/15834471/155294255-232b1759-0664-41f7-9298-f660a6a79660.png">

<img width="1021" alt="Στιγμιότυπο 2022-02-23, 11 32 39 πμ" src="https://user-images.githubusercontent.com/15834471/155294294-e046ea0b-dad1-4da2-bbfe-d1f893d6eb5a.png">

**Comment by psotofer** [comment]
Hello,
Thank you for letting us know.
We will discuss the best way to deploy this fix in a future release and will keep you informed.

**Comment by acolomer** [comment]
Good afternoon,
We thank you for the comments.
The fix has been implemented it in the [masterbranch](https://github.com/OP-TED/ESPD-EDM/blob/master/codelists/ESPD-criterion.xlsx) and it will be released it in the next version.
We therefore close the ticket.
Kind regards,
The ESPD-EDM Team
