### ISSUE TITLE
C#59 - QUESTION of type CODE without the code list

### ISSUE THREAD

**Issue by nico3dfx** [OP-TED/ESPD-EDM#323]
Hi,
i have a question for C#59 and the question "**Please indicate the role of the economic operator in the group (leader, responsible for specific tasks...)**", **CODE** with **EORoleType** code list.

In the extended request example file provided in this repo (**ESPD-Request.xml**) inside the TenderingCriterionProperty node the indication of the **EORoleType** is missing.

So I can read the request file but when building the UI, I can't provide a select field for this question because I don't have the related code list for this QUESTION of CODE type.

How to implement this?
Nico

**Comment by psotofer** [comment]
Hello,
We are currently analysing this case and will come back to you as soon as possible with more details.
Thank you for your feedback.

**Comment by acolomer** [comment]
Good afternoon,
We thank you for the comments.
Please take into account that the ESPD-EDM specifies that CODE values for criterion 59 must come from code list EORoleType, but it is up to the implementors to define how to implement it.
Kind regards,
The ESPD-EDM Team
