### ISSUE TITLE
Incorrect element code in ESPD-criterion.xlsx v3.0.1 for Criterion #27 #interproc

### ISSUE THREAD

**Issue by konstantinosraptis91** [OP-TED/ESPD-EDM#325]
Hello ESPD team,

I found a minor wording issue in the criteria taxonomy. In the sheet "SC-Suitability-II" the element code of the criterion 27 is written as "autorisation". I think the correct wording is "authorisation". I found that it is also written as "autorisation" in every example inside the Technical Handbook, that connects with this particular criterion and this particular element. Is this wording on purpose or it is actually a mistake?

<img width="927" alt="Στιγμιότυπο 2022-03-01, 5 59 37 μμ" src="https://user-images.githubusercontent.com/15834471/156203338-ea39fbce-3bc9-4503-889e-d6599420edf9.png">

**Comment by psotofer** [comment]
Greetings,
We are analysing this case and will come back to you as soon as possible.
Thank you for your feedback.

**Comment by acolomer** [comment]
Hello, Konstantinos,
Although this is only a code (and therefore it should have no semantic), we will fix it to make it consistent with the other codes (it will be updated so it is written in english - authorisation).
All artifacts mentioning the criterion will be updated in a future release. 
Kind regards,
The ESPD Team

**Comment by pascalinelaur** [comment]
Hi @konstantinosraptis91 , 

The latest codelist for "Criterion" has been downloaded from EU Vocabularies. Also, the corresponding version has been updated in ESPD-Codelists and XSLT files. The fix will be available for the v3.2.0. 

KR, 
The ESPD Team.
