### ISSUE TITLE
Question of type EVIDENCE_IDENTIFIER with different cardinality

### ISSUE THREAD

**Issue by nico3dfx** [OP-TED/ESPD-EDM#326]
Hi,
there are 2 questions inside criterion 41 (e.g.) for a EVIDENCE_IDENTIFIER.
The cardinality for those questions is different

![image](https://user-images.githubusercontent.com/14906908/157627088-a248ee87-14c1-47d2-932b-0285ccf2f573.png)

**The problem is**: how to render the UI?

In the first case there is only **one** answer but in the second case the EO can provide **multiple** answers.

How to archive this scenario?

Thanks,
Nico.

**Comment by acolomer** [comment]
Good afternoon,
If your question is related to v2.1.1, we inform you we no longer maintain this version.
If your question is related to v3.0.1, any correction required after analysis and discussion with the OUC will be integrated in a future release.
This issue will be updated as necessary.
Kind regards,
The ESPD-EDM Team

**Comment by acolomer** [comment]
Good afternoon,
EVIDENCE_IDENTIFIER: 0a166f0a-0c5f-42b0-81e9-0fc9fa598a48 cardinality is to be fixed to 1..n in criteria 40 and 41 in ESPD-criterion.xlsx file.
Kind regards,
The ESPD-EDM Team

**Comment by acolomer** [comment]
Good afternoon,
We thank you for the comments.
The fix has been implemented it in the [masterbranch](https://github.com/OP-TED/ESPD-EDM/blob/master/codelists/ESPD-criterion.xlsx) (EVIDENCE_IDENTIFIER: 0a166f0a-0c5f-42b0-81e9-0fc9fa598a48 cardinality already fixed to 1..n in criteria 40 and 41 in ESPD-criterion.xlsx file) and it will be released it in the next version.
We therefore close the ticket.
Kind regards,
The ESPD-EDM Team
