### ISSUE TITLE
Cardinality issue for the element cac:ProcurementProjectLotReference/cbc:ID #interproc

### ISSUE THREAD

**Issue by konstantinosraptis91** [OP-TED/ESPD-EDM#328]
Hello ESPD team,

Section: 2.4 Root Elements

By looking at table 5 in the technical handbook v3.0.1, I noticed that the cardinality of the element ../cac:TenderingCriterion/cac:ProcurementProjectLotReference/cbc:ID is presented as 0..n. I think the correct cardinality for the identifier cbc:ID, which is inside the cac:ProcurementProjectLotReference is 1..1 and the 0..n cardinality belongs to ../cac:TenderingCriterion/cac:ProcurementProjectLotReference.

![Στιγμιότυπο 2022-04-15, 12 37 32 μμ](https://user-images.githubusercontent.com/15834471/163555167-56fd19f6-3249-4a80-8bbb-71710750df9e.png)

<img width="1027" alt="Στιγμιότυπο 2022-04-15, 12 43 58 μμ" src="https://user-images.githubusercontent.com/15834471/163556143-08a544cd-200f-4b45-9e38-907782a9a7f1.png">

**Comment by acolomer** [comment]
Good morning,
We thank you for the comments.
The cardinality is not the same for Exclusion Grounds and Selection Criteria:
- Exclusion Grounds are common to all lots, and therefore a Lot Reference is not required (for Exclusion Grounds, cardinality is 0).
- For Selection Criteria it is mandatory to specify the Lot Reference for all lots for which the Selection Criterion applies (for Selection Criteria, cardinality is 1.n).
Therefore, combining the two, gives a cardinality of 0.n.
We therefore close the ticket.
Kind regards,
The ESPD-EDM Team
