### ISSUE TITLE
Wording/Spelling issues in the technical handbook v3.0.1 #interproc

### ISSUE THREAD

**Issue by konstantinosraptis91** [OP-TED/ESPD-EDM#329]
Hello ESPD team,

I have detected some wording/spelling issues in the technical handbook version 3.0.1.

**Issue 1**

_Section 2.5 Lot Management_

The following sentence doesn't make sense as it looks right now. I think instead of Selection you would like to say Exclusion Grounds.

![Στιγμιότυπο 2022-04-15, 1 00 57 μμ](https://user-images.githubusercontent.com/15834471/163558132-4ee6bbab-9cf6-4339-91f7-f3a0bc9d981d.png)

**Issue 2**

_Section 6.6 Economic Operator_

This is a minor spelling issue I noticed, that concerns the cac:EconomicOperatorRole element. As you can see in the photo attached the spelling of this element in table 32 is not correct.

![Στιγμιότυπο 2022-04-15, 1 10 20 μμ](https://user-images.githubusercontent.com/15834471/163558873-011de100-0e41-4257-bb5c-3042cb23dae6.png)

**Issue 3**

_Section 3.1 General Behavior_

The Legislation element has an incorrect namespace prefix. More specifically the prefix is displayed as cbc, but the correct one is cac.

![Στιγμιότυπο 2022-04-15, 1 15 54 μμ](https://user-images.githubusercontent.com/15834471/163559539-38698248-ac2d-4e55-8b7f-f9bdca809bc4.png)

**Issue 4**

_Section 3.4 Properties_

There is a minor spelling issue in the description of cbc:ValueDataTypeCode element in table 23. The word property is written as poperty.

![Στιγμιότυπο 2022-04-15, 1 57 30 μμ](https://user-images.githubusercontent.com/15834471/163563232-8ed85191-87a0-4385-b783-64e6634256e8.png)

**Issue 5**

_Section 5.1 Lot Management approach for Selection Criteria_

There is an issue with the wording in the second sentence. As it is right now it does not make sense in my opinion.

![Στιγμιότυπο 2022-04-15, 2 09 57 μμ](https://user-images.githubusercontent.com/15834471/163564256-5a09defd-729d-457f-ba3e-2dc4814efff1.png)

**Comment by acolomer** [comment]
Good morning,
We thank you for the comments.
We have updated the Technical Handbook (https://docs.ted.europa.eu/ESPD-EDM/3.0.1/index.html) as detailed in section Annex III. Revisions of the Document.
We therefore close the ticket.
Kind regards,
The ESPD-EDM Team
