### ISSUE TITLE
Part IV: Selection criteria, D: Quality assurance schemes and environmental management standards - Specific requirements

### ISSUE THREAD

**Issue by rantati7** [OP-TED/ESPD-EDM#33]
**Certificates by independent bodies about quality assurance standards**

CA must be able to define  what are the required quality assurance standards, including accessibility for disabled persons.

**Comment by paulakeen** [comment]
Requirements from issue #34 :
**Certificates by independent bodies about environmental management systems or standards**
CA must be able to define what are the required environmental management systems or standards.

**Comment by paulakeen** [comment]
Could you please provide examples of particular requirements for the different criteria for several procedures, so we can identify the information that should be required to the CA?

**Comment by paulakeen** [comment]
Requirements from issue #48 :
Quality assurance does only have a description, but it could also refer to well identified standards (e.g. (ISO 9000 family, ISO 27000 standards, and also the parts, e.g. ISO 11179:5 for metadata registry, etc.

it affects the XML instantiation "super-model" , doesn’t impact the XSD Schema.

**Comment by paulakeen** [comment]
Please find below what was commented about this issue in the discussion group:

Timo Rantanen / Hansel / Finland: no ! cannot come from eCertis 

Giampaolo Sellitto 2: but we can insert in e-CERTIS that kind of requirements

Giampaolo Sellitto 2: we manage them at national level 

Jose Luis Cueva (Spain): ISO 9000 - Quality management family odf standards

Timo Rantanen / Hansel / Finland 2: Not only ISO but several others also

Jose Luis Cueva (Spain): some examples: ISO/TS 29001 – Petroleum, petrochemical and natural gas industriesISO 13485 – Medical devices ISO/IEC 90003 – Software engineering 

Giampaolo Sellitto 2: yes this fits for us

Timo Rantanen / Hansel / Finland 2: Here's a list of - ONLY SOME - environmental "standards". I think there are very many others

Timo Rantanen / Hansel / Finland 2: https://en.wikipedia.org/wiki/Environmental_standard

Giampaolo Sellitto 2: yes but they are in the ESPD in the case they are required for the qualification of process not of product

Giampaolo Sellitto 2: that is if we require that the company is certified to execute some work or service

Timo Rantanen / Hansel / Finland 2: http://www.herinst.org/BusinessManagedDemocracy/environment/consumerism/images/eco-labels-graphic.png

Timo Rantanen / Hansel / Finland 2: http://thepackaginginsider.com/wp-content/uploads/2012/01/eco-label.jpg

Giampaolo Sellitto 2: also in italy you fulfill a requirement 

Giampaolo Sellitto 2: but you show a certificate or declare that you have a similar measure in place

Giampaolo Sellitto 2: this is a simple way 

Giampaolo Sellitto 2: usually these are the certificates that the EO shall provide by himself

Giampaolo Sellitto 2: uploading them or sending them

Jose Luis Cueva (Spain): ok

Jose Luis Cueva (Spain): they should provide it electronically, of course

**Comment by paulakeen** [comment]
Please find below a proposal of mock-ups, both for the view of the CA and the view of the EO:

- View of the CA: The CA can provide as many requirements as needed. The CA should provide requirements, and not require a particular certificate.

![image](https://cloud.githubusercontent.com/assets/16134316/25130921/3c349b98-2444-11e7-8ea4-5db8e8bd045c.png)

- View of the EO: When the EO answers YES, the EO will need to provide the URL, the Reference/Code and the Issuer. When the EO answers NO, the EO will be able to provide the reasons why it is not certificated.

![image](https://cloud.githubusercontent.com/assets/16134316/25130931/464e967e-2444-11e7-9f92-a2fbf3fbad5f.png)

**Comment by paulakeen** [comment]
Please find below what was commented about this issue in the discussion group:

Rudolf Maier: Each!

Anne Katrine, NIRAS A/S, DK: Each it may be different answer.

Rudolf Maier: There shoul be  I field for an URL

Rudolf Maier: EO

Rudolf Maier: EO should have the possibility to fill in the URL to his/her EMAS documents.

Rudolf Maier: There is a number.

Rudolf Maier: The number is from the Certificate.

Timo Rantanen / Hansel / Finland: this is ok

Anne Katrine, NIRAS A/S, DK: We do not have those in DK. 

Anne Katrine, NIRAS A/S, DK: Yes, good to link to eCertis like that.

Timo Rantanen / Hansel / Finland: Yes we do have a lot

Anne Katrine, NIRAS A/S, DK: Ok.

**Comment by paulakeen** [comment]
Please find below a proposal of the mock-up for the view of the EO, as commented in the last meeting:

![image](https://cloud.githubusercontent.com/assets/16134316/25390568/34076a00-29d4-11e7-8d6d-acc2897f93c5.png)

**Comment by paulakeen** [comment]
Please find the details of the final decision in https://github.com/ESPD/ESPD-EDM/wiki/14.-Quality-assurance-schemes-and-environmental-management-standards
