### ISSUE TITLE
Compulsory attributes of the code elements (datatype=Code) #interproc

### ISSUE THREAD

**Issue by konstantinosraptis91** [OP-TED/ESPD-EDM#330]
Hello ESPD team,

I think there is an inconsistency regarding the compulsory attributes of elements classified as codes (datatype = Code) in the technical handbook v.3.0.1.

In table 1 there is a requirement that clearly says, that the current ESPD specification requires always three mandatory attributes. Those are listID, listAgencyID , listVersionID.

![Στιγμιότυπο 2022-04-15, 2 38 53 μμ](https://user-images.githubusercontent.com/15834471/163566457-a6b003b2-b3b4-455b-a4a2-6f32a97b8123.png)

but in table 3, from the definitions in the definition column, it appears that the mandatory attributes in the current version of ESPD are: listID, listAgencyName, and listVersionID. So, according to the requirement listAgencyName is not included in the mandatory attributes, but according to table 3, it is. And in table 3 listAgencyID is not marked as (MANDATORY in this version of ESPD). 

![Στιγμιότυπο 2022-04-15, 2 49 23 μμ](https://user-images.githubusercontent.com/15834471/163567378-3271e9d9-5421-412c-9ff6-ca711bb421b0.png)

**Comment by acolomer** [comment]
Good morning,
We thank you for the comments.
We have updated the Technical Handbook (https://docs.ted.europa.eu/ESPD-EDM/3.0.1/index.html) as detailed in section Annex III. Revisions of the Document.
We therefore close the ticket.
Kind regards,
The ESPD-EDM Team
