### ISSUE TITLE
Questions regarding the relationship at syntax binding level between data type and response data type and ESPD TestCases Mapping document #interproc

### ISSUE THREAD

**Issue by konstantinosraptis91** [OP-TED/ESPD-EDM#331]
Hello ESPD team,

I was reviewing the Schematron files and I came across BR-TCR-08. I see that all the rules are documented in more detail with a complete description in [BIS 41](https://wiki.ds.unipi.gr/display/ESPDInt/BIS+41+-+ESPD+V2.1.0), a specification, to which the technical handbook has many references and links. By looking at BIS 41 I noticed that the referenced rule's description mentions a table in a specific docx document ([ESPD_TestCases_mapping_v10.docx](https://wiki.ds.unipi.gr/download/attachments/109379675/ESPD_TestCases_mapping_v10.docx?version=1&modificationDate=1654004859858&api=v2)). I found the document and realize it was an additional helper tool for the technical implementation process of v2.x.x. By reading the document I found the content extremely useful for someone who wants to proceed with the implementation of the ESPD. The questions are:

1. Is there an updated or equivalent document concerning the ESPD v3.x.x which uses UBL 2.3?
2. The first question mostly covers the second one which is: Is the relationship between data type and response data type documented at the syntax binding level in the technical handbook?

**Comment by acolomer** [comment]
Good afternoon,
Thank you for your comments.
Unfortunately we do not have access to the document you discuss.
We are going to update our documentation so if you could provide us with the documentation we will see whether it is possible to address our documentation in a similar way.
Kind regards,
The ESPD Team

**Comment by konstantinosraptis91** [comment]
Yes, you are right, you need an account in order to download the referenced document. I will attach the document here 
[ESPD_TestCases_mapping_v10.docx](https://github.com/OP-TED/ESPD-EDM/files/8900504/ESPD_TestCases_mapping_v10.docx)

**Comment by acolomer** [comment]
Good morning,
Thank you very much for your comment. 
A simplified version of the document will be provided as an annex to the technical handbook in a future release.
Kind regards,
The ESPD Team

**Comment by acolomer** [comment]
Good morning,
As mentioned, the information from the document has been provided in Annex IV. Business Rules Guide of the Technical Handbook for version 3.1.0 (https://docs.ted.europa.eu/ESPD-EDM/latest/xml_technical_handbook.html#business-rules-guide).
Kind regards,
The ESPD Team
