### ISSUE TITLE
DATE Response Data Type

### ISSUE THREAD

**Issue by Tannex** [OP-TED/ESPD-EDM#332]
Hi,

I have a question regarding the description of the `DATE` response data type.
In the CodeLists, we see the format specified as `YYYY-DD-MM` [https://github.com/OP-TED/ESPD-EDM/blob/515c6d0a156c819aa668518a345500dab6c18d16/codelists/gc/ResponseDataType.gc#L166](https://github.com/OP-TED/ESPD-EDM/blob/515c6d0a156c819aa668518a345500dab6c18d16/codelists/gc/ResponseDataType.gc#L166)

But when exploring the XML output from ESPD-Service, the format seems to be `YYYY-MM-DD`, e.g.
```xml
<ccv:Requirement responseDataType="DATE">
  <cbc:ID schemeID="CriterionRelatedIDs" schemeAgencyID="EU-COM-GROW" schemeVersionID="1.0">ecf40999-7b64-4e10-b960-7f8ff8674cf6</cbc:ID>
  <cbc:Description>Date of conviction</cbc:Description>
  <ccv:Response>
    <cbc:Date>2022-06-28</cbc:Date>
  </ccv:Response>
</ccv:Requirement>
```

**Comment by acolomer** [comment]
Good morning,
We thank you for the comment.
The format YYYY-MM-DD has been adopted everywhere. The [fix ](https://github.com/OP-TED/ESPD-EDM/compare/master...update-codelist)has been implemented in a [specific branch](https://github.com/OP-TED/ESPD-EDM/tree/update-codelist) and it will be released in a future version.
We therefore close the ticket.
Kind regards,
The ESPD-EDM Team
