### ISSUE TITLE
Misinterpretation additional description lines

### ISSUE THREAD

**Issue by arunas-z** [OP-TED/ESPD-EDM#339]
Hello,

in taxonomy Excel file misinterpr criteria has multiple lines, and for that reason ADDITIONAL_DESCRIPTION_LINE elements are used:
![image](https://user-images.githubusercontent.com/30899510/183393640-61fed0b3-589c-467b-b450-826c18e8afbb.png)

However the text returned from eCertis does not match and cannot be split into these:
`Can the economic operator confirm that it has not been guilty of serious misrepresentation in supplying the information required for the verification of the absence of grounds for exclusion or the fulfilment of the selection criteria, it has not withheld such information, it has been able, without delay, to submit the supporting documents required by a contracting authority or contracting entity, and it has not undertaken to unduly influence the decision making process of the contracting authority or contracting entity, to obtain confidential information that may confer upon it undue advantages in the procurement procedure or to negligently provide misleading information that may have a material influence on decisions concerning exclusion, selection or award?"`

**Comment by hricolor** [comment]
Greetings, 
Thank you so much for your comments. 

On our view there are two points: 
1. Additional_description_lines are elements that are allowed and recommended by UBL for the given usage. Therefore, technically it is possible and it is correct. That drives to the second bullet; 
2. The inconsistency is between descriptions from ESPD and eCertis. This aspect is already spotted by other OUC users in issue #336. Then, we are going to provide a solution in the future once we tackle this topic. 

We will inform you of new advances on the issue.

**Comment by acolomer** [comment]
Good morning,
Thank you very much for your comment.
The issue you report will be solved in the future, when information is automatically retrieved from eCertis and, therefore, there will be one single source of truth and texts will not be duplicated in eCertis and ESPD.
Kind regards,
The ESPD Team

**Comment by dragos-eu** [comment]
Hello @arunas-z,

Please find the solution implemented in ESPD-EDM v4.0.0 (https://github.com/OP-TED/ESPD-EDM/releases/tag/v4.0.0).

Kind regards,
ESPD Team
