### ISSUE TITLE
Part IV, Section D (Certificates by independent bodies about environmental management systems or standards)

### ISSUE THREAD

**Issue by rantati7** [OP-TED/ESPD-EDM#34]
**Certificates by independent bodies about environmental management systems or standards**

CA must be able to define what are the required environmental management systems or standards.

**Comment by lauramrtn** [comment]
Agree, we think when the ESPD is self-contained the required certificates/standards should sit next to the question.

**Comment by paulakeen** [comment]
In principle this would not affect the data model but the GUI interfaces and the XML implementation rules: the element criterion contains sufficient placeholders to define which is the exact requirement and to refer to online available information.

**Comment by paulakeen** [comment]
We close this issue, for it's been unified with issue #33
