### ISSUE TITLE
trouble building java-library

### ISSUE THREAD

**Issue by simevo** [OP-TED/ESPD-EDM#341]
The [README.md file in `/java-library`](/OP-TED/ESPD-EDM/blob/master/java-library/README.md) mentions the `bindings.xjb` file, but it is not clear whether it is supposed to be created by us or by you (in that case it is missing).

The link to `https://jaxb.java.net/` redirects to `https://github.com/javaee/jaxb-v2` which in turn "_has been archived by the owner_" and redirects to the [corresponding Eclipse repository](https://github.com/eclipse-ee4j/jaxb-ri) (apparently JAXB has been rebranded **Jakarta XML Binding**).

The link to the [JAXB2 Maven plugin](https://java.net/projects/maven-jaxb2-plugin/pages/Home) points to [source code](/javaee/metro-maven-jaxb2-plugin) that is unmaintained since 2017. Apparently there is [an alternative, maintained implementation](/mojohaus/jaxb2-maven-plugin), but I am not sure if should migrate to that.

The command `mvn verify` when launched in the `java-library` dir of this project reports:

```
[WARNING] The POM for org.glassfish.jaxb:jaxb-runtime:jar:2.2.11 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] The POM for org.glassfish.jaxb:jaxb-core:jar:2.2.11 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] The POM for org.glassfish.jaxb:txw2:jar:2.2.11 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] The POM for org.glassfish.jaxb:jaxb-xjc:jar:2.2.11 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] The POM for org.glassfish.jaxb:codemodel:jar:2.2.11 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] The POM for com.sun.xml.bind.external:rngom:jar:2.2.11 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] The POM for com.sun.istack:istack-commons-tools:jar:2.21 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] No schemas to compile. Skipping XJC execution.
```

then fails with:

```
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] Source option 5 is no longer supported. Use 6 or later.
[ERROR] Target option 1.5 is no longer supported. Use 1.6 or later.
```

(I tried on Debian stable with [`openjdk-11-jre-headless 11.0.16`](https://packages.debian.org/bullseye/openjdk-11-jre-headless) and [`maven 3.6.3`](https://packages.debian.org/bullseye/maven)).

Finally, it would help to make this project actionable to have a simple, clear, operative guide how to use the java library, supported by an example application.

**Comment by acolomer** [comment]
Good morning,
This issue is related to a previous version of the ESPD which is no longer maintained. Currently, ESPD services can be implemented and maintained using different technologies and, therefore, these files are not provided.
Best regards,
The ESPD Team

**Comment by simevo** [comment]
Thanks for your reply @acolomer.

My issue refers to files present in the `master` branch and in the currently released version of this repository. If these files are not anymore maintained, you should remove them from the repository, from the README and from [the documentation](https://docs.ted.europa.eu/ESPD-EDM/3.0.1/release_notes.html#_reorganisation_of_the_distribution_package_folders).

Alas with this part removed, this project is just a collection of schemas and documentation, and as such it is not really helpful for someone with a practical problem (i.e. converting from ESPD Response version 1.0.2 to version 3.0.1, or semantically diffing two Responses). Language bindings make the schemas actionable and usable!

For this reason I'm very interested in the "_different technologies_" for implementing ESPD services that you mention. Please share links/roadmaps if you can. I have found this related project https://github.com/ESPD/ESPD-Service but it's stuck at 5 years ago.

Thanks again, Paolo

**Comment by acolomer** [comment]
Good morning,

Thank you for your comment. We have the following considerations about it:

1. As the artefact is not maintained, it will be removed from release 3 and the upcoming ones.
 
2. The ESPD-EDM project provides a data model, a set of schemas and constraints (business rules) that can be considered a specification. Therefore, the implementation of the ESPD Services need to follow and be compliant with the requirements stated in the ESPD-EDM, providing an XML as an output that needs to be validated using the ESPD Validator.
 
3. The implementation can be performed using any technology that complies with the specifications. These technologies depend on the possibilities and preferences of each organisation.
 
Kind regards,

The ESPD Team

**Comment by acolomer** [comment]
Good morning,
Despite what was said before, we have not removed the java library.
Please see https://github.com/OP-TED/ESPD-EDM/tree/138fa20d305b1675ba18f63a65a13e59de48d7e7/java-library
_NOTE: This section is related to older ESPD versions and it´s no longer maintaned. Currently the ESPD services can be implemented and maintained using different technologies, according to business and technical needs/requirement of implementers, and not only Java._
Kind regards,
The ESPD Team
