### ISSUE TITLE
Criterion sections grouping and titles

### ISSUE THREAD

**Issue by JelenaCaik** [OP-TED/ESPD-EDM#342]
For both Exclusion and Selection criterion Espdv2 had A. | B. | C. | D. sections. Looking at ESPDv3 I do not see anymore A. | B. | C. | D. sections. ESPD v3 taxonomy and handbook have these sections:
* Exclusion criteria: Convictions, Contributions, Environment, Social, Labour Law, Business, ..... Purely national criteria.
* Selection criteria: Suitability, Turnovers, Financial ratios, ...Other aspects of participation and selection.
Which one variant is correct and how groups/sections should be implemented?

![question1](https://user-images.githubusercontent.com/113527358/190175946-af77ffb5-6c5d-4696-9b03-7d36075a6276.png)

**Comment by acolomer** [comment]
Good afternoon,
Thank you for your comment.
After reviewing your comment we can remark the following:

- In the Business Handbook, information about the A, B, C, D section is provided:
![image](https://user-images.githubusercontent.com/24680296/191756014-6008ac16-2ec3-450f-9312-3784eac479ff.png)

- In the Criterion Excel file, there is a separate tab for each selection criterion, but they are not grouped in sections.
- In the Technical Handbook, detailed information on each selection criterion is provided, but they are not grouped in sections in the index.  


Best regards,
The ESPD Team

**Comment by acolomer** [comment]
Good morning,

The grouping is just a categorisation provided in the ESPD regulation, but it does not affect the ESPD implementation. For the ESPD services, you can implement any grouping and ordering you want, since this is not validated in the ESPD validation rules.

Best regards,
The ESPD Teams
