### ISSUE TITLE
Selection criteria. Suitability > Enrolment in a relevant professional register: Other occupation 

### ISSUE THREAD

**Issue by JelenaCaik** [OP-TED/ESPD-EDM#344]
Selection criteria: 
Suitability > Enrolment in a relevant professional register
Requirement: Occupation > 0000.0 Other

From Technical handbook:
NOTE: The code list 'occupation' is used to determine the area to which the EO should be registered in. It comes from the ESCO classification, in case the Buyer do not find the appropiate code to define the type of professional enrolement it can select code '0000.0' which stands for other. Then would be able to include the type using a text box.

![1_question](https://user-images.githubusercontent.com/113527358/190649411-fdaeed66-e45b-4df2-8ad5-c4e55f19c642.png)

QUESTION: Is it possible to choose several times code 0000.0 Other or is it possible to select only once?

**Comment by hricolor** [comment]
Good morning,
Thank you for your comment.
After reviewing your comment we can remark the following: 
First of all, as can be read in the image of data structures you attached, the cardinality of REQUIREMENTS is [1]. It means that in one REQUIREMENT_GROUP it is only possible to include one code 0000.0 other + one additional text box. 

However, the cardinality of the whole REQUIREMENT_GROUP is 1..n, therefore, it would be possible to add two REQUIREMENT_GROUPS with their corresponding requirements and questions nested. 
 
Hope this answer is helpful for your purpose. 
 
Best Regards, 
The ESPD Team
