### ISSUE TITLE
Missing "0000.0" code in Occupation codelist

### ISSUE THREAD

**Issue by JustinaZaltauskaite** [OP-TED/ESPD-EDM#347]
Hi,
Occupation codelist is missing "0000.0" code for other occupations, not found in the list.
This code is mentioned in the handbook
![image](https://user-images.githubusercontent.com/75019622/195529105-27740981-7357-44dd-a53b-4534c0152931.png)

We tried to find it in these places:
- https://op.europa.eu/en/web/eu-vocabularies/dataset/-/resource?uri=http://publications.europa.eu/resource/dataset/occupation
- https://raw.githubusercontent.com/OP-TED/ESPD-EDM/update-codelist/codelists/gc/occupation.gc, that we found in https://github.com/OP-TED/ESPD-EDM/blob/update-codelist/codelists/gc/occupation.gc

**Comment by acolomer** [comment]
Good afternoon,
Thank you very much for your comment.
This code "0000.0", which stands for other occupations, is not provided by ESCO (Multilingual classification of European Skills, Competences, Qualifications and Occupations), but  was instead a customisation in the technical code list we were using. Now we are not using this customised technical code list anymore, but a data code list provided by ESCO, and therefore the option "0000.0" is no longer available and therefore it is necessary for the Economic Operator to select a value from the list.
We will remove this option "0000.0" from the documentation to avoid any misunderstanding.
Kind regards,
The ESPD Team

**Comment by Nikanoras** [comment]
What about the field "Other register" in taxonomy excel? Will you remove it also?  @acolomer

**Comment by acolomer** [comment]
Good afternoon,
Thank you very much for your comment.
We will remove the  field "Other register" in the taxonomy excel. 
We will let you know when the update is available, and it will be released in ESPD v3.1.0, scheduled for the end of this year.
Kind regards,
The ESPD Team

**Comment by acolomer** [comment]
Good morning,
The following updates are available:

- Update of the occupation.gc codelist file, available in the ["update-codelist" branch](https://github.com/OP-TED/ESPD-EDM/tree/update-codelist);
- Update of the data structure by removing the requirement "other register" in the criterion C25 SC prof-regist, available in the ["criterion-evolution" branch](https://github.com/OP-TED/ESPD-EDM/tree/criterion-evolution).

As mentioned in a previous comment, we will also remove option "0000.0" from the documentation to avoid any misunderstanding.

Kind regards,
The ESPD Team

**Comment by aurimas-jankauskas** [comment]
@acolomer Will this fix be available on ESPD 3.1.0?

**Comment by acolomer** [comment]
Good morning,
Yes, the update will be effective from version 3.1.0.
Documentation will also be updated for ESPD-EDM v3.1.0, because the current documentation is valid for ESPD-EDM v3.0.1 (latest version available now), as we are still using the technical code list.
Kind regards,
The ESPD Team
