### ISSUE TITLE
Two different occupations have same ID in occupations codelist

### ISSUE THREAD

**Issue by JustinaZaltauskaite** [OP-TED/ESPD-EDM#348]
Two different occupations have same ID in occupations codelist
**ID:** 7412.12
**Occupations:**
- wind turbine technician
- theme park technician

We took codelist from here: https://raw.githubusercontent.com/OP-TED/ESPD-EDM/update-codelist/codelists/gc/occupation.gc

**Comment by acolomer** [comment]
Good afternoon,
Thank you very much for your comment. 
We have reported the issue to the author of the code list.
We will let you know when the problem is solved.
Kind regards,
The ESPD Team

**Comment by hricolor** [comment]
Good afternoon, 
Thanks for your comments. 

The codes are not duplicated in the latest ESCO classification version (v.1.1.1). Then, we will manage with the good EU Vocabularies team the creation of the gc updated according to the latest version of the ESCO classification. This will be available for the next major release. 

Kind Regards,
The ESPD Team.

**Comment by aurimas-jankauskas** [comment]
@hricolor just to clarify, this fix will be available on ESPD 3.1.0?

**Comment by hricolor** [comment]
Hi @aurimas-jankauskas unfortunately, the EU Vocabularies has a very clear calendar for new releases of the codelists. Therefore, It will not be possible to include the fix in the next 3.1.0 release. We are working to get the fix ready as soon as possible.

**Comment by pascalinelaur** [comment]
Hi @aurimas-jankauskas, 

The latest codelists for "Occupation" has been downloaded from EU Vocabularies. Also, the corresponding version has been updated in ESPD-Codelists and XSLT files. The fix will be available for the v3.2.0. 

KR, 
The ESPD Team.
