### ISSUE TITLE
Occupations in the codelist randomly start with uppercase or lowercase {minor}

### ISSUE THREAD

**Issue by JustinaZaltauskaite** [OP-TED/ESPD-EDM#349]
Hi,
here is a minor issue in occupations codelist - some occupations in the codelist randomly start with uppercase or lowercase letter. 
There is no consistency in here:
- different languages have different rule for uppercase/lowercase. 
- even in the same language it sometimes is in uppercase or lowercase. 

**Example 1:**
![image](https://user-images.githubusercontent.com/75019622/197148947-75dd7224-f970-45e9-8cd6-e7338b51fe7e.png)

**Example 2** (our visual implementation, but we show exactly what we get in the codelist):
![image](https://user-images.githubusercontent.com/75019622/197149043-19d60caa-5cef-4315-a328-3503535ee841.png)

**Comment by hricolor** [comment]
Good afternoon.
Many thanks for your comment.
After analysing your inputs, we can elaborate as follows: 

The ESCO classification reused/is based on the ISCO classification. Therefore, the first four levels are coming from there and are written using upper-case. The fifth level is ESCO occupations, in which labels are written in lower-case except if the language of the translation does not allow the lower-case format. 
Kind Regards, 
The ESPD team.
