### ISSUE TITLE
Part VI: Concluding statements

### ISSUE THREAD

**Issue by rantati7** [OP-TED/ESPD-EDM#35]
**"The undersigned formally declare..."**

There is no place, nor need to sign anything. Could the wording be changed?

if the text stays as it is CA needs to insert its name in this section!

Better option: 

The economic operator formally declares that the information stated under Parts II - V above is accurate and correct and that it has been set out in full awareness of the consequences of serious misrepresentation.

The exonomic operator formally declare to be able, upon request and without delay, to provide the certificates and other forms of documentary evidence referred to, except where:

a) The contracting authority or contracting entity has the possibility of obtaining the supporting documentation concerned directly by accessing a national database in any Member State that is available free of charge (on condition that the economic operator has provided the necessary information (web address, issuing authority or body, precise reference of the documentation) allowing the contracting authority or contracting entity to do so. Where required, this must be accompanied by the relevant consent to such access), or

b) As of 18 October 2018 at the latest (depending on the national implementation of the second subparagraph of Article 59(5) of Directive 2014/24/EU), the contracting authority or contracting entity already possesses the documentation concerned.

The economic operator formally consent to the contracting authority or contracting entity as set out in Part I, Section A, gaining access to documents supporting the information, which has been provided in this European Single Procurement Document for the purposes of this procurement procedure:"

Alternatively, the text could say I / We.

**Comment by ec-mcs** [comment]
This issue can be closed. It will be upated in the ESPD service
https://github.com/ESPD/ESPD-Service/issues/167
