### ISSUE TITLE
Question regarding national sub-criteria #interproc

### ISSUE THREAD

**Issue by naerp** [OP-TED/ESPD-EDM#352]
Hello all,

We are implementing ESPD-EDM v3, based on our previous implementation of ESPD-EDM v2.
Despite there is no change in the taxonomy from v2 to v3, we have a structural doubt we need to clarify, regarding how we should interpret the subcriterion, mainly in Exclusion Grounds.
Right now, for each criterion, we show the standard text of the criterion description and we get from eCertis eventual additional information for a national sub-criterion associated with the criterion, but we have just one question to the EO, to state if he fulfils the criterion or not.
Looking in more detail at the taxonomy Excel file, we realize that the Sub-Criterion itself has an "INDICATOR" question associated, independent from the Criterion "INDICATOR" question (see the example below).
![image](https://user-images.githubusercontent.com/38315856/201316147-46183071-4ebd-4ac4-b432-00360e2081f4.png)

When discussing this with other members of the Interproc project, I was alerted to the fact that, despite in the mockups there is only one question, there is a note stating that it was a simplification, where it was assumed that a "Yes" to the EU criterion meant also a "Yes" to the national criterion. Also in the "Requirement" Tech Handbook definition, it is stated they are independent.
![image](https://user-images.githubusercontent.com/38315856/201316242-8c1ad617-287a-41b5-985c-d30f843df228.png)
![image](https://user-images.githubusercontent.com/38315856/201316515-8ba0e0ae-3cd2-412b-984d-acc621c5daca.png)

So, just to be clear and understand if we need to change it:
a) If we have a national sub-criterion associated with an EU criterion, in practice this means that the EO will need to be able to answer to BOTH the EU criterion and national sub-criterion in separate and be able to provide separate evidences for each of them?
b) Does the answer to a) changes depending on being an Exclusion Ground Criterion or a Selection Criterion?
c) In case of an affirmative answer to a) and negative to b), a national sub-criterion for exclusion grounds is also mandatory like the EU criterion it is associated with (meaning the CA/CE needs to ask always for them)? 

Thank you in advance on your time to analyze this issue and answering to it.

**Comment by konstantinosraptis91** [comment]
This is a critical issue, and the usage of national criteria should be explained more thoroughly in the technical handbook. In my understanding, based on the NOTE from the technical handbook that clarifies that (the EO) by answering "YES" to an EU criterion, is like also automatically answering "YES" to all the corresponding national criteria of that EU criterion means that displaying the national criteria to the EO can be omitted. But this assumption/understanding does not fit with the Requirement Nuno has posted above that states that the EO will have to respond "YES" or "NO" to each national criterion. I see the wording there is very carefully selected because it says "in the ESPD Response document" and the Requirement avoids mentioning that this has to be an option that the EO user must have during the ESPD Response creation that has to be filled in the user interface.

**Comment by Nikanoras** [comment]
Would be great to get an answer to this question ASAP, as we are also working on this now.

**Comment by hricolor** [comment]
Good afternoon,
Many thanks for all your comments.

After reading your comments, the subcriterion is mainly to be used for the Purely National EG where the link with eCertis is made. Here @ec-mcs can add additional and useful information.
 
For other criteria (EG or SC), additional information regarding the national context can be provided as context. However, national criteria are not foreseen as it would break the mapping between the ESPD and eCertis.
 
However, we are going to update the documentation to ensure that the message is clear and therefore, it is helpful for implementation.
 
Kind Regards,
The ESPD Team

**Comment by naerp** [comment]
Good afternoon. Thank you for your answer.
To make sure there are no doubts, since the word MAINLY is subject to interpretations, should we can assume that ONLY inside the Purely National Exclusion Grounds we will receive national subcriteria which needs to be answered by Economic Operators and NEVER inside any of the other EG and SC?

**Comment by acolomer** [comment]
Good morning,
As mentioned, we updated the documentation in version 3.1.0 to ensure that everything is clear and therefore, that documentation is helpful for implementation (https://docs.ted.europa.eu/ESPD-EDM/latest/xml_technical_handbook.html#business-rules-guide).
Regarding your last question, the asnwer is yes, you can assume that ONLY inside the Purely National Exclusion Grounds we will receive national subcriteria which needs to be answered by Economic Operators and NEVER inside any of the other EG and SC.
Kind regards,
The ESPD Team
