### ISSUE TITLE
Regarding the translations for criteria #interproc

### ISSUE THREAD

**Issue by Nikanoras** [OP-TED/ESPD-EDM#355]
Hello,
As I understand, one of eCertis functionalities is to serve translations for criteria. At the moment, there's only translations in eCertis for criteria informational structure, like name, description, etc. but there's no translations for properties. Also, in eCertis there're no translations for "other" criteria.

1. Where can we find translations for properties? Or should we translate them ourselves? 
2. Where to find translations for "other' criteria?

**Comment by Nikanoras** [comment]
Also, to my knowledge there was a translation file for version 2.x of ESPD. Will there be for version 3?

**Comment by acolomer** [comment]
Good morning,
Thank you very much for your comments.
The reason why there is no translation in eCertis for properties and for "other" criteria is because they are not actual criteria but additional information instead.
We will provide a translation file as soon as possible.
Kind regards,
The ESPD Team

**Comment by acolomer** [comment]
Good morning,
The criteria will be translated in the Authority Table in EU Vocabularies when the concepts are updated in agreement with eCertis.
Could you please clearly identify what are the properties you are referring to? Perhaps you can provide some examples and a screenshot?
Kind regards,
The ESPD Team

**Comment by Nikanoras** [comment]
Hello,
The description column in taxonomy for questions, question goups/subgroups, requirement requirement groups/subgroups.
![image](https://user-images.githubusercontent.com/37303011/213653240-9894e13a-dfe8-4765-b163-af52c3543100.png)

**Comment by Nikanoras** [comment]
For all criteria, not only other criteria. In version 2 there was a file with all translations for these descriptions.

**Comment by dragos-eu** [comment]
Hello @Nikanoras,

The Publications Office does not provide the translations. Our colleagues from DG Grow will deal with the ticket.

Kind regards,
ESPD Team
