### ISSUE TITLE
Question regarding the procurement project description #interproc

### ISSUE THREAD

**Issue by konstantinosraptis91** [OP-TED/ESPD-EDM#357]
Hello ESPD team,

I am reviewing the **cac:procurementProject/cbc:Description** element and I am wondering if its value must be the same with **cac:AdditionalDocumentReference/cbc:Description[0]** in cases where the procurement procedure is above the threshold and AdditionalDocumentReference points to the contract notice published on TED.

**Comment by hricolor** [comment]
Good morning,
Many thanks for your comment.

After reviewing your comment, our approach is that for those procurement procedures above the threshold the information is referring to the same source and information.

The 'cac:procurementProject/cbc:description' was updated in the last major release to be aligned with eForms. In this sense, the documentation should refer as well in the 'cac:AdditionalDocumentReference/cbc:Description' that when the procedure is above the threshold, the information shall come from eForms.

Kind Regards,
The ESPD Team

**Comment by acolomer** [comment]
Good afternoon,
Thank you very much for your comments.
We will now close the issue since clarification has been provided in the previous comment, we can reopen it if necessary in case further discussion is needed.
Kind regards,
The ESPD Team
