### ISSUE TITLE
Question regarding mandatory EG #interproc

### ISSUE THREAD

**Issue by Nikanoras** [OP-TED/ESPD-EDM#358]
Hi,
We have uncertainties regarding the validation of exclusion ground mandatory to have criteria. In the validation rules for ESPD Request it's stated that's mandatory to have Section A and B of EG. 
https://github.com/OP-TED/ESPD-EDM/blob/e9d9972cb12b6f3f42e5d5ab62bda9a705d4a9aa/validation/ESPDRequest/sch/03-ESPD-req-criterion-br.sch#L21-L44

Could you clarify if only Section A and B of EG grounds are mandatory or all EG grounds, except purely national EG, are mandatory in ESPD Request XML?

**Comment by mc-ec** [comment]
Hi, under the classical public procurement Directive 2014/24/EU it is indeed mandatory to have always section A and B mandatory. Section C and D are facultative. For other Directives this might be different. In the coming year eCertis and ESPD will be getting closer and then the information, which criteria are mandatory under which law can be retrieved from eCertis.
I hope that this answers your question. The issue will be closed. Feel free, if you have additional questions on this issue.
Best MC

**Comment by acolomer** [comment]
Good afternoon,
Thank you very much for your comments.
We will now close the issue since clarification has been provided in the previous comment, we can reopen it if necessary in case  further discussion is needed.
Kind regards,
The ESPD Team
