### ISSUE TITLE
ESPD alignment with TED notices

### ISSUE THREAD

**Issue by rantati7** [OP-TED/ESPD-EDM#36]
In TED notices there is Section III: Legal, economic and financial and technical information. 

This information is actually in ESPD. With self-contained ESPD section III would need be aligned with TED. It is not very useful to fill in the same information twice. This also increases the risk of having discrepancies between TED notices and the information contained in ESPD.

**Comment by lauramrtn** [comment]
As the ESPD is not self-contained at the moment, we (the Scottish Government) have been directing buyers to use this section to state their minimum standards / criteria to allow suppliers to answer the generic questions in the ESPD.  We recommend to buyers that they should put the ESPD question number beside the criteria to make it easier for suppliers to answer the correct ESPD question.  

I agree that when the ESPD is self-contained that there is a risk that discrepancies occur between both if the buyer think they need to fill in the same information twice.

Due to the limited number of characters available in the Section III fields, some of our buyers have struggled to fit all their criteria into these fields and have had to add further information as a separate attachment.

**Comment by rantati7** [comment]
We are doing it the other way. We tell CAs to put in TED Section III only "see section X in Hanki -service" (name of our eTendering service). We have currenty a temporary ESPD in the eTendering system where CA can insert the minimum requirements. (i.e. we already have a temporary solution for self-contained ESPD and we are using it.. or actually those CAs who are already using our national  eTendering are using also the temporary ESPD).

**Comment by ESPD** [comment]
We are currently working on the next phase of standard forms. There the idea is to provide an additional option like "The conditions are only in the European Single Procurement Document (ESPD)".

**Comment by lauramrtn** [comment]
Unfortunately at the moment our system does not allow us to add the requirements along side the ESPD questions.  Hopefully as the data model develops this is something we will be able to build into our systems as I think this would be really helpful to EOs.  

I think the idea of an additional option in the notice would be helpful once the ESPD is fully self contained.

**Comment by paulakeen** [comment]
Please find below what was commented about this issue in the discussion group (22/03/2017):

Anne Katrine Mortensen, DK: copy same text from one to the other

Marit Lysemose Thomsen, Mercell, DK: ESPD is part of notice

Marc-Christopher SCHMIDT: 1 "copy" part III and Part IV into notice

Marc-Christopher SCHMIDT: 2 link from notice to ESPD

John Degiorgio: I believe that a no reply should disqualify the EO from tendering

Marit Lysemose Thomsen, Mercell, DK: Why not merge entirely?

Jose Luis Cueva - Spain: The Notice culd be just a by-product of the ESPD.

John Degiorgio: No need for further info. The simpler the better

Michaël De Winne / e-Proc Belgium: I would prefer option 2, it emphasizes the value of the espd as the selection/exclusion doc

Jose Luis Cueva - Spain: CN must make public the info parts required for searching and selecting.  Some parts of the ESPD cannot be relevant to the CN, but the ESPD should have all info.

John Degiorgio: Marc we have to remove unnecessary info 

Anne Katrine Mortensen, DK: Difficult to choose as I haven´t seen both possibilites.  But the simpler the better for all parties.

Jose Luis Cueva - Spain: Single base document, two "renderizations"

John Degiorgio: The data "if not" ...

Marit Lysemose Thomsen, Mercell, DK: yes Jose :-)

Jose Luis Cueva - Spain: Either not all info in the ESPD is relevant to the CN (so CN is a partt of ESPD) or both c an be the same

Marc-Christopher SCHMIDT: P1 (CN), P2 (EO), P3 (Excl), P4 (Sel), P5 (EO), P6 (EO)

Enric Staromiejski (GROW): if we want a true self-contained ESPD the CN should take the information from the ESPD

Enric Staromiejski (GROW): @JLC:+1

Enric Staromiejski (GROW): We should depict the call-for-tender preparation Value Chain Actions and the Information Life Cycle well

Enric Staromiejski (GROW): to make this understandable

**Comment by ec-mcs** [comment]
We plan to provide the possibility to allow p III and p IV to be copied into the notice itself (in the new forms). This will be discussed in the ESWG. So let's close this for the time being.
