### ISSUE TITLE
Question regarding EconomicOperatorSize code list #interproc

### ISSUE THREAD

**Issue by Nikanoras** [OP-TED/ESPD-EDM#361]
Hi,
I'm trying to understand in what case EO will select the first option, **micro, small or medium**, but I can't think of a case. If the first option contains option 2, option 3 and option 4, what's the point of having them as separate?

**Comment by mc-ec** [comment]
Hi, this field is used for statistical purposes. In the new eForms, the public buyer can indicate for bidders not only, if they are an SME but also if they are micro, small or medium. Therefore to use this also in the ESPD makes sense. It helps the buyer to select the approapriate entry. 
I will close this issue. If you have further questions please feel free to open it again.
MC

**Comment by acolomer** [comment]
Good afternoon,
Thank you very much for your comments.
We will now close the issue since clarification has been provided in the previous comment, we can reopen it if necessary in case  further discussion is needed.
Kind regards,
The ESPD Team
