### ISSUE TITLE
SC-General_Yearly_Turnover #interproc 

### ISSUE THREAD

**Issue by af0rte** [OP-TED/ESPD-EDM#365]
In the Selection Criterion in the group "SC-General_Yearly_Turnover", why the question 7458d42a-e581-4640-9283-34ceb3ad4345 are repetead,it´s error?

![Captura de ecrã 2022-12-20 154239](https://user-images.githubusercontent.com/36008040/208708076-7820a7f4-055f-4e2a-8ca5-f2027a4e7d80.png)

**Comment by acolomer** [comment]
Good morning,
Thank you very much for your comment.
We have reviewed it in detail and the conclusion is that this is not an error, since the structure behind these IDs is exactly the same, and therefore it is correct that the same ID is used. 
Kind regards,
The ESPD Team
