### ISSUE TITLE
Typo's in taxonomy #interproc

### ISSUE THREAD

**Issue by Nikanoras** [OP-TED/ESPD-EDM#368]
Hi,
As we are looking through the taxonomy we find a lot of typo's in descriptions of criteria and other places, like double spaces `"  "` between words, duplicated words like `"or  or"`. 
e.g. `"finan-rat"` criterion description: `Concerning the financial ratios  specified in the relevant notice, the in the ESPD, the relevant notice or  or the ESPD, the economic operator declares that the actual values for the required ratios are as follows:`

Could you check the spelling and fix the issues?

Nikanoras

**Comment by acolomer** [comment]
Good morning,
Thank you very much for your comment.
We will provide a corrected version of the excel file as soon as possible and let you know when it is available.
Kind regards,
The ESPD Team

**Comment by ghost** [comment]
Good afternoon,

the typo mentioned in this issue for the description in criterion 34 (financial ratios) is already fixed and available [here](https://github.com/OP-TED/ESPD-EDM/blob/master/codelists/ESPD-criterion.xlsx).

A deeper analysis in typos and spelling issues will be performed, fixed and included in the next ESPD release.

Kind Regards,
The ESPD Team.

**Comment by konstantinosraptis91** [comment]
Hi ESPD team,

I was checking the version 3.2.0 taxonomy, and I detected a remaining "or  or " typo. It is in "spec-year-to" criterion’s description. I don't know if this has already been reported, so to ensure that it has been communicated to you, I write it as a comment here.

![image](https://github.com/OP-TED/ESPD-EDM/assets/15834471/6c464242-fa04-4380-b2c5-76909d83eaf8)

Kind regards,
Konstantinos

**Comment by arillpa** [comment]
Dear @konstantinosraptis91 

thank you for your remark.
We will update the typos Taxonomy and release it with the next version of EDM.
We will present this in the OUC on 29 June

Kind regards
ESPD Team
