### ISSUE TITLE
Missing cardinalities values in ESPD-Criterion.xlsx v3.1.0 #interproc

### ISSUE THREAD

**Issue by konstantinosraptis91** [OP-TED/ESPD-EDM#374]
Hello ESPD team,

It seems that this is not a new issue because there were missing cardinalities also in the previous 3.x.x versions, but I noticed that the issue persists. I can count many cases in different criteria where question subgroups exist, and their relevant cardinality has been omitted in ESPD-criterion.xlsx (former Criteria Taxonomy excel sheet).

A list of the criteria that includes QSGs and the cardinality value is missing:

QSG[ID='0e50931d-4d39-4f1d-9fdc-b2cf16c0807a']

- 25 prof-regist
- 26 trade-regist
- 27 autorisation
- 28 membership
- 29 gen-year-to
- 30 aver-year-to
- 31 spec-aver-to
- 32 spec-year-to
- 34 finan-rat
- 35 indem-insu
- 40 qual-cont-tech
- 41 work-tech
- 42 qual-facil
- 43 research-fac
- 44 chain-manage
- 45 envir-measure
- 46 tech-equip
- 47 qualification
- 48 spec-req-check
- 49 manage-staff
- 50 year-manpower
- 51 suncont-port
- 52 wo-autent
- 53 w-autent
- 54 qa-certif-inst
- 55 qu-certif-indep
- 56 envir-certif-indep

QSG[ID='9b3a04ff-e36d-4d4f-b47c-82ad402b9b02']

- 36 finan-requ

QSG[ID='5fe93344-ed91-4f97-bcab-b6720a131798']

- 36 finan-requ

I have also detected some other "cardinality missing" issues

CRITERION 24 [element code = 'nati-ground']

<img width="1073" alt="Στιγμιότυπο οθόνης 2023-01-19, 1 49 19 μμ" src="https://user-images.githubusercontent.com/15834471/213435189-86e57426-cea8-4e48-85bc-6423a742ed6e.png">

**Comment by ghost** [comment]
Good afternoon,
missed cardinalities have been fixed. The corrected version of the criterion excel file is available [here](https://github.com/OP-TED/ESPD-EDM/blob/master/codelists/ESPD-criterion.xlsx) and they will be included in the next patch-release.

Kind Regards,
The ESPD Team.
