### ISSUE TITLE
Pending fixed issues and v3.1.0 release #interproc

### ISSUE THREAD

**Issue by konstantinosraptis91** [OP-TED/ESPD-EDM#377]
Hello ESPD team,

It seems that quite a number of issues have been fixed but have been omitted to be merged with the v3.1.0 release, even though some of them are listed in the release notes. For instance, the fixes added in criterion-evolution-new branch #368, #369, #371. In the context of the InterProc project, we decided to implement the v3.1.0 of ESPD-EDM because it would include fixes for issues that were issued, discussed, and addressed during the previous period after the release of ESPD-EDM v3.0.1. Having that in mind, we thought the ESPD-EDM v3.1.0 would be "stable" and "completed". We noticed from an answer to #371 that you plan to include those fixes in the next major release (v4.0.0), but those fixes were meant to merge with ESPD v3. Therefore, it would be beneficial for all the pending fixes to be grouped and released in a minor ESPD-EDM version, e.g., v3.1.1. Not including those fixes in a specific v3 release indicates we cannot currently adopt them in our implementations because that will break interoperability. Finally, releasing them alongside v4.0.0 implies that in order to adopt them, we will have to comply and adopt everything that a major ESPD-EDM release brings (like the "UUID issue").

**Comment by acolomer** [comment]
Good morning,
Thank you very much for your comment.
We are working on a patch release that will include the 3 issues you mention. In the meantime, they have already been solved and are implemented in the masterbranch, and no further changes have been made in the masterbranch since v3.1.0.
Kind regards,
The ESPD Team
