### ISSUE TITLE
Question regarding the mandatory presence of at least one property in property groups #interproc

### ISSUE THREAD

**Issue by konstantinosraptis91** [OP-TED/ESPD-EDM#379]
Hello ESPD team,

There is a business rule in the technical handbook under [3.1 General Behavior](https://docs.ted.europa.eu/ESPD-EDM/latest/xml_technical_handbook.html#_general_behavior) that states that **One group of properties must always specify at least one 'property'**. I checked the taxonomy and noticed cases where this rule does not apply. For instance,
in criterion 36 (finan-requ), the outer REQUIREMENT_GROUP has an optional internal CAPTION, which means that there is a case where it could be a property group in an XML file (the outer REQUIREMENT_GROUP in this case) that doesn't have a property inside. What is the actual meaning of that business rule?

![Στιγμιότυπο οθόνης 2023-02-07, 1 53 12 μμ](https://user-images.githubusercontent.com/15834471/217238010-1d247e6e-4b6b-40e7-b173-67f00056a6e1.png)

**Comment by acolomer** [comment]
Good morning,
We will discuss this issue in the next OUC meeting, scheduled for 23rd of February.
Kind regards,
The ESPD Team

**Comment by acolomer** [comment]
Good morning,
As discussed in the OUC meeting of 23rd of February:
- It is proposed that CAPTION elements within question groups are removed.
- As Italy is currently using this CAPTION element in Purely National Exclusion Grounds, it is agreed that, for the moment, the CAPTION element will be kept within this criterion (in the future, Purely National Exclusion Grounds should be retrieved from eCertis and this will be reviewed).
- All other  CAPTION elements within question groups will be removed unless there is any other case where CAPTION elements within question groups are being used, which has not been reported so far.
This issue will be discussed again in the next OUC meeting, scheduled for 23rd of March, to come to a final agreement.
Kind regards,
The ESPD Team

**Comment by pascalinelaur** [comment]
Hello, 

As discussed in the lest OUC meeting in March 2023, it is agreed that all CAPTION elements will be kept in the taxonomy for the time being. This GitHub issue will not be included in ESPD-EDM v3.2.0, and it will be analysed in detailed by the ESPD Team and discussed again with the OUC in a future meeting. 

KR, 
The ESPD team.

**Comment by pascalinelaur** [comment]
Hello,

After internal discussion it has been agreed to wait before further analysis until eCertis updates and a better link between eForms and ESPD. 

KR, 
The ESPD Team.

**Comment by dragos-eu** [comment]
Hello @konstantinosraptis91,

The solution was provided and implemented in ESPD-EDM v4.0.0 (https://github.com/OP-TED/ESPD-EDM/releases/tag/v4.0.0).

Kind regards,
ESPD Team
