### ISSUE TITLE
Defining attributes in the adoc main document

### ISSUE THREAD

**Issue by klakegg** [OP-TED/ESPD-EDM#38]
Some attributes are set in the pom.xml only, forcing use of Maven to build the documentation as intended. Please move those attributes to index.adoc.

**Comment by paulakeen** [comment]
Dear klakegg, 

could you please specify which are the exact attributes you need us to move?

Thank you so much.

**Comment by klakegg** [comment]
https://github.com/ESPD/ESPD-EDM/blob/master/docs/pom.xml#L30

**Comment by virgiliu-ratoi-ec-ext** [comment]
I think you can add them inside the adoc file like this:
`:imagesdir: ./images
:icons: font
:sectanchors: true
:toc: left
:idseparator: -
idprefix:
:sectlinks:true
docinfo1:true`

**Comment by paulakeen** [comment]
Can we close this?

**Comment by klakegg** [comment]
No commit is linked to this issue. Is it fixed?

**Comment by ec-mcs** [comment]
Virgiliu, can we close this one?

**Comment by paulakeen** [comment]
Solved in the latest master branch of version 2.0.0.
