### ISSUE TITLE
Question regarding the correct listID values #interproc

### ISSUE THREAD

**Issue by konstantinosraptis91** [OP-TED/ESPD-EDM#380]
Hello ESPD team,

It seems that some of the examples (snippets) that are included in the technical handbook have different listID attribute values for certain elements compared to the respective Schematron rules. For instance, according to the technical handbook, the correct @listID value for cbc:PropertyGroupType is "property-group-type" 

![Στιγμιότυπο οθόνης 2023-02-20, 4 46 25 μμ](https://user-images.githubusercontent.com/15834471/220137544-607d4bd8-26f2-4677-9aa3-7650e07706c4.png)

![Στιγμιότυπο οθόνης 2023-02-20, 4 46 56 μμ](https://user-images.githubusercontent.com/15834471/220137669-152d7705-8ab9-46d2-8d76-e736aa9312c5.png)

But the relevant Schematron rule demands the @listID value for this element to be equal to "PropertyGroupType". Can you clarify please what are the correct listID values for those elements?

**Comment by konstantinosraptis91** [comment]
Following the discussion we had in today's OUC (OUC 23-02-2023) considering this issue, I would like to ask because I am unsure if I got it right if this issue will be addressed within the v3.2.0 or later with the v4.0.0 release.

**Comment by ghost** [comment]
Good afternoon, 

this issue will be addressed with the v4.0.0 release since the scope for v3.2.0 was already closed some weeks ago and this release is about to be published shortly (pending to fix some technical issues).

We are analyzing these inconsistencies in the codelist elements and will provide more information here after the conclusion of the analysis.

Kind Regards,
The ESPD Team.

**Comment by konstantinosraptis91** [comment]
Hello @delgajc 

Thank you for your answer. Can you please provide us with a list containing the exact listID values per codelist expected in version 3.1.0 and 3.2.0 to avoid further misconceptions? It would also be nice if you could update the technical handbook because, as it is right now, it is not clear what are the correct values.

**Comment by ghost** [comment]
Dear Konstantinos,

please find below a table with the right listID values per codelist expected in version 3.1.0 and 3.2.0. We will fix the errors in the technical handbook and in the schematron files for 3.2.0, but bear in mind that currently the codelists maintained by ESPD Team are not validating the listID (this attribute is not included in the genericode files). This validation will be included in a future release.

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/jdelgcab/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/jdelgcab/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



ShortName | ListID | Maintainer
-- | -- | --
AccessRight | access-right | EU   Vocabularies
BooleanGUIControlType | boolean-gui-control-type | ESPD Team
Country | country | EU   Vocabularies
Criterion | criterion | EU   Vocabularies
CriterionElementType | criterion-element-type | ESPD Team
Currency | currency | EU   Vocabularies
DocRefContentType | docrefcontent-type | EU   Vocabularies
EconomicOperatorSize | economic-operator-size | EU   Vocabularies
EOIDType | eoid-type | ESPD Team
EoRoleType | eo-role-type | EU   Vocabularies
FinancialRatioType | financial-ratio-type | ESPD Team
Language | language | EU   Vocabularies
Occupation | occupation | ESPD Team
ProfileExecutionID | profile-execution-id | ESPD Team
PropertyGroupType | property-group-type | ESPD Team
ResponseDataType | response-data-type | ESPD Team



</body>

</html>

Kind Regards,
The ESPD Team.

**Comment by konstantinosraptis91** [comment]
Thank you! @delgajc

**Comment by Nikanoras** [comment]
What about ProcedureType?

**Comment by ghost** [comment]
Dear @konstantinosraptis91 

there were some mistakes in the table I previously sent. Please find below the correct listID values for all the codelists:

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/jdelgcab/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/jdelgcab/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">



</head>

</html>

We are working to fix all the discrepancies in the documentation and ESPD artifacts to be included in next release 3.2.0.

Dear @Nikanoras, ProcedureType is an obsolete codelist no longer maintained in ESPD in versions 3.x.x.

Kind regards,
The ESPD Team.














































































<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/jdelgcab/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<link rel=themeData
href="file:///C:/Users/jdelgcab/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/jdelgcab/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-GB link="#0563C1" vlink="#954F72" style='tab-interval:36.0pt;
word-wrap:break-word'>




ShortName | ListID | Maintainer
-- | -- | --
AccessRight | http://publications.europa.eu/resource/authority/access-right | EU Vocabularies
BooleanGUIControlType | boolean-gui-control-type | ESPD Team
Country | http://publications.europa.eu/resource/authority/country | EU Vocabularies
Criterion | http://publications.europa.eu/resource/authority/criterion | EU Vocabularies
CriterionElementType | criterion-element-type | ESPD Team
Currency | http://publications.europa.eu/resource/authority/currency | EU Vocabularies
DocRefContentType | http://publications.europa.eu/resource/authority/docrefcontent-type | EU Vocabularies
EconomicOperatorSize | http://publications.europa.eu/resource/authority/economic-operator-size | EU Vocabularies
EOIDType | eoid-type | ESPD Team
EoRoleType | http://publications.europa.eu/resource/authority/eo-role-type | EU Vocabularies
FinancialRatioType | financial-ratio-type | ESPD Team
Language | http://publications.europa.eu/resource/authority/language | EU Vocabularies
Occupation | http://publications.europa.eu/resource/authority/occupation | EU Vocabularies
ProfileExecutionID | profile-execution-id | ESPD Team
PropertyGroupType | property-group-type | ESPD Team
ResponseDataType | response-data-type | ESPD Team




</body>

</html>

**Comment by pascalinelaur** [comment]
Hello @Nikanoras , 

Related the codelist "ProcedureType", the proper name is actually "ProcurementProcedureType" from the EU Vocabularies. 
However, this codelist is not maintain in the ESPD project because the data can be retrieved from the eForms and hence there is no use-context for the ESPD . 

For the next release, you will find the element "ProcedureCode" with the attribute "listID" assigned to a Dummy value. You can already check this in the master branch, folder [xml-examples](https://github.com/OP-TED/ESPD-EDM/tree/master/xml-examples).

Kind regards, 
The ESPD Team.

**Comment by pascalinelaur** [comment]
Hello, 

The ESPD version 3.2.0 has been released with a broader solution for this github issue. We reviewed all the codelists listID values in XSL file, generic code files, XSLT files, XML files and Schematron files as well. We also updated the listID values in the online documentation. 

With all that being said, this issue is resolved and closed. 

Kind regards, 
The ESPD Team.
