### ISSUE TITLE
Triggerable requirement subgroup XML export #interproc

### ISSUE THREAD

**Issue by Nikanoras** [OP-TED/ESPD-EDM#384]
Hi,

We have a "finan-requ" criterion. In this criterion we have a requirement of type CODE_BOOLEAN "Select the type of requirement". Then we have two requirement subgroups (**subgroup1** ca15c15f-110e-4a10-8d6e-5e41cf5f9098,  **subgroup2** cc96aa19-a0be-4409-af58-ff3f3812741b) which are triggered based on the answer from previously mentioned requirement. My question is, when we export ESPD Request XML should we include both requirement subgroups(subgroup1, subgroup2) or only the triggered one?

**Comment by pascalinelaur** [comment]
Hello @Nikanoras ,

Thank you for your question.

This github issue is related to criterion C36 SC finan-requ .

If the contracting authority selected a given "Requirement Subgroup", then only this subgroup should appear in the published Request and the Related Responses.

The core initial Request is not filled in by a contracting authority and hence not "published". It is the raw structure of all Requests and will then always include all the initial elements, meaning here the 2 requirements subgroups.

The published Request is customized by the contacting authority. He/She might select, remove or provide values for various elements and by doing so, re-defines the final structure of the Request that will be provided for a given procurement to the economic operators to tender to.

Kind regards, 
The ESPD Team.

**Comment by Nikanoras** [comment]
Thank you for the answer!

**Comment by pascalinelaur** [comment]
As we have no more comments, we proceed to close this issue.
