### ISSUE TITLE
Can the evidence group or subgroup be dropped to follow the ESPD regulation? 

### ISSUE THREAD

**Issue by pascalinelaur** [OP-TED/ESPD-EDM#386]
For some criteria, the regulation does not require an evidence to be provided. Hence, Italy is proposing that the evidence group could be removed in the taxonomy criterion excel file for consistency purpose with the regulation.

The ESPD team needs to check the regulation to identify all the criteria that could be updated. For that purpose, Italy has already provided an excel file with a list of criteria. These criteria have to be checked with the regulation to confirm the deletion of the evidence group.

Below is an image of what the update could look like. 

![Evidence_group_drop](https://github.com/OP-TED/ESPD-EDM/assets/102807568/ded37e5f-21be-4280-a418-606b7f120de8)

**Comment by dragos-eu** [comment]
Dear User Community,

The proposed solution is to set the cardinality for such **QUESTION_GROUP** to **0..1**, making it optional. This will accommodate both situations: 
- when the EVIDENCE must be provided or 
- when the EVIDENCE is not required by the ESPD Service implementer, according to the national legislation.

This solution is valid not only for C9, this was used to showcase the user business requirement.

We also recommend to use the **SUBCRITERION** and **LEGISLATION** to accommodate national specific legislation and supplementary conditions. The **SUBCRITERION** is flexible as structure and allows Users to customize it as required.

For further information do not hesitate contact us.

Kind regards,
ESPD Team
