### ISSUE TITLE
Field for EOs role

### ISSUE THREAD

**Issue by rantati7** [OP-TED/ESPD-EDM#39]
EO can participate in a tender basically in four roles: 
1. As sole tenderer
2. As a member of a group of companies
3. As a subcontractor whose resources the main tenderer uses to fulfil the minimun requirement
4. As a subcontactor whose resources the main tenderer is NOT using to fulfil the mimimun criteria

Even though there is space for the EO to state in which role it takes part in the tender, in practice the answers are varied and it's sometimes impossible to tell what what role each EO takes part in tender.

Could there be a ready made alternatives? The four above mentioned and a fifth one: "other... please specify".

**Comment by lauramrtn** [comment]
I agree, we think it would be good to understand this information in a more systematic format.

**Comment by paulakeen** [comment]
The element ESPDResponseType/espd-cac:EconomicOperatorParty/espd-cbc:EconomicOperatorRoleCode aims precisely at the specification of the role of the Tenderer. The codelist we proposed to use is the one defined by CEN/BII Workshop 3 (see attached image). Please see the file "ESPD-CodeLists-V1.0.xls" for the rest of CodeLists used in ESPD-EDM v1.0.2.

If you consider it necessary we can extended the list of roles and put it forward for its normalisation/standardisation throught the CEN's PC440 task-force.

![image](https://cloud.githubusercontent.com/assets/16134316/19034707/4a6d955e-8965-11e6-9d0f-b217b252a082.png)

**Comment by paulakeen** [comment]
Duplicate. Please see issue #57.
