### ISSUE TITLE
id scheda nel crea appalto

### ISSUE THREAD

**Issue by spagne** [OP-TED/ESPD-EDM#391]
Il servizio crea-appalto nell'aggiornamento dell'08/06 presenta come dato di input l'id scheda
Cosa significa? Che per creare l'id appalto dobbiamo prima creare la scheda? Fino ad ora non c'era bisogno di questo step poiché ci era stato spiegato che avremmo passato i dati della scheda Anac direttamente su crea-appalto (o al limite sul modifica-appalto).

**Comment by arillpa** [comment]
Dear @spagne,

our colleagues from Italy have confirmed that the issues opened by you should be addressed to them.

The reference GitHub for ANAC's eForms platform and eSender is the following:
[https://github.com/anticorruzione/anticorruzione.github.io/blob/main/NPA.yaml](https://urldefense.com/v3/__https:/github.com/anticorruzione/anticorruzione.github.io/blob/main/NPA.yaml__;!!DOxrgLBm!Etv8hitXvMVwFSW-DB6lynEfREnGyboK7nNq3pOysXEkaIlqK9Xiaszk_T1RpxWCdXzoCvzeCwLhLwO60hWmTxydZ3JzjmHikVVeyiWyhdzCfWOm$)
Could you please put your questions in that GitHub?

We proceed to close this issue.

Kind regards
The ESPD-EDM team
