### ISSUE TITLE
flusso orchestratore

### ISSUE THREAD

**Issue by spagne** [OP-TED/ESPD-EDM#392]
Il flusso definito dall’orchestratore è obbligatorio? Ad esempio, creando un appalto con la P1.10, posso successivamente chiamare la A29 per l’aggiudicazione o devo per forza transitare per S1 e S2?

**Comment by arillpa** [comment]
Dear @spagne,

our colleagues from Italy have confirmed that the issues opened by you should be addressed to them.

The reference GitHub for ANAC's eForms platform and eSender is the following:
[https://github.com/anticorruzione/anticorruzione.github.io/blob/main/NPA.yaml](https://urldefense.com/v3/__https:/github.com/anticorruzione/anticorruzione.github.io/blob/main/NPA.yaml__;!!DOxrgLBm!Etv8hitXvMVwFSW-DB6lynEfREnGyboK7nNq3pOysXEkaIlqK9Xiaszk_T1RpxWCdXzoCvzeCwLhLwO60hWmTxydZ3JzjmHikVVeyiWyhdzCfWOm$)
Could you please put your questions in that GitHub?

We proceed to close this issue.

Kind regards
The ESPD-EDM team
