### ISSUE TITLE
versionamento schede

### ISSUE THREAD

**Issue by spagne** [OP-TED/ESPD-EDM#393]
Quando una scheda viene aggiornata ci aspettiamo sia manutenuto il versionamento sull’orchestratore; invece, nonostante i cambiamenti avvenuti l’08/06, tutte le schede all’interno del file sono rimaste in versione 1. Non abbiamo visto un changelog, fondamentale per chi ha già iniziato a lavorare sull’implementazione.

**Comment by arillpa** [comment]
Dear @spagne,

our colleagues from Italy have confirmed that the issues opened by you should be addressed to them.

The reference GitHub for ANAC's eForms platform and eSender is the following:
[https://github.com/anticorruzione/anticorruzione.github.io/blob/main/NPA.yaml](https://urldefense.com/v3/__https:/github.com/anticorruzione/anticorruzione.github.io/blob/main/NPA.yaml__;!!DOxrgLBm!Etv8hitXvMVwFSW-DB6lynEfREnGyboK7nNq3pOysXEkaIlqK9Xiaszk_T1RpxWCdXzoCvzeCwLhLwO60hWmTxydZ3JzjmHikVVeyiWyhdzCfWOm$)
Could you please put your questions in that GitHub?

We proceed to close this issue.

Kind regards
The ESPD-EDM team
