### ISSUE TITLE
time out

### ISSUE THREAD

**Issue by spagne** [OP-TED/ESPD-EDM#396]
Quali sono i tempi di risposta massimi delle API? Inoltre quale è il tempo massimo per l’invio dei dati prima di ricevere un  408 Request Timeout  ?

**Comment by arillpa** [comment]
Dear @spagne,

our colleagues from Italy have confirmed that the issues opened by you should be addressed to them.

The reference GitHub for ANAC's eForms platform and eSender is the following:
[https://github.com/anticorruzione/anticorruzione.github.io/blob/main/NPA.yaml](https://urldefense.com/v3/__https:/github.com/anticorruzione/anticorruzione.github.io/blob/main/NPA.yaml__;!!DOxrgLBm!Etv8hitXvMVwFSW-DB6lynEfREnGyboK7nNq3pOysXEkaIlqK9Xiaszk_T1RpxWCdXzoCvzeCwLhLwO60hWmTxydZ3JzjmHikVVeyiWyhdzCfWOm$)
Could you please put your questions in that GitHub?

We proceed to close this issue.

Kind regards
The ESPD-EDM team
