### ISSUE TITLE
path orchestrazione

### ISSUE THREAD

**Issue by spagne** [OP-TED/ESPD-EDM#397]
Rispetto allo schema delle regole di orchestrazione ( documento schema-cronologia-schede.xlsx  ) quando nella colonna “schedaSuccessiva” (elenco delle schede successive ammesse o non ammesse) compaiono più schede cosa bisogna fare?

- a.	Chiamare tutte le schede elencate ? 
- b.	Chiamarne una sola ?
- c.	Da un flusso è possibile generare più flussi di uscita (colonna Q)?

- Quando una scheda successiva è identificata come “STATO FINALE” tale stato è relativo al flusso della scheda o all’intero processo ?

**Comment by arillpa** [comment]
Dear @spagne,

our colleagues from Italy have confirmed that the issues opened by you should be addressed to them.

The reference GitHub for ANAC's eForms platform and eSender is the following:
[https://github.com/anticorruzione/anticorruzione.github.io/blob/main/NPA.yaml](https://urldefense.com/v3/__https:/github.com/anticorruzione/anticorruzione.github.io/blob/main/NPA.yaml__;!!DOxrgLBm!Etv8hitXvMVwFSW-DB6lynEfREnGyboK7nNq3pOysXEkaIlqK9Xiaszk_T1RpxWCdXzoCvzeCwLhLwO60hWmTxydZ3JzjmHikVVeyiWyhdzCfWOm$)
Could you please put your questions in that GitHub?

We proceed to close this issue.

Kind regards
The ESPD-EDM team
