### ISSUE TITLE
versioning tipologiche

### ISSUE THREAD

**Issue by spagne** [OP-TED/ESPD-EDM#398]
Al fine di poter indicare nelle chiamate con le schede in input anche la loro versione,  la tipologica “codice scheda” conterrà anche  la versione ( che è campo mandatory nelle chiamate)?
a.	In alternativa dove deve essere recuperato il valore della versione di una scheda ?

**Comment by arillpa** [comment]
Dear @spagne,

our colleagues from Italy have confirmed that the issues opened by you should be addressed to them.

The reference GitHub for ANAC's eForms platform and eSender is the following:
[https://github.com/anticorruzione/anticorruzione.github.io/blob/main/NPA.yaml](https://urldefense.com/v3/__https:/github.com/anticorruzione/anticorruzione.github.io/blob/main/NPA.yaml__;!!DOxrgLBm!Etv8hitXvMVwFSW-DB6lynEfREnGyboK7nNq3pOysXEkaIlqK9Xiaszk_T1RpxWCdXzoCvzeCwLhLwO60hWmTxydZ3JzjmHikVVeyiWyhdzCfWOm$)
Could you please put your questions in that GitHub?

We proceed to close this issue.

Kind regards
The ESPD-EDM team
