### ISSUE TITLE
gestione variazione schema variazione regole orchestrazione

### ISSUE THREAD

**Issue by spagne** [OP-TED/ESPD-EDM#399]
Considerato il fatto che  lo schema delle regole di orchestrazione ( documento schema-cronologia-schede.xlsx  ) nel tempo potrebbe cambiare , potrebbe ANAC farsi carico di costruire un servizio che sia in grado di restituire i dati presenti nel  documento schema-cronologia-schede.xlsx   come output json in risposta ad una chiamata API dando un set di dati in ingresso  ( ad esempio fase,evento,schedaCodice ) ?

**Comment by arillpa** [comment]
Dear @spagne,

our colleagues from Italy have confirmed that the issues opened by you should be addressed to them.

The reference GitHub for ANAC's eForms platform and eSender is the following:
[https://github.com/anticorruzione/anticorruzione.github.io/blob/main/NPA.yaml](https://urldefense.com/v3/__https:/github.com/anticorruzione/anticorruzione.github.io/blob/main/NPA.yaml__;!!DOxrgLBm!Etv8hitXvMVwFSW-DB6lynEfREnGyboK7nNq3pOysXEkaIlqK9Xiaszk_T1RpxWCdXzoCvzeCwLhLwO60hWmTxydZ3JzjmHikVVeyiWyhdzCfWOm$)
Could you please put your questions in that GitHub?

We proceed to close this issue.

Kind regards
The ESPD-EDM team
