### ISSUE TITLE
Part III: Exclusion grounds, National exclusion grounds

### ISSUE THREAD

**Issue by rantati7** [OP-TED/ESPD-EDM#4]
CA must be able to define the purely national exclusion grounds and what CA has defined should be shown to EO for answering yes or no.

**Comment by steveP1967** [comment]
Agree, this would need to be specified at MS level.

**Comment by ec-mcs** [comment]
Likely we don't have to change the model for this, only the XML. If this is the case we would introduce this into our Christmas XML.

**Comment by ec-mcs** [comment]
**Assumption:** 
- The Member States have a defined list of the purely national exclusion grounds.
- They are all mandatory

**Proposal**
- In eCertis MS define their purely national exclusion grounds. This can be already done.
- In ESPD service we would do the following changes:
  - For a given MS all purely national exclusion grounds are shown as separate criteria 
  - The EO needs to answer them all with YES/NO
  - The EO can provide "Information is available electronically" for each of them
  - The EO can describe them if they have breached them
  - The EO can explain why they are nevertheless able to perfom the contract

**Screenshot**

![capture](https://cloud.githubusercontent.com/assets/20335285/19107150/31a65c18-8aeb-11e6-80b1-5082c93a680e.PNG)

**Comment by paulakeen** [comment]
Please find below a proposal for a solution and mock-ups regarding national exclusion grounds.

Exclusion grounds will have 3 levels: top level, EU level and national level. Therefore, all national exclusion grounds will be related to a top level (for example, "Corruption"). The ESPD will display information of all 3 levels. Information about national exclusion grounds will be retrieved from e-Certis, so all national criteria must be properly classified in e-Certis so it can be displayed in the correct part of the ESPD.
In Section D (Purely national exclusion grounds) the information displayed will be the criteria classified as “Other exclusion grounds” in e-Certis.
The EO will provide an answer at top level, that is, it will not be required to provide an answer for each national criteria. The answer provided will apply to all national criteria related to that top level.

- View of the CA (example of national information)

![mu_corruption_text_ca](https://cloud.githubusercontent.com/assets/16134316/24659943/7d8a0bd8-194e-11e7-91b6-b7429f1b8b79.png)

- View of the CA (example of purely national exclusion grounds)

![mu_purely_national_exclusion_grounds_ca](https://cloud.githubusercontent.com/assets/16134316/24659953/86858910-194e-11e7-8729-6ce6a778024a.png)

- View of the EO (example of national information)

![mu_guilty_grave_professional_misconduct_eo](https://cloud.githubusercontent.com/assets/16134316/24659966/8eac3d1e-194e-11e7-8522-9df727325451.png)

- View of the EO (example of purely national exclusion grounds)

![mu_purely_national_exclusion_grounds_eo](https://cloud.githubusercontent.com/assets/16134316/24659975/943a6e72-194e-11e7-9de5-174961ea70cd.png)

We need to discuss the following questions:

- When a CA selects an exclusion ground (top level), all related national exclusion grounds are mandatory, that is, the CA is not able to select exclusion grounds on national level?

- When a CA selects the option “Purely national exclusion grounds”, all related criteria are mandatory, that is, the CA is not able to select specific purely national exclusion grounds for a particular procedure?

**Comment by rantati7** [comment]
Quick reply to the questions:


  *   When a CA selects an exclusion ground (top level), all related national exclusion grounds are mandatory, that is, the CA is not able to select exclusion grounds on national level?

In part III all the items coming from eCertis are just to clarify the top level criteria, for example corruption - i.e. failing to meet any of those coming from eCertis will lead to exclusion. The way this is executed seems ok to me.

HOWEVER, we need to do something to the text coming from eCertis. HOw about headlining the text box as "national grounds". Also something new to be done to the txt 'no existences'. This needs to be changed to something else as an EO will be definitely confused when the text first says the criminal misconduct and right after it it says 'no evidences'. This just looks very very odd to an EO who does not understand what this 'no evidences' text means - he does not understand that this means that there are no official evidences to prove that he has not been found guilty of this misconduct!

  *   When a CA selects the option “Purely national exclusion grounds”, all related criteria are mandatory, that is, the CA is not able to select specific purely national exclusion grounds for a particular procedure?

Yes, all there are mandatory national exclusion grounds and o breach of any of those coming from eCertis is a ground for exclusion. This is at least the way it's in Finland.

The same comment on the text 'no evidences' applies to this as well.

Timo





Sent from my iPad

On 4 Apr 2017, at 16.55, paulakeen <notifications@github.com<mailto:notifications@github.com>> wrote:


Please find below a proposal for a solution and mock-ups regarding national exclusion grounds.

Exclusion grounds will have 3 levels: top level, EU level and national level. Therefore, all national exclusion grounds will be related to a top level (for example, "Corruption"). The ESPD will display information of all 3 levels. Information about national exclusion grounds will be retrieved from e-Certis, so all national criteria must be properly classified in e-Certis so it can be displayed in the correct part of the ESPD.
In Section D (Purely national exclusion grounds) the information displayed will be the criteria classified as “Other exclusion grounds” in e-Certis.
The EO will provide an answer at top level, that is, it will not be required to provide an answer for each national criteria. The answer provided will apply to all national criteria related to that top level.

  *   View of the CA (example of national information)

[mu_corruption_text_ca]<https://cloud.githubusercontent.com/assets/16134316/24659943/7d8a0bd8-194e-11e7-91b6-b7429f1b8b79.png>

  *   View of the CA (example of purely national exclusion grounds)

[mu_purely_national_exclusion_grounds_ca]<https://cloud.githubusercontent.com/assets/16134316/24659953/86858910-194e-11e7-8729-6ce6a778024a.png>

  *   View of the EO (example of national information)

[mu_guilty_grave_professional_misconduct_eo]<https://cloud.githubusercontent.com/assets/16134316/24659966/8eac3d1e-194e-11e7-8522-9df727325451.png>

  *   View of the EO (example of purely national exclusion grounds)

[mu_purely_national_exclusion_grounds_eo]<https://cloud.githubusercontent.com/assets/16134316/24659975/943a6e72-194e-11e7-9de5-174961ea70cd.png>

We need to discuss the following questions:

  *   When a CA selects an exclusion ground (top level), all related national exclusion grounds are mandatory, that is, the CA is not able to select exclusion grounds on national level?

  *   When a CA selects the option “Purely national exclusion grounds”, all related criteria are mandatory, that is, the CA is not able to select specific purely national exclusion grounds for a particular procedure?

**Comment by rantati7** [comment]
Btw... the same possibility of misunderstanding applies also to those eCertis issues where there are 'official evidences / attestations. The EO will definitely not understand if he should get those certificates already in tendering phase....

Timo

Sent from my iPad

On 4 Apr 2017, at 16.55, paulakeen <notifications@github.com<mailto:notifications@github.com>> wrote:


Please find below a proposal for a solution and mock-ups regarding national exclusion grounds.

Exclusion grounds will have 3 levels: top level, EU level and national level. Therefore, all national exclusion grounds will be related to a top level (for example, "Corruption"). The ESPD will display information of all 3 levels. Information about national exclusion grounds will be retrieved from e-Certis, so all national criteria must be properly classified in e-Certis so it can be displayed in the correct part of the ESPD.
In Section D (Purely national exclusion grounds) the information displayed will be the criteria classified as “Other exclusion grounds” in e-Certis.
The EO will provide an answer at top level, that is, it will not be required to provide an answer for each national criteria. The answer provided will apply to all national criteria related to that top level.

  *   View of the CA (example of national information)

[mu_corruption_text_ca]<https://cloud.githubusercontent.com/assets/16134316/24659943/7d8a0bd8-194e-11e7-91b6-b7429f1b8b79.png>

  *   View of the CA (example of purely national exclusion grounds)

[mu_purely_national_exclusion_grounds_ca]<https://cloud.githubusercontent.com/assets/16134316/24659953/86858910-194e-11e7-8729-6ce6a778024a.png>

  *   View of the EO (example of national information)

[mu_guilty_grave_professional_misconduct_eo]<https://cloud.githubusercontent.com/assets/16134316/24659966/8eac3d1e-194e-11e7-8522-9df727325451.png>

  *   View of the EO (example of purely national exclusion grounds)

[mu_purely_national_exclusion_grounds_eo]<https://cloud.githubusercontent.com/assets/16134316/24659975/943a6e72-194e-11e7-9de5-174961ea70cd.png>

We need to discuss the following questions:

  *   When a CA selects an exclusion ground (top level), all related national exclusion grounds are mandatory, that is, the CA is not able to select exclusion grounds on national level?

  *   When a CA selects the option “Purely national exclusion grounds”, all related criteria are mandatory, that is, the CA is not able to select specific purely national exclusion grounds for a particular procedure?

**Comment by paulakeen** [comment]
Please find below what was commented about this issue in the discussion group:

Jose Luis Cueva (Spain): It should be in eCertis

Laura Martin / Scottish Government: Yeah, I agree

Timo Rantanen / Hansel / Finland 2: I would prefer to have the yes / no next to each eCertis item.... we could ...

Jose Luis Cueva (Spain): As long as it is just click "Yes/no" the burden is minimal be it one or several

Giampaolo Sellitto 2: partecipazione in organizzazione criminale

Jose Luis Cueva (Spain): I think that article 57.4 rules here: it is the CA's country who rules here

**Comment by paulakeen** [comment]
Please find below a proposal of a mock-up for the view of the EO, where:

- The EO is able to answer YES/NO to each purely national exclusion ground;

- The text "No evidences" has been replaced by "No evidence required for this criterion".

![image](https://cloud.githubusercontent.com/assets/16134316/25128334/9fc5d696-2439-11e7-9f9e-1b609b1e8c2a.png)

**Comment by paulakeen** [comment]
Please find the details of the final decision in https://github.com/ESPD/ESPD-EDM/wiki/13.-Purely-national-exclusion-grounds
