### ISSUE TITLE
ERRORS in current ESPD: average yearly turnover and average and specific average turnover

### ISSUE THREAD

**Issue by rantati7** [OP-TED/ESPD-EDM#40]
I put this here as I do not know where to put ERRORS in the  current version of ESPD.

Section IV B: Economic and Financial Standing

If CA asks average turnover or specific average turnover, the EO must answer with one number. Not give numbers for several years. This is correct in paper ESPD but not in the electronic version.

![espd paper 1](https://cloud.githubusercontent.com/assets/20238848/17357131/efe290ca-5963-11e6-8571-ec4b5d76264f.JPG)
![espd paper 2](https://cloud.githubusercontent.com/assets/20238848/17357138/f66ce0c6-5963-11e6-9d7c-fd4dd3971939.JPG)
![iv b](https://cloud.githubusercontent.com/assets/20238848/17357145/fb50300c-5963-11e6-9523-84b63df60d9c.JPG)

**Comment by ec-mcs** [comment]
You are right we have to change it. We will put just one line instead of multiple. It has no effect on the current model but it has an effect on our and other ESPD services. Therefore I will use a link from the issue management of the ESPD services to this one.

**Comment by virgiliu-ratoi-ec-ext** [comment]
this will break the compatibility with the previous versions, meaning that the ESPDs generated by older versions and imported in the new version will not contain the old fields belonging to 'Average yearly turnover' and 'Specific average turnover'

**Comment by ec-mcs** [comment]
Indeed this will happen. We have to specify what kind of how the system will resolve it (which data will be lost and which might be taken over). I expect that only the first line will be filled out and not all 5. So we would only take the first line...

**Comment by rantati7** [comment]
Average annual turnover is not widely used. In fact I have never seen anyone using this. From where and how did this come to ESPD? While it makes sense this may be complicated for CAs to check / calculate and require.

**Comment by ec-mcs** [comment]
I guess when we spoke about this in the beginning I wanted to align the fields as much as possible and there I went into the wrong direction.
As well I don't assume that it is used that much. Usually the turnover is the relevant one.

**Comment by rantati7** [comment]
BTW: I will be in STO, Sweden on Wednesday and cannot attend the online meeting. Sorry for that!

**Comment by virgiliu-ratoi-ec-ext** [comment]
Well, we will not be able to preserve anything from the old ESPDs for these 2 criteria except the 'Info available electronically' groups

**Comment by paulakeen** [comment]
Issue 41, proposing the transformation of previous version 1.0.2 into the new 1.1.0 one via XLS-T will be developed once the new 1.1.0 is finished and will cope with this "truncation" of the unnecessary average values.
