### ISSUE TITLE
appalti no CIG

### ISSUE THREAD

**Issue by spagne** [OP-TED/ESPD-EDM#400]
10.	Nel caso in cui l’appalto sia escluso dall'obbligo di richiesta del codice CIG per le motivazioni citate sul vostro sito  ([https://www.anticorruzione.it/-/tracciabilit%C3%A0-dei-flussi-finanziari](https://urldefense.proofpoint.com/v2/url?u=https-3A__www.anticorruzione.it_-2D_tracciabilit-25C3-25A0-2Ddei-2Dflussi-2Dfinanziari&d=DwMGaQ&c=eIGjsITfXP_y-DLLX0uEHXJvU8nOHrUK8IrwNKOtkVU&r=R7gHg28E3dNtu9pauSryqxYeRlE5d87rlZVQl8sUM2U&m=H4fcVXTz_nhNsyCS13qcULPtByinkCBEZUE5uGZXbLtjI06efEJJio4qJ5VxIXRd&s=D6rYghdSSYncAYBLaS5JV4IDDXKRtVYiNiPnBm9wtFg&e=) SEZIONE A8) o per altre tipologie di motivazioni è comunque necessaria la creazione dell’appalto e quindi il colloquio con NPA? Se SI potreste indicarci la scheda di riferimento?

**Comment by arillpa** [comment]
Dear @spagne 
thank you for your message. However we are not sure if the question is for us, the ESPD Exchange Data Model Team at the Publications Office of the EU.

We reckon that you wanted to contact your ESPD service colleagues in Italy. If this is not the case and the question really refers to the ESPD Model and is addressed to us  come back please to us.

Kind regards
The ESPD-EDM team

**Comment by arillpa** [comment]
Dear @spagne,

our colleagues from Italy have confirmed that the issues opened by you should be addressed to them.

The reference GitHub for ANAC's eForms platform and eSender is the following:
[https://github.com/anticorruzione/anticorruzione.github.io/blob/main/NPA.yaml](https://urldefense.com/v3/__https:/github.com/anticorruzione/anticorruzione.github.io/blob/main/NPA.yaml__;!!DOxrgLBm!Etv8hitXvMVwFSW-DB6lynEfREnGyboK7nNq3pOysXEkaIlqK9Xiaszk_T1RpxWCdXzoCvzeCwLhLwO60hWmTxydZ3JzjmHikVVeyiWyhdzCfWOm$)
Could you please put your questions in that GitHub?

Kind regards
The ESPD-EDM team

**Comment by arillpa** [comment]
Dear @spagne,
As we understand that the question is for the ANAC's platform we proceed to close this issue.

Kind regards
The ESPD-EDM team
