### ISSUE TITLE
Missing Criteria 33 in ESPD-criterion.xlsx #interproc 

### ISSUE THREAD

**Issue by Mateo-RH** [OP-TED/ESPD-EDM#401]
I'm not sure wether the enumeration it's wrong or is it that the criteria 33 from the section B is missing in the ESPD-criterion.xlsx document.

**Comment by arillpa** [comment]
Dear @Mateo-RH,
thank you for your remark.

The selection criterion 33 'Set up of economic operator' from section B was removed in the past from the criterion taxonomy and integrated as 'question' in the criteria related to the Turnover (criteria 29, 30, 31 and 32).
Criterion 33 was deprecated.

Kind regards
The ESPD-EDM team

**Comment by arillpa** [comment]
Dear @Mateo-RH,

as there are no modifications  to apply from our side, we proceed to close this issue.

Kind regards
The ESPD-EDM team
