### ISSUE TITLE
ProcurementProjectLot Identifier duplication

### ISSUE THREAD

**Issue by andreea-pasare** [OP-TED/ESPD-EDM#404]
In ESPD-EDM Request TOV v3.3.0 there is a duplication for the reference of a ProcurementProjectLot, highlighted in the diagram below:
![image](https://github.com/OP-TED/ESPD-EDM/assets/88081600/cb40a5af-dc0c-4872-9864-b4f64628ed65)

Is this an error? Which one is it going to be used as a reference for the ProcurementProjectLot?

**Comment by dragos-eu** [comment]
Hello Andreea,

Thank you for the information. We will analyse the issue and come back to you with a proposal.

Kind regards,
The ESPD Team

**Comment by dragos-eu** [comment]
Hello @andreea-pasare ,

We have made the update to the ESPD model and it will be published in release v4.0.0.

Kind regards,
The ESPD Team
