### ISSUE TITLE
ExclusionGround are linked to the ProcurementProjectLot

### ISSUE THREAD

**Issue by andreea-pasare** [OP-TED/ESPD-EDM#405]
In ePO [v4.0.0](https://docs.ted.europa.eu/EPO/latest/conceptual.html) the Exclusion Grounds are at the Procedure level, but in the ESPD-EDM Request TOV v3.3.0 they are linked to ProcurementProjectLot (Lot) instead of ProcurementProject (Procedure).
![image](https://github.com/OP-TED/ESPD-EDM/assets/88081600/e3deb8f1-a7e5-4ea0-9f6e-c0bd4d555806)

Is the link between TenderingCriterion and ProcurementProject going to be aligned with ePO?

This was discussed in the ePO Working Group Meeting. These [meeting minutes](https://docs.ted.europa.eu/epo-wgm/notes/2023-10-31-wgm.html) might be useful to get into the context.

**Comment by dragos-eu** [comment]
The models of ESPD v3.3.0 and ePO v4.0 are aligned.

**Comment by pascalinelaur** [comment]
The management of lots in the ESPD is defined at 2 levels :
    - EG are common to all lots
    - SC can be defined for different lots. Also, in a SC, different requirements can be assigned to different lots.
It has been agreed that the EPO management of lots should be aligned with the ESPD management of lots.
