### ISSUE TITLE
UBL terms: IssueDate and IssueTime. Should it be "issued" or "dispatched"? 

### ISSUE THREAD

**Issue by AchillesDougalis** [OP-TED/ESPD-EDM#406]
In the Working Group meeting about Collecting eSubmission requirements for ePO on 16/1/2024, while going through UBL terms from [ESPD-EDM Response Technical Overview](https://docs.ted.europa.eu/ESPD-EDM/latest/_attachments/ESPD_CM_html/index.html) :

Regarding UBL terms: IssueDate, and IssueTime under cac::QualificationApplicationResponse:
The ESPD-EDM team should check if these should be "issued "or "dispatch".

**Comment by pascalinelaur** [comment]
Hello @MummiaDoug , 

Thank you for your comment. 

We have checked the definition of the term "Issue Date/Time" (to make something available), as well as the UBL definition and options available. 

The actual wording is correct and for the time being there are no other UBL terms.

Kind regards, 
The ESPD Team.

**Comment by andreea-pasare** [comment]
Could you please provide an answer by mid-February.
Based on ePO v4.0.0, there are two different attributes at the level of epo:Document that can be used: 

1. **epo:hasDispatchDate**  with the definition:
    "Date and time of transmission of a record to an Organization."
2. **dct:issued** with the definition: 
    "Date of formal issuance of the resource.

    Additional information:
    This is generally used for modules other than eNotice.
    The xsd:dateTime here means that we can provide either xsd:date, xsd:dateTime, or xsd:timeStamp or any other variant of time expression. This extension needs to be encoded/automated in the ontology and in the application profile.
     Why is it like this? Because UML cannot handle such expressions of disjunctive property ranges."

![image](https://github.com/OP-TED/ESPD-EDM/assets/88081600/42512b87-7827-4ce3-a2f4-0d17d1f99c67)

To which one of the before mentioned attribute should cbc::IssueDate and cbc::IssueTime be mapped to ePO?

**Comment by pascalinelaur** [comment]
Hello, 

Thank you for your follow up question. 

EPO attributes "epo:hasDispatchDate" and "dct:issued" are of datatype "xsd:dateTime". 

ESPD attribute "cbc::IssueDate" is of datatype "xsd:date". 

ESPD attribute "cbc::IssueTime"  is of datatype "xsd:time". 

Moreover, we don't have the notion of "dispatch" in the ESPD. 

Hence, the ESPD attributes "cbc::IssueDate" and "cbc::IssueTime" could be merged as to become of datatype "xsd:dateTime" before being assigned to the EPO attribute "dct:issued". No modification will be done to the ESPD model.

Kind regards, 
The ESPD Team.

**Comment by pascalinelaur** [comment]
Since there are any further comments, we proceed to close this issue.
