### ISSUE TITLE
Provide a usecase for UBL term:PreviousVersionID

### ISSUE THREAD

**Issue by AchillesDougalis** [OP-TED/ESPD-EDM#407]
In the Working Group meeting about Collecting eSubmission requirements for ePO on 16/1/2024, while going through UBL terms from [ESPD-EDM Response Technical Overview](https://docs.ted.europa.eu/ESPD-EDM/latest/_attachments/ESPD_CM_html/index.html) :

It was agreed that the ESPD-EDM team should provide a use case for PreviousVersionID UBL term.

**Comment by pascalinelaur** [comment]
Hello @MummiaDoug , 

Thank you for your question. 

PreviousVersionID UBL terms is used to keep track of the various submission updates of a ESPD Response. 

Whenever the EO needs to update his response, a new VersionID is created and the PreviousVersionID is his latest existing response. Hence, the first Response does not have a PreviousVersionID. 

Kind regards, 
The ESPD Team.

**Comment by AchillesDougalis** [comment]
Thank you for your reply. We understand that the economic operator can change any content when submitting a new version of his ESPD Response. If our understanding is correct, please close this ticket.

**Comment by pascalinelaur** [comment]
Since we don't have any further comments, we proceed to close this github issue.
