### ISSUE TITLE
typos in the UBL terms

### ISSUE THREAD

**Issue by AchillesDougalis** [OP-TED/ESPD-EDM#409]
In the Working Group meeting about Collecting eSubmission requirements for ePO on 16/1/2024, while going through UBL terms from [ESPD-EDM Response Technical Overview](https://docs.ted.europa.eu/ESPD-EDM/latest/_attachments/ESPD_CM_html/index.html) , some possible typos were discovered that should be checked. Namely:

At cbc::DocumentTypeCode : there is a typo in name of the codelist.
At cac::QualifyingParty/Party/cbc::IndustryClassificationCode: is there a typo in this ESPD-EDM attribute? Should it be cac::Party?
At cbc::BirthplaceName: Typo: p should be capital letter.

**Comment by pascalinelaur** [comment]
Hello @MummiaDoug ,

Thank you for you question.

1. At cbc::DocumentTypeCode : there is a typo in name of the codelist.

"cbc::DocumentTypeCode" is not a codelist name, it is the UBL element that makes the link with the codelist "docrefcontent-type". Actually, there is a typo error in the spelling of the codelist with an extra hyphen "docref-content-type" in the conceptual model.

2. At cac::QualifyingParty/Party/cbc::IndustryClassificationCode: is there a typo in this ESPD-EDM attribute? Should it be cac::Party?

The prefix is indeed missing.

3. At cbc::BirthplaceName: Typo: p should be capital letter.

UBL element follow the Camel Case Pattern. So, each word should start with a capital letter. However, in this case the word is "Birthplace", so the spelling is correct and you can see that in the UBL documentation, it is the same spelling as well. Hence, there is no typo error here.

The various updates (1 and 2) will be available in the next release.

Kind regards, 
The ESPD Team.

**Comment by pascalinelaur** [comment]
Since we don't have any further comments, we proceed to close this github issue.
