### ISSUE TITLE
Transformation from old XML to new XML via XSLT

### ISSUE THREAD

**Issue by ec-mcs** [OP-TED/ESPD-EDM#41]
Erlend Klakegg Bergheim: Will there be made available XSLT to upgrade old XML files?

**Comment by paulakeen** [comment]
From version 1.0.2 into 2.0.0 there will be an XSL-T transformation soon.

**Comment by millstream** [comment]
Any update on this?

**Comment by paulakeen** [comment]
Currently, XML are being tested. Transformation will begin when the examples are stable.

**Comment by ec-mcs** [comment]
I will close it as this is currently foreseen we will open it or create a new one if this is still necessary
