### ISSUE TITLE
cac:ResidenceAddress link  to at-voc::country missing. 

### ISSUE THREAD

**Issue by AchillesDougalis** [OP-TED/ESPD-EDM#411]
According to the notes taken In the WG meeting on 24/1/2024, it seems that the link of cac:ResidenceAddress to the at-voc::country is missing in the ESPD model.

**Comment by pascalinelaur** [comment]
Hello @MummiaDoug , 

Thank you for your remark. 

Actually, the label on the link is missing and we will update this for the next release. 

Kind regards, 
The ESPD Team.

**Comment by pascalinelaur** [comment]
Since there are any more comments on this issue, we proceed to closing the github issue.
