### ISSUE TITLE
ESPD Response requirements

### ISSUE THREAD

**Issue by andreea-pasare** [OP-TED/ESPD-EDM#412]
For the eSubmission requirements we need some main important examples of questions that could be made on data for the ESPD Response.
Can you please provide a list with questions that can be discussed on Tuesday 30th of January during the ePO Working Group Meeting?

**Comment by pascalinelaur** [comment]
Hello @andreea-pasare , 

Thank you for your question. 

Could you please clarify your needs? What is the purpose of the examples of questions to provide? 

Also, we can discuss all this tomorrow during the meeting or you can also call us in the morning.  

Kind regards, 
The ESPD Team.

**Comment by andreea-pasare** [comment]
Hi @pascalinelaur. Those questions will be used to create additional user stories/competency questions for the eSubmission module.

**Comment by andreea-pasare** [comment]
The eSubmission (based on ESPD Response) requirements have been completed and can be reviewed. On our next meeting we can go through the comments that we may have.

**Comment by pascalinelaur** [comment]
Since there are any further comments, we proceed to close this issue.
