### ISSUE TITLE
UBL-UnqualifiedDataTypes-2.2.xsd in ubl-2.3 directory

### ISSUE THREAD

**Issue by rgannu** [OP-TED/ESPD-EDM#414]
In the `ubl-2.3/xsd/common` we are having `UBL-UnqualifiedDataTypes-2.2.xsd`. 
Should this not be `UBL-UnqualifiedDataTypes-2.3.xsd`?

**Comment by dragos-eu** [comment]
Hello @rgannu ,

Thank you for your feedback.
We will check the official distribution from UBL v2.3. 
Most probably we need to update the version of the file for the next release.

Kind regards,
The ESPD Team

**Comment by dragos-eu** [comment]
Hello @rgannu ,

We investigated the files from UBL distribution version 2.3 and the file UBL-UnqualifiedDataTypes-2.2.xsd is indeed from version 2.2.

The file is currently used for the Testbed processing validation of ESPD examples. We will run further tests to see if the file can be removed in a future release.

 

Kind regards,
The ESPD Team

**Comment by dragos-eu** [comment]
Hello @rgannu ,

We will check with the official distribution from UBL v2.3 and we updated the folder [ESPD-EDM/ubl-2.3 at v4.0.0-rc · OP-TED/ESPD-EDM (github.com)](https://github.com/OP-TED/ESPD-EDM/tree/v4.0.0-rc/ubl-2.3) contains the exact copy of the UBL 2.3 distribution files. This will be merged into main branch and published in ESPD v4.0.0 release.


Kind regards,
The ESPD Team
