### ISSUE TITLE
Schematron rule (BR-TC-17-02) is incorrect 

### ISSUE THREAD

**Issue by rgannu** [OP-TED/ESPD-EDM#416]
For the tendering property group '26ece6a2-b360-46c1-890d-8338913b8719', the requirement "type of requirement" can either be "true"/"false". Depending upon the value of the "type of requirement" either the requirement sub group "ca15c15f-110e-4a10-8d6e-5e41cf5f9098" (ONTRUE)  or  "cc96aa19-a0be-4409-af58-ff3f3812741b" (ON FALSE) will be filled in.

![image](https://github.com/OP-TED/ESPD-EDM/assets/5080106/843125c2-5391-437c-980f-3d97e7edef4a)

But, the schematron rule "BR-TC-17-02" expects that both the requirement groups needs to there in the generated request XML. This seems to be incorrect. Anyone of the requirement sub group alone can be there.   

```shell
[text=The subtendering criterion property group ('cac:TenderingCriterionPropertyGroup[cbc:ID = '4ddccd16-91e4-4b72-ae0f-78f2f1ab9490']/cac:SubsidiaryTenderingCriterionPropertyGroup[cbc:ID = '26ece6a2-b360-46c1-890d-8338913b8719']') has '1' missing 'cac:SubsidiaryTenderingCriterionPropertyGroup' element(s)., 
id=BR-TC-17-02, 
location=/*[local-name()='QualificationApplicationRequest']/*[local-name()='TenderingCriterion'][28]/*[local-name()='TenderingCriterionPropertyGroup']/*[local-name()='SubsidiaryTenderingCriterionPropertyGroup'], 
test=not($currentIDExist) or (($currentIDExist) and not($ElementUUID_SUBExists)) or (count($ParentUUID_SUB/cac:SubsidiaryTenderingCriterionPropertyGroup) <= count(cac:SubsidiaryTenderingCriterionPropertyGroup) and ($currentIDExist) and ($ElementUUID_SUBExists)), 
role=null, 
numericLevel=400, 
diagnosticReferences=[]
]
```

**Comment by dragos-eu** [comment]
Hello @rgannu ,

Thank you for your feedback.
We are working to provide a fix for this issue. 
There is a partial fix for the XSLT transformation for the ESPD Response - https://github.com/OP-TED/ESPD-EDM/commit/cbd888a64e24baf08f27f31aebb955b59250d200 and we will provide a fix for the Schematron rules, too.

Kind regards,
The ESPD Team

**Comment by pascalinelaur** [comment]
Hello, 

This issue will be  included in the release version 4. 
We then proceed to close this issue on github. 

Kind regards, 
The ESPD Team.
