### ISSUE TITLE
[Question]: Will the xsd files updated with version 2.4 for the new upcoming v.4.0.0 or will the version 2.3 be kept?

### ISSUE THREAD

**Issue by MicheleAmoroso** [OP-TED/ESPD-EDM#418]
### Your question

Hi, I noticed that for all versions of the espd the xsd files have also been updated, for example for the espd 1.0.0 the xsd files with version 2.1 are used, for the 2.0.0 version the xsd 2.2 version is used etc.. for version 4.0.0, will the xsd files with version 2.4 be uploaded or will the currently present version 2.3 remain?

### ESPD Version

3.3.0 (latest)

**Comment by dragos-eu** [comment]
Hello @MicheleAmoroso,

Thank you for your feedback using the new template for Issues.
We checked UBL v2.4 and it does not bring updates to ESPD related documents based on UBL v2.3. We will not update the UBL version for ESPD-EDM release v4.0.0, keeping UBL 2.3 as reference for ESPD documents.
Please let us know if you would like to have more details from our side.

Kind regards,
The ESPD Team

**Comment by MicheleAmoroso** [comment]
Hi, I also noticed that these 2 tags xml:

  - cac:TenderingCriterionProperty -> cbc:QuantityUnitCode
  - cac:TenderingCriterionProperty -> cbc:ExpectedQuantity
 
are present in the xml example file "ESPD-Response.xml", but they are not present in the "UBL-CommonAggregateComponents-2.3" xsd file, is it possible to verify how is it possible that these two fields are not present?

**Comment by dragos-eu** [comment]
Hello @MicheleAmoroso,

Thank you for your feedback on v4.0.0-rc.
We created a separate issue for your new request: #419 
Please consult the new ticket for further information.
We will close this ticket as the initial question has been answered.

Kind regards,
The ESPD Team
