### ISSUE TITLE
Financial ratio type translations (bis?)

### ISSUE THREAD

**Issue by mdewinne** [OP-TED/ESPD-EDM#420]
Looking at the [current codelist for financial ratio](https://github.com/OP-TED/ESPD-EDM/blob/main/codelists/gc/FinancialRatioType.gc), it seems the issue mentioned in https://github.com/OP-TED/ESPD-EDM/issues/337 has reappeared?

**Comment by dragos-eu** [comment]
Hello @mdewinne,

Thank you for your feedback.
We confirm that the translations are not uniform for ESPD v3.3.0. Not all English translations are registered to the right row, some of them are registered to Bulgarian or Spanish language.
Please check the visual display for Code Lists for ESPD v3.3.0 on the [ESPD Demo site](https://docs.ted.europa.eu/espd-demo/), Code Lists section.

We provided a fix in **V4.0.0-rc**, that was released in April 2024. You can inspect the structure of the file on the ESPD Demo site.

Kind Regards,
ESPD Team

**Comment by mdewinne** [comment]
Thank you for your answer. Are there any plans to translate this codelist to other EU languages?

**Comment by srdjankr** [comment]
Hello @mdewinne,

Thank you for your new question.
The FinancialRatioType codelist is provided by the Bank of France only in English. OP/ESPD Team is not providing the translation of this codelist.

Kind Regards,
ESPD Team

**Comment by srdjankr** [comment]
Dear @mdewinne,
Since there are no further comments we proceed to close this issue.

Kind regards,
The ESPD Team

**Comment by srdjankr** [comment]
Dear @mdewinne,
Since there are no further comments we proceed to close this issue.

Kind regards,
The ESPD Team
