### ISSUE TITLE
Link between ESPD and e-Certis: the information displayed is based on the country of the CA, or on the country of the EO?

### ISSUE THREAD

**Issue by SVdMeulen** [OP-TED/ESPD-EDM#43]
This is not really an issue, but a rather a question/remark on the link between ESPD and e-Certis.
In the current ESPD-tool, information about the criteria that is available in e-Certis is displayed. The information displayed depends on the country one selected when starting the tool.
My question: if a CA opens the ESPD response of a foreign company, will the information that comes from e-Certis be based on the country of the CA, or on the country of the EO?
It could be handy for the CA if he could see, in the response of the foreign EO, the e-Certis data that applies to the EO country. This way he could already see what certificates to expect. 
This is certainly useful as not every country has certificates available online for all exclusion or selection criteria, or if they have, they might not be accessible for foreign CA. Inserting a link in the ESPD is then rather useless, while e-Certis could provide interesting information of the type of evidence that exists in the EO's country.

**Comment by paulakeen** [comment]
Please find below what was commented about this issue in the discussion group (22/03/2017):

Marc-Christopher SCHMIDT: The information for EO from eCertis should be from the country of the EO not the CA

Anne Katrine Mortensen, DK: I agree

virgiliu: this should be taken into consideartion for version 2017.03 of the espd application

Marc-Christopher SCHMIDT: indeed

**Comment by dg-grow-alexey-lukashov** [comment]
more detailed duplicate #152
