### ISSUE TITLE
Codelist for CustomizationID contains wrong values

### ISSUE THREAD

**Issue by SiwMeckelborg** [OP-TED/ESPD-EDM#45]
The codelist for element <cbc:CustomizationID> contains wrong values from CEN BII. 

Example: 
The ESPD response message should have customizationID 
urn:www.cenbii.eu:transaction:bii**trdm**092:ver3.0

Whereas the codelist (gz and pdf) shows the value
urn:www.cenbii.eu:transaction:bii**trns**090:ver3.

**Comment by paulakeen** [comment]
Thank you,

1) I understand you refer to the XML produced by the ESPD-Service and to the (pdf) documentation generated by the ESPD-Service development team, don't you?

I'll pass this issue to the ESPD-Service workspace in this Github.

2) The ESPD-Service used the ESPD-CodeList-V1.0.xls Excel file that was distribute with version 1.0 of the ESPD-EDM. This list contains the codes and values provided by the CEN/BII WS-3. 

I observe that in that list the codes do all of them contain the ID urn:www.cenbii.eu:transaction:biit**rns**nnn:ver3.0

We weren't notified of any change about this list. We'll check with them. 

*Thks.

**Comment by paulakeen** [comment]
I've been talking to some CEN/BII team member and we discovered that there's an inconsistency with this Code List: apparently the one used by the pre-award team differs from the one used by post-award (urn:www.cenbii.eu:transaction:biitrdm092:ver3.0 and urn:www.cenbii.eu:transaction:biitrns090:ver3 are being used distinctly in both teams). 

They will revise the situation asap.

**Comment by paulakeen** [comment]
From issue #60 
The GITB ESPD validator reports an error for the cbc:CustomizationID element, although the content is obviously correct. For an ESPD Request (fragment) as shown below, the error message is as follows:
The value must be 'urn:www.cenbii.eu:transaction:biitrns070:ver3.0'.

<espd-req:ESPDRequest ...>
   ...
   <cbc:CustomizationID schemeName="CustomizationID" schemeAgencyID="BII" schemeVersionID="3.0">urn:www.cenbii.eu:transaction:biitrns070:ver3.0</cbc:CustomizationID>

**Comment by paulakeen** [comment]
New version of the ESPD-2.0.0 (UBL-2.2) will hold the value "2.0.0" meaning that the UBL-2.2 cusomisation is ESPD-2.0.0. The attributes also map now the ones by GROW (See ESPD-EDM-2.0.0 documentation).
