### ISSUE TITLE
Pre-qualification systems and classification of EOs

### ISSUE THREAD

**Issue by paulakeen** [OP-TED/ESPD-EDM#47]
The type of activity should be required in the criterion to specify for which activities the company (the EO) is classified. This is the practice in Belgium, Portugal, Spain, and possibly other countries (Austria?) and for which amounts (no limit, up to 5M€,etc.). 

--> This doesn’t impact on the schema, but on new XML group of requirements structure. Its about coding the activities and specifying amounts. Codes would be provided by the classifying organisation, and amounts possibly too.

**Comment by ec-mcs** [comment]
Rudolf: Insurence  amount is a pass/fail criteria.

Jose Luis Cueva: In my understanding, pre-qualification is a 2-dimensional issue:

Jose Luis Cueva: type of activity/ceiling of amount

Jose Luis Cueva: For instance: activity = building construction/up to 1M. euro

**Comment by arocamop** [comment]
This discussion is still pending of resolution. Two options were suggested:

1. Use an international widely used codelist, and optionally

2. A free text

**Comment by ec-mcs** [comment]
![untitled](https://cloud.githubusercontent.com/assets/20335285/23460287/e4e3f5f8-fe84-11e6-85af-1472987c0668.png)

**Comment by paulakeen** [comment]
Please find below a proposal for the mock-up with the information required to the EO regarding the pre-qualification system.
To take into account:

- In a), the EO will select the pre-qualification system from a list retrieved from e-Certis.

- If the EO answers "NO" to the question "Does the registration or certification cover all of the required selection criteria?", the ESPD should display a list with all exclusion and selection criteria in order to allow the EO to select those that are covered by the pre-qualification system. If there is information available in e-Certis regarding the criteria covered by the pre-qualification system, it will be displayed in the ESPDResponse.

- Those criteria already covered by the pre-qualification system will not be displayed later on in parts III and IV.

![image](https://cloud.githubusercontent.com/assets/16134316/23900054/f6312686-08b7-11e7-8a4a-d2e8473f5d3e.png)

Let's discuss this tomorrow.

**Comment by paulakeen** [comment]
Please find below what was commented about this issue in the discussion group:

Jose Luis Cueva - Spain: seems a good solution, flexible enough

Zilvaras Gelumbauskas: OK

Zilvaras Gelumbauskas: :)

Jose Luis Cueva - Spain: it is  about the same in Spain

Anne Katrine Mortensen: We do not have it in Denmark, so not relevant here.

Timo Rantanen / Hansel / Finland: Official list is an issue in ESPD that we get most questions from suppliers

Zilvaras Gelumbauskas: Lithuania has it, but is going to cancel

Jose Luis Cueva - Spain: For Public Works, and for many types of Services contratcts

Timo Rantanen / Hansel / Finland: this could be hidden if not used in a country / CA

Anne Katrine Mortensen: Good idea.

Timo Rantanen / Hansel / Finland: Thumbs Up for hiding it

Anne Katrine Mortensen: Yes.

Zilvaras Gelumbauskas: Now it is used only for declaration in what economic activity the company can take part 

Zilvaras Gelumbauskas: Yes

Anne Katrine Mortensen: Unclear what is meant by "the references".

Zilvaras Gelumbauskas: We must take into account that the Contracting Authority can not know if in the country of economic operator such register exists

Zilvaras Gelumbauskas: Great!

Rudolf Maier: Every prequalification system as certain rules/criateria for a EO to be registered.

Rudolf Maier: The company provides all evidences mentioned in the Procurement Law.

Jose Luis Cueva - Spain: And the rules could be complex and leghty and wordy

Rudolf Maier: Yes, it would be difficult and shouldn't be necessary.

Anne Katrine Mortensen 2: I agree with JL and R

Rudolf Maier: The Link will be provided to the various evidences. It would make sense if with this statements, it is not necessary foir the EO to provide the single evidences.

Jose Luis Cueva - Spain: In the Spanish case the rules can be summarized as: staff/employee, equipment, experience in performing similar contracts, financial standing

Rudolf Maier: That is OK - optional field.

Anne Katrine Mortensen 2: I agree option

Rudolf Maier: It should cover all required KO criteria, but it will not provide specific selection criteria to choose the best out of the eligibly EO.

Rudolf Maier: KO = Pass or fail

Rudolf Maier: Either there is a "global" prequalification or each single evidence has to be provide.d

Rudolf Maier: Yes, otherwise it would be difficult for teh CA to prove which evidences ar eprovided and which not.

Jose Luis Cueva - Spain: it seems my micro does not work

Jose Luis Cueva - Spain: my problem is the mock-up

Jose Luis Cueva - Spain: it is not clear where the EO must click on

Giampaolo Sellitto ANAC: The evidence must not necessarily be provided by the EO even if there is no global prequalification system.... we have an aggregator that retrieves evidences form the issuing bodies but does not store it and it is not a pre-qualification service

Jose Luis Cueva - Spain: I agree to the concept

Jose Luis Cueva - Spain: I just think the screen layout is tot clear enough

Anne Katrine Mortensen 2: Yes

Jose Luis Cueva - Spain: is not clear enough

Rudolf Maier: Our Service provides all the evidences but the final decision "eliible or not" is with the CA.

Anne Katrine Mortensen 2: No should mean that every info asked for must be filled out

Giampaolo Sellitto ANAC: the same for us, the CA has the final decision if the OE is eligible or not

Anne Katrine Mortensen 2: c): yes, I agree. d): I agree 

Michaël De Winne / e-Proc Belgium: I agree for both points as well

Jose Luis Cueva - Spain: Qualification might nor cover EXCLUSION CRITERIA

Jose Luis Cueva - Spain: because too volatile

Rudolf Maier: What I stated is for the PASS/FAIL criteria. The selection criteria to choose out of the EO who had passed the PASS/FAIL criteria is not included as this is specific for each tender procedure.

Giampaolo Sellitto ANAC: yes in italy qualification does not cover exclusion criteria ar at least it could be not up to date

Jose Luis Cueva - Spain: OK

Rudolf Maier: This is the matter of the registration with a professional and/or trade register.

Rudolf Maier: The CPV can be an additional information the key is the professional register.

Jose Luis Cueva - Spain: An EO can be qualified only for a given sert of works/services

Rudolf Maier: Right, no necessity here for CPV.

Jose Luis Cueva - Spain: So the ESPD needs a way to express which field/type of activities is qualified for

Rudolf Maier: Yes, some services for EO use the CPV for finding Tender oportuinties. But the CPV is given by the CA not by the EO.

Jose Luis Cueva - Spain: either CPV, NACE, free text...

Jose Luis Cueva - Spain: a given EO is qualifies for buildings, or roads, or bridges...

Rudolf Maier: I agree with Jose Luis. But the CPV is stated by the CA for his respective contract procedure. Zhis is to help to EO to find notices beyond language boarders.

Jose Luis Cueva - Spain: So you mean it is implied on the procurement doc?

Rudolf Maier: Bigger companies are qualified for a whole host of CPVs.

Jose Luis Cueva - Spain: OK

Antanina Akulich, Germany: I agree

Giampaolo Sellitto ANAC: in italy qualification exists fo public works and it involves technical capabilities and financuìial one as well

Jose Luis Cueva - Spain: so we put the specification in part I?

Giampaolo Sellitto ANAC: categories are defined by law

Rudolf Maier: These are the CVP codes stated by the CA, then it is OK.

Michaël De Winne / e-Proc Belgium: @Giampaolo: same in Belgium

Giampaolo Sellitto ANAC: we have a code for the procurement procedure will it be enclosed there?

Jose Luis Cueva - Spain: OK

**Comment by paulakeen** [comment]
Please find below a new proposal for the mock-ups regarding pre-qualification systems, according to the final decision made in last Wednesday's meeting:

- View of the CA: the CA will be able to provide one or several CPV codes for the procurement procedure.

![mu_parti_ca](https://cloud.githubusercontent.com/assets/16134316/24096008/f906cb7a-0d5f-11e7-9598-55bd388b6769.png)

- View of the EO: the EO will be able to provide one or several references (or none) in c). 

![mu_part2_a_eo_47](https://cloud.githubusercontent.com/assets/16134316/24096000/f264c20e-0d5f-11e7-8562-1a3f95af534b.png)

**Comment by paulakeen** [comment]
Please find below a new proposal for the mock-up regarding pre-qualification systems (view of the EO). As agreed in last Wednesday's meeting, we've changed the text in b).

![mu_a_part2_criteria_eo](https://cloud.githubusercontent.com/assets/16134316/24351889/d1757e2a-12e7-11e7-86eb-f0ba664f6e98.png)

**Comment by paulakeen** [comment]
Please find the details of the final decision in https://github.com/ESPD/ESPD-EDM/wiki/7.-Pre-qualification-systems-and-classification-of-EOs
