### ISSUE TITLE
Quality assurance

### ISSUE THREAD

**Issue by paulakeen** [OP-TED/ESPD-EDM#48]
Quality assurance does only have a description, but it could also refer to well identified standards (e.g. (ISO 9000 family, ISO 27000 standards, and also the parts, e.g. ISO 11179:5 for metadata registry, etc. 

it affects the XML instantiation "super-model" , doesn’t impact the XSD Schema.

**Comment by ec-mcs** [comment]
Jose Luis Cueva: It sounds sensible

**Comment by paulakeen** [comment]
We close this issue for it has been unified with issue #33
