### ISSUE TITLE
Part IV: Selection criteria, ɑ: Global indication for all selection criteria 

### ISSUE THREAD

**Issue by rantati7** [OP-TED/ESPD-EDM#5]
If CA decides to use this option other options on the same page should not be shown to CA. I would personally prefer this option not to be in ESPD at all. It would be better if all selection criteria used would be inputted by CA to ESPD and not to various places in the tender documents. This compicates the matter to EO and leads to unneccessary exclusions. 

[One additional thing: we have advised the CAs always to ask EO if there is "a wrong" answer in ESPD and not to exclude the EO straight away. Maybe this practice should be used by others, too. At least in the early stages when EOs are not yet familiar with the ESPD.]

**Comment by ec-mcs** [comment]
I personally completely agree! This alpha criterion is introducing a lot of uncertainty for both sides. CAs should always select the relevant selection criteria. Unfortunately quite a number of Member States asked explicitly this one so we can't get rid of it. 

About your idea with this advise, we should add this in our FAQ as a general statement. As we can't really do something about this. I close it and hope you don't mind...
