### ISSUE TITLE
Diferent qualification criteria for subcontractors

### ISSUE THREAD

**Issue by Zilvaras** [OP-TED/ESPD-EDM#50]
Qualification criteria for EO and subcontractors are usualy diferrent. How it will be adressed in ESPD?

**Comment by arocamop** [comment]
See please issue [https://github.com/ESPD/ESPD-EDM/issues/55](url)

**Comment by paulakeen** [comment]
See please issue https://github.com/ESPD/ESPD-EDM/issues/57 (not issue #55)
