### ISSUE TITLE
Part II, Section C - Consortium

### ISSUE THREAD

**Issue by ghost** [OP-TED/ESPD-EDM#52]
In "Part II" - "C: Information about reliance on the capacities of other entities" when you select "Yes" it's possible to enter a "Consortium Name". Why is this not a requirement under criterion "0d62c6ed-f074-4fcf-8e9f-f691351d52ad"?

**Comment by virgiliu-ratoi-ec-ext** [comment]
because this field was saved from the beginning, unfortunately, under the `EconomicOperatorGroupName` element. We would like to fix this next year when we will use version 1.1 of the data model.
