### ISSUE TITLE
ResponseDataType should be an element of Requirement not an attribute

### ISSUE THREAD

**Issue by paulakeen** [OP-TED/ESPD-EDM#53]
**Change Request:**

Transform the attribute ResponseDataType of the element ccv:Requirement into an element

**Rationale:**
In order to align the model to UBL-2.2 and leverage the extension of the ccv:Requirement with the elements required recently during the latest discussions on Turnover and Ratio (inclusion of minimum and maximum amounts and quantities; see issues on Turnovers and Ratios).

**Impacts:** **Major**
It introduces consequential changes in the Data Model and therefore modifies the XSD Schema

**Milestone:** 
version 1.1.0

**Comment by arocamop** [comment]
**Mockup**: No impact on the user interfaces

**Data model:**

1. Current version (version 1.0.2)

![image](https://cloud.githubusercontent.com/assets/24680325/22026454/222423dc-dcd1-11e6-8c35-9c054abafaa2.png)

2. Next release (version 1.1.0):

![image](https://cloud.githubusercontent.com/assets/24680325/22026564/708dd04a-dcd1-11e6-9a92-35016dc0e294.png)

**Comment by paulakeen** [comment]
This is aligned to UBL2.2 and is very technical. The impact is on the software applications but it is minimal, so let's close it..
