### ISSUE TITLE
Part III, Section B - Payments of Taxes and Social Security

### ISSUE THREAD

**Issue by ec-mcs** [OP-TED/ESPD-EDM#54]
If a supplier from country A participates in a public procedure in country B they have to respect the amount of the buyer. In Lithuania in PP procedures if the supplier has more than 50 € unpaid tax they will be excluded. 
**eCertis:** In eCertis we should provide the possibility to indicate the amount which will be expected (or if this is upon the CA)
**ESPD service:** In the ESPD service if in eCertis you would define for Lithuania 50 € it should be displayed or if the CA can define it they should enter the amount which would be accepted.

**Comment by ec-mcs** [comment]
Rudolf Maier: In most cases the space in the ESPD should be sufficient for description. I cdon't think that lengthy descriptions bythe CA concerning the exclusion grounds are necessary.

Marc-Christopher SCHMIDT: I agree Rudolf

Marc-Christopher SCHMIDT: We had just before Christmas a very interesting mail exchange with LT about taxes

Marc-Christopher SCHMIDT: The case: If a supplier from country A participates in a public procedure in country B they have to respect the amount of the buyer. In Lithuania in PP procedures if the supplier has more than 50 € unpaid tax they will be excluded.

Timo Rantanen / Hansel / Finland: in this one case that I had, 500 marks was nto enouhgt for the CA. And I agreed as their environmental law requirements went on far more detalled level than what was in the law (the reqwuirments were still inline with the law)

Timo Rantanen / Hansel / Finland: about taxes....

Marc-Christopher SCHMIDT: Ok. How about providing the possibility for the CA to define a threshold?

Marc-Christopher SCHMIDT: Please Rudolf

Rudolf Maier: The EO is always adviced to make sure that there are no debts even though the € 50 should not be a problem.

Marc-Christopher SCHMIDT: The threshold depends on the country. In LT by law > 50 € and EO is out

Marc-Christopher SCHMIDT: In Germany this is up to the CA to decide

Laura Martin / Scottish Government: In the UK, its up to the CA too

Marc-Christopher SCHMIDT: Please Timo

Timo Rantanen / Hansel / Finland: Finland: 0€ and you are out. Unless you have made an agreement with the tax man on payback

Marc-Christopher SCHMIDT: How about providing in eCertis the possibility for countries to define the threshold?

Timo Rantanen / Hansel / Finland: This actually shows that in other places of ESPD (part III) there might be a need to have a description field. Currently this can be described in eCertis (if we had instructions whihc part in eCertis becomes visible in ESPD and how it's shown there).

Marc-Christopher SCHMIDT: Indeed... we have to identify them

Timo Rantanen / Hansel / Finland: I updated eCertis data before our new PP law came to power on 1.1.2017 and made a complete mess out of eCertis....

Marc-Christopher SCHMIDT: Timo - I guess you did a fantastic job with eCertis :-)

Marc-Christopher SCHMIDT: As well here I would suggest to make a mockup for eCertis/ESPD to show how this could be integrated

Timo Rantanen / Hansel / Finland: as I said - complete mess! But those fields really do need to be identified. I would leave this however to eCertis and would not do anything new with ESPD

Marc-Christopher SCHMIDT: Timo we need to address both: In LT by PP law 50 € is the threshold. In Germany or UK up to the CA. In eCertis for the Taxes critiera the editor allows for providing a threshold or saying "Up to CA". If it is by law, the threshold will be shown in ESPD if "Up to CA" the CA can provide the threshold

Marc-Christopher SCHMIDT: Using only the chat is a good exercise to learn typiing ;-)

Timo Rantanen / Hansel / Finland: other topics?

Marc-Christopher SCHMIDT: Please Rudolf

Marc-Christopher SCHMIDT: None from my side. Anyone else?

Laura Martin / Scottish Government: not for me

Marc-Christopher SCHMIDT: Ok I would suggest for the agenda next week to discuss the mockups and go through the Timo mentioned list to check where we are and what we still have to do

Timo Rantanen / Hansel / Finland: thanks!

Laura Martin / Scottish Government: sounds good!

Michael De Winne / e-Proc Belgium: ok

Rudolf Maier: The EO can avoid the problem of the € 50 by using a evidence issued by the tax authority which states that there are no debts as 50 or more € can be shown on the tax account due to small differences occuring in the prescription and booking of the bank transfers. What I mean is that this 50 or more € are onlay a problem if the tax authoirity has aready urged the EO to pay this debt.

Marc-Christopher SCHMIDT: True Rudolf. So if I understand correctly the Tax certificate would show 50€ if this is missing.

Marc-Christopher SCHMIDT: I would suggest to continue the discussion next week. Bye bye! See you next week!

**Comment by paulakeen** [comment]
We may be should initiate a separate thread/issue space/wiki or whatever titled "e-Certis2 + ESPD Synergies" and list/discuss them there too.

**Comment by ec-mcs** [comment]
I would suggest to do it in the ESPD service repository and mark them with eCertis. The reason is we can more easily see what features of the ESPD service can be linked to eCertis.

**Comment by ec-mcs** [comment]
The current vision as a screenshot
![capture](https://cloud.githubusercontent.com/assets/20335285/21854823/83425f76-d81c-11e6-9cbd-6163c1aa0050.PNG)

**Comment by paulakeen** [comment]
Please find below what was commented about this issue in the discussion group (22/03/2017):

Michaël De Winne / e-Proc Belgium: In Belgium the tax authority issues a certificate stating that the EO has no debts higher than X euro (don't know the exact amount, but it's a lot higher than 50€)

Michaël De Winne / e-Proc Belgium: but the specific amount of the debt is not mentioned, so a foreign CA consulting the certificate would not know whether the Belgian EO is in compliance with the national threshold (of for example 50€)

Michaël De Winne / e-Proc Belgium: ok

Jose Luis Cueva - Spain: ok

**Comment by paulakeen** [comment]
Please find below what was commented about this issue in the discussion group:

Anne Katrine Mortensen, NIRAS A/S, DK: Yes, logical. But makes the ESPD longer.

Steve Pastterson (Scottish Government): isn't that a minimun standard and should appear in the notice?

Steve Pastterson (Scottish Government): Sorry MC, I thought you said the idea of the self-contained ESPD was still in some doubt? Is this not part of that ?

Steve Pastterson (Scottish Government): For the avoidance of doubt, I would support a sellf -contained ESPD, and for those criteria to appear in the ESPD and the contract notice.

Anne Katrine Mortensen, NIRAS A/S, DK: I support no repeated text.

Steve Pastterson (Scottish Government): As long as the contract notice has the space to recive this information. It could be quite lengthy.

Steve Pastterson (Scottish Government): The fileds for selection criteria have historically been quite small. Th enew forms are a chance to fix this.

Steve Pastterson (Scottish Government): no

Jose Luis Cueva - Spain: The redundances are between the ESPD-request and the CN

Steve Pastterson (Scottish Government): yes!

John Degiorgio: ok

Jose Luis Cueva - Spain: I can hear you

Jose Luis Cueva - Spain: hi

Steve Pastterson (Scottish Government): yes

Michaël De Winne - Belgium: how do I get rid of the little video pop-up in the bottom left corner?

Jose Luis Cueva - Spain: I guess the same applies

Michaël De Winne - Belgium: I would have to check

Steve Pastterson (Scottish Government): I think each case would be judged on a case by case basis.

Jose Luis Cueva - Spain: for both taxes and SS

**Comment by paulakeen** [comment]
Please find below a proposal for the mock-up of the view of the CA regarding Payment of Taxes and Payment of Social Security, as commented in the last meeting:

![mu_payments_ca_54](https://cloud.githubusercontent.com/assets/16134316/24657281/e45fb9f6-1945-11e7-822d-2bdc674c7c8e.png)

**Comment by paulakeen** [comment]
Please find the details of the final decision in https://github.com/ESPD/ESPD-EDM/wiki/10.-Payments-of-Taxes-and-Social-Security
