### ISSUE TITLE
Evidence Issuer is separate requirement; Should be inside <cev:Evidence>

### ISSUE THREAD

**Issue by jerouris** [OP-TED/ESPD-EDM#58]
The current implementation of the ESPD Service and the ESPD Data model contains requirement groups that ask for evidence data (Evidence URL, Reference Code, Evidence Issuer). Although these elements can be found in the cev:Evidence element, 3 different non-correlated requirements are used instead:

Current Use:
```
<ccv:RequirementGroup pi="GROUP_FULFILLED.ON_TRUE">
            <cbc:ID schemeAgencyID="EU-COM-GROW" schemeVersionID="1.0">41dd2e9b-1bfd-44c7-93ee-56bd74a4334b</cbc:ID>
            <ccv:Requirement responseDataType="EVIDENCE_URL">
               <cbc:ID schemeID="CriterionRelatedIDs" schemeAgencyID="EU-COM-GROW" schemeVersionID="1.0">f4313bb6-21b6-499e-bdff-debe10e11d2c</cbc:ID>
               <cbc:Description>URL</cbc:Description>
               <ccv:Response>
                  <cev:Evidence>
                     <cev:EvidenceDocumentReference>
                        <cbc:ID schemeAgencyID="EU-COM-GROW">d2268dec-f6b9-4601-bdb4-ed077af28ef8</cbc:ID>
                        <cac:Attachment>
                           <cac:ExternalReference>
                              <cbc:URI>http://the.url</cbc:URI>
                           </cac:ExternalReference>
                        </cac:Attachment>
                     </cev:EvidenceDocumentReference>
                  </cev:Evidence>
               </ccv:Response>
            </ccv:Requirement>
            <ccv:Requirement responseDataType="CODE">
               <cbc:ID schemeID="CriterionRelatedIDs" schemeAgencyID="EU-COM-GROW" schemeVersionID="1.0">1f1cd18e-3e01-4ca2-af4c-e2981924ba8d</cbc:ID>
               <cbc:Description>Code</cbc:Description>
               <ccv:Response>
                  <ccv-cbc:Code>The Reference/Code</ccv-cbc:Code>
               </ccv:Response>
            </ccv:Requirement>
            <ccv:Requirement responseDataType="DESCRIPTION">
               <cbc:ID schemeID="CriterionRelatedIDs" schemeAgencyID="EU-COM-GROW" schemeVersionID="1.0">c3ccfa31-0c5e-4e3a-a3fd-db9fb83d78d4</cbc:ID>
               <cbc:Description>Issuer</cbc:Description>
               <ccv:Response>
                  <cbc:Description>the issuer</cbc:Description>
               </ccv:Response>
            </ccv:Requirement>
</ccv:RequirementGroup>
```
Suggested/Corrected Use:
```
         <ccv:RequirementGroup pi="GROUP_FULFILLED.ON_TRUE">
            <cbc:ID schemeAgencyID="EU-COM-GROW" schemeVersionID="1.0">41dd2e9b-1bfd-44c7-93ee-56bd74a4334b</cbc:ID>
            <ccv:Requirement responseDataType="EVIDENCE_URL">
               <cbc:ID schemeID="CriterionRelatedIDs" schemeAgencyID="EU-COM-GROW" schemeVersionID="1.0">f4313bb6-21b6-499e-bdff-debe10e11d2c</cbc:ID>
               <cbc:Description>URL</cbc:Description>
               <ccv:Response>
                  <cev:Evidence>
                     <cev:EvidenceIssuerParty>
                       <cac:Party>
                         <cac:PartyName>
                           <cbc:Name>The Issuer</cbc:Name>
                         </cac:PartyName>
                      </cac:Party>
                     </cev:EvidenceIssuerParty>
                     <cev:EvidenceDocumentReference>
                        <cbc:ID schemeAgencyID="EU-COM-GROW">d2268dec-f6b9-4601-bdb4-ed077af28ef8</cbc:ID>
                        <cac:Version>
                           <cbc:VersionID>The Reference/Code</cbc:VersionID>
                        </cac:Version>
                        <cac:Attachment>
                           <cac:ExternalReference>
                              <cbc:URI>http://the.url</cbc:URI>
                           </cac:ExternalReference>
                        </cac:Attachment>
                     </cev:EvidenceDocumentReference>
                  </cev:Evidence>
               </ccv:Response>
            </ccv:Requirement>
         </ccv:RequirementGroup>
```
This way, all the evidence data can be grouped under the cev:evidence type which is semantically better. It also makes the use of evidence easier, when multiple evidence (document types/attestations) must be provided (according to e-Certis). 
This also makes it compatible with e-Certis, the VCD and future projects/implementations that might provide evidences (eg. aggregators)

**Comment by virgiliu-ratoi-ec-ext** [comment]
I see your point but it's impossible to make this change right now. What is the correlation between the VersionID element and the Reference/Code?

**Comment by jerouris** [comment]
This is provided as an example as to how the current disjoint evidence semantics could be joined. The VersionID is used as the reference code. 

Of course this should be answered in the 2.0.0 version of the ESPD. Having this structure also in version 2.0.0 for evidences (different split requirements) will be an interoperability mess and a barrier to OOP initiatives.

**Comment by paulakeen** [comment]
Jerry is right. But I still think that the presence of the IssuerParty inside the Evidence component is redundant and inconsistency prone, as the component DocumentReference inside the Evidence does ALSO aggregate a cac:IssuerParty. We should use the cac:DocumentReference/cac:IssuerParty component and ask UBL-2.2 to remove the one aggregated to the Evidence!

Please confirm that you agree...or not, so I can raise the issue to UBL-2.2.

**Comment by jerouris** [comment]
Yes, I think that using documentReference is also fine, if not better. Using less elements where possible and on multiple instantiations of the CAC (eg Issuer Party can then be used consistently inside the external document reference of the ESPD itself and of the evidences).

**Comment by paulakeen** [comment]
Done, submitted to UBL-2.2. Issue open for discussion. I don't thing they will have a problem with this.

**Comment by paulakeen** [comment]
UBL-2.2 accepts our proposal: We will use the cac:DocumentReference/cac:IssuerParty element.

This was already commented in a special note in version 2.0.0:

*Duplicity of the Issuer:*

"Beware that the current modeel of UBL-2.2 provides two elements for the Issuer, one for the issuer of the evidence and another for the issuer of the document reference.

The ESPD-EDM V02.00.00 uses always the one inside the document reference to refer to the issuer of the evidence (and of the document that 'is' the evidence). Thus the element used in the ESPD is cac:Evidence/cac:DocumentReference/cac:IssuerParty."
