### ISSUE TITLE
Part IV: Selection criteria, A: Suitability

### ISSUE THREAD

**Issue by rantati7** [OP-TED/ESPD-EDM#6]
CA must be able to write next to the questions under Section A what is the requirement. 

E.g 

not relevant professional register but CA must be able to define what professional register registration is required. In certain sectors (e.g. healt) there are many that can be required at the same time.

not authorisation or membership of particular organisation but which organisation.

**Comment by ec-mcs** [comment]
As this might apply to other sections as well, to have one textfield might be not really reusable in the end (nor machine readable). Should we have something like 
[ Domain] [Name of certificate] [Type of certificate]. Could this information come from eCertis? Then we could provide here the possibility to simply select them. The domains should be provided through eCertis.

**Comment by paulakeen** [comment]
Could you please provide examples of particular requirements for several criteria, so we can identify the information that should be required to the CA?

**Comment by paulakeen** [comment]
Please find below what was commented about this issue in the discussion group:

Steve Pastterson (Scottish Government): I htink there is an important difference between the qualifications of individuals and company registers

John Degiorgio: The name of the insitution they are registered with such as Malta Financial Services 

Jose Luis Cueva - Spain: cannot hear you

Steve Pastterson (Scottish Government): 07825256987

Steve Pastterson (Scottish Government): thats wron

Steve Pastterson (Scottish Government): 07825356087

Anne Katrine Mortensen, NIRAS A/S, DK: I suggest that in the 2 Enrolments-sections, I suggest that there also would be a text box named "Please describe them".

Jose Luis Cueva - Spain: it is similar to Spain

John Degiorgio: Is this a mandatory requirement ?

Jose Luis Cueva - Spain: It is, for some domains

Jose Luis Cueva - Spain: AFAIK domains with this requirement are  the exception, not the rule

Jose Luis Cueva - Spain: Only one

Jose Luis Cueva - Spain: Reg. Number can be optional, but useful in most cases

Jose Luis Cueva - Spain: In some cases the VAT number doubles as Reg number

Marc-Christopher SCHMIDT: CA: Name/URL and for EO: Registration number

Steve Pastterson (Scottish Government): here's an example register https://www.gassaferegister.co.uk/

Marc-Christopher SCHMIDT: CA Name/URL/Lots

**Comment by paulakeen** [comment]
Please find below a proposal for the mock-ups, as commented in the last meeting:

- View of the CA (without lots)

![mu_suitability_ca](https://cloud.githubusercontent.com/assets/16134316/24657355/35b7efb2-1946-11e7-83ba-f5229297fae9.png)

- View of the CA (with lots)

![mu_suitability_lots_ca](https://cloud.githubusercontent.com/assets/16134316/24657370/3efeae3a-1946-11e7-8459-6fa4d2473758.png)

- View of the EO

![image](https://cloud.githubusercontent.com/assets/16134316/24697927/3444e384-19ef-11e7-895d-c93b6cb8ffb3.png)

**Comment by paulakeen** [comment]
Please find below what was commented about this issue in the discussion group:

Timo Rantanen / Hansel / Finland: we consilt eCertis and look for what is the same / Similan atteatation

Timo Rantanen / Hansel / Finland: similar

Timo Rantanen / Hansel / Finland: If There is no similar attestation we suffice with self-declaration (i.e. what the supplier has provided in ESPD already)

Jose Luis Cueva (Spain): ok

Timo Rantanen / Hansel / Finland: seems ok to me

Jose Luis Cueva (Spain): I guess  "registered activities" it should be stated by each country in e_Certis

**Comment by paulakeen** [comment]
Please find below a proposal for the mock-ups, as commented in the last meeting. 

In the ESPDResponse, the EO will need to provide the registration number when the answer is YES, and will be able to provide a reason why it is not registered when the answer is NO.

- View of the CA (without lots)

![image](https://cloud.githubusercontent.com/assets/16134316/25128023/79e4bf1a-2438-11e7-85e6-9a4bd1a80254.png)

- View of the CA (with lots)

![image](https://cloud.githubusercontent.com/assets/16134316/25128031/83914150-2438-11e7-92b1-75559c8b0698.png)

- View of the EO

![image](https://cloud.githubusercontent.com/assets/16134316/25128041/8d97b562-2438-11e7-829e-8f3b0c953ce2.png)

**Comment by paulakeen** [comment]
Please find the details of the final decision and mock-ups in https://github.com/ESPD/ESPD-EDM/wiki/12.-Part-IV:-Selection-criteria,-Section-A:-Suitability

**Comment by paulakeen** [comment]
Please find below a proposal of a new mock-up of the view of the EO. 

When the EO answers YES to a particular requirement, the EO will not be required to provide a registration number. If the information is available online, the EO will provide the exact URL where to get the evidence, a verification code, etc.

![image](https://cloud.githubusercontent.com/assets/16134316/25613163/969d4168-2f2d-11e7-8f30-9c60c9b46bf7.png)
