### ISSUE TITLE
Conformance testing issue with <cbc:CustomizationID> for ESPD Request

### ISSUE THREAD

**Issue by lotzmann** [OP-TED/ESPD-EDM#60]
The GITB ESPD validator reports an error for the <cbc:CustomizationID> element, although the content is obviously correct. For an ESPD Request (fragment) as shown below, the error message is as follows: 
_The value must be 'urn:www.cenbii.eu:transaction:biitrns070:ver3.0'_. 

```
<espd-req:ESPDRequest ...>
   ...
   <cbc:CustomizationID schemeName="CustomizationID" schemeAgencyID="BII" schemeVersionID="3.0">urn:www.cenbii.eu:transaction:biitrns070:ver3.0</cbc:CustomizationID>
```

**Comment by paulakeen** [comment]
We close this issue for it's been unified with issue #45
