### ISSUE TITLE
Bug in <cac:AdditionalDocumentReference> used for “Information concerning the procurement procedure” (document type code: TED_CN)

### ISSUE THREAD

**Issue by lotzmann** [OP-TED/ESPD-EDM#61]
`…<cac:ExternalReference>.<cbc:Description>` is used for two different purposes: 
(a) short description and (b) received notice number, so it cannot consistently be derived which of the tags belong to which content (without taking the order in which the tags appear into consideration - something that should strictly be avoided).

```
<cac:AdditionalDocumentReference>
   <cbc:ID schemeID="ISO/IEC 9834-8:2008 - 4UUID" schemeAgencyID="EU-COM-GROW" schemeAgencyName="DG GROW (European Commission)" schemeVersionID="1.1">4321/S 421-654321</cbc:ID>
   <cbc:DocumentTypeCode listID="ReferencesTypeCodes" listAgencyID="EU-COM-GROW" listVersionID="1.0">TED_CN</cbc:DocumentTypeCode>
   <cac:Attachment>
      <cac:ExternalReference>
         <cbc:FileName>Title</cbc:FileName>
         <cbc:Description>Short Description</cbc:Description>
         <cbc:Description>0987654321 - Received notice number</cbc:Description>
      </cac:ExternalReference>
   </cac:Attachment>
</cac:AdditionalDocumentReference>
```

**Comment by virgiliu-ratoi-ec-ext** [comment]
This is true because when we implemented the temporary notice number feature we had no other place to put it and still don't know what's the best way to include this temporary number.

**Comment by paulakeen** [comment]
Isn't the temporary number a replacement of the OJEU  number? if yes it should go the the cbc:ID component.

BTW the attributes of the cbc:ID would be wrong, as this is never a UUID.

**Comment by virgiliu-ratoi-ec-ext** [comment]
no, the temporary number is used by the ESPD service to retrieve the actual information from the publication office. The OJEU number is stored in the cbc:ID element. I think I mentioned a while back that the OJEU is not a UUID. What should be put instead?

**Comment by paulakeen** [comment]
Something like this would work, but ideally the OPOCE should confirm at least the version:

<cbc:ID schemeID="OJEU-CN-NO" schemeAgencyID="EU-COM-OPOCE" schemeVersionID="1.0">4321/S 421-654321</cbc:ID>

**Comment by ec-mcs** [comment]
When I discussed with OP the structure there are actually two ways: 2017/S 042-077570  or  77570-2017
We both agreed that this format 77570-2017 is the best one. It will affect I assume the updated interface with them.

**Comment by paulakeen** [comment]
Let's rediscuss this together once again...I see different solutions but like none of them.

**Comment by EU-Supply-Renier** [comment]
Hi
A small comment.
The Service API that eSenders are using in order to publish notices to TED is returning the Document number (NoDocOjs) in format/structure "2017/S 042-077570". Those eSenders are often Tender platform publishing notices to TED and they do also need to implement the ESPD EDM. 
My point is that If the data requested in the ESPD match the data in the Publication forms the ESPD implementation will be easier.

**Comment by rantati7** [comment]
Now that that the EDM is somewhat ready - I think we should review it again from a more holistic viewpoint. To. Me there as now some very problematic issues including those dates for turnover... just one on many the nag that I noticed would not work in practice.

Timo Rantanen

Hansel Oy
PL 1386, 00101 Helsinki
(Mannerheiminaukio 1 A)
Matkapuhelin 0294 444 250
timo.rantanen@hansel.fi<mailto:timo.rantanen@hansel.fi>
www.hansel.fi<http://www.hansel.fi>

Teemme yhdessä onnistuneita hankintoja.
________________________________

**Comment by EU-Supply-Renier** [comment]
A bit of more information for the review phase

In a Tender process
The ESPD (ESPD Request Creation) is done during the preparation of the Tender Material. This happens before publication, in other words before publishing the Tender.
Both numbers or publication references discussed here (2017/S 042-077570 or 77570-2017) can be received after or during publication process. 

But there is third number/reference it’s call NoDocExt. The format looks like YYYY-NNNNN (2017-777570). This number is sent in and control by eSender meaning it’s available before publishing. In other words, the ESPD (ESPD Request Creation) can be fully completed when the Tender Material is being prepared. Unfortunately, I have not seen that number been show on TED site, and it’s not unique across eSenders. So, then a prefix is needed like TED000-2017-000000 ([TED eSender]-[YYYY]-[NNNNN])

One more thing the numbers discussed here are only for TED not taking in consideration other references from National sites (Maybe already been cover in https://github.com/ESPD/ESPD-EDM/wiki/6.-Information-about-publication)

This became a long story, but I do hope it can help.
