### ISSUE TITLE
Issues with <cac:AdditionalDocumentReference> used in ESPD Response for referring to ESPD Request document (document type code: ESPD_REQUEST)

### ISSUE THREAD

**Issue by lotzmann** [OP-TED/ESPD-EDM#62]
1. An ESPD Request document is referenced in the ESPD Response (using the related UUID) within AdditionalDocumentReference. Questions:
   - Why to reference the request? This is not foreseen in the instantiation guide. 
   - The ESPD Response generated by the ESPD Service (DG Grow) does not use the `<cbc:UUID…>` but the `<cbc:ID…>` element inside the document reference to link to the ESPD Request.  This causes problems with conformance testing (see bullet item 2 below). Why is the UUID not used? 
2. The existing schematron rule is dedicated to only check the TeD ID inside AdditionalDocumentReference. This causes conformance testing issues when the ESPD Request document is referenced there. At the moment, the GITB ESPD validator reports the following error: “_'YYYY' is a year, '/S' is a constant label, and 'D' represent digits. Beware of the existence of a space (a blank) between the 'S' and the first 'D'._” A possible solution to amend the schematron rule is to introduce DocumentTypeCodes with varying ID types.

```
<cac:AdditionalDocumentReference>
   <cbc:ID schemeID="ISO/IEC 9834-8:2008 - 4UUID" schemeAgencyID="EU-COM-GROW" schemeAgencyName="DG GROW (European Commission)" schemeVersionID="1.1">669970a3-f7e3-4692-b9b5-f1027e455109</cbc:ID>
   <cbc:IssueDate>2017-01-24</cbc:IssueDate>
   <cbc:IssueTime>14:45:57</cbc:IssueTime>
   <cbc:DocumentTypeCode listID="ReferencesTypeCodes" listAgencyID="EU-COM-GROW" listVersionID="1.0">ESPD_REQUEST</cbc:DocumentTypeCode>
   <cbc:DocumentDescription>ESPDRequest 123 - File reference number</cbc:DocumentDescription>
   <cac:Attachment>
      <cac:ExternalReference>
         <cbc:Description>-</cbc:Description>
      </cac:ExternalReference>
   </cac:Attachment>
</cac:AdditionalDocumentReference>
```

**Comment by virgiliu-ratoi-ec-ext** [comment]
This is an issue with the Schematron rules which need to be updated. The idea of including the request from which a response was generated was for tracking purposes but it does not have a real value right now.

**Comment by paulakeen** [comment]
1. In the new ESPD-EDM 2.0.0 the UUID for both the Request and the Response will be mandatory. 
2. The Response needs to reference the Request because in the new Response document the responses are not aggregated to the requirement anymore (but are a list of responses hanging directly from the root of the document); and the criteria (namely the selection ones) are optional in the Response document. 
I can share with you the latest UBL-2.2 version of the schemas.

**Comment by jerouris** [comment]
Please provide some correlated examples of requests/responses, so that we can understand and further discuss and elaborate.

**Comment by paulakeen** [comment]
Lotzmann is right when saying that the reference should use either ID or UUID but not the two in the two documents to refer to the ESPD Request. As Lotzman I think it'd make more sense to use the UIID, as the UUID identifies the instance, not the document. But in the end what would be truly relevant is being able to access to the XML instance through the URL in the attachement element.

**Comment by paulakeen** [comment]
Final elaboration: Use of both, the ID and the UUID to refer to the ESPD Request document. Beware that the document content can be versioned (cbc:VersionID), thus the need of using the UUID.

An extra specific REQUIREMENT was alredy added in the online documentation on this aspect:

"The economic operator must include in its ESPD Response document a reference to the ESPD Request. For this, the values of the two identifiers cbc:ID and cbc:UUID of the ESPD Request must be used as the values for the cbc:ID and cbc:UUID in the ESPD Response cac:AdditionalDocumentReference (to refer to that ESDP Request)."

See section "VII.5 Reference to publications and to the ESPD Request".
