### ISSUE TITLE
ESPD XML Schema version incosistencies

### ISSUE THREAD

**Issue by jerouris** [OP-TED/ESPD-EDM#63]
The ESPD XML Schema version, according to the document found at https://espd.github.io/ESPD-EDM/#root-properties states that the version must always be 2014.06.02 

> Rule: Use always the value "2016.04.2 for this version (this may change in future releases)

but the current ESPD Service Version marks the Schema version as 2017.01.01. Why we are using deployment dates for the ESPD Schema versions? 
Which is the correct version of the Schema? 
What are the differences between 2016.04.02 and 2017.01.01? (change logs?)
Should we consider 2016.04.02 incompatible with 2017.01.01? 
Shouldn't it be better if we just use 1.0.2 instead?

**Comment by virgiliu-ratoi-ec-ext** [comment]
I agree, the version number that is put is the version of the ESPD application, it will be better to specify the data model version.

For more details, you can check [the release notes of the ESPD Service](http://espd.github.io/ESPD-Service/docs/html/releaseNotes.html) and also [the XML related changes](http://espd.github.io/ESPD-Service/docs/html/xmlChanges.html)

**Comment by paulakeen** [comment]
In the new version 2.0.0 of the ESPD (100% UBL2.2) we are proposing:

   <cbc:UBLVersionID schemeAgencyID="OASIS-UBL-TC">2.2</cbc:UBLVersionID>
   <cbc:CustomizationID schemeAgencyID="GROW">2.0.0</cbc:CustomizationID>

In our document about governance and maintenance we advise not to use dates for versioning but adopting frequent versioning practices (as in CEN/BII) and specify to use the xx.yy.zz scheme to distinguish major, minor and editorial versions.

**Comment by virgiliu-ratoi-ec-ext** [comment]
Would it be also useful to know which information system (and its version) generated a particular XML file? Where would we store such information?

**Comment by paulakeen** [comment]
<xsd:element ref="cbc:ProfileExecutionID" minOccurs="0"/>

![image](https://cloud.githubusercontent.com/assets/16134316/25237590/5ec6771e-25eb-11e7-8b01-13fb28df2be4.png)

**Comment by paulakeen** [comment]
See proposal in Issue #82 "Possibility to refer an Xml Version in the Data Model".
