### ISSUE TITLE
EO roles

### ISSUE THREAD

**Issue by arocamop** [OP-TED/ESPD-EDM#64]
The roles of the EO impact several aspects of the ESPD. Let's discuss this issue of the roles in a separate Issue instead of having it spread over different issues.

**Comment by arocamop** [comment]
Proposal of a mock-up for section A of Part II: Information concerning the economic operator with:
- identification of the role of the EO that fills in the ESPD
- selection of the lots for wich the EO tenders
- for main contractors that lead a group (joint venture, consortium or other), identification of the other EO that are part of the group.

![mu_roles_parta](https://cloud.githubusercontent.com/assets/24680325/22705467/e4a257f8-ed6b-11e6-8719-476401d847de.png)

**Comment by arocamop** [comment]
The final decision on the EO roles does not have impact on the XSD Schema. However, the Codelist Tenderer Role has to be updated and, instead of using the CEN/BII proposal, we will have to use our own. The figure below shows the new Codelist that we will have to use from ESPD-EDM v.1.0.1 on:

![image](https://cloud.githubusercontent.com/assets/24680325/22938349/d938c274-f2db-11e6-9444-e93b799e8b59.png)

**Comment by arocamop** [comment]
As you can see in the figure below, the XSD Schema is not impacted (it is the same that we had in version 1.0.2. The 2 first elements of the EconomicOperatorPartyType are: (1) the role code; and (2) the role description). 

![image](https://cloud.githubusercontent.com/assets/24680325/22939881/6ab278ea-f2e0-11e6-92fb-8b7a46dc5309.png)

And the XML instance corresponding to this section, would look like this:

![image](https://cloud.githubusercontent.com/assets/24680325/22940303/b5c1d30c-f2e1-11e6-8313-ae6f58722dd1.png)

Given that the EO answered that he is a sole contractor, the set of questions about his belonging to a group is not necessary and, therefore, the questions made in Section A of Part II for the EO shall not be shown to the EO in the ESPD Service.

**Comment by ec-mcs** [comment]
Jose Luis Cueva - Spain: Good!

**Comment by paulakeen** [comment]
Duplicate. Please see issue #57.
