### ISSUE TITLE
Part IV, Section C (Trade Secret)

### ISSUE THREAD

**Issue by rantati7** [OP-TED/ESPD-EDM#65]
Particularly in these fields the suppliers sometimes provide information that is their trade secret. To be discussed: should / could the EO be able to mark some of their "reference" works, deliveries or services as trade secrets?

**Comment by ec-mcs** [comment]
That is a good point. We could add a marker (checkbox) where the company says that this is a trade secret. In this case we should probably make it mandatory to sign an ESPD electronically?

**Comment by SVdMeulen** [comment]
Be aware that e.g. in Belgium, the ESPD will not be signed separately. It will be part of the documents that constitute an offer, and this offer will be signed "globally" by signing a submission report, containing information of the uploaded documents.

**Comment by ec-mcs** [comment]
Indeed. The reason why signing the ESPD in this case is more "technical" than legal. The ESPD is a self-declaration and that will be normally not be signed. For confidential information like trade secret (or information about criminal convictions) we should see if there is a need to "protect" this information.

**Comment by steveP1967** [comment]
In Scotland. the use of e-signatures is not mandated. A CA has the option of requiring an e-signature on a case by case basis.
Also,  under our existing freedom of information legislation the fact that an EO has marked something as a trade secret, or commercially confidential does not necessarily exempt it from release . It is ultimately up to the CA to decide whether the information should be released.

**Comment by SVdMeulen** [comment]
In what way will a signature "protect" this information? The signature will prove the authenticity, integrity and non-repudiation of the data, but not make it "invisible" or "locked". Or I am wrong?

**Comment by rantati7** [comment]
No signature, please. Period.

Sent from my iPad

On 21 Feb 2017, at 14.50, SVdMeulen <notifications@github.com<mailto:notifications@github.com>> wrote:


In what way will a signature "protect" this information? The signature will prove the authenticity, integrity and non-repudiation of the data, but not make it "invisible" or "locked". Or I am wrong?

**Comment by SVdMeulen** [comment]
I second that :)

**Comment by ec-mcs** [comment]
Ok ok, point taken. No signature... We would only provide a checkbox to say that an  entry is a trade secret?

**Comment by rantati7** [comment]
We found more fields where the supplier may want to restrict the inforamation provided in IV (Selection) C part. Maybe all answers in this section could have the "trade secret" checkbox. Only the following do not need the checkbox:
- Allowance of checks
- Number of managerial staff 
-  Average annual manpower

**Comment by paulakeen** [comment]
Please find below what was commented about this issue in the discussion group:

Giampaolo Sellitto ANAC: Trade secrets are usually part of the technical offer not off the ESPD 

Jose Luis Cueva - Spain: does the concept "trade secrets" applies for some item in the ESPD or it only applies to the bid (outside the ESPD?

Steve Patterson (Scottish Government): Agree with Giampaolo

Jose Luis Cueva - Spain: my point is the same as of the Giampaolo

Giampaolo Sellitto ANAC: anyway we need confidentiality for disclosure of natural person that are condamned but not guilty for something pertinent to public procurement

Giampaolo Sellitto ANAC: e.g. for an incident with a car 

Jose Luis Cueva - Spain: Could somebody provide an example of "trade secret" applied to something in the ESPD?

Giampaolo Sellitto ANAC: yes good example MC, personal infroamtion are another example

Jose Luis Cueva - Spain: but "confidencial" is not equal to "trade secret"!

Jose Luis Cueva - Spain: Nor personal info is equal to 

Anne Katrine Mortensen 2: "Not to be revealed"

Jose Luis Cueva - Spain: I still think  "trade secret2 does not apply to any info un the ESPD, 

Rudolf Maier: Normally onla the CA sees the data. If there is a court case the EO can demand from the judge to desclose onlay certain parts of his tender. If there are specific situations like in Greece it should be solved by a national version of the ESPD.

Jose Luis Cueva - Spain: but to the technical-economic offer

Jose Luis Cueva - Spain: I believe Greece should provide the "case"

Jose Luis Cueva - Spain: We colud be solving the wrong problem!

**Comment by paulakeen** [comment]
Please find below what was commented about this issue in the discussion group:

Jose Luis Cueva (Spain): right

Jose Luis Cueva (Spain): Confidential, yes. Secret = useless for selection

Rudolf Maier: José Luisis right.

Jose Luis Cueva (Spain): right, not accessible to anyone but the C.A.

**Comment by paulakeen** [comment]
Please find below a proposal of the mock-up, where the EO is able to identify the references that must be treated as confidential:

![image](https://cloud.githubusercontent.com/assets/16134316/25128580/7f622674-243a-11e7-8870-c68221a9d276.png)

**Comment by paulakeen** [comment]
Please find the details of the final decision in https://github.com/ESPD/ESPD-EDM/wiki/11.-Confidentiality

**Comment by paulakeen** [comment]
Please find below what was commented about this issue in the discussion group:

Enric Staromiejski (GROW): @MC should be for the whole reference, included the evidence

Anne Katrine, NIRAS A/S, DK: only criteria

Jose Luis Cueva (Spai): only criteria
