### ISSUE TITLE
Semantic error in ESPD XML Schema: Usage of XML element […].Postbox for postcode (zipcode)

### ISSUE THREAD

**Issue by lotzmann** [OP-TED/ESPD-EDM#66]
For both the EO and the representatives of the EO a postcode can be specified. In case of the EO, this information is represented by the XML element `espd-cac:ContractingParty.Party.PostalAddress.Postbox`, in case of the EO representative the element `espd-cac:EconomicOperatorParty.Party.Person.ResidenceAddress.Postbox` is used. 
The usage of the Postbox element in semantically wrong in both cases (i.e. a postbox number refers to a post office box registered for postal delivery by a postal service provider).  The element `[…].PostalZone` should be used instead.

**Comment by paulakeen** [comment]
This will be reported to UBL2.2 as in ESPD-EDM we reuse their party ABIE.
Thank you for noticing this inconsistency.

**Comment by lotzmann** [comment]
I don't think this is an UBL issue. The party ABIE is used incorrectly. 
In the user interface the field is (correctly) named Postcode, and the related element PostalZone is present in UBL, which should be used instead of Postbox.
The description in the ESPD-EDM is also incorrect.

**Comment by paulakeen** [comment]
Our apologies. You are right. We are using the wrong element of all the ones defined by UBL. We'll pass this to our ESPD Service Developvment Team.
