### ISSUE TITLE
Part II A: Tick boxes for SME

### ISSUE THREAD

**Issue by ec-mcs** [OP-TED/ESPD-EDM#69]
https://github.com/ESPD/ESPD-Service/issues/156

**Comment by paulakeen** [comment]
Please find below what was commented about this issue in the discussion group:

Laura Martin / Scottish Government: Agree that this will be useful for reporting

Timo Rantanen / Hansel / Finland: micro, small, medium sized should be asked separately

Timo Rantanen / Hansel / Finland: it would be better to ask the number of employees etc...  easy for suppliers

Timo Rantanen / Hansel / Finland: yes yes I support this and is better than asking if SME or not

Rudolf Maier: To ask for turnover and employees if necessary is better

**Comment by hildekjol** [comment]
It is important that we don't add more than necessary, we have to remember that the EOs will have to fill it in as well.

**Comment by paulakeen** [comment]
Please find below a proposal for a solution and a mock-up.

When the EO indicates that it is a SME, the EO will need to provide the number of employees and the anual turnover, in order for the CA to know if the EO is a Micro, a Small or a Medium-Sized Enterprise.

![image](https://cloud.githubusercontent.com/assets/16134316/25128696/df59b998-243a-11e7-94fe-f1b7d621928f.png)

**Comment by paulakeen** [comment]
Please find below what was commented about this issue in the discussion group:

Anne Katrine, NIRAS A/S, DK: Are those SME info necessary?

Anne Katrine, NIRAS A/S, DK: Ok, MC.

Rudolf Maier: There should be an information what for are these data used.

Anne Katrine, NIRAS A/S, DK: I agree, R.

Rudolf Maier: A balance sheet is also necessary to proof the financial ratio asked for earlker

Timo Rantanen / Hansel / Finland: there's a spelling mistake - anual

Timo Rantanen / Hansel / Finland: :-)=

Jose Luis Cueva (Spain): yearly turnover

**Comment by paulakeen** [comment]
Please find below a proposal of a mock-up, as commented in the last meeting:

![image](https://cloud.githubusercontent.com/assets/16134316/25390661/7c0407dc-29d4-11e7-8363-c2e4f26bd268.png)

**Comment by paulakeen** [comment]
Please find the details of the final decision in https://github.com/ESPD/ESPD-EDM/wiki/15.-Information-about-SMEs

**Comment by paulakeen** [comment]
Please find below a new proposal of a mock-up, where the SME needs to provide its turnover:

![image](https://cloud.githubusercontent.com/assets/16134316/25613396/572e0dfe-2f2e-11e7-8fe8-921c47c6c05b.png)

**Comment by rantati7** [comment]
Just one note (not to be taken into account... I have wanted to raise this Q many times but haven't dared to):

Why is this SME question asked in the first place...

- Commission ESPD service is 'stupid' and does not gather any statistical information
- it is highly likely that this information is not gathered either by eTendering systems and even if it is, it only gives information of those procedures that are run on that particular platform (many countries have several different platforms and it's next to impossible to gather the information together from the many platforms.

Maybe to please the politicians?

Timo

On 2 May 2017, at 12.56, paulakeen <notifications@github.com<mailto:notifications@github.com>> wrote:


Please find below a new proposal of a mock-up, where the SME needs to provide its turnover:

[image]<https://cloud.githubusercontent.com/assets/16134316/25613396/572e0dfe-2f2e-11e7-8fe8-921c47c6c05b.png>
