### ISSUE TITLE
QualifyingParty - TendererID & Party

### ISSUE THREAD

**Issue by millstream** [OP-TED/ESPD-EDM#70]
In the implementation guide there is a reference to the QualifyingParty but no XML artifact example.

In the schema I can’t see a TendererID attribute in the QualifyingParty node.

Also wondering why we would need to collect party information?

Also, where does the qualification system name get stored? We are not going to be connecting directly to eCertis in this iteration.

document attached for reference

[5.5.3.3.docx](https://github.com/ESPD/ESPD-EDM/files/1047533/5.5.3.3.docx)

**Comment by paulakeen** [comment]
This was discussed with UBL-2.2 just after the publication of the document you attach in your comment. The solution adopted is now aligned with the requests issued by the Member States during the weekly meeting (each Wednesday). The latest UBL-2.2  Schema, dated 2017-05-25, artefacts-ubl-2.2-csd02wd01pa03-20170525-2200z.zip, can be found here:

[https://www.oasis-open.org/committees/document.php?document_id=60554](url).

In principle this new version solves the request expressed by the MS, including the name of the qualification system and the tenderer ID. We'll improve the documentation the soonest to show this by means of a figure of the new schema and a snippet of XML instance.

**Comment by millstream** [comment]
Sorry but this version of the schema does not include those new fields.

**Comment by paulakeen** [comment]
OK, I drop herein a fragment of doc with the modified specification and XML example ([Pre-qualification.docx](https://github.com/ESPD/ESPD-EDM/files/1054058/Pre-qualification.docx))
