### ISSUE TITLE
EvidenceTypeCode

### ISSUE THREAD

**Issue by millstream** [OP-TED/ESPD-EDM#72]
There does not appear to be any evidence type codes in the code list. Can you please advise?

/QualificationApplicationResponse/cac:Evidence/cbc:EvidenceTypeCode

**Comment by paulakeen** [comment]
We do not have a harmonised EvidenceTypeCode Code List for the time beign. We do have, however, the DocRefContentType for other documents that are not evidences. 

I'd like to propose such a list to:

1) the Publications Office MDR http://publications.europa.eu/mdr/cdm/index.html
2) the ISA2 programme, in  the context of SEMIC's Core Public Service Vocabulary

e-Certis should somehow refer to that CodeList.

**Comment by paulakeen** [comment]
The types of evidences are so many that to produce a closed list seems if not impossible at least very difficult and needs to be the responsibility of a standardisation organisation.
