### ISSUE TITLE
Missing Taxonomy Text

### ISSUE THREAD

**Issue by millstream** [OP-TED/ESPD-EDM#73]
In the document criteriataxonomy there are some criteria with no question text or UUID. 

C5, C6, C17, C18

**Comment by millstream** [comment]
Any update on this please?

**Comment by millstream** [comment]
Can we please have an update on this?

**Comment by paulakeen** [comment]
See this updated version, 100% based on the XML instances exported from the ESPD Service tool: [CriteriaTaxonomy-V2.0.0.xlsx](https://github.com/ESPD/ESPD-EDM/files/1080573/CriteriaTaxonomy-V2.0.0.xlsx)

However, beware that the CriteriaTaxonomy spread-sheet is currently being modified to reflect the decisions made by the MS during the weekly meetings, notably to include the national subcriteria and the MS's and CA's-specific requirements.

KR

**Comment by millstream** [comment]
Thank you!
