### ISSUE TITLE
How to handle Group processing Intructions?

### ISSUE THREAD

**Issue by millstream** [OP-TED/ESPD-EDM#74]
I note that there is now a PropertyGroupTypeCode and no CriteriaGroupTypeCode in the TenderingCriterionPropertyGroup. Can you tell me how you would handle the processing instruction now for a group?

For example:

<cbc:CriteriaGroupTypeCode>GROUP_FULFILLED.ON_TRUE</cbc:CriteriaGroupTypeCode>

**Comment by paulakeen** [comment]
The new PropertyGroupTypeCode replaces the former CriteriaGroupTypeCode, as the naming was considered wrong. We requested UBL-2.2 to change the name as this code is being used to instruct on **how to process a group of properties** (and not a group of criteria). 

To sum up: use it as you were using it up to now.
