### ISSUE TITLE
IDENTIFIER & CODE COLLECTIONS

### ISSUE THREAD

**Issue by millstream** [OP-TED/ESPD-EDM#75]
Can we please have an xml example of how we would construct a TenderingCriterionProperty with a ValueDataTypeCode of IDENTIFIER_COLLECTION or CODE_COLLECTION. These types are not in the latest schema.

`<cac:TenderingCriterionProperty>
          <cbc:ValueDataTypeCode  listID="ResponseDataType" listAgencyName="EU-COM-GROW" listVersionID="2.0.0">IDENTIFIER_COLLECTION</cbc:ValueDataTypeCode>
          <cbc:ID schemeID="CriteriaID" schemeAgencyID="EU-COM-GROW" schemeVersionID="2.0.0">...</cbc:ID>
	  <cbc:Description>...</cbc:Description>
           ???
</cac:TenderingCriterionProperty>`

**Comment by paulakeen** [comment]
See example in Multple Response Values #77 for collection of identifiers. A similar example for a collection of CPV codes will be provided asap.
