### ISSUE TITLE
ValueDataTypeCode v ResponseValue

### ISSUE THREAD

**Issue by millstream** [OP-TED/ESPD-EDM#76]
In version 1x of the model the requirement type and the response type used to match. Now ValueDataTypeCodes are not the same as possible ResponseValue nodes.

For example, there is no equivalent URL or Evidence URL elements in the ResponseValue. There is a description, but then why have it in the ValueDataTypes?

Can you explain how we may these values to the correct values?

**Comment by paulakeen** [comment]
They should match. If they do not then either the examples provided recently or the documentation is wrong. However I think you're referring to this, too (please correct me if I'm wrong or confirm I'm not):

In the new model we leverage the use of UBL-2.2 complex component that model data structures that in the previous version were kept in text fields. This is the case of: (1) Period and (2) Evidence (at least).

We think it's much more useful using those structures and reduce to the maximum free-text fields.

Beware also that: (1) The CodeList "ExpectedDataType" has been renamed "AnswerDataType" and that three new types have been added: IDENTIFIER_COLLECTION, CODE_COLLECTION, and URL.

**Comment by paulakeen** [comment]
This has been reviewed and we confirm that the expected response data types in the ESPD Request match the ones expected in the ESPD Response ResponsValue. The Codelist to use is: "ResponseDataType" (see spread-sheet book "ESPD-CodeLists-V02.00.01").
