### ISSUE TITLE
Jurisdiction level of AdditionalReferenceDocument

### ISSUE THREAD

**Issue by millstream** [OP-TED/ESPD-EDM#78]
The implementation guide describes a Jurisdiction level for a document reference, but there does not appear to be an element to store this, can you please advise?

**Comment by paulakeen** [comment]
Many thanks for this comment, it's helped improve several things:

1) In the the Codelist "DocRefContentType" we've prepended the text "Document published on a..." to the three last entries (e.g. Document published on a National Government Official Journal, etc.);

2) The Codelist "JurisdictionLevel" was created with the intention of specifying the legal scope of the documents, but Indeed the cac:DocumentReference element does not have currently a placeholder with this semantics; and the DocumentTypeCode is used to specify the type of document content (using the CodeList "DocRefContentType". The extension of this UBL element to add a cbc:JurisdictionLevel element to cac:DocumentReference is currently under discussion in the UBL-2.2 TC. **We'll come up with a proposal very soon**.

3) The documentation will be modified timely to describe how to use this feature.

**Comment by paulakeen** [comment]
After consulting this with UBL, the recommendation by UBL was to use the cbc:DocumentType element. So in version 2.0.0 we already introduced codes to combine the type of document plus the jurisdicion. See CodeList "DocRefContentType" (see codes NOJCN, ROJCN, LOJCN, etc.).

Version 2.0.1 and subsequent will use this element and CodeList, too.
