### ISSUE TITLE
Part IV, Section B (General yearly turnover)

### ISSUE THREAD

**Issue by rantati7** [OP-TED/ESPD-EDM#8]
**General yearly turnover**

 CA must be able to define minumun requirement for turnover in determined currency. Also, CA must be able to define´the years from which this turnover is required. EO must not be able to fill in the years on its own. 

[there is a problem if EO is allowed to select currency on its own. The problem concerns the exchange rate that CA will use. Maybe the CA would also need to be able to define which exhange rate will be used it if the EO gives its turover in any other currency than what the CA has defined]

**Comment by JoseLuisCueva** [comment]
I think each party (CA, EO) should be able to use his own currency when expressing his own data in the Request and the Response, leaving the verification of sufficiency to where it belongs to: the opening of bids (openning of ESPD Responses). This way, nobody is forced to express turnover in a currency different than his own (ie the attestation for the EO will be expressed in the currency he does business with), and the Exchange rate will only be needed for the final comparison.
Regarding the number of years, it might be more flexible to leave it open in the EDM. There are legitimate cases when the EO cannot provide the turnover for the number of years requested (for instance, new or too young companies). OTOH, the CA can ignore the turnover for the extra years provided by an EO (if any EO bothers to provide info not requested!)

**Comment by paulakeen** [comment]
Please find the details of the final decision in https://github.com/ESPD/ESPD-EDM/wiki/1.-General-Turnover
