### ISSUE TITLE
Schematron files

### ISSUE THREAD

**Issue by klakegg** [OP-TED/ESPD-EDM#80]
Will Schematron files used to generate XSLT-files be made available? Schematron files are easier to use to get an overview of rules.

Also, given a file validates according to the XSD schema and the  Schematron rules, what is then the statement of the validated file? Is it then seen as correct and ready to be used in a tender?

**Comment by paulakeen** [comment]
Dear Klakegg,

We're preparing a set of Test Cases where all possible variables related to the ESPD are taken into account (ESPD-Regulated, ESPD-Selfcontained, Type of Economic Operator, Lots/No Lots, Consortium/no Consortium,...).

Schematron files will be provided to test all the cases using the ISA2's Interoperability Testbed infrastructure [https://joinup.ec.europa.eu/asset/itb/description](url). The objective is having these solutions ready by end of July.

**Comment by klakegg** [comment]
Sounds good. Does this mean the existing Schematron XSLT files will be made available as Schematron, and will this be done for both version 1.0.2 and 2.0?

**Comment by paulakeen** [comment]
- There were already Schematron files for version 1.0.2. By the way, they are quite elemental/experimental but they exist and were used by VCD and Interoperability Testbed. 

- For version 2.0.0 we'll distribute Schematron files for all the Test Cases identified (including ESPD Regulated and ESPD Self-contained).

**Comment by paulakeen** [comment]
Based on the business scenarios that were distributed in v2.0.0 (folder dist/val), the development of the Schematron rules have been started and a first draft version is intended by March.

**Comment by klakegg** [comment]
It seems like you accidentally closed this issue as this issue is not solved.

**Comment by paulakeen** [comment]
Thanks for the observation, Erlend. If understand well, what you imply is that until having the Schematron files this issue should be kept open. Is that right?

I'll reopen it.

**Comment by klakegg** [comment]
The 1.0.2 contained compiled Schematron files for a fraction of the rules applying to ESPD 1.0.2. I've not looked into the 2.0.0 branch, but based on your feedback I understand Schematron for 2.0.0 is expected.

The complete lack of Schematron files according to the ISO Schematron standard is just as much an issue to us as it was 6 months ago.

I'd prefer to have this issue open as long as expectations related to availability of Schematron files is not fulfilled as it would make it easier to trace the state of this delivery.

**Comment by paulakeen** [comment]
The Schematron files that are being developed will cover the **ESPD 2.0.1** REGULATED and SELF-CONTAINED versions in great detail. We can share with you the intermediate documentation about how we're breaking down the scenarios into specific rules, but until end of February any documentation we share will be unstable. 

For the reasons about why these rules were not developed and made available publicy earlier are to be asked to this project's business owners.

I understand and share the motivation behind keeping the issue open until having stable versions of the Schematron rules. Apologies for having closed them.

KR

**Comment by klakegg** [comment]
We created two Schematron files (ESPD Request and ESPD Response repectively) each containing ~1200 rules when we created (Norwegian) EHF ESPD 1.0 based on ESPD 1.0.2. We're looking forward to get access to the documentation related to generation of Schematron rules related to ESPD 2.0.1.

**Comment by paulakeen** [comment]
Huge work you've done there. Impressive. We're eager to share ours with you. You're experience and knowledge acquired during version 1.0.2 will be invaluable. BTW, Would you mind sharing this community where to have a look into your work? 

Many thanks

**Comment by klakegg** [comment]
Our policy is to be open by default for our specifications. We've been working hard to make the user experience for developers better. You may find all resources releated to EHF ESPD 1.0 right here:
https://vefa.difi.no/ehf-pre/guide/espd/1.0/

**Comment by mireiaBM** [comment]
This issue was solved in version 2.1.0 of the ESPD-EDM
