### ISSUE TITLE
Code Lists - Missing CriteriaType

### ISSUE THREAD

**Issue by millstream** [OP-TED/ESPD-EDM#81]
The latest version of the codelists document is missing some of the new criteria type.

CRITERION.OTHER.EO_DATA.SME
CRITERION.OTHER.PROCUREMENT_PROCEDURE_CPV

**Comment by paulakeen** [comment]
They are not needed anymore. 

- for the SME datum we use now the "cac:QualifyingParty/cac:Party/cbc:IndustryClassificationCode". See section "VII.6 Economic Operator" of the online documentation (https://github.com/ESPD/ESPD-EDM, from versions 2.0.0 on).
. for the CPV we have the data as part of a data structure, e.g. see the "specific" turnovers.
