### ISSUE TITLE
ESPD Part I - V and ESPD EDM

### ISSUE THREAD

**Issue by jerouris** [OP-TED/ESPD-EDM#83]
While the ESPD Document and the ESPD XML Implementation Guideline mention Parts of ESPD as discrete semantic sections of the ESPD Artifacts, there is no mention of the Parts in either the XSD, Codelists etc. This makes it problematic when implementing, as mentions of criteria, elements etc being a members of specific parts cannot be placed and represented inside those parts only by using the EDM Files. 

As an example, from current EDM 2.0.0:

> Lots management:
>  - The Contracting Authority (CA) needs to be able to provide the number of lots into which the  procurement procedure is divided in the Request document.
>  - The CA provides, for each criteria in **Part IV** of the ESPD Request document, the specific requirements and the set of lots these requirements apply to. By default, all specific requirements will apply to all lots, so the CA must only select the lots for requirements that apply only to particular lots;
> - The EO provides the lots for which the economic operator wishes to tender in **Part II** of the ESPD Response document;
> - When the EO relies on the capacities of other entities in order to meet the selection criteria, the EO must provide the lots for each entity in **Part II** of the ESPD Response document;
> - In **Part IV** of the ESPD Response document, the system will display the specific requirements that apply to each lot, and the EO will be able to provide information for specific lots.

Another Example from EDM 2.0.0 (new codelists):

> - GM / Group member/ Member (not leader) of the Consortium, Joint Venture or other type of group. This role has to produce a complete ESPD except **Part II A - b** (identify procurers).
> - OERON/ Other entity (relied upon) / Entity on which the main contractor, the group or another subcontractor relies in order to meet the selection criteria. This role has to produce a complete ESPD except **Part II A - b** (identify procurers).
> - OENRON/ Other entity (not relied upon) / Entity on which the main contractor, the group or another subcontractor does not rely in order to meet the selection criteria. This role has to produce an ESPD without **Part IV** and **Part V**.

There should be a mapping, at least for the generic elements like the criteria, between Parts and criteria or criteria types (through the taxonomy values maybe or introducing parts as part of the path of the taxonomy?)

**Comment by paulakeen** [comment]
After discussing on this topic raised by Jerry, it was considered that the ESPD-EDM specification should not refer to the Parts of the The Annex 2 of the Commission Implementing Regulation (EU) No 2016/7. Right now the only two places where a reference to the Annex are done is 1) in an XML example and in a footnote (footnote 6). 
The codelists, too, are now devoided of references to the Annex II Parts.
