### ISSUE TITLE
Criteria 25 - 28 - Incorrect Mappings

### ISSUE THREAD

**Issue by millstream** [OP-TED/ESPD-EDM#86]
Criteria 25 to 28 appear to have incorrect mappings, as their are properties and groups which are for the response, but are children of the groups marked as guidance.

C25/G1
C25/G1/P1
C25/G1/G1.1
C25/G1/G1.1/P1
C25/G1/G1.1/P2
C25/G1/G1.1/G1.1.1
C25/G1/G1.1/G1.1.1/P1
C25/G1/G1.1/G1.1.1/G1.1.1.1
C25/G1/G1.1/G1.1.1/G1.1.1.1/P1
C25/G1/G1.1/G1.1.1/G1.1.1.1/P2
C25/G1/G1.1/G1.1.2
C25/G1/G1.2/G1.2.1/P1
C25/G1/G1.2/G1.2.1/G1.2.1.1
C25/G1/G1.2/G1.2.1/G1.2.1.1/P1
C25/G1/G1.2/G1.2.1/G1.2.1.1/P2
C25/G1/G1.2/G1.2.1/G1.2.1.1/P3

Should be

C25/G1
C25/G1/P1
C25/G1/G1.1
C25/G1/G1.1/P1
C25/G1/G1.1/P2
C25/G2
C25/G2/P1
C25/G2/G2.1
C25/G2/G2.1/P1
C25/G2/G2.1/P2
C25/G3
C25/G3/P1
C25/G3/G3.1
C25/G3/G3.1/P1
C25/G3/G3.1/P2
C25/G3/G3.1/P3

**Comment by mondorf** [comment]
We will have a look into the details and come back with a solution.

**Comment by paulakeen** [comment]
Version 2.0.0 introduced a new way of structuring the data where this, in principle, has been solved. Please confirm: see spread-sheet files "ESPD-Data_Structures-*" in the dist/cl folder.
