### ISSUE TITLE
Part IV, Section B (Average yearly turnover)

### ISSUE THREAD

**Issue by rantati7** [OP-TED/ESPD-EDM#9]
**Average yearly turnover**

CAS must be able to define what is the minimum requirement for the average yearly turnover. Also CA must be able to define not just from how many years the average is but also from which years the average will need to be calculated.

**Comment by JoseLuisCueva** [comment]
I agree with the concept. The period for computing the average yearly turnover must be clearly defined.
A "period" element might be the most flexible solution: startDate/endDate.
We should take into account cases where the accounting year for an EO is not January 1st/Dec 31. The "period solution" can accomodate these cases.

**Comment by paulakeen** [comment]
Please find below a proposal for the mock-ups, both for the view of the CA and the view of the EO:

- View of the CA

![image](https://cloud.githubusercontent.com/assets/16134316/23906802/5d22aa38-08cf-11e7-90df-e3a7bc74c460.png)

- View of the EO

![image](https://cloud.githubusercontent.com/assets/16134316/23906813/675152fc-08cf-11e7-84ab-5c0c8e49b46f.png)

**Comment by paulakeen** [comment]
Please find below what was commented about this issue in the discussion group:

Anne Katrine Mortensen 2: I have never seen it used. And I don´t understand the need for it.

Rudolf Maier: Is this additionally to the statement of the turnover of the last three years, listed year by year?

Anne Katrine Mortensen 2: Don´t understand "in the relevant notice".

Jose Luis Cueva - Spain: Either average or yearly for a given procedure. It does not make sense ask for both

**Comment by paulakeen** [comment]
Please find the details of the final decision in https://github.com/ESPD/ESPD-EDM/wiki/1.-General-Turnover
