### ISSUE TITLE
V2.0.0 Self-contained and division into lots

### ISSUE THREAD

**Issue by EU-Supply-Renier** [OP-TED/ESPD-EDM#94]
My understanding is that the multi lot (When a tender is divided into lots) feature can only be used for those criteria where their data structure is involving the lot data relationship.
For example, I cannot add specific requirements to lots for criteria “Number of managerial staff” in the abilities category.
Can you please confirm if my understanding is correct?

Please note that the term data structure is referring to the excel file in the documentation page displaying the criteria anatomy.

**Comment by mondorf** [comment]
There is the possibility to relate the entire ESPD to specific lot. For criteria the lot relationsship was only added to those criteria where needed. We see that is makes sense to add lots to the "number of managerial staff" criterion. Do you see other criteria where this is needed or even to provide a general pattern for this for all selection criteria?

**Comment by EU-Supply-Renier** [comment]
Hi and thanks for your answer.
The "Number of managerial staff" was only an example. Even if it **may** be one that needs to be extended in order to carter for lots. In such a case I do not know what the requirement will looks like then. 
However, you did confirm our understanding about how the lots have been Model. (Thanks again)

Regarding “Do you see other criteria where this is needed”
Not at the moment but I will get back to you when I know. (We are currently working on two criteria that **may** need an extension, leave it with me i will get back to you if need it)

Regarding "a general pattern for this for all selection criteria"
The only one (general pattern) that i do know at the moment is the possibility to associate a criterion to a Lot. This is need it when you have big frameworks or Tenders and not all criteria in your ESPD is applicable for all lots. Please note that in this case there no specific requirement that needs to be specify. it's only an association between the lot and the criteria so the supplier (EO) knows what criteria needs to be answered for the lots they are applying to

Regards

**Comment by mondorf** [comment]
Hi, many thanks for your answer and further clarification. We require some more time to look into the details and come back on this issue. Due to the impact on the EDM it might not be part of 2.0.1 but on version 2.0.2.

**Comment by EU-Supply-Renier** [comment]
One more comment. if you like we can try to set up a meeting or workshop where we can share detail information about multi Lots, Evidences etc.

**Comment by paulakeen** [comment]
At least up to four different fora are currently discussing how to model Lots: DG GROW + the Publications office (in the context of the e-Forms); DG GROW, MS and ESPDint (in the context of the ESPD-EDM); CEN/TC 440 (in the context of the eProcurement Process Modelling and Standardisation); and the UBL-2.3 TC.

It would be great if we could muster all our good will and efforts towards having one common understanding of the information requirements and come up with a single model that we all could share.

What about forming a working group about this specific subject, asap? 

In the meanwhile we can discuss this internally, I mean in the context of the ESPD-EDM v2.0.1, and come with a proposal to share with any other fora.

The resulting proposal would be included in the version 2.0.2 of the ESP-EDM.

BTW: the proposal of having a link to Lots in all the selection criteria doesn't seem a bad idea.

**Comment by EU-Supply-Renier** [comment]
Absolutely
if you can shared your thoughts and ideas with me i can definitely provide you with my comments
Regards

**Comment by paulakeen** [comment]
This issue cannot be solved in v.2.0.3, as the analysis and discussion on lots has not taken place yet. It would go to a v3 of the ESPD-EDM, as labelled by Mondorf.

**Comment by JosePRevenga** [comment]
The ePO (e-Procurement Ontology), currently being developed by the Publications Office, provides a flexible approach to this problem. Everyone is more than welcome to join the ePO working group and contribute to its refinement. You can check the current version (ongoing work) at its GitHub repository and Wiki: https://github.com/eprocurementontology/eprocurementontology/wiki.

Additionally, the Publications Office and the ESPD working group are working together with the UBL TC to introduce the results of the ePO in UBL-3.0.

In any case, it will be addressed on the future in a dedicated session.

**Comment by hricolor** [comment]
After having analysed the issue, we proceed to close it since the new approach for the Lots Management (aligned with eForms) solve the need to have multiple criteria related to some specific lots. The new approach is as follows: 

1 ESPD Request per all exclusion grounds (same per all lots in the procedure) and the selection criteria (that can differ per lot).

There might be multiple responses, 1 per lot or group of lots including the exclusion grounds and the selection criteria related to each specific lot. 

Therefore, as mentioned above, since there might be 1 response per Lot or group of lots there is no need to specify within the criteria to which Lot would apply. It is currently done by specifying the LOT_IDENTIFIER within the requirement but would not be needed anymore.
