### ISSUE TITLE
SELECTION > SUITABILITY Criteria

### ISSUE THREAD

**Issue by millstream** [OP-TED/ESPD-EDM#95]
New implementation guide excludes suitability questions from the taxonomy tree, yet the criteria is listed in the taxonomy doc. Is this a mistake?

Similarly  in the exclusion section there seems to be a new EARLY_TERMINATION sub section, however the taxonomy list does not represent this.

![image](https://user-images.githubusercontent.com/28925615/31138266-44940970-a844-11e7-9c49-84983fd7de03.png)

**Comment by mondorf** [comment]
We will elaborate the issue in the documentation and correct the issue. It seems to be an editorial inconsistency.

**Comment by paulakeen** [comment]
Indeed there were errors in the representation of both taxonomies: the one about the Exclusion Criteria and the one about the Exclusion Criteria.

The drawings in the documentation have been updated to match the Criteria Taxonomy category codes as they appear in the spread-sheet books "ESPD-CriteriaTaxonomy-*" and "ESPD-Data_Structures-*".
