### ISSUE TITLE
CRITERIATYPE > CPV & LOTS

### ISSUE THREAD

**Issue by millstream** [OP-TED/ESPD-EDM#96]
The list of Criteria type appears to be missing CPV, SME and LOTS, can you please confirm if these are still meant to be criteria?

C63 - LOTS
C64 - CPV
C66 - SME

**Comment by mondorf** [comment]
In C63 the properties were missing and we corrected it. However, we do not found the exact part of the specification refering to C64 and C66. Could you please clarify which part of the specification you are refering to?

**Comment by paulakeen** [comment]
C62 and C63: Relied on entities three questions had no PropertyDataType assigned. 

Corrected in v2.0.1 to be released by the 25th February 2018.
