### ISSUE TITLE
All criteria satisfied

### ISSUE THREAD

**Issue by millstream** [OP-TED/ESPD-EDM#97]
Can you please explain how 'all criteria satisfied' is handled in the new model as there does not appear to be a criteria?

CRITERION.SELECTION.ALL_SATISFIED

**Comment by mondorf** [comment]
This relates to the alpha criterion and was intenitally not  foreseen in version 2.0.0 (regulated and self-contained). We will elaborate if and how it can be included to version 2.0.1. The current discussion has shown that we propably will include this alpha criterion for the "regulated" ESPD version 2.0.1 to maintain equivalence with version 1.0.2 and legal validity.  However, in the "self-contained" ESPD version 2.0.1 the intention is still to deprecate this alpha criterion.

**Comment by paulakeen** [comment]
The decision is not to have it in version 2.0.1 as this breaks all possibility of interoperability. However you still have the possibility of "repealling" this decision and we could re-discuss if this should go or not to version 2.0.2.

**Comment by paulakeen** [comment]
The decision has been reconsidered: alpha criterion should be added in version 2.0.3 for the ESPD REGULATED, but not for the ESPD SELF-CONTAINED.

**Comment by mireiaBM** [comment]
This issue was solved in version 2.1.0 of the ESPD-EDM
