### ISSUE TITLE
ResponseDataType - EVIDENCE_IDENTIFIER

### ISSUE THREAD

**Issue by millstream** [OP-TED/ESPD-EDM#99]
There seems to be a new data type of EVIDENCE_IDENTIFIER listed in the taxonomy document, however this does not exist in the code list document. Can you please advise?

**Comment by ec-mcs** [comment]
It is in the code list document (probably you had an older version)
https://github.com/ESPD/ESPD-EDM/blob/2.0.0/docs/src/main/asciidoc/dist/cl/xlsx/ESPD-CodeLists-V02.00.00.xlsx

**Comment by paulakeen** [comment]
The code was introduced in version 2.0.0 to identify the group structuring the data about the information available electronically #UUID 9026e403-3eb6-4705-a9e9-e21a1efc867d
